(function(){'use strict';
var O=globalThis.Day1Orchestrator,G=globalThis.MathGymEngine,store=localStorage,state=O.load(store),view='home';
var $=function(id){return document.getElementById(id)},root=$('view');
var UIKEY='dr-merissa-day1-ui-v3';
var ui={mathArea:null,mathSessions:{},chemMode:'menu'};try{ui=Object.assign(ui,JSON.parse(store.getItem(UIKEY)||'{}'));ui.mathSessions=ui.mathSessions||{};}catch(e){}
var engine={logs:'logs_estimation',algebra:'algebra',exponents:'exponents',scientific_notation:'scientific_notation',fractions_percent:'fractions_percentages',unit_conversions:'unit_conversions'};
var areas={
logs:{name:'Logs & estimation',toolbox:['log(1)=0','log(10)=1','log(100)=2','log(2)≈0.30','log(3)≈0.48','log(5)≈0.70','log(ab)=log(a)+log(b)'],probe:[['log(10,000) =',4],['If log(x) = −4, x =','0.0001'],['Estimate −log(6×10⁻⁶)',5.2,.15]],steps:[
{t:'What a log asks',say:'A logarithm asks for an exponent. Ten to what power gives the number?',v:'10³ = 1000\nso log(1000) = 3',fact:'A logarithm asks which exponent belongs on 10.'},
{t:'Power-of-ten anchors',say:'Use powers of ten as landmarks. These are exact and worth knowing.',v:'log(1)=0\nlog(10)=1\nlog(100)=2\nlog(0.1)=−1',fact:'Useful log anchors: log(1)=0, log(10)=1, log(100)=2.'},
{t:'Small no-calculator landmarks',say:'For estimation, memorize only a tiny useful set.',v:'log(2)≈0.30\nlog(3)≈0.48\nlog(5)≈0.70',fact:'No-calculator log landmarks: log(2)≈0.30, log(3)≈0.48, log(5)≈0.70.'},
{t:'Build log(6)',say:'Six is two times three. The product rule turns multiplication inside a log into addition.',v:'6 = 2×3\nlog(6)=log(2)+log(3)\n≈0.30+0.48=0.78',fact:'Product rule: log(ab)=log(a)+log(b).'},
{t:'pKa-style example',say:'Separate the power of ten first, then estimate the front number.',v:'−log(6×10⁻⁶)\n= 6 − log(6)\n≈ 6 − 0.78\n= 5.22',fact:'For −log(a×10⁻ⁿ), separate the power-of-ten part from log(a).'}]},
algebra:{name:'Algebra',toolbox:['Equals sign = balance','Do the same operation to both sides','Undo addition/subtraction before division','Proportion: multiply diagonally, then solve'],probe:[['4x + 5 = x + 20',5],['Solve V=lwh for h','V/(lw)'],['2/x = 6/15',5]],steps:[
{t:'Equation means balance',say:'An equation is a balance. Both sides have the same value, so every legal move must happen to both sides.',v:'7x + 2 = 3x + 26',fact:'An equation stays balanced when the same operation is done to both sides.'},
{t:'Collect x terms',say:'We want the x terms together. Subtract three x from both sides, not just from one side.',v:'7x + 2 = 3x + 26\n−3x        −3x\n──────────────\n4x + 2 = 26',fact:'To collect variable terms, apply the same subtraction to both sides.'},
{t:'Move constants',say:'Now remove the plus two. Subtract two from both sides.',v:'4x + 2 = 26\n     −2   −2\n──────────\n4x = 24',fact:'To isolate a variable term, undo added constants on both sides.'},
{t:'Isolate x',say:'Four times x equals twenty-four. Divide both sides by four, because division undoes multiplication.',v:'4x = 24\n÷4   ÷4\n──────\nx = 6',fact:'To isolate x in 4x=24, divide both sides by 4.'},
{t:'What cross-multiply means',say:'Cross multiplication is a shortcut for clearing two denominators in a proportion. Multiply diagonally, then solve the simpler equation.',v:'2/x = 6/15\n2×15 = 6×x\n30 = 6x\nx = 5',fact:'Cross multiplication in a proportion multiplies diagonally to clear denominators.'}]},
exponents:{name:'Exponents',toolbox:['Same base ×: add exponents','Same base ÷: subtract exponents','Negative exponent: reciprocal','Anything nonzero to 0 = 1'],probe:[['2^-4 =','1/16'],['(a^4)(a^3)/a^2 =','a^5'],['10^2 × 10^3 =','100000']],steps:[
{t:'Exponent means repeated multiplication',say:'An exponent tells how many copies of the same factor are multiplied.',v:'a⁴ = a·a·a·a',fact:'An exponent counts repeated factors.'},
{t:'Product rule',say:'When the base is the same and you multiply, count all the factors, so the exponents add.',v:'a⁴·a³\n= a·a·a·a · a·a·a\n= a⁷',fact:'Same-base multiplication adds exponents.'},
{t:'Quotient rule',say:'When the same base is divided, cancel matching factors, so exponents subtract.',v:'a⁷/a² = a⁵',fact:'Same-base division subtracts exponents.'},
{t:'Negative exponent',say:'A negative exponent means reciprocal. It does not mean the value is negative.',v:'2⁻⁴ = 1/2⁴ = 1/16',fact:'A negative exponent means take the reciprocal.'}]},
scientific_notation:{name:'Scientific notation',toolbox:['Coefficient must be ≥1 and <10','Multiply coefficients, add exponents','Divide coefficients, subtract exponents','Renormalize at the end'],probe:[['0.00061 =','6.1x10^-4'],['(4.0×10^6)(2.0×10^-3) =','8x10^3'],['(9.0×10^-5)/(3.0×10^-2) =','3x10^-3']],steps:[
{t:'Standard form',say:'Scientific notation keeps one nonzero digit before the decimal and records place value with a power of ten.',v:'0.00061 = 6.1 × 10⁻⁴',fact:'Scientific notation uses a coefficient from 1 up to 10 times a power of ten.'},
{t:'Decimal movement',say:'Count how many places the decimal moves. Small numbers use negative powers; large numbers use positive powers.',v:'61000 → 6.1×10⁴\n0.0061 → 6.1×10⁻³',fact:'The exponent records how many decimal-place moves are needed.'},
{t:'Multiply',say:'Multiply the front numbers and add the powers of ten.',v:'(4×10⁶)(2×10⁻³)\n=8×10³',fact:'Scientific-notation multiplication multiplies coefficients and adds exponents.'},
{t:'Divide',say:'Divide the front numbers and subtract exponents, then make sure the coefficient is between one and ten.',v:'(9×10⁻⁵)/(3×10⁻²)\n=3×10⁻³',fact:'Scientific-notation division divides coefficients and subtracts exponents.'}]},
fractions_percent:{name:'Fractions & percentages',toolbox:['10% = divide by 10','1% = divide by 100','5% = half of 10%','20% = double 10%','25% = one fourth','50% = one half','75% = half + one fourth','Formal: part ÷ whole × 100'],probe:[['5/6 − 1/3 =','1/2'],['3/8 of 160 =',60],['24 is what percent of 300?',8]],steps:[
{t:'Fractions need equal-sized pieces',say:'You can add or subtract fractions only after the pieces are the same size. Make a common denominator first.',v:'5/6 − 1/3\n= 5/6 − 2/6\n= 3/6\n= 1/2',fact:'Fractions need a common denominator before adding or subtracting.'},
{t:'Percent means out of 100',say:'Percent means per hundred. Twenty-five percent is twenty-five out of one hundred, which is one fourth.',v:'25% = 25/100 = 1/4',fact:'Percent means out of 100.'},
{t:'Mental percent anchors',say:'Build percentages in your head from a few anchors. Ten percent is divide by ten. Five percent is half of ten percent. Twenty-five percent is one fourth.',v:'10% = ÷10\n1% = ÷100\n5% = half of 10%\n25% = 1/4\n50% = 1/2',fact:'Mental percent anchors: 10%, 1%, 5%, 25%, and 50%.'},
{t:'24 is what percent of 300?',say:'Do it mentally first. Ten percent of three hundred is thirty. Two percent is six. Twenty-four is thirty minus six, so it is eight percent.',v:'10% of 300 = 30\n2% of 300 = 6\n30 − 6 = 24\n10% − 2% = 8%',fact:'A percent can often be built mentally from 10%, 5%, 1%, halves, or fourths.'},
{t:'Formal percent check',say:'Now connect the mental answer to the formal method: part divided by whole times one hundred.',v:'24 ÷ 300 × 100\n= 0.08 × 100\n= 8%',fact:'Formal percent method: part ÷ whole × 100.'},
{t:'Flexible mental math',say:'Use anchors instead of a calculator when the numbers are friendly.',v:'15% of 80 = 8 + 4 = 12\n25% of 60 = 60÷4 = 15\n75% of 40 = 20 + 10 = 30',fact:'15% can be built as 10%+5%; 75% can be built as 50%+25%.'}]},
unit_conversions:{name:'Unit conversions',toolbox:['1 L = 1000 mL','1 g = 1000 mg','1 mg = 1000 mcg','1 gal = 4 qt','1 qt = 2 pt','1 pt = 2 cups','Big → small: number gets bigger','Small → big: number gets smaller'],probe:[['0.062 L to mL',62],['8 g/5 min for 12 min',19.2],['0.015 mol/s to mmol/min',900]],steps:[
{t:'Conversion keeps the amount',say:'A conversion changes the unit label without changing the physical amount. Start from an anchor relationship.',v:'1 L = 1000 mL',fact:'1 L = 1000 mL.'},
{t:'Big unit to smaller unit',say:'One liter contains one thousand milliliters. Going from a big unit to a smaller unit makes the number larger.',v:'2.5 L × 1000\n= 2500 mL',fact:'Going from liters to milliliters means multiply by 1000.'},
{t:'Small unit to bigger unit',say:'Going from milliliters to liters makes the number smaller, so divide by one thousand.',v:'750 mL ÷ 1000\n= 0.75 L',fact:'Going from milliliters to liters means divide by 1000.'},
{t:'Let the written units prove it',say:'Write the conversion factor so the old unit appears once on top and once on bottom. The matching written labels cancel.',v:'0.062 L × (1000 mL / 1 L)\nL cancels\n= 62 mL',fact:'In dimensional analysis, arrange conversion factors so unwanted units cancel.'},
{t:'Pharmacy metric anchors',say:'The same thousand pattern repeats for common pharmacy metric units.',v:'1 L = 1000 mL\n1 g = 1000 mg\n1 mg = 1000 mcg',fact:'Pharmacy metric anchors: 1 L=1000 mL, 1 g=1000 mg, 1 mg=1000 mcg.'},
{t:'Rate conversions',say:'For a rate, convert one unit at a time and keep every label visible.',v:'0.015 mol/s\n× 1000 mmol/mol\n× 60 s/min\n= 900 mmol/min',fact:'For rate conversions, change one unit at a time and keep labels visible until they cancel.'},
{t:'U.S. liquid anchors',say:'Use a small reference set instead of guessing.',v:'1 gal = 4 qt\n1 qt = 2 pt\n1 pt = 2 cups\n1 gal = 16 cups',fact:'U.S. volume anchors: 1 gal=4 qt, 1 qt=2 pt, 1 pt=2 cups.'}]}}
;
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])})}
function saveUI(){store.setItem(UIKEY,JSON.stringify(ui));O.save(state,store);if($('saveState'))$('saveState').textContent='Saved just now'}
function session(id){if(!ui.mathSessions[id])ui.mathSessions[id]={phase:'entry',step:0,probeIndex:0,score:0,practiceIndex:0,practiceCorrect:0,practiceNeeded:0,verification:false,status:'Not started'};return ui.mathSessions[id]}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.rate=.88;speechSynthesis.speak(u)}
function recordFact(f){if(!f)return;O.addNotebookFact(state,f,'TEACH');saveUI()}
function setView(v){view=v;if(v==='math')ui.mathArea=null;if(v==='chemistry')ui.chemMode='menu';document.querySelectorAll('#navTabs button').forEach(function(b){b.classList.toggle('on',b.dataset.view===v)});render()}
$('navTabs').addEventListener('click',function(e){if(e.target.dataset.view)setView(e.target.dataset.view)});
function toolbox(a){return '<details class="card" open><summary><b>Math Toolbox</b></summary><div class="chips">'+a.toolbox.map(function(x){return '<span class="pill">'+esc(x)+'</span>'}).join('')+'</div></details>'}
function switchMath(){return '<button class="btn ghost" id="mathMenu">← Change math skill</button>'}
function home(){return '<div class="hero"><div class="phase">DAY 1</div><h1>Choose where you want to work.</h1><p>Math and chemistry keep separate progress. You can leave one skill, work somewhere else, and return later.</p></div><div class="grid"><div class="card subject"><h2>Math Foundation</h2><p>Six skill areas with Teach first or Try first.</p><button class="btn" data-go="math">Open math</button></div><div class="card subject"><h2>Chemistry Foundation</h2><p>Animated teacher lesson plus multi-molecule practice and transfer.</p><button class="btn" data-go="chemistry">Open chemistry</button></div></div>'}
function mathMenu(){return '<div class="card"><div class="phase">Math Foundation</div><h2>Choose a math skill</h2><p class="muted">Opening another skill does not erase the one you were working on.</p><div class="grid">'+Object.keys(areas).map(function(id){var s=session(id);return '<button class="mathArea" data-area="'+id+'"><b>'+areas[id].name+'</b><span class="status">'+(state.math.statuses[id]||s.status||'Not started')+(s.phase!=='entry'&&s.phase!=='done'?' • Resume available':'')+'</span></button>'}).join('')+'</div></div>'}
function entry(id,a,s){return switchMath()+'<div class="card"><div class="phase">'+a.name+'</div><h2>How do you want to start?</h2><div class="actions"><button class="btn" id="teachFirst">▶ Teach me the lesson</button><button class="btn secondary" id="tryFirst">✏️ Let me try it first</button></div><p class="muted">If you try first and get stuck, you can open the full lesson at any time.</p></div>'}
function lesson(id,a,s){var x=a.steps[s.step];recordFact(x.fact);return switchMath()+'<div class="card teacher"><div class="avatar">🎓</div><div class="bubble"><b>Dr. Merissa</b><div>'+esc(x.say)+'</div></div></div><div class="card"><div class="phase">Learning • '+(s.step+1)+' of '+a.steps.length+'</div><h2>'+esc(x.t)+'</h2><div class="stage"><div class="visual small" style="white-space:pre-line">'+esc(x.v)+'</div></div><div class="actions"><button class="btn secondary" id="back" '+(s.step===0?'disabled':'')+'>← Back</button><button class="btn" id="next">'+(s.step===a.steps.length-1?'Practice this →':'Next →')+'</button><button class="btn secondary" id="replay">Replay this step</button><button class="btn ghost" id="stillIdk">I still don’t get this</button><button class="btn ghost" id="skipTry">Skip teaching and try</button></div><div id="feedback"></div></div>'+toolbox(a)}
function probe(id,a,s){var q=a.probe[s.probeIndex];return switchMath()+'<div class="card"><div class="phase">Try first • '+(s.probeIndex+1)+' of 3</div><h2>'+a.name+'</h2><div class="question">'+esc(q[0])+'</div><input id="answer" class="input" autocomplete="off"><div class="actions"><button class="btn" id="checkProbe">Check answer</button><button class="btn secondary" id="idkProbe">I don’t know yet</button><button class="btn ghost" id="fullLesson">Teach the full lesson</button></div><div id="feedback"></div></div>'+toolbox(a)}
function newItem(id){var s=session(id);s.currentPrompt=null;s.currentItem=G.generate(engine[id]);s.currentPrompt=s.currentItem.prompt;}
function practice(id,a,s){if(!s.currentItem)newItem(id);return switchMath()+'<div class="card"><div class="phase">'+(s.verification?'Fresh verification':'Practice')+' • '+(s.practiceIndex+1)+' of '+s.practiceNeeded+'</div><h2>'+a.name+'</h2><div class="question">'+esc(s.currentItem.prompt)+'</div><input id="answer" class="input" autocomplete="off"><div class="actions"><button class="btn" id="checkPractice">Check answer</button><button class="btn secondary" id="idkPractice">I don’t know yet</button><button class="btn ghost" id="fullLesson">Teach the full lesson</button></div><div id="feedback"></div></div>'+toolbox(a)}
function result(id,a,s){return switchMath()+'<div class="card '+(s.status==='Cleared'?'success':'warning')+'"><h2>'+a.name+': '+s.status+'</h2><p>'+(s.status==='Cleared'?'You showed enough fresh evidence for today.':'This skill is saved as Developing and can be revisited without blocking chemistry.')+'</p><div class="actions"><button class="btn" id="morePractice">Do more fresh practice</button><button class="btn secondary" id="mathMenu2">Choose another math skill</button></div></div>'}
function math(){if(!ui.mathArea)return mathMenu();var id=ui.mathArea,a=areas[id],s=session(id);if(s.phase==='entry')return entry(id,a,s);if(s.phase==='teach')return lesson(id,a,s);if(s.phase==='probe')return probe(id,a,s);if(s.phase==='practice')return practice(id,a,s);return result(id,a,s)}
function normalize(v){return String(v).toLowerCase().replace(/\s+/g,'').replace(/×/g,'x').replace(/⁻/g,'-').replace(/⁴/g,'^4').replace(/³/g,'^3').replace(/²/g,'^2')}
function probeCorrect(q,v){if(typeof q[1]==='number')return Math.abs(Number(v)-q[1])<=(q[2]||1e-9);return normalize(v)===normalize(q[1])}
function exactHelp(id,p){p=String(p||'');if(id==='algebra')return '<b>Stay on THIS equation.</b><p>Write the equation before and after each operation. Ask: what operation will undo the term I want to remove? Whatever you do, show it on both sides. If it is a proportion, cross multiplication means multiplying the two diagonals, then solving the new equation.</p>';if(id==='fractions_percent'&&/percent/i.test(p))return '<b>Stay on THIS percent problem.</b><p>First find 10% of the whole in your head, then build from 5%, 1%, halves, or fourths. After the mental route, verify with <b>part ÷ whole × 100</b>.</p>';if(id==='fractions_percent')return '<b>Stay on THIS fraction.</b><p>Make the denominators match first. Rewrite both fractions with equal-sized pieces, then combine the numerators.</p>';if(id==='unit_conversions')return '<b>Stay on THIS conversion.</b><p>Use the toolbox anchor. Predict whether the number should get bigger or smaller. Then write a conversion factor so the old unit appears once above and once below and cancels on the written setup.</p>';if(id==='logs')return '<b>Stay on THIS log.</b><p>Ask what exponent of 10 is being requested. Separate powers of ten from the front coefficient before estimating.</p>';if(id==='exponents')return '<b>Stay on THIS exponent step.</b><p>Expand the power as repeated multiplication if the rule is not obvious. Then count or cancel matching factors.</p>';return '<b>Stay on THIS scientific-notation step.</b><p>Move the decimal until one nonzero digit remains before it, count the moves, then decide the exponent sign from whether the original number was large or small.</p>'}
function chemistry(){if(ui.chemMode==='menu')return '<div class="card"><div class="phase">Chemistry Foundation</div><h2>Lewis structures</h2><p>You can teach first, jump to practice, or return to the chemistry menu at any time.</p><div class="actions"><button class="btn" id="chemTeach">▶ Teach me the lesson</button><button class="btn secondary" id="chemPractice">✏️ Let me try/practice</button></div></div>';var hash=ui.chemMode==='practice'?'#practice':'';return '<button class="btn ghost" id="chemMenu">← Chemistry menu</button><div class="card iframeWrap"><iframe src="../chemistry-teacher-preview/'+hash+'" title="Lewis structures teacher and practice"></iframe></div>'}
function notebook(){return '<div class="card"><div class="phase">What We Know</div><h2>Notebook</h2><p class="muted">Notes are added from teaching steps. They are for learning, not cold mastery.</p>'+(state.notebook.length?state.notebook.map(function(x){return '<div class="notebookFact">'+esc(x)+'</div>'}).join(''):'<p>No lesson facts have been saved yet.</p>')+'</div>'}
function summary(){var chemDone=false;try{chemDone=!!JSON.parse(store.getItem('astarryia-chemistry-mastery-v1')||'null')}catch(e){}return '<div class="card"><div class="phase">Day 1 Summary</div><h2>Progress</h2><table class="summaryTable">'+Object.keys(areas).map(function(id){var s=session(id);return '<tr><td>'+areas[id].name+'</td><td><b>'+(state.math.statuses[id]||s.status||'Not started')+'</b></td></tr>'}).join('')+'<tr><td>Chemistry Lewis structures</td><td><b>'+(chemDone?'Mastery evidence complete':'In progress')+'</b></td></tr><tr><td>Notebook facts saved</td><td><b>'+state.notebook.length+'</b></td></tr><tr><td>Review items</td><td><b>'+(state.sameSessionReview.length+state.nextSessionQueue.length)+'</b></td></tr></table></div>'}
function review(){var q=state.sameSessionReview.concat(state.nextSessionQueue);return '<div class="card"><h2>Review Queue</h2>'+(q.length?q.map(function(x){return '<div class="queue">'+esc((areas[x]&&areas[x].name)||x)+'</div>'}).join(''):'<p>Nothing queued right now.</p>')+'</div>'}
function render(){root.innerHTML=view==='home'?home():view==='math'?math():view==='chemistry'?chemistry():view==='notebook'?notebook():view==='review'?review():summary();bind();}
function finishProbe(id){var s=session(id);if(s.score===3){s.status='Cleared';s.phase='done';state.math.statuses[id]='Cleared';saveUI();render();return}if(s.score===2){s.phase='practice';s.verification=true;s.practiceNeeded=2;s.practiceIndex=0;s.practiceCorrect=0;s.currentItem=null;saveUI();render();return}s.phase='teach';s.step=0;s.afterTeachPractice=true;s.verification=false;saveUI();render();var x=areas[id].steps[0];speak(x.say)}
function finishPractice(id){var s=session(id);var needed=s.practiceNeeded,pass=s.verification?s.practiceCorrect===needed:s.practiceCorrect>=Math.max(3,needed-1);s.status=pass?'Cleared':'Developing';s.phase='done';state.math.statuses[id]=s.status;if(!pass&&state.nextSessionQueue.indexOf(id)<0)state.nextSessionQueue.push(id);saveUI();render()}
function bind(){document.querySelectorAll('[data-go]').forEach(function(b){b.onclick=function(){setView(this.dataset.go)}});document.querySelectorAll('[data-area]').forEach(function(b){b.onclick=function(){ui.mathArea=this.dataset.area;saveUI();render()}});
['mathMenu','mathMenu2'].forEach(function(id){if($(id))$(id).onclick=function(){ui.mathArea=null;saveUI();render()}});
if($('teachFirst'))$('teachFirst').onclick=function(){var s=session(ui.mathArea);s.phase='teach';s.step=0;s.afterTeachPractice=true;saveUI();render();speak(areas[ui.mathArea].steps[0].say)};
if($('tryFirst'))$('tryFirst').onclick=function(){var s=session(ui.mathArea);s.phase='probe';s.probeIndex=0;s.score=0;saveUI();render()};
if($('back'))$('back').onclick=function(){var s=session(ui.mathArea);if(s.step>0)s.step--;saveUI();render();speak(areas[ui.mathArea].steps[s.step].say)};
if($('next'))$('next').onclick=function(){var s=session(ui.mathArea),a=areas[ui.mathArea];if(s.step<a.steps.length-1){s.step++;saveUI();render();speak(a.steps[s.step].say)}else{s.phase='practice';s.verification=false;s.practiceNeeded=5;s.practiceIndex=0;s.practiceCorrect=0;s.currentItem=null;saveUI();render()}};
if($('replay'))$('replay').onclick=function(){var s=session(ui.mathArea),x=areas[ui.mathArea].steps[s.step];speak(x.say+' '+x.v.replace(/\n/g,'. '))};
if($('stillIdk'))$('stillIdk').onclick=function(){var s=session(ui.mathArea),x=areas[ui.mathArea].steps[s.step];$('feedback').innerHTML='<div class="idkbox"><b>Let me make this exact step smaller.</b><p>'+esc(x.say)+'</p><div style="white-space:pre-line;font-weight:800">'+esc(x.v)+'</div></div>';O.scheduleReview(state,ui.mathArea,'repeated_idk');saveUI()};
if($('skipTry'))$('skipTry').onclick=function(){var s=session(ui.mathArea);s.phase='probe';s.probeIndex=0;s.score=0;saveUI();render()};
if($('fullLesson'))$('fullLesson').onclick=function(){var s=session(ui.mathArea);s.phase='teach';s.step=0;s.afterTeachPractice=true;s.currentItem=null;saveUI();render();speak(areas[ui.mathArea].steps[0].say)};
if($('checkProbe'))$('checkProbe').onclick=function(){var id=ui.mathArea,s=session(id),q=areas[id].probe[s.probeIndex],v=$('answer').value.trim();if(!v)return;if(probeCorrect(q,v))s.score++;else O.scheduleReview(state,id,'repeated_idk');s.probeIndex++;saveUI();if(s.probeIndex>=3)finishProbe(id);else render()};
if($('idkProbe'))$('idkProbe').onclick=function(){var id=ui.mathArea,s=session(id),q=areas[id].probe[s.probeIndex];$('feedback').innerHTML='<div class="idkbox">'+exactHelp(id,q[0])+'</div>';O.scheduleReview(state,id,'repeated_idk');saveUI()};
if($('checkPractice'))$('checkPractice').onclick=function(){var id=ui.mathArea,s=session(id),v=$('answer').value.trim();if(!v)return;if(s.currentItem.check(v)){s.practiceCorrect++;$('feedback').innerHTML='<div class="feedback good"><b>Correct.</b> A fresh problem is next.</div>';}else{$('feedback').innerHTML='<div class="feedback bad"><b>Not yet.</b>'+exactHelp(id,s.currentItem.prompt)+'</div>';O.scheduleReview(state,id,'repeated_idk');}s.practiceIndex++;s.currentItem=null;saveUI();if(s.practiceIndex>=s.practiceNeeded)setTimeout(function(){finishPractice(id)},450);else setTimeout(render,450)};
if($('idkPractice'))$('idkPractice').onclick=function(){var id=ui.mathArea,s=session(id);$('feedback').innerHTML='<div class="idkbox">'+exactHelp(id,s.currentItem.prompt)+'</div>';O.scheduleReview(state,id,'repeated_idk');saveUI()};
if($('morePractice'))$('morePractice').onclick=function(){var s=session(ui.mathArea);s.phase='practice';s.verification=false;s.practiceNeeded=5;s.practiceIndex=0;s.practiceCorrect=0;s.currentItem=null;saveUI();render()};
if($('chemTeach'))$('chemTeach').onclick=function(){ui.chemMode='teach';saveUI();render()};if($('chemPractice'))$('chemPractice').onclick=function(){ui.chemMode='practice';saveUI();render()};if($('chemMenu'))$('chemMenu').onclick=function(){ui.chemMode='menu';saveUI();render()};}
window.addEventListener('message',function(e){if(!e.data||e.data.type!=='dr-merissa-notebook-fact')return;O.addNotebookFact(state,e.data.fact,'TEACH');saveUI()});
render();
})();