(function(){'use strict';
var O=globalThis.Day1Orchestrator,G=globalThis.MathGymEngine,store=localStorage,state=O.load(store),view='home';
var $=function(id){return document.getElementById(id)};
var root=$('view');
var started=Number(store.getItem('astarryia-math-started-at')||0);if(!started){started=Date.now();store.setItem('astarryia-math-started-at',String(started));}
var S={area:null,phase:'menu',entry:null,step:0,probeIndex:0,score:0,practice:[],pi:0,correct:0,current:null,verification:0,needsFull:false};
var areas={
logs:{name:'Logs & estimation',engine:'logs_estimation',probe:[['log(10,000) =',4],['If log(x) = −4, x =','0.0001'],['Estimate −log(6×10⁻⁶)',5.2,.15]],lessons:[
['What a log asks','A logarithm asks which exponent belongs on ten.','10³ = 1000\nlog(1000) = 3'],
['Power-of-ten anchors','Learn a few landmarks, not log one through twenty-nine.','log(1)=0   log(10)=1   log(100)=2\nlog(0.1)=−1'],
['Useful small landmarks','For no-calculator estimation, a tiny toolbox is enough.','log(2)≈0.30   log(3)≈0.48   log(5)≈0.70'],
['Build log six','Six is two times three, so use the product rule.','log(6)=log(2)+log(3)\n≈0.30+0.48=0.78'],
['pKa-style example','Separate the power of ten first, then handle the front number.','−log(6×10⁻⁶)=6−log(6)\n≈6−0.78=5.22']],toolbox:['log(1)=0','log(10)=1','log(100)=2','log(2)≈0.30','log(3)≈0.48','log(5)≈0.70','log(ab)=log(a)+log(b)']},
algebra:{name:'Algebra',engine:'algebra',probe:[['4x + 5 = x + 20',5],['Solve V=lwh for h','V/(lw)'],['2/x = 6/15',5]],lessons:[
['Equation means balance','Both sides have the same value. Whatever operation happens to one side must happen to the other.','7x + 2 = 3x + 26'],
['Collect x terms','Subtract 3x from both sides.','4x + 2 = 26'],
['Move constants','Subtract 2 from both sides.','4x = 24'],
['Isolate x','Divide both sides by 4.','x = 6'],
['What cross-multiply means','For a proportion, multiply diagonally across the equals sign. This clears the denominators.','2/x = 6/15\n2×15 = 6×x\n30 = 6x\nx = 5']],toolbox:['Equals sign = balance','Undo addition/subtraction first','Undo multiplication/division next','Proportion: multiply diagonally, then solve']},
exponents:{name:'Exponents',engine:'exponents',probe:[['2^-4 =','1/16'],['(a^4)(a^3)/a^2 =','a^5'],['10^2 × 10^3 =','100000']],lessons:[
['Exponent means repeated multiplication','An exponent counts repeated factors.','a⁴ = a·a·a·a'],
['Product rule','Same base multiplied means count all factors, so add exponents.','a⁴·a³ = a⁷'],
['Quotient rule','Same base divided means cancel factors, so subtract exponents.','a⁷/a² = a⁵'],
['Negative exponent','A negative exponent means reciprocal, not a negative value.','2⁻⁴ = 1/2⁴ = 1/16']],toolbox:['Same base ×: add exponents','Same base ÷: subtract exponents','Negative exponent: reciprocal','Anything nonzero to 0 = 1']},
scientific_notation:{name:'Scientific notation',engine:'scientific_notation',probe:[['0.00061 =','6.1x10^-4'],['(4.0×10^6)(2.0×10^-3) =','8x10^3'],['(9.0×10^-5)/(3.0×10^-2) =','3x10^-3']],lessons:[
['One nonzero digit first','Scientific notation uses a number from 1 up to 10 times a power of ten.','0.00061 = 6.1 × 10⁻⁴'],
['Decimal movement','Count the decimal moves. The direction determines the sign of the exponent.','61000 → 6.1 × 10⁴\n0.0061 → 6.1 × 10⁻³'],
['Multiply','Multiply the front numbers and add exponents.','(4×10⁶)(2×10⁻³)=8×10³'],
['Divide','Divide the front numbers and subtract exponents, then renormalize.','(9×10⁻⁵)/(3×10⁻²)=3×10⁻³']],toolbox:['Coefficient must be ≥1 and <10','Multiply: multiply coefficients, add exponents','Divide: divide coefficients, subtract exponents','Renormalize at the end']},
fractions_percent:{name:'Fractions & percentages',engine:'fractions_percentages',probe:[['5/6 − 1/3 =','1/2'],['3/8 of 160 =',60],['24 is what percent of 300?',8]],lessons:[
['Fractions need equal-sized pieces','Before adding or subtracting fractions, make the denominators match.','5/6 − 1/3\n= 5/6 − 2/6\n= 3/6 = 1/2'],
['Percent means out of 100','Percent is another way to describe a fraction of one hundred.','25% = 25/100 = 1/4'],
['Mental percent anchors','Use a tiny set of anchors to do common percentages in your head.','10% = ÷10\n1% = ÷100\n5% = half of 10%\n25% = one fourth\n50% = half'],
['24 is what percent of 300? Mental route','Ten percent of 300 is 30. Two percent is 6. Since 24 is 30 minus 6, 24 is 8 percent.','10% of 300 = 30\n2% of 300 = 6\n30 − 6 = 24\n10% − 2% = 8%'],
['Same problem, formal route','Now connect the mental route to part divided by whole times one hundred.','24 ÷ 300 × 100\n= 0.08 × 100\n= 8%'],
['Flexible mental math','Build other percentages from the anchors instead of reaching for a calculator.','15% of 80 = 8 + 4 = 12\n25% of 60 = 60 ÷ 4 = 15\n75% of 40 = 20 + 10 = 30']],toolbox:['10% = divide by 10','1% = divide by 100','5% = half of 10%','20% = double 10%','25% = one fourth','50% = one half','75% = one half + one fourth','Formal: part ÷ whole × 100']},
unit_conversions:{name:'Unit conversions',engine:'unit_conversions',probe:[['0.062 L to mL',62],['8 g/5 min for 12 min',19.2],['0.015 mol/s to mmol/min',900]],lessons:[
['Conversion changes the unit, not the amount','Start with an anchor relationship and predict whether the number should grow or shrink.','1 L = 1000 mL'],
['Big unit to smaller unit','Liters to milliliters makes the number larger, so multiply by 1000.','2.5 L × 1000 = 2500 mL'],
['Small unit to bigger unit','Milliliters to liters makes the number smaller, so divide by 1000.','750 mL ÷ 1000 = 0.75 L'],
['Let the units prove the setup','Put the unit you have opposite itself in the conversion factor. The matching units cancel on the written setup.','0.062 L × (1000 mL / 1 L)\nL cancels → 62 mL'],
['Pharmacy metric anchors','The same thousand pattern repeats through common metric pharmacy units.','1 L = 1000 mL\n1 g = 1000 mg\n1 mg = 1000 mcg'],
['Rate conversions','For a rate, change one unit at a time and keep labels visible until they cancel.','0.015 mol/s × 1000 mmol/mol × 60 s/min\n= 900 mmol/min'],
['U.S. volume anchors','Use a small toolbox for common U.S. volume relationships.','1 gal = 4 qt\n1 qt = 2 pt\n1 pt = 2 cups\n1 gal = 16 cups']],toolbox:['1 L = 1000 mL','1 g = 1000 mg','1 mg = 1000 mcg','1 gal = 4 qt','1 qt = 2 pt','1 pt = 2 cups','Big → small: number gets bigger','Small → big: number gets smaller','Set factors so units cancel']}
};
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])})}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.rate=.9;speechSynthesis.speak(u)}
function save(){O.save(state,store);if($('saveState'))$('saveState').textContent='Saved just now'}
function mins(){return Math.floor((Date.now()-started)/60000)}
function timer(){if($('mathTimer'))$('mathTimer').textContent='Math '+mins()+' min'}setInterval(timer,15000);
function setView(v){view=v;document.querySelectorAll('#navTabs button').forEach(function(b){b.classList.toggle('on',b.dataset.view===v)});render()}
$('navTabs').addEventListener('click',function(e){if(e.target.dataset.view)setView(e.target.dataset.view)});
function toolbox(a){return '<details class="card" open><summary><b>Math Toolbox</b></summary><div class="chips" style="margin-top:12px">'+a.toolbox.map(function(x){return '<span class="pill">'+esc(x)+'</span>'}).join('')+'</div></details>'}
function home(){var cleared=Object.keys(state.math.statuses).filter(function(k){return state.math.statuses[k]==='Cleared'}).length;return '<div class="hero"><div class="phase">DAY 1</div><h1>Choose where you want to work.</h1><p>Math and chemistry save separately. Nothing has to be finished before you switch subjects.</p></div><div class="grid"><div class="card subject"><h2>Math Foundation</h2><p>'+cleared+' of '+state.math.order.length+' areas cleared. All six original math areas are here.</p><button class="btn" data-go="math">Open math</button></div><div class="card subject"><h2>Chemistry Foundation</h2><p>Learn with the animated teacher or try first and get support from mistakes.</p><button class="btn" data-go="chemistry">Open chemistry</button></div></div>'}
function mathMenu(){return '<div class="card"><div class="phase">Adaptive Math Reset</div><h2>Choose a math area</h2><p class="muted">Logs, algebra, exponents, scientific notation, fractions/percentages and unit conversions are all preserved.</p><div class="grid">'+state.math.order.map(function(id){var a=areas[id],st=state.math.statuses[id]||'Not started';return '<button class="mathArea" data-area="'+id+'"><b>'+a.name+'</b><span class="status">'+st+'</span></button>'}).join('')+'</div></div>'}
function entry(a){return '<div class="card"><div class="phase">'+a.name+'</div><h2>How do you want to start?</h2><div class="actions"><button class="btn" id="teachFirst">▶ Teach me the lesson</button><button class="btn secondary" id="tryFirst">✏️ Let me try it first</button></div><p class="muted">Trying first keeps the 3-question adaptive probe. You can open the full lesson at any time.</p></div>'}
function lesson(a){var l=a.lessons[S.step];return '<div class="card teacher"><div class="avatar">🎓</div><div class="bubble"><b>Dr. Merissa</b><div>'+esc(l[1])+'</div></div></div><div class="card"><div class="phase">Learning • '+(S.step+1)+' of '+a.lessons.length+'</div><h2>'+esc(l[0])+'</h2><div class="stage"><div class="visual small" style="white-space:pre-line">'+esc(l[2])+'</div></div><div class="actions" style="margin-top:12px"><button class="btn secondary" id="back" '+(S.step===0?'disabled':'')+'>← Back</button><button class="btn" id="next">'+(S.step===a.lessons.length-1?'Start 3-question probe →':'Next →')+'</button><button class="btn secondary" id="replay">Replay this step</button><button class="btn ghost" id="stillIdk">I still don’t get this</button><button class="btn ghost" id="skipToProbe">Skip lesson and try</button></div><div id="help"></div></div>'+toolbox(a)}
function probe(a){var q=a.probe[S.probeIndex];return '<div class="card"><div class="phase">Probe '+(S.probeIndex+1)+' of 3</div><h2>'+a.name+'</h2><div class="question">'+esc(q[0])+'</div><input id="answer" class="input" autocomplete="off"><div class="actions" style="margin-top:12px"><button class="btn" id="checkProbe">Check answer</button><button class="btn secondary" id="probeIdk">I don’t know yet</button><button class="btn ghost" id="fullLesson">Teach the full lesson</button></div><div id="feedback"></div></div>'+toolbox(a)}
function practice(a){if(!S.current)S.current=G.generate(a.engine);return '<div class="card"><div class="phase">'+(S.verification?'Fresh verification':'Guided → independent practice')+'</div><h2>'+a.name+'</h2><div class="question">'+esc(S.current.prompt)+'</div><input id="answer" class="input" autocomplete="off"><div class="actions" style="margin-top:12px"><button class="btn" id="checkPractice">Check answer</button><button class="btn secondary" id="practiceIdk">I don’t know yet</button><button class="btn ghost" id="fullLesson">Teach the full lesson</button></div><div class="muted" style="margin-top:8px">Question '+(S.pi+1)+' of '+S.practice.length+'</div><div id="feedback"></div></div>'+toolbox(a)}
function result(a){var st=state.math.statuses[S.area];return '<div class="card '+(st==='Cleared'?'success':'warning')+'"><h2>'+a.name+': '+st+'</h2><p>'+(st==='Cleared'?'Enough independent evidence for today.':'Saved as Developing. It returns for review and does not block chemistry.')+'</p><div class="actions"><button class="btn" id="another">Choose another math area</button><button class="btn secondary" data-go="chemistry">Switch to chemistry</button></div></div>'}
function math(){if(mins()>=60)return '<div class="card warning"><h2>60-minute math cap reached.</h2><p>Unfinished areas are saved for later. Chemistry remains available.</p><button class="btn" data-go="chemistry">Go to chemistry</button></div>';var top=mins()>=50?'<div class="warning">50-minute checkpoint: new areas use the short probe. Unclear areas are saved as Developing instead of starting a long reteach.</div>':'';if(!S.area||S.phase==='menu')return top+mathMenu();var a=areas[S.area];if(S.phase==='entry')return top+entry(a);if(S.phase==='teach')return top+lesson(a);if(S.phase==='probe')return top+probe(a);if(S.phase==='practice')return top+practice(a);return top+result(a)}
function norm(s){return String(s).toLowerCase().replace(/\s+/g,'').replace(/×/g,'x').replace(/⁻/g,'-').replace(/⁴/g,'^4').replace(/⁵/g,'^5').replace(/³/g,'^3').replace(/²/g,'^2')}
function probeOK(q,v){if(typeof q[1]==='number')return Math.abs(Number(v)-q[1])<=(q[2]||1e-9);return norm(v)===norm(q[1])}
function targeted(area,prompt){if(area==='fractions_percent'&&/percent/i.test(prompt))return '<b>Let’s teach THIS percent problem.</b><p>Start with 10% and 1% of the whole. Build the answer mentally, then verify with <b>part ÷ whole × 100</b>. Example: 24 of 300 → 10%=30, 2%=6, so 8%=24.</p>';if(area==='fractions_percent')return '<b>Let’s teach THIS fraction.</b><p>Make the denominator pieces the same size first. Rewrite each fraction, then combine the numerators.</p>';if(area==='unit_conversions')return '<b>Let’s teach THIS conversion.</b><p>Do not circle or drag anything that is not actually interactive. Use the written labels. Start from an anchor such as 1 L = 1000 mL, predict whether the number should grow or shrink, then write the factor so matching units cancel.</p>';if(area==='logs')return '<b>Let’s teach THIS log step.</b><p>Ask “10 to what power?” first. For no-calculator estimates use only the toolbox landmarks, then build values like log(6)=log(2)+log(3).</p>';if(area==='algebra')return '<b>Let’s teach THIS algebra step.</b><p>Keep the equals sign balanced. For proportions, cross-multiply means multiply diagonally across the equals sign, write the new equation, then solve it.</p>';if(area==='exponents')return '<b>Let’s teach THIS exponent step.</b><p>Expand one power as repeated multiplication so you can see whether factors combine, cancel, or flip into a reciprocal.</p>';return '<b>Let’s teach THIS scientific-notation step.</b><p>First normalize the front number between 1 and 10, then count decimal moves and handle exponent arithmetic separately.</p>'}
function startArea(id){S={area:id,phase:'entry',entry:null,step:0,probeIndex:0,score:0,practice:[],pi:0,correct:0,current:null,verification:0,needsFull:false};state.math.index=Math.max(0,state.math.order.indexOf(id));O.setSubject(state,'math');save();render()}
function startProbe(){S.phase='probe';S.probeIndex=0;S.score=0;render()}
function makePractice(n,verification){S.practice=[];for(var i=0;i<n;i++)S.practice.push(G.generate(areas[S.area].engine));S.pi=0;S.correct=0;S.current=S.practice[0];S.verification=verification||0;S.phase='practice';render()}
function finishProbe(){var score=S.score,id=S.area;if(score===3){state.math.statuses[id]='Cleared';S.phase='result';save();render();return}if(mins()>=50){state.math.statuses[id]='Developing';if(state.nextSessionQueue.indexOf(id)<0)state.nextSessionQueue.push(id);S.phase='result';save();render();return}if(score===2){makePractice(2,2);return}S.needsFull=true;S.phase='teach';S.step=0;render();speak(areas[id].lessons[0][1])}
function finishPractice(){var clear=S.verification?S.correct===S.practice.length:(S.correct>=3&&S.practice.length>=4);state.math.statuses[S.area]=clear?'Cleared':'Developing';if(!clear&&state.nextSessionQueue.indexOf(S.area)<0)state.nextSessionQueue.push(S.area);S.phase='result';save();render()}
function chemistry(){return '<div class="card"><div class="phase">Chemistry Foundation</div><h2>How do you want to start?</h2><div class="actions"><button class="btn" id="chemTeach">▶ Teach me the lesson</button><button class="btn secondary" id="chemTry">✏️ Let me try it first</button></div><p class="muted">Teaching keeps the animated electron lesson, Back, Replay and alternate explanations. Trying first opens the chemistry practice system.</p></div><div id="chemHost"></div>'}
function notebook(){return '<div class="card"><h2>Notebook</h2>'+(state.notebook.length?state.notebook.map(function(x){return '<div class="notebookFact">'+esc(x)+'</div>'}).join(''):'<p>No lesson facts saved yet.</p>')+'</div>'}
function review(){var q=state.sameSessionReview.concat(state.nextSessionQueue);return '<div class="card"><h2>Review Queue</h2>'+(q.length?q.map(function(x){return '<div class="queue">'+esc((areas[x]&&areas[x].name)||x)+'</div>'}).join(''):'<p>Nothing queued yet.</p>')+'</div>'}
function summary(){return '<div class="card"><h2>Day 1 Summary</h2><table class="summaryTable">'+state.math.order.map(function(id){return '<tr><td>'+areas[id].name+'</td><td><b>'+(state.math.statuses[id]||'Not started')+'</b></td></tr>'}).join('')+'</table></div>'}
function render(){root.innerHTML=view==='home'?home():view==='math'?math():view==='chemistry'?chemistry():view==='notebook'?notebook():view==='review'?review():summary();bind();timer()}
function bind(){document.querySelectorAll('[data-go]').forEach(function(b){b.onclick=function(){setView(this.dataset.go)}});document.querySelectorAll('[data-area]').forEach(function(b){b.onclick=function(){startArea(this.dataset.area)}});
var b=$('teachFirst');if(b)b.onclick=function(){S.phase='teach';S.step=0;render();speak(areas[S.area].lessons[0][1])};b=$('tryFirst');if(b)b.onclick=startProbe;
b=$('back');if(b)b.onclick=function(){if(S.step>0)S.step--;render();speak(areas[S.area].lessons[S.step][1])};b=$('next');if(b)b.onclick=function(){var a=areas[S.area];if(S.step<a.lessons.length-1){S.step++;render();speak(a.lessons[S.step][1])}else if(S.needsFull){S.needsFull=false;makePractice(4,0)}else startProbe()};b=$('replay');if(b)b.onclick=function(){speak(areas[S.area].lessons[S.step][1])};b=$('stillIdk');if(b)b.onclick=function(){$('help').innerHTML='<div class="idkbox"><b>Let me make this smaller.</b><p>'+esc(areas[S.area].lessons[S.step][1])+'</p><p>You can go Back or Replay without restarting.</p></div>'};b=$('skipToProbe');if(b)b.onclick=startProbe;
b=$('fullLesson');if(b)b.onclick=function(){S.phase='teach';S.step=0;render();speak(areas[S.area].lessons[0][1])};b=$('probeIdk');if(b)b.onclick=function(){$('feedback').innerHTML='<div class="idkbox">'+targeted(S.area,areas[S.area].probe[S.probeIndex][0])+'<p class="muted">Stay on this exact problem until the step makes sense.</p></div>';O.scheduleReview(state,S.area,'repeated_idk');save()};
b=$('checkProbe');if(b)b.onclick=function(){var q=areas[S.area].probe[S.probeIndex],v=$('answer').value;if(probeOK(q,v))S.score++;else O.scheduleReview(state,S.area,'repeated_idk');S.probeIndex++;save();if(S.probeIndex>=3)finishProbe();else render()};
b=$('practiceIdk');if(b)b.onclick=function(){$('feedback').innerHTML='<div class="idkbox">'+targeted(S.area,S.current.prompt)+'</div>';O.scheduleReview(state,S.area,'repeated_idk');save()};b=$('checkPractice');if(b)b.onclick=function(){var ok=S.current.check($('answer').value);if(ok)S.correct++;else O.scheduleReview(state,S.area,'repeated_idk');S.pi++;save();if(S.pi>=S.practice.length)finishPractice();else{S.current=S.practice[S.pi];render()}};
b=$('another');if(b)b.onclick=function(){S.area=null;S.phase='menu';render()};b=$('chemTeach');if(b)b.onclick=function(){$('chemHost').innerHTML='<div class="card iframeWrap"><iframe src="../chemistry-teacher-preview/" title="Chemistry teacher lesson"></iframe></div>'};b=$('chemTry');if(b)b.onclick=function(){$('chemHost').innerHTML='<div class="card iframeWrap"><iframe src="../chemistry-teacher-preview/#practice" title="Chemistry practice"></iframe></div>'};}
render();})();