(function(){'use strict';var O=window.Day1Orchestrator,G=window.MathGymEngine;if(!O||!G)return;var s=O.load(localStorage),item=null,probeCorrect=0,probeSeen=0,mode='probe',lessonStep=0;
var names={logs:'Logs and pKa math',algebra:'Algebra',exponents:'Exponent rules',scientific_notation:'Scientific notation',fractions_percent:'Fractions and percentages',unit_conversions:'Unit conversions'};
var $=function(id){return document.getElementById(id)};
function persist(){O.save(s,localStorage);renderSummary();}
function generator(area){var map={logs:'logs_estimation',algebra:'algebra',exponents:'exponents',scientific_notation:'scientific_notation',fractions_percent:'fractions_percentages',unit_conversions:'unit_conversions'};return G.generate(map[area]||area);}
function show(panel){['mathPanel','chemPanel','notebookPanel'].forEach(function(x){$(x).classList.toggle('hidden',x!==panel)});$('mathTab').className=panel==='mathPanel'?'active':'secondary';$('chemTab').className=panel==='chemPanel'?'active':'secondary';$('notebookTab').className=panel==='notebookPanel'?'active':'secondary';}
function area(){return O.currentMathArea(s)}
function newProblem(){if(!area()){finishMath();return;}item=generator(area());$('mathTitle').textContent=names[area()]||area();$('mathProblem').textContent=item.prompt;$('mathAnswer').value='';$('mathFeedback').textContent='';$('mathProgress').textContent=mode==='probe'?'Quick check '+(probeSeen+1)+' of 3':'Practice until you can do it without me.';}
function explain(){var a=area(),t='';if(a==='logs'){t='A log asks: 10 to what power makes this number? Anchor facts are log(1)=0, log(10)=1, log(100)=2, and log(0.1)=-1. You do not memorize log 1 through 29. For estimates, locate the number between powers of ten first.';O.addNotebookFact(s,'Logs: ask “10 to what power?” Use powers-of-ten anchors; do not memorize log 1–29.','TEACH');}
else if(a==='algebra'){t='Your goal is to isolate the unknown. Whatever operation you do to one side, do to the other. In a proportion, cross multiply means multiply diagonally: top-left × bottom-right and top-right × bottom-left, then set those products equal.';O.addNotebookFact(s,'Proportions: cross multiply diagonally, then solve the resulting equation.','TEACH');}
else if(a==='exponents'){t='Same-base product rule: add exponents. Same-base quotient rule: subtract exponents. A negative exponent means reciprocal, not a negative number.';O.addNotebookFact(s,'Exponent rules: product → add exponents; quotient → subtract; negative exponent → reciprocal.','TEACH');}
else if(a==='scientific_notation'){t='Scientific notation has one nonzero digit before the decimal. Moving the decimal left makes the exponent larger; moving it right makes the exponent smaller.';O.addNotebookFact(s,'Scientific notation: one nonzero digit before the decimal; track decimal moves with the power of 10.','TEACH');}
else if(a==='fractions_percent'){t='A percent means out of 100. For fraction work, first decide whether you need a common denominator. Keep the meaning of the quantity before doing arithmetic.';O.addNotebookFact(s,'Percent means “out of 100.” Fractions need a common denominator for addition/subtraction.','TEACH');}
else{t='Unit conversion is multiplication by a form of 1. Put the unwanted unit opposite itself so it cancels. For stacked rates, cancel one unit at a time.';O.addNotebookFact(s,'Unit conversions: arrange conversion factors so unwanted units cancel.','TEACH');}
$('mathTeacher').textContent=t;mode='lesson';lessonStep=0;O.scheduleReview(s,a,'repeated_idk');persist();}
function diagnoseWrong(v){var a=area();if(a==='logs')return 'Your answer tells me we should rebuild the power-of-ten anchor before estimating this log.';if(a==='algebra')return 'This looks like the equation setup or inverse-operation step needs attention. We will work that step, not restart unrelated easy problems.';if(a==='exponents')return 'We need to identify which exponent rule applies before calculating.';if(a==='scientific_notation')return 'Check two things separately: decimal placement and exponent direction.';if(a==='fractions_percent')return 'We need to identify the relationship first: fraction operation, fraction of a whole, or percent.';return 'Track the units themselves. The unit that should disappear must appear once on top and once on bottom.';}
function submit(){if(!item)return;var v=$('mathAnswer').value.trim();if(!v){$('mathFeedback').innerHTML='<span class="bad">Type an answer, or choose I don\'t know.</span>';return;}var correct=item.check(v);if(mode==='probe'){probeSeen++;if(correct)probeCorrect++;$('mathFeedback').innerHTML=correct?'<span class="good">Yes.</span>':'<span class="bad">Not yet.</span> '+diagnoseWrong(v);if(probeSeen>=3){var route=O.routeMathProbe(s,probeCorrect);if(route.action==='clear_area'){O.markMathStatus(s,'Cleared');$('mathTeacher').textContent='You showed this skill three times. Cleared. Moving forward.';resetProbe();setTimeout(newProblem,450);}else{explain();$('mathFeedback').textContent=route.action==='targeted_correction_then_verify'?'You are close. I am correcting the exact weak step, then you will verify it twice.':'We found a real gap. I will teach it, practice with you, then remove the help.';}}else setTimeout(newProblem,350);return;}
if(correct){lessonStep++;$('mathFeedback').innerHTML='<span class="good">Correct.</span> Now prove it again on a fresh problem.';if(lessonStep>=4){O.markMathStatus(s,'Cleared');resetProbe();persist();setTimeout(newProblem,450);}else setTimeout(newProblem,350);}else{$('mathFeedback').innerHTML='<span class="bad">Not yet.</span> '+diagnoseWrong(v)+' '+$('mathTeacher').textContent;O.scheduleReview(s,area(),'repeated_idk');persist();setTimeout(newProblem,900);}}
function resetProbe(){mode='probe';probeSeen=0;probeCorrect=0;lessonStep=0;persist();}
function finishMath(){$('mathTitle').textContent='Math reset complete';$('mathProblem').textContent='✓';$('mathTeacher').textContent='Day 1 math areas are complete. Developing skills remain in the review queue instead of disappearing.';$('mathAnswer').classList.add('hidden');$('mathCheck').classList.add('hidden');}
function renderNotebook(){$('notebook').innerHTML=s.notebook.length?s.notebook.map(function(x){return '<div class="pill">'+x+'</div>'}).join(''):'Nothing here yet. The notebook fills only with things actually taught.';$('review').innerHTML=(s.sameSessionReview.concat(s.nextSessionQueue)).length?s.sameSessionReview.concat(s.nextSessionQueue).map(function(x){return '<div class="pill">'+ (names[x]||x) +'</div>'}).join(''):'No queued review right now.';}
function renderSummary(){var statuses=s.math.statuses||{},cleared=Object.keys(statuses).filter(function(k){return statuses[k]==='Cleared'}).length;$('summary').textContent=cleared+' of '+s.math.order.length+' math areas cleared • Chemistry progress is preserved separately • '+s.nextSessionQueue.length+' skill(s) queued for next session.';}
$('mathTab').onclick=function(){O.setSubject(s,'math');persist();show('mathPanel')};$('chemTab').onclick=function(){O.setSubject(s,'chemistry');persist();show('chemPanel')};$('notebookTab').onclick=function(){renderNotebook();show('notebookPanel')};$('mathCheck').onclick=submit;$('mathAnswer').addEventListener('keydown',function(e){if(e.key==='Enter')submit()});$('mathIdk').onclick=function(){O.scheduleReview(s,area(),'repeated_idk');explain();$('mathFeedback').textContent='That is useful information. I am teaching this exact skill now, then I will give you a fresh problem.';persist();};$('mathTeach').onclick=explain;
if(s.updatedAt){$('resume').classList.remove('hidden');$('resume').innerHTML='<b>Welcome back.</b> Your place was saved. You can switch subjects without losing your work.';}renderSummary();show(s.subject==='chemistry'?'chemPanel':'mathPanel');newProblem();})();