(function(){'use strict';var O=window.Day1Orchestrator,G=window.MathGymEngine;if(!O||!G)return;var s=O.load(localStorage),item=null,probeCorrect=0,probeSeen=0,mode='probe',needed=0,practiceSeen=0,practiceCorrect=0;
var names={logs:'Logs and pKa math',algebra:'Algebra',exponents:'Exponent rules',scientific_notation:'Scientific notation',fractions_percent:'Fractions and percentages',unit_conversions:'Unit conversions'};
var map={logs:'logs_estimation',algebra:'algebra',exponents:'exponents',scientific_notation:'scientific_notation',fractions_percent:'fractions_percentages',unit_conversions:'unit_conversions'};
var $=function(id){return document.getElementById(id)};if(!s.math.startedAt)s.math.startedAt=Date.now();
function persist(){O.save(s,localStorage);renderSummary()}
function area(){return O.currentMathArea(s)}function generator(a){return G.generate(map[a]||a)}
function elapsed(){return Math.floor((Date.now()-s.math.startedAt)/60000)}
function show(panel){['mathPanel','chemPanel','notebookPanel'].forEach(function(x){$(x).classList.toggle('hidden',x!==panel)});$('mathTab').className=panel==='mathPanel'?'active':'secondary';$('chemTab').className=panel==='chemPanel'?'active':'secondary';$('notebookTab').className=panel==='notebookPanel'?'active':'secondary'}
function hardStop(){if(elapsed()<60)return false;while(area())O.markMathStatus(s,'Developing');persist();finishMath('The 60-minute Math Reset cap was reached. Remaining areas are Developing and moved to Math Gym. Chemistry is next.');return true}
function checkpoint(){return elapsed()>=50}
function newProblem(){if(hardStop()||!area()){if(!area())finishMath();return}item=generator(area());$('mathTitle').textContent=names[area()]||area();$('mathProblem').textContent=item.prompt;$('mathAnswer').value='';$('mathFeedback').textContent='';$('mathProgress').textContent=(mode==='probe'?'Quick check '+(probeSeen+1)+' of 3':mode==='verify'?'Fresh verification '+(practiceSeen+1)+' of 2':'Independent practice '+(practiceSeen+1)+' of 4')+' • Math reset '+elapsed()+' min';}
function lessonText(a){if(a==='logs')return 'A log asks: 10 to what power makes this number? Anchor facts: log(1)=0, log(10)=1, log(100)=2, log(0.1)=-1. You do NOT memorize log 1 through 29. For estimates, locate the number between powers of ten first. Example: −log(4×10⁻⁵)=5−log(4), about 4.4.';if(a==='algebra')return 'An equation is a balance. Whatever you do to one side, do to the other. Collect variables, collect constants, then divide. Cross multiply means multiply diagonally across a proportion, then set those two products equal.';if(a==='exponents')return 'Negative exponent means reciprocal. Same-base multiplication adds exponents. Same-base division subtracts exponents. Example: a⁴×a³÷a² = a⁵.';if(a==='scientific_notation')return 'Scientific notation has one nonzero digit before the decimal. Multiply front numbers and add exponents; divide front numbers and subtract exponents.';if(a==='fractions_percent')return 'Fractions must be cut into equal-sized pieces before adding or subtracting. Percent means per hundred: part ÷ whole × 100.';return 'Convert one unit at a time. Multiply by a conversion factor arranged so the unwanted unit appears once on top and once on bottom and cancels.'}
function explain(targetMode){var a=area(),t=lessonText(a);$('mathTeacher').textContent=t;O.addNotebookFact(s,t,'TEACH');O.scheduleReview(s,a,'repeated_idk');if(targetMode){mode=targetMode;practiceSeen=0;practiceCorrect=0;needed=targetMode==='verify'?2:3}persist()}
function diagnoseWrong(v){var a=area();if(a==='logs')return 'First identify the power-of-ten anchor. Do not reach for a calculator or memorize a log table.';if(a==='algebra')return 'Find the first move where both sides stopped staying balanced. If this is a proportion, write the two diagonal products before solving.';if(a==='exponents')return 'Name the rule before calculating: product, quotient, or negative exponent.';if(a==='scientific_notation')return 'Separate decimal placement from exponent direction and check them one at a time.';if(a==='fractions_percent')return 'First classify the task: combine fractions, take a fraction of a whole, or find a percent.';return 'Write the units beside every number. The unwanted unit must cancel.'}
function completeArea(status,msg){O.markMathStatus(s,status);$('mathTeacher').textContent=msg;mode='probe';probeSeen=probeCorrect=practiceSeen=practiceCorrect=0;needed=0;persist();setTimeout(newProblem,450)}
function submit(){if(!item||hardStop())return;var v=$('mathAnswer').value.trim();if(!v){$('mathFeedback').innerHTML='<span class="bad">Type an answer, or choose I don\'t know.</span>';return}var correct=item.check(v);if(mode==='probe'){probeSeen++;if(correct)probeCorrect++;$('mathFeedback').innerHTML=correct?'<span class="good">Yes.</span>':'<span class="bad">Not yet.</span> '+diagnoseWrong(v);if(probeSeen<3){setTimeout(newProblem,350);return}if(checkpoint()){if(probeCorrect===3)completeArea('Cleared','Three for three. Cleared.');else completeArea('Developing','We are past the 50-minute checkpoint, so this area is Developing and moves to Math Gym instead of expanding today.');return}var route=O.routeMathProbe(s,probeCorrect);if(route.action==='clear_area'){completeArea('Cleared','You showed this skill three times. Cleared.');return}if(route.action==='targeted_correction_then_verify'){explain('verify');$('mathFeedback').textContent='You are close. I corrected the weak step. Now you need 2 fresh answers, both correct.';}else{explain('independent');$('mathFeedback').textContent='We found a real gap. I taught the rule. Now you need at least 3 of 4 fresh independent problems.';}setTimeout(newProblem,650);return}
practiceSeen++;if(correct)practiceCorrect++;$('mathFeedback').innerHTML=correct?'<span class="good">Correct.</span>':'<span class="bad">Not yet.</span> '+diagnoseWrong(v);var total=mode==='verify'?2:4;if(practiceSeen<total){setTimeout(newProblem,450);return}if(mode==='verify'){if(practiceCorrect===2)completeArea('Cleared','Both fresh verification items were correct. Cleared.');else{mode='independent';practiceSeen=practiceCorrect=0;needed=3;explain();$('mathFeedback').textContent='Verification exposed a gap, so we are escalating to the full mini-lesson path.';setTimeout(newProblem,650)}}else{if(practiceCorrect>=3)completeArea('Cleared','You got at least 3 of 4 fresh independent problems correct. Cleared.');else completeArea('Developing','This skill is not secure yet. It is marked Developing and queued for Math Gym instead of trapping you here.')}}
function finishMath(msg){$('mathTitle').textContent='Math reset complete';$('mathProblem').textContent='✓';$('mathTeacher').textContent=msg||'Day 1 math reset is complete. Developing areas stay in the review queue. Move to Chemistry when you are ready.';$('mathAnswer').classList.add('hidden');$('mathCheck').classList.add('hidden');$('mathIdk').classList.add('hidden');$('mathTeach').classList.add('hidden')}
function renderNotebook(){if(!O.notebookVisible(s)){$('notebook').textContent='Notebook hidden during unaided mastery.';return}$('notebook').innerHTML=s.notebook.length?s.notebook.map(function(x){return '<div class="pill">'+x+'</div>'}).join(''):'Nothing here yet. It fills only with material actually taught.';var q=s.sameSessionReview.concat(s.nextSessionQueue);$('review').innerHTML=q.length?q.map(function(x){return '<div class="pill">'+(names[x]||x)+'</div>'}).join(''):'No queued review right now.'}
function chemistryStatus(){try{var c=JSON.parse(localStorage.getItem('astarryia-chemistry-mastery-v1')||'null');if(c&&c.completedAt){s.chemistry.masteryMet=true;s.chemistry.phase='complete';return 'Met'}}catch(e){}return s.chemistry.masteryMet?'Met':'Not Met'}
function renderSummary(){var st=s.math.statuses||{},cleared=Object.keys(st).filter(function(k){return st[k]==='Cleared'}).length,developing=Object.keys(st).filter(function(k){return st[k]==='Developing'}).length;$('summary').textContent=cleared+' Cleared • '+developing+' Developing • Chemistry '+chemistryStatus()+' • progress saved locally.'}
$('mathTab').onclick=function(){O.setSubject(s,'math');persist();show('mathPanel')};$('chemTab').onclick=function(){O.setSubject(s,'chemistry');s.chemistry.phase='learning';persist();show('chemPanel')};$('notebookTab').onclick=function(){if(!O.notebookVisible(s))return;renderNotebook();show('notebookPanel')};$('mathCheck').onclick=submit;$('mathAnswer').addEventListener('keydown',function(e){if(e.key==='Enter')submit()});$('mathIdk').onclick=function(){O.scheduleReview(s,area(),'repeated_idk');explain(mode==='probe'?'independent':mode);$('mathFeedback').textContent='Good choice. I am teaching this exact skill, not sending you back to unrelated problems. Then you will get a fresh problem.';setTimeout(newProblem,650)};$('mathTeach').onclick=function(){explain(mode==='probe'?'independent':mode);setTimeout(newProblem,650)};
window.addEventListener('storage',function(e){if(e.key==='astarryia-chemistry-mastery-v1'){chemistryStatus();persist()}});if(s.updatedAt){$('resume').classList.remove('hidden');$('resume').innerHTML='<b>Welcome back.</b> Your place was saved. Switch subjects whenever you need to; neither side resets.'}renderSummary();show(s.subject==='chemistry'?'chemPanel':'mathPanel');newProblem();setInterval(function(){if(area())$('mathProgress').textContent=$('mathProgress').textContent.replace(/Math reset \d+ min/,'Math reset '+elapsed()+' min');renderSummary()},30000)})();