(function(root){'use strict';
function shouldAutoAdvance(mode){return mode==='speed';}
function scoreText(correct,total){return correct+' correct / '+total+' '+(total===1?'attempt':'attempts');}
function cleanNumber(n){n=Number(n);if(!Number.isFinite(n))return String(n);return Math.abs(n-Math.round(n))<1e-10?String(Math.round(n)):String(Math.round(n*1000000)/1000000);}
function norm(v){return String(v==null?'':v).trim().toLowerCase().replace(/\s+/g,'').replace(/−/g,'-').replace(/×/g,'x');}
function near(v,x,t){var n=Number(String(v).replace(/%/g,'').trim());return Number.isFinite(n)&&Math.abs(n-Number(x))<=(t==null?1e-9:t);}
function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b){var t=a%b;a=b;b=t;}return a||1;}
function lcm(a,b){return Math.abs(a*b)/gcd(a,b);}
function helpPolicy(mode){
 if(mode==='speed')return{available:false,masteryEnds:false,label:'No help during Speed Round'};
 if(mode==='mastery')return{available:true,masteryEnds:true,label:'Help me (practice this one)'};
 return{available:true,masteryEnds:false,label:'Help me'};
}
function masteryCreditAllowed(mode,helpTier,priorWrong){return mode==='mastery'&&Number(helpTier||0)===0&&!priorWrong;}
function fractionPercentHint(it){
 var type=it&&it.type,prompt=String(it&&it.prompt||'');
 if(type==='fraction_of_whole'){
  var m=prompt.match(/^([+-]?\d+)\/([+-]?\d+)\s+of\s+([+-]?(?:\d+(?:\.\d*)?|\.\d+))$/i);
  if(m){
   var n=Number(m[1]),d=Number(m[2]),whole=Number(m[3]),one=whole/d;
   if(Number.isFinite(one)&&d!==0)return 'This question wants an amount, not a percent. Divide '+cleanNumber(whole)+' by the denominator '+d+' first: '+cleanNumber(whole)+' ÷ '+d+' = '+cleanNumber(one)+'. Then multiply that amount by the numerator '+n+'.';
  }
  return 'This question wants an amount, not a percent. Divide the whole by the denominator first, then multiply by the numerator.';
 }
 if(type==='percent'){
  var p=prompt.match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))\s+is\s+what\s+percent\s+of\s+([+-]?(?:\d+(?:\.\d*)?|\.\d+))\??$/i);
  var target=Number(it&&it.answer);
  if(p&&Number.isFinite(target)){
   var part=Number(p[1]),wholePct=Number(p[2]),anchors=[10,20,30,40,50,60,70,80,90],anchor=anchors[0];
   anchors.forEach(function(x){if(Math.abs(x-target)<Math.abs(anchor-target))anchor=x;});
   var anchorAmount=wholePct*anchor/100,delta=Math.abs(anchorAmount-part),direction=part<anchorAmount?'lower':'higher';
   if(delta<1e-10)return 'Use a familiar anchor: '+anchor+'% of '+cleanNumber(wholePct)+' = '+cleanNumber(anchorAmount)+'. Compare that anchor amount with the part in the question.';
   return 'Start from a nearby percent anchor: '+anchor+'% of '+cleanNumber(wholePct)+' = '+cleanNumber(anchorAmount)+'. The target part, '+cleanNumber(part)+', is '+cleanNumber(delta)+' '+direction+'. Find what percent '+cleanNumber(delta)+' is of '+cleanNumber(wholePct)+', then '+(direction==='lower'?'subtract that percent from ':'add that percent to ')+anchor+'%.';
  }
  return 'This question asks for a percent. Estimate with a nearby percent anchor first, then adjust or use part ÷ whole × 100 to verify.';
 }
 if(type==='fraction')return 'This is fraction addition or subtraction. Make equal-sized pieces first: rewrite the fractions with a common denominator, combine the numerators, then reduce.';
 return 'First identify what the question wants: a fraction result, an amount, or a percent. Then choose the matching route instead of switching between them.';
}
function hintFor(it){var a=it&&it.area;if(a==='fractions_percentages')return fractionPercentHint(it);if(a==='algebra')return 'Name the operation trapping x, then use the inverse on both sides. Keep the equation balanced.';if(a==='exponents')return 'First identify the rule: repeated factors, same-base multiply, same-base divide, power of a power, or reciprocal for a negative exponent.';if(a==='scientific_notation')return 'Keep the coefficient between 1 and 10. Estimate the size first so the exponent sign makes sense.';if(a==='logs_estimation')return 'Translate log into “10 to what power?” Use exact powers of ten and the small landmark set before estimating.';return 'Write the conversion relationship first. Put the unwanted unit opposite so it cancels, then do the number math mentally if possible.';}
function stepsFor(it){
 var p=String(it&&it.prompt||''),m,steps=[];
 if(!it)return steps;
 if(it.type==='fraction_of_whole'){
  m=p.match(/^([+-]?\d+)\/([+-]?\d+)\s+of\s+([+-]?(?:\d+(?:\.\d*)?|\.\d+))$/i);if(m){var n=Number(m[1]),d=Number(m[2]),w=Number(m[3]),one=w/d;steps.push({prompt:'First find one denominator-sized group. What is '+cleanNumber(w)+' ÷ '+d+'?',check:function(v){return near(v,one)},hint:'The denominator tells how many equal groups to split the whole into.'});steps.push({prompt:'Now take '+n+' of those groups. What is '+cleanNumber(one)+' × '+n+'?',check:function(v){return near(v,one*n)},hint:'The numerator tells how many equal groups to take.'});return steps;}
 }
 if(it.type==='percent'){
  m=p.match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))\s+is\s+what\s+percent\s+of\s+([+-]?(?:\d+(?:\.\d*)?|\.\d+))\??$/i);if(m){var part=Number(m[1]),whole=Number(m[2]),onePct=whole/100,target=Number(it.answer);steps.push({prompt:'What is 1% of '+cleanNumber(whole)+'?',check:function(v){return near(v,onePct)},hint:'One percent means divide the whole by 100.'});steps.push({prompt:'How many '+cleanNumber(onePct)+'-sized 1% chunks fit into '+cleanNumber(part)+'?',check:function(v){return near(v,target,.0001)},hint:'Divide the part by the amount that represents 1%.'});return steps;}
 }
 if(it.type==='fraction'){
  m=p.match(/^([+-]?\d+)\/([+-]?\d+)\s*([+-])\s*([+-]?\d+)\/([+-]?\d+)$/);if(m){var a=Number(m[1]),b=Number(m[2]),op=m[3],c=Number(m[4]),d2=Number(m[5]),den=lcm(b,d2),a2=a*(den/b),c2=c*(den/d2);steps.push({prompt:'What common denominator can '+b+' and '+d2+' both use?',check:function(v){return near(v,den)},hint:'Use the least common multiple of the denominators.'});steps.push({prompt:'With denominator '+den+', what is the first numerator?',check:function(v){return near(v,a2)},hint:'Multiply the numerator by the same factor used on its denominator.'});steps.push({prompt:'With denominator '+den+', what is the second numerator?',check:function(v){return near(v,c2)},hint:'Use the same multiply-top-and-bottom rule on the second fraction.'});steps.push({prompt:'Now '+(op==='+'?'add':'subtract')+' the numerators and reduce. Enter the simplified fraction.',check:function(v){try{return it.check(v)}catch(e){return false}},hint:'Keep the common denominator while combining, then simplify.'});return steps;}
 }
 if(it.type==='two_sided_linear'&&it.params){var q=it.params,coef=q.a-q.c,constDiff=q.d-q.b;steps.push({prompt:'Move the x terms together. What is '+q.a+' − '+q.c+'?',check:function(v){return near(v,coef)},hint:'Subtract the smaller x-coefficient from both sides.'});steps.push({prompt:'Move the constants to the other side. What is '+q.d+' − ('+q.b+')?',check:function(v){return near(v,constDiff)},hint:'Use the inverse operation on the constant.'});steps.push({prompt:'Now divide '+cleanNumber(constDiff)+' by '+cleanNumber(coef)+'. What is x?',check:function(v){return near(v,it.answer)},hint:'Divide both sides by the coefficient on x.'});return steps;}
 if(it.type==='proportion'){
  m=p.match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))\/x\s*=\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+))\/([+-]?(?:\d+(?:\.\d*)?|\.\d+))$/i);if(m){var pa=Number(m[1]),pc=Number(m[2]),pd=Number(m[3]),cross=pa*pd;steps.push({prompt:'Cross-multiply the known diagonal. What is '+cleanNumber(pa)+' × '+cleanNumber(pd)+'?',check:function(v){return near(v,cross)},hint:'Multiply the numerator next to x by the denominator across from it.'});steps.push({prompt:'Now divide '+cleanNumber(cross)+' by '+cleanNumber(pc)+'. What is x?',check:function(v){return near(v,it.answer)},hint:'The other cross-product is '+cleanNumber(pc)+' × x.'});return steps;}
 }
 if(it.type==='formula_rearrangement'){
  if(/V\s*=\s*lwh/i.test(p)){steps.push({prompt:'To isolate h, what factor should you divide both sides by?',check:function(v){var s=norm(v);return s==='lw'||s==='l*w'||s==='wl'||s==='w*l'},hint:'h is multiplied by both l and w.'});steps.push({prompt:'Now write h by itself.',check:function(v){try{return it.check(v)}catch(e){return false}},hint:'Divide V by the product lw.'});return steps;}
  if(/d\s*=\s*rt/i.test(p)){steps.push({prompt:'To isolate t, what should you divide both sides by?',check:function(v){return norm(v)==='r'},hint:'t is multiplied by r.'});steps.push({prompt:'Now write t by itself.',check:function(v){try{return it.check(v)}catch(e){return false}},hint:'Divide d by r.'});return steps;}
  if(/P\s*=\s*2l\s*\+\s*2w/i.test(p)){steps.push({prompt:'First remove the 2l term. Enter the expression left on the P side after subtracting 2l.',check:function(v){var s=norm(v);return s==='p-2l'||s==='p-(2l)'},hint:'Subtract 2l from both sides.'});steps.push({prompt:'Now divide by 2 and write w by itself.',check:function(v){try{return it.check(v)}catch(e){return false}},hint:'After subtracting 2l, 2w remains.'});return steps;}
 }
 if(it.type==='negative_exponent'){
  m=p.match(/^([+-]?\d+)\^\(([+-]?\d+)\)$/);if(m){var base=Number(m[1]),exp=Number(m[2]),pos=Math.abs(exp),denom=Math.pow(base,pos);steps.push({prompt:'A negative exponent means reciprocal. What positive exponent goes in the denominator?',check:function(v){return near(v,pos)},hint:'Drop the negative sign when the power moves to the denominator.'});steps.push({prompt:'What is '+base+'^'+pos+'?',check:function(v){return near(v,denom)},hint:'Multiply '+base+' by itself '+pos+' times.'});steps.push({prompt:'Write the final reciprocal.',check:function(v){try{return it.check(v)}catch(e){return false}},hint:'Put 1 over the positive power.'});return steps;}
 }
 if(it.type==='same_base_rules'){
  var am=String(it.answer||'').match(/\^([+-]?\d+)$/),ansExp=am?Number(am[1]):null;if(ansExp!==null){steps.push({prompt:'Work only with the exponents first. What exponent should remain?',check:function(v){return near(v,ansExp)},hint:'Multiply same base → add exponents. Divide same base → subtract exponents.'});steps.push({prompt:'Now write the final power with the original base.',check:function(v){try{return it.check(v)}catch(e){return false}},hint:'Keep the base unchanged and use the exponent you just found.'});return steps;}
 }
 if(it.area==='scientific_notation'){
  if(it.type==='convert'&&it.answer&&typeof it.answer==='object'){steps.push({prompt:'Move the decimal so the coefficient is between 1 and 10. What coefficient do you get?',check:function(v){return near(v,it.answer.coefficient)},hint:'Ignore the power of ten for this step and focus only on the leading digits.'});steps.push({prompt:'How many places did the decimal move, with the correct sign for the exponent?',check:function(v){return near(v,it.answer.exponent)},hint:'Large original number → positive exponent. Small original number → negative exponent.'});steps.push({prompt:'Now write the full scientific notation.',check:function(v){try{return it.check(v)}catch(e){return false}},hint:'Combine the coefficient and power of ten.'});return steps;}
  if(it.answer&&typeof it.answer==='object'){steps.push({prompt:'Work the front numbers first. What coefficient will the final answer have before any renormalizing?',check:function(v){return near(v,it.answer.coefficient)},hint:'Multiply front numbers for multiplication; divide them for division.'});steps.push({prompt:'Now work only the powers of ten. What exponent remains?',check:function(v){return near(v,it.answer.exponent)},hint:'Multiply → add exponents. Divide → subtract exponents.'});steps.push({prompt:'Write the full normalized scientific notation.',check:function(v){try{return it.check(v)}catch(e){return false}},hint:'Coefficient must stay between 1 and 10.'});return steps;}
 }
 if(it.type==='exact_log'){
  steps.push({prompt:'Rewrite the number inside log as 10 to a power. What is that exponent?',check:function(v){return near(v,it.answer)},hint:'Ask: 10 to what power gives the number inside the log?'});return steps;
 }
 if(it.type==='inverse_log'){
  m=p.match(/log\(x\)\s*=\s*([+-]?\d+)/i);var e=m?Number(m[1]):null;steps.push({prompt:'Rewrite the log equation in exponential form: 10^'+e+' = x. What is x?',check:function(v){return near(v,it.answer,Math.abs(Number(it.answer))*1e-10+1e-12)},hint:'A log equation tells you the exponent on base 10.'});return steps;
 }
 if(it.type==='estimate_negative_log'){
  m=p.match(/−?log\(([+-]?(?:\d+(?:\.\d*)?|\.\d+))×10\^−([0-9]+)\)/i);if(m){var front=Number(m[1]),pow=Number(m[2]),frontLog=Math.log10(front);steps.push({prompt:'What is log(10^−'+pow+')?',check:function(v){return near(v,-pow)},hint:'log(10^n) = n.'});steps.push({prompt:'Estimate log('+front+').',check:function(v){return near(v,frontLog,.08)},hint:'Use the landmark logs and product rule when possible.'});steps.push({prompt:'Now apply the outside negative sign. About what value do you get?',check:function(v){return near(v,it.answer,.15)},hint:'Work the ordinary log first, then negate the result.'});return steps;}
 }
 if(it.type==='single_conversion'&&it.conversion){var conv=it.conversion,src=parseFloat(p),factor=Number(conv.factor);steps.push({prompt:'What numerical conversion factor changes '+conv.from+' into '+conv.to+'?',check:function(v){return near(v,factor)},hint:'Use the unit equality, then choose the factor that cancels the starting unit.'});steps.push({prompt:'Now calculate '+cleanNumber(src)+' × '+cleanNumber(factor)+'.',check:function(v){return near(v,it.answer)},hint:'The units tell you whether the number should get bigger or smaller.'});return steps;}
 if(it.type==='stacked_rate'){
  var source=parseFloat(p),mmolPerSec=source*1000;steps.push({prompt:'First convert mol to mmol. What is '+cleanNumber(source)+' × 1000?',check:function(v){return near(v,mmolPerSec,1e-8)},hint:'1 mol = 1000 mmol.'});steps.push({prompt:'Now convert per second to per minute. What is '+cleanNumber(mmolPerSec)+' × 60?',check:function(v){return near(v,it.answer,1e-8)},hint:'There are 60 seconds in 1 minute.'});return steps;
 }
 return steps;
}
function firstStepFor(it){var s=stepsFor(it);return s.length?s[0].prompt:hintFor(it);}
var rules={shouldAutoAdvance:shouldAutoAdvance,scoreText:scoreText,hintFor:hintFor,fractionPercentHint:fractionPercentHint,helpPolicy:helpPolicy,masteryCreditAllowed:masteryCreditAllowed,stepsFor:stepsFor,firstStepFor:firstStepFor};
if(typeof module!=='undefined'&&module.exports)module.exports=rules;
root.MathGymUIRules=rules;
if(typeof document==='undefined')return;
var G=root.MathGymEngine;if(!G)return;var viewRoot=document.getElementById('view'),nav=document.getElementById('navTabs');if(!viewRoot||!nav)return;
var currentArea='fractions_percentages',mode='practice',item=null,correctCount=0,total=0,started=0,timer=null,timeLeft=60;
var independentCorrect=0,supportedCorrect=0,itemHelpTier=0,itemAttempts=0,walkSteps=[],walkIndex=0;
var names={fractions_percentages:'Fractions & percentages',algebra:'Algebra',exponents:'Exponents',scientific_notation:'Scientific notation',logs_estimation:'Logs & estimation',unit_conversions:'Unit conversions'};
function addTab(){if(document.getElementById('mathGymTab'))return;var b=document.createElement('button');b.id='mathGymTab';b.textContent='Math Gym';b.type='button';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();openGym()});nav.appendChild(b)}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function resetItemEvidence(){itemHelpTier=0;itemAttempts=0;walkSteps=[];walkIndex=0;}
function newItem(){item=G.generate(currentArea);started=Date.now();resetItemEvidence();renderProblem()}
function modeHelp(){if(mode==='practice')return 'Practice mode: full help is available. Use it to learn, then prove it later on a fresh problem.';if(mode==='speed')return 'Speed Round: no help while the clock is running. Work mentally and build automaticity.';if(mode==='challenge')return 'Challenge: help is available if you get stuck, but helped items are marked supported.';return 'Fresh Mastery: solve independently. If you choose help, this item becomes practice and the next mastery check will be fresh.'}
function openGym(){stopTimer();Array.from(nav.children).forEach(function(x){x.classList.remove('on')});document.getElementById('mathGymTab').classList.add('on');viewRoot.innerHTML='<div class="card"><div class="phase">Math Gym</div><h1>Train it until it is fast.</h1><p>'+modeHelp()+'</p><div class="row" id="gymAreas"></div><div class="row" id="gymModes" style="margin-top:12px"></div></div><div id="gymBody"></div>';
 var a=document.getElementById('gymAreas');Object.keys(names).forEach(function(k){var b=document.createElement('button');b.type='button';b.className='btn '+(k===currentArea?'':'secondary');b.textContent=names[k];b.onclick=function(){currentArea=k;correctCount=0;total=0;independentCorrect=0;supportedCorrect=0;openGym()};a.appendChild(b)});
 var m=document.getElementById('gymModes');[['practice','Practice'],['speed','Speed Round'],['challenge','Challenge'],['mastery','Fresh Mastery']].forEach(function(x){var b=document.createElement('button');b.type='button';b.className='btn '+(x[0]===mode?'':'secondary');b.textContent=x[1];b.onclick=function(){mode=x[0];correctCount=0;total=0;independentCorrect=0;supportedCorrect=0;openGym()};m.appendChild(b)});
 if(mode==='speed')startSpeed();else newItem();}
function startSpeed(){stopTimer();timeLeft=60;newItem();timer=setInterval(function(){timeLeft--;var t=document.getElementById('gymTimer');if(t)t.textContent=timeLeft+' sec';if(timeLeft<=0){stopTimer();showFinish('Speed Round complete: '+correctCount+' correct out of '+total+' attempts.')}} ,1000)}
function updateScore(){var s=document.getElementById('gymScore');if(s)s.textContent=scoreText(correctCount,total);var e=document.getElementById('gymEvidence');if(e)e.textContent=mode==='mastery'?independentCorrect+' independent / 3 needed'+(supportedCorrect?' • '+supportedCorrect+' supported':''):(supportedCorrect?independentCorrect+' independent • '+supportedCorrect+' supported':'');}
function helpButtonHtml(){var policy=helpPolicy(mode);return policy.available?'<button type="button" id="gymHelp" class="btn secondary">'+policy.label+'</button>':'';}
function renderProblem(){var body=document.getElementById('gymBody');if(!body||!item)return;var ev=mode==='speed'?'':'<div id="gymEvidence" class="muted" style="margin-top:4px">'+(mode==='mastery'?independentCorrect+' independent / 3 needed'+(supportedCorrect?' • '+supportedCorrect+' supported':''):(supportedCorrect?independentCorrect+' independent • '+supportedCorrect+' supported':''))+'</div>';body.innerHTML='<div class="card"><div class="phase">'+names[currentArea]+' • '+mode.replace('_',' ')+'</div><div class="row" style="justify-content:space-between"><div><b id="gymScore">'+scoreText(correctCount,total)+'</b>'+ev+'</div>'+(mode==='speed'?'<b id="gymTimer">'+timeLeft+' sec</b>':'')+'</div><div class="question">'+item.prompt+'</div><input id="gymAnswer" class="input" autocomplete="off" inputmode="text" placeholder="Your answer"><div class="actions" style="margin-top:12px"><button type="button" id="gymCheck" class="btn">Check answer</button>'+helpButtonHtml()+'<button type="button" id="gymSkip" class="btn ghost">Skip</button></div><div id="gymHelpPanel"></div><div id="gymFeedback"></div></div>';
 document.getElementById('gymCheck').onclick=check;var h=document.getElementById('gymHelp');if(h)h.onclick=showHelpMenu;document.getElementById('gymSkip').onclick=function(){total++;newItem()};}
function markHelp(tier){itemHelpTier=Math.max(itemHelpTier,tier||1);}
function showHelpMenu(){var policy=helpPolicy(mode);if(!policy.available)return;if(policy.masteryEnds)markHelp(1);var panel=document.getElementById('gymHelpPanel');if(!panel)return;panel.innerHTML='<div class="warning" style="margin-top:12px">'+(policy.masteryEnds?'<b>This item is now practice, not Fresh Mastery.</b><br>The next mastery check will be a different fresh problem.<br><br>':'')+'<b>How much help do you want?</b><div class="actions" style="margin-top:10px"><button type="button" id="gymHelpHint" class="btn secondary">Give me a hint</button><button type="button" id="gymHelpFirst" class="btn secondary">Give me the first step</button><button type="button" id="gymHelpWalk" class="btn secondary">Walk me through it</button></div><div id="gymHelpContent" style="margin-top:10px"></div></div>';document.getElementById('gymHelpHint').onclick=function(){markHelp(1);document.getElementById('gymHelpContent').innerHTML='<b>Mental hint</b><p>'+hintFor(item)+'</p>'};document.getElementById('gymHelpFirst').onclick=function(){markHelp(2);document.getElementById('gymHelpContent').innerHTML='<b>First step</b><p>'+firstStepFor(item)+'</p><p class="muted">Do that step, then return to the original answer box when you are ready.</p>'};document.getElementById('gymHelpWalk').onclick=function(){markHelp(3);walkSteps=stepsFor(item);walkIndex=0;renderWalkStep()};}
function renderWalkStep(){var host=document.getElementById('gymHelpContent');if(!host)return;if(!walkSteps.length){host.innerHTML='<b>Walkthrough</b><p>'+hintFor(item)+'</p><p class="muted">Use that route, then finish the original problem above.</p>';return;}if(walkIndex>=walkSteps.length){host.innerHTML='<div class="feedback good"><b>You worked through the structure.</b> Now finish the original problem in the answer box above. This item counts as supported practice.</div>';return;}var s=walkSteps[walkIndex];host.innerHTML='<b>Walkthrough step '+(walkIndex+1)+' of '+walkSteps.length+'</b><p>'+s.prompt+'</p><input id="gymStepAnswer" class="input" autocomplete="off" inputmode="text" placeholder="Your step answer"><div class="actions" style="margin-top:8px"><button type="button" id="gymStepCheck" class="btn">Check this step</button><button type="button" id="gymStepHint" class="btn ghost">Hint for this step</button></div><div id="gymStepFeedback"></div>';document.getElementById('gymStepHint').onclick=function(){document.getElementById('gymStepFeedback').innerHTML='<div class="warning" style="margin-top:8px">'+s.hint+'</div>'};document.getElementById('gymStepCheck').onclick=function(){var v=document.getElementById('gymStepAnswer').value,ok=false;try{ok=s.check(v)}catch(e){ok=false}if(ok){walkIndex++;renderWalkStep()}else document.getElementById('gymStepFeedback').innerHTML='<div class="feedback bad"><b>Not yet.</b> Try this same step again.</div>'};}
function advance(){if(mode==='mastery'&&independentCorrect>=3){showFinish('Fresh mastery passed with 3 independent correct answers.')}else if(mode==='challenge'&&correctCount>=5){showFinish('Challenge complete: 5 correct.')}else newItem()}
function check(){var v=document.getElementById('gymAnswer').value,ok=false,priorWrong=itemAttempts>0,clean=itemHelpTier===0&&!priorWrong;try{ok=item.check(v)}catch(e){ok=false}itemAttempts++;total++;if(ok){correctCount++;if(clean)independentCorrect++;else supportedCorrect++;}updateScore();if(ok){var masteryClean=masteryCreditAllowed(mode,itemHelpTier,priorWrong);if(shouldAutoAdvance(mode)){document.getElementById('gymFeedback').innerHTML='<div class="feedback good"><b>Correct.</b> Keep moving.</div>';setTimeout(advance,550)}else{var note=mode==='mastery'&&!masteryClean?'<br><span class="muted">Correct with support/correction. This one does not count toward Fresh Mastery.</span>':'<br><span class="muted">'+(clean?'Independent correct.':'Supported/repaired correct.')+'</span>';document.getElementById('gymFeedback').innerHTML='<div class="feedback good"><b>Correct.</b>'+note+'<br>Now notice the shortest mental route you could use next time.</div><div class="actions" style="margin-top:8px"><button type="button" id="gymContinue" class="btn">Continue</button></div>';document.getElementById('gymContinue').onclick=advance}}else{var help=helpPolicy(mode).available?'<div class="actions" style="margin-top:8px"><button type="button" id="gymHelpAfterWrong" class="btn secondary">Help me</button></div>':'';document.getElementById('gymFeedback').innerHTML='<div class="feedback bad"><b>Not yet.</b> Stay on this same problem and try again.</div>'+help;var hb=document.getElementById('gymHelpAfterWrong');if(hb)hb.onclick=showHelpMenu;}}
function showFinish(msg){var body=document.getElementById('gymBody');if(body)body.innerHTML='<div class="card success"><h2>'+msg+'</h2><div class="actions"><button type="button" id="gymAgain" class="btn">Do another round</button><button type="button" id="gymBackMath" class="btn secondary">Back to Math</button></div></div>';document.getElementById('gymAgain').onclick=function(){correctCount=0;total=0;independentCorrect=0;supportedCorrect=0;openGym()};document.getElementById('gymBackMath').onclick=function(){var b=nav.querySelector('[data-view="math"]');if(b)b.click()}}
addTab();
})(typeof globalThis!=='undefined'?globalThis:this);
