(function(){'use strict';
var G=window.MathGymEngine;if(!G)return;var root=document.getElementById('view'),nav=document.getElementById('navTabs');if(!root||!nav)return;
var currentArea='fractions_percentages',mode='practice',item=null,correctCount=0,total=0,started=0,timer=null,timeLeft=60;
var names={fractions_percentages:'Fractions & percentages',algebra:'Algebra',exponents:'Exponents',scientific_notation:'Scientific notation',logs_estimation:'Logs & estimation',unit_conversions:'Unit conversions'};
function btn(text,cls){return '<button class="btn '+(cls||'')+'">'+text+'</button>'}
function addTab(){if(document.getElementById('mathGymTab'))return;var b=document.createElement('button');b.id='mathGymTab';b.textContent='Math Gym';b.type='button';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();openGym()});nav.appendChild(b)}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function newItem(){item=G.generate(currentArea);started=Date.now();renderProblem()}
function modeHelp(){if(mode==='practice')return 'Practice mode: hints are available. Focus on accuracy and mental strategy.';if(mode==='speed')return 'Speed Round: no hints. Work mentally and build automaticity.';if(mode==='challenge')return 'Challenge: mixed, harder thinking. Hints are allowed if you get stuck.';return 'Fresh Mastery: no hints and no calculator. This checks what you can do independently.'}
function openGym(){stopTimer();Array.from(nav.children).forEach(function(x){x.classList.remove('on')});document.getElementById('mathGymTab').classList.add('on');root.innerHTML='<div class="card"><div class="phase">Math Gym</div><h1>Train it until it is fast.</h1><p>'+modeHelp()+'</p><div class="row" id="gymAreas"></div><div class="row" id="gymModes" style="margin-top:12px"></div></div><div id="gymBody"></div>';
 var a=document.getElementById('gymAreas');Object.keys(names).forEach(function(k){var b=document.createElement('button');b.className='btn '+(k===currentArea?'':'secondary');b.textContent=names[k];b.onclick=function(){currentArea=k;correctCount=0;total=0;openGym();newItem()};a.appendChild(b)});
 var m=document.getElementById('gymModes');[['practice','Practice'],['speed','Speed Round'],['challenge','Challenge'],['mastery','Fresh Mastery']].forEach(function(x){var b=document.createElement('button');b.className='btn '+(x[0]===mode?'':'secondary');b.textContent=x[1];b.onclick=function(){mode=x[0];correctCount=0;total=0;openGym();if(mode==='speed')startSpeed();else newItem()};m.appendChild(b)});
 if(mode==='speed')startSpeed();else newItem();}
function startSpeed(){stopTimer();timeLeft=60;newItem();timer=setInterval(function(){timeLeft--;var t=document.getElementById('gymTimer');if(t)t.textContent=timeLeft+' sec';if(timeLeft<=0){stopTimer();showFinish('Speed Round complete: '+correctCount+' correct out of '+total+' attempts.')}} ,1000)}
function hintFor(it){var a=it.area;if(a==='fractions_percentages')return 'Look for friendly fractions or percent anchors first: 10%, 5%, 25%, 50%, 75%. Break the number into easy chunks.';if(a==='algebra')return 'Name the operation trapping x, then use the inverse on both sides. Keep the equation balanced.';if(a==='exponents')return 'First identify the rule: repeated factors, same-base multiply, same-base divide, power of a power, or reciprocal for a negative exponent.';if(a==='scientific_notation')return 'Keep the coefficient between 1 and 10. Estimate the size first so the exponent sign makes sense.';if(a==='logs_estimation')return 'Translate log into “10 to what power?” Use exact powers of ten and the small landmark set before estimating.';return 'Write the conversion relationship first. Put the unwanted unit opposite so it cancels, then do the number math mentally if possible.'}
function renderProblem(){var body=document.getElementById('gymBody');if(!body||!item)return;body.innerHTML='<div class="card"><div class="phase">'+names[currentArea]+' • '+mode.replace('_',' ')+'</div><div class="row" style="justify-content:space-between"><b id="gymScore">'+correctCount+' correct / '+total+' attempts</b>'+(mode==='speed'?'<b id="gymTimer">'+timeLeft+' sec</b>':'')+'</div><div class="question">'+item.prompt+'</div><input id="gymAnswer" class="input" autocomplete="off" inputmode="text" placeholder="Your answer"><div class="actions" style="margin-top:12px"><button id="gymCheck" class="btn">Check answer</button>'+(G.MODES[mode].hints?'<button id="gymHint" class="btn secondary">Mental hint</button>':'')+'<button id="gymSkip" class="btn ghost">Skip</button></div><div id="gymFeedback"></div></div>';
 document.getElementById('gymCheck').onclick=check;var h=document.getElementById('gymHint');if(h)h.onclick=function(){document.getElementById('gymFeedback').innerHTML='<div class="warning"><b>Mental strategy</b><br>'+hintFor(item)+'</div>'};document.getElementById('gymSkip').onclick=function(){total++;newItem()};}
function check(){var v=document.getElementById('gymAnswer').value,ok=false;try{ok=item.check(v)}catch(e){ok=false}total++;if(ok){correctCount++;var ms=Date.now()-started;document.getElementById('gymFeedback').innerHTML='<div class="feedback good"><b>Correct.</b> '+(mode==='speed'?'Keep moving.':'Now notice the shortest mental route you could use next time.')+'</div>';setTimeout(function(){if(mode==='mastery'&&correctCount>=3){showFinish('Fresh mastery passed with 3 independent correct answers.')}else if(mode==='challenge'&&correctCount>=5){showFinish('Challenge complete: 5 correct.')}else newItem()},550)}else{document.getElementById('gymFeedback').innerHTML='<div class="feedback bad"><b>Not yet.</b> Stay on this same problem and correct it.'+(G.MODES[mode].hints?'<br><br>'+hintFor(item):'')+'</div>'}}
function showFinish(msg){var body=document.getElementById('gymBody');if(body)body.innerHTML='<div class="card success"><h2>'+msg+'</h2><div class="actions"><button id="gymAgain" class="btn">Do another round</button><button id="gymBackMath" class="btn secondary">Back to Math</button></div></div>';document.getElementById('gymAgain').onclick=function(){correctCount=0;total=0;openGym()};document.getElementById('gymBackMath').onclick=function(){var b=nav.querySelector('[data-view="math"]');if(b)b.click()}}
addTab();
})();