(function(){'use strict';
var O=globalThis.Day1Orchestrator,G=globalThis.MathGymEngine;var store=localStorage,state=O.load(store),view='home';var session={area:null,mode:null,step:0,practice:[],pi:0,correct:0,current:null};
var $=id=>document.getElementById(id),root=$('view');
var areas={
fractions_percent:{name:'Fractions & percentages',lessons:[
{title:'What a percent means',say:'Percent means out of one hundred. Before using a formula, build number sense.',visual:'25% = 25/100 = 1/4'},
{title:'Mental percent anchors',say:'Memorize a tiny set of useful anchors, not dozens of answers.',visual:'10% = ÷10   •   1% = ÷100   •   5% = half of 10%   •   25% = one fourth   •   50% = half'},
{title:'Example: 24 is what percent of 300?',say:'First use number sense. Ten percent of 300 is 30. One percent is 3. Twenty-four is six less than thirty. Six is two percent of 300. So 24 is eight percent.',visual:'10% of 300 = 30\n2% of 300 = 6\n30 − 6 = 24\n10% − 2% = 8%'},
{title:'Same problem, formal method',say:'Now connect the mental idea to the formal method. Part divided by whole times one hundred.',visual:'24 ÷ 300 × 100\n= 0.08 × 100\n= 8%'},
{title:'Fast route',say:'You can also simplify the fraction mentally. Twenty-four over three hundred becomes eight over one hundred when both are divided by three.',visual:'24/300  →  8/100  →  8%'},
{title:'Build flexible mental math',say:'For fifteen percent, find ten percent and five percent. For twenty-five percent, divide by four. For seventy-five percent, find half plus one fourth.',visual:'15% of 80 = 8 + 4 = 12\n25% of 60 = 60 ÷ 4 = 15\n75% of 40 = 20 + 10 = 30'}],toolbox:['10% = divide by 10','1% = divide by 100','5% = half of 10%','20% = double 10%','25% = one fourth','50% = one half','75% = one half + one fourth','Formal: part ÷ whole × 100']},
unit_conversions:{name:'Unit conversions',lessons:[
{title:'Conversion is changing the label without changing the amount',say:'Start with one anchor relationship. Then decide whether the number should get bigger or smaller.',visual:'1 L = 1000 mL'},
{title:'Big unit to smaller unit',say:'One liter contains one thousand milliliters. Moving from liters to milliliters makes the number larger, so multiply by one thousand.',visual:'2.5 L × 1000 = 2500 mL'},
{title:'Small unit to bigger unit',say:'Moving from milliliters to liters makes the number smaller, so divide by one thousand.',visual:'750 mL ÷ 1000 = 0.75 L'},
{title:'Let the units prove the setup',say:'A conversion factor is equal to one. Put the unit you have opposite itself so it cancels. The screen will show the cancellation for you.',visual:'0.062 L × (1000 mL / 1 L)\nL cancels → 62 mL'},
{title:'Pharmacy metric anchors',say:'The same thousand pattern repeats through common pharmacy units.',visual:'1 L = 1000 mL\n1 g = 1000 mg\n1 mg = 1000 mcg'},
{title:'Rate conversions',say:'For a rate, change one unit at a time. Keep the units visible until they cancel.',visual:'0.015 mol/s × 1000 mmol/mol × 60 s/min\n= 900 mmol/min'},
{title:'U.S. volume anchors',say:'When these are needed, use a small toolbox instead of guessing.',visual:'1 gal = 4 qt\n1 qt = 2 pt\n1 pt = 2 cups\nso 1 gal = 16 cups'}],toolbox:['1 L = 1000 mL','1 g = 1000 mg','1 mg = 1000 mcg','1 gal = 4 qt','1 qt = 2 pt','1 pt = 2 cups','Big → small: number gets bigger','Small → big: number gets smaller','Set factors so units cancel']},
logs:{name:'Logs & estimation',lessons:[{title:'What a log asks',say:'A logarithm asks which exponent belongs on ten.',visual:'10³ = 1000  ⇔  log(1000)=3'},{title:'Power-of-ten anchors',say:'Learn a few landmarks, not log one through twenty-nine.',visual:'log(1)=0   log(10)=1   log(100)=2\nlog(0.1)=−1'},{title:'Useful small landmarks',say:'For no-calculator estimation, a tiny toolbox is enough.',visual:'log(2)≈0.30   log(3)≈0.48   log(5)≈0.70'},{title:'Build log six',say:'Six is two times three, so use the product rule.',visual:'log(6)=log(2)+log(3)≈0.30+0.48=0.78'},{title:'pKa-style example',say:'Separate the power of ten first.',visual:'−log(6×10⁻⁶)=6−log(6)≈6−0.78=5.22'}],toolbox:['log(1)=0','log(10)=1','log(100)=2','log(2)≈0.30','log(3)≈0.48','log(5)≈0.70','log(ab)=log(a)+log(b)']},
algebra:{name:'Algebra',lessons:[{title:'Equation means balance',say:'Both sides have the same value. Whatever you do to one side, do to the other.',visual:'7x + 2 = 3x + 26'},{title:'Move variable terms together',say:'Subtract three x from both sides.',visual:'4x + 2 = 26'},{title:'Move constants',say:'Subtract two from both sides.',visual:'4x = 24'},{title:'Isolate x',say:'Divide both sides by four.',visual:'x = 6'},{title:'What cross multiply means',say:'In a proportion, multiply diagonally across the equals sign. It is not magic; it clears the denominators.',visual:'2/x = 6/15\n2×15 = 6×x\n30 = 6x\nx = 5'}],toolbox:['Equals sign = balance','Undo addition/subtraction first','Undo multiplication/division next','Proportion: multiply diagonally, then solve']},
exponents:{name:'Exponents',lessons:[{title:'Exponent means repeated multiplication',say:'An exponent counts repeated factors.',visual:'a⁴ = a·a·a·a'},{title:'Product rule',say:'Same base multiplied means count all factors, so add exponents.',visual:'a⁴·a³ = a⁷'},{title:'Quotient rule',say:'Same base divided means cancel factors, so subtract exponents.',visual:'a⁷/a² = a⁵'},{title:'Negative exponent',say:'A negative exponent means reciprocal, not a negative value.',visual:'2⁻⁴ = 1/2⁴ = 1/16'}],toolbox:['Same base ×: add exponents','Same base ÷: subtract exponents','Negative exponent: reciprocal','Anything nonzero to 0 = 1']},
scientific_notation:{name:'Scientific notation',lessons:[{title:'One nonzero digit first',say:'Scientific notation writes a number as a value from one up to ten times a power of ten.',visual:'0.00061 = 6.1 × 10⁻⁴'},{title:'Decimal movement',say:'Count the decimal moves. Moving left gives a positive exponent; moving right gives a negative exponent when converting ordinary numbers into scientific notation.',visual:'61000 → 6.1 × 10⁴\n0.0061 → 6.1 × 10⁻³'},{title:'Multiply',say:'Multiply the front numbers and add exponents.',visual:'(4×10⁶)(2×10⁻³)=8×10³'},{title:'Divide',say:'Divide the front numbers and subtract exponents, then renormalize if needed.',visual:'(9×10⁻⁵)/(3×10⁻²)=3×10⁻³'}],toolbox:['Coefficient must be ≥1 and <10','Multiply: multiply coefficients, add exponents','Divide: divide coefficients, subtract exponents','Renormalize at the end']}}
};
function save(){O.save(state,store);$('saveState').textContent='Saved just now';}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.rate=.9;speechSynthesis.speak(u);}
function setView(v){view=v;document.querySelectorAll('#navTabs button').forEach(b=>b.classList.toggle('on',b.dataset.view===v));render();}
$('navTabs').addEventListener('click',e=>{if(e.target.dataset.view)setView(e.target.dataset.view)});
function home(){return '<div class="hero"><div class="phase">DAY 1</div><h1>Choose where you want to work.</h1><p>You can learn first or try questions first. Switching subjects does not erase your place.</p></div><div class="grid"><div class="card subject"><h2>Math Foundation</h2><p>Teacher lessons, mental math, toolboxes, guided practice and fresh checks.</p><button class="btn" data-go="math">Open math</button></div><div class="card subject"><h2>Chemistry Foundation</h2><p>Teacher animation first if you want it, or try building first and learn from mistakes.</p><button class="btn" data-go="chemistry">Open chemistry</button></div></div>'}
function mathMenu(){return '<div class="card"><div class="phase">Math Foundation</div><h2>Choose a skill</h2><div class="grid">'+Object.keys(areas).map(id=>'<button class="mathArea" data-area="'+id+'"><b>'+areas[id].name+'</b><span class="status">'+(state.math.statuses[id]||'Not started')+'</span></button>').join('')+'</div></div>'}
function entry(a){return '<div class="card"><div class="phase">'+a.name+'</div><h2>How do you want to start?</h2><p>You can change your mind at any time.</p><div class="actions"><button class="btn" id="teachFirst">▶ Teach me the lesson</button><button class="btn secondary" id="tryFirst">✏️ Let me try it first</button></div><p class="muted">If you try first and get stuck, Dr. Merissa will teach the exact step and show the work.</p></div>'}
function toolbox(a){return '<details class="card" open><summary><b>Math Toolbox</b></summary><div class="chips" style="margin-top:12px">'+a.toolbox.map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'</div></details>'}
function teach(a){var l=a.lessons[session.step];return '<div class="card teacher"><div class="avatar">🎓</div><div class="bubble"><b>Dr. Merissa</b><div>'+esc(l.say)+'</div></div></div><div class="card"><div class="phase">Learning • '+(session.step+1)+' of '+a.lessons.length+'</div><h2>'+esc(l.title)+'</h2><div class="stage"><div class="visual small" style="white-space:pre-line">'+esc(l.visual)+'</div></div><div class="actions" style="margin-top:12px"><button class="btn secondary" id="back" '+(session.step===0?'disabled':'')+'>← Back</button><button class="btn" id="next">'+(session.step===a.lessons.length-1?'Practice this →':'Next →')+'</button><button class="btn secondary" id="replay">Replay this step</button><button class="btn ghost" id="stillIdk">I still don’t get this</button><button class="btn ghost" id="skipToTry">Skip lesson and try</button></div><div id="help"></div></div>'+toolbox(a)}
function newPractice(){session.current=G.generate(({fractions_percent:'fractions_percentages',unit_conversions:'unit_conversions',logs:'logs_estimation',algebra:'algebra',exponents:'exponents',scientific_notation:'scientific_notation'})[session.area]);}
function practice(a){if(!session.current)newPractice();return '<div class="card"><div class="phase">'+(session.mode==='try'?'Try it first':'Practice')+'</div><h2>'+a.name+'</h2><div class="question">'+esc(session.current.prompt)+'</div><input id="answer" class="input" autocomplete="off"><div class="actions" style="margin-top:12px"><button class="btn" id="check">Check answer</button><button class="btn secondary" id="dontKnow">I don’t know yet</button><button class="btn ghost" id="fullLesson">Teach the full lesson</button></div><div id="feedback"></div></div>'+toolbox(a)}
function specificTeach(area,prompt){if(area==='fractions_percent'){if(/percent/i.test(prompt))return '<b>Let’s work THIS problem.</b><p>First ask: what is 10% of the whole? Then use 1%, 5%, 25%, or another anchor to build the percent mentally. After that, connect it to <b>part ÷ whole × 100</b>. For “24 is what percent of 300?”: 10% of 300 is 30. 2% is 6. 24 is 30−6, so it is 8%. Formal check: 24÷300×100=8%.</p>';return '<b>Let’s work THIS fraction.</b><p>Fractions can only be added or subtracted when their pieces are the same size. Find a common denominator, rewrite each fraction, then combine numerators.</p>'}
if(area==='unit_conversions')return '<b>Let’s work THIS conversion.</b><p>Do not “circle” anything. Watch the units instead. Write the starting amount, multiply by a conversion factor, and place the unit you already have on the opposite side so the printed units cancel. Use the toolbox anchors. Example: 0.062 L × (1000 mL / 1 L) = 62 mL. The L cancels on screen.</p>';
return '<b>Let’s work THIS step.</b><p>We will keep the current problem and break it into one visible operation at a time. If this explanation still does not click, choose Teach the full lesson.</p>'}
function math(){if(!session.area)return mathMenu();var a=areas[session.area];if(session.mode==='entry')return entry(a);if(session.mode==='teach')return teach(a);return practice(a)}
function chemistry(){return '<div class="card"><div class="phase">Chemistry Foundation</div><h2>How do you want to start?</h2><div class="actions"><button class="btn" id="chemTeach">▶ Teach me the lesson</button><button class="btn secondary" id="chemTry">✏️ Let me try it first</button></div><p class="muted">Teaching includes narration, electron animation, Back, Replay and alternate explanations. Trying first lets mistakes decide what gets taught.</p></div><div id="chemHost"></div>'}
function notebook(){return '<div class="card"><h2>Notebook</h2>'+(state.notebook.length?state.notebook.map(x=>'<div class="notebookFact">'+esc(x)+'</div>').join(''):'<p>Facts taught during lessons will appear here.</p>')+'</div>'}
function review(){return '<div class="card"><h2>Review Queue</h2><p>'+(state.sameSessionReview.concat(state.nextSessionQueue).map(esc).join('<br>')||'Nothing queued yet.')+'</p></div>'}
function summary(){return '<div class="card"><h2>Day 1 Summary</h2><p>Math and chemistry progress save separately. Supported work teaches; cold checks measure mastery.</p></div>'}
function render(){root.innerHTML=view==='home'?home():view==='math'?math():view==='chemistry'?chemistry():view==='notebook'?notebook():view==='review'?review():summary();bind();}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{session={area:b.dataset.area,mode:'entry',step:0,practice:[],pi:0,correct:0,current:null};render()});
if($('teachFirst'))$('teachFirst').onclick=()=>{session.mode='teach';session.step=0;render();speak(areas[session.area].lessons[0].say)};if($('tryFirst'))$('tryFirst').onclick=()=>{session.mode='try';newPractice();render()};
if($('back'))$('back').onclick=()=>{if(session.step>0)session.step--;render();speak(areas[session.area].lessons[session.step].say)};if($('next'))$('next').onclick=()=>{var a=areas[session.area];if(session.step<a.lessons.length-1){session.step++;render();speak(a.lessons[session.step].say)}else{session.mode='practice';session.current=null;render()}};if($('replay'))$('replay').onclick=()=>speak(areas[session.area].lessons[session.step].say);if($('skipToTry'))$('skipToTry').onclick=()=>{session.mode='try';session.current=null;render()};
if($('stillIdk'))$('stillIdk').onclick=()=>{$('help').innerHTML='<div class="idkbox"><b>Let me make it smaller.</b><p>'+esc(areas[session.area].lessons[session.step].say)+'</p><p>Look only at the single relationship on the screen. You can go Back, Replay, or open the Toolbox. You do not have to guess which part you missed.</p></div>'};
if($('fullLesson'))$('fullLesson').onclick=()=>{session.mode='teach';session.step=0;render();speak(areas[session.area].lessons[0].say)};if($('dontKnow'))$('dontKnow').onclick=()=>{$('feedback').innerHTML='<div class="idkbox">'+specificTeach(session.area,session.current.prompt)+'<p class="muted">Stay on this exact problem until the step makes sense. Then you will get a fresh problem.</p></div>';O.scheduleReview(state,session.area,'repeated_idk');save()};
if($('check'))$('check').onclick=()=>{var v=$('answer').value.trim();if(!v)return;var ok=session.current.check(v);if(ok){session.correct++;$('feedback').innerHTML='<div class="feedback good"><b>Correct.</b> Now prove the idea on a fresh problem.</div>';session.current=null;setTimeout(render,650)}else{$('feedback').innerHTML='<div class="feedback bad"><b>Not yet.</b>'+specificTeach(session.area,session.current.prompt)+'</div>';O.scheduleReview(state,session.area,'repeated_idk');save()}};
if($('chemTeach'))$('chemTeach').onclick=()=>{$('chemHost').innerHTML='<div class="card iframeWrap"><iframe src="../chemistry-teacher-preview/" title="Chemistry teacher lesson"></iframe></div>'};if($('chemTry'))$('chemTry').onclick=()=>{$('chemHost').innerHTML='<div class="card"><p><b>Try first mode:</b> start with the builder below. If you ask for help, this attempt becomes supported learning instead of cold mastery.</p><iframe style="width:100%;min-height:900px;border:0" src="../chemistry-teacher-preview/#practice" title="Chemistry practice"></iframe></div>'};}
render();})();