(function(){
  'use strict';
  var Data=globalThis.Chapter1TeachingData,Engine=globalThis.Chapter1TeachingEngine,Router=globalThis.StudentModelIdkRouter,Teach=globalThis.Chapter1SupportedTeaching;
  if(!Data||!Engine||!Router||!Teach)throw new Error('Chapter 1 adaptive teaching dependencies are missing');
  var host=document.querySelector('[data-ch1-host]'),cards=document.querySelector('[data-ch1-lessons]');
  var active=null,message='',supportedIntervention=null,wrongCounts={},watchFeedback='';
  var PHASE_LABELS={prerequisite:'Prerequisite check',watch:'Watch · I Do',concept:'Supported Concept Check',build:'Build Together · We Do',guided:'Guided Practice · You Do With Support',independent:'Cold Independent',explain:'Explain Why',transfer:'Transfer',activity:'Intervening Chemistry Activity','retrieval-wait':'Later Retrieval',retrieval:'Later Retrieval · Cold',complete:'Mastered'};
  var WATCH_CHECKS={
    lewis:[
      {q:'Quick prediction: which neutral atom contributes more valence electrons here?',choices:['Nitrogen','Oxygen'],answer:'Oxygen',why:'Oxygen contributes 6; nitrogen contributes 5.'},
      {q:'What is the first move in the Lewis method?',choices:['Count total valence electrons','Draw all bonds first'],answer:'Count total valence electrons',why:'The electron budget has to exist before bonds can spend it.'},
      {q:'CH4 has how many total valence electrons?',choices:['4','8','12'],answer:'8',why:'Carbon contributes 4 and four hydrogens contribute 4 more.'},
      {q:'After three N-H bonds in NH3 use 6 electrons, how many of the original 8 remain?',choices:['0','2','6'],answer:'2',why:'Those 2 remaining electrons become one lone pair on nitrogen.'}
    ],
    'formal-charge':[
      {q:'Formal charge is best treated here as what?',choices:['Electron bookkeeping','The same thing as partial charge'],answer:'Electron bookkeeping',why:'It is a bookkeeping assignment made by splitting covalent bonds evenly.'},
      {q:'In FC = V - N - B, what does N count?',choices:['Lone pairs','Nonbonding electrons'],answer:'Nonbonding electrons',why:'N counts individual nonbonding electrons, not pairs.'},
      {q:'For carbon in CH4, V=4, N=0, B=4. What is FC?',choices:['0','+1','-1'],answer:'0',why:'4 - 0 - 4 = 0.'},
      {q:'For hydronium oxygen, V=6, N=2, B=3. What is FC?',choices:['0','+1','-1'],answer:'+1',why:'6 - 2 - 3 = +1.'},
      {q:'The sum of all atom formal charges must equal what?',choices:['The species charge','The number of atoms'],answer:'The species charge',why:'The whole-structure charge check must match the charge written on the species.'}
    ]
  };

  function key(id){return'chm221.chapter1.'+id+'.v1';}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function save(){if(active)localStorage.setItem(key(active.lessonId),JSON.stringify(active));renderCards();}
  function load(id){try{var raw=localStorage.getItem(key(id));return raw?JSON.parse(raw):null;}catch(_){return null;}}
  function lesson(){return active?Data.lesson(active.lessonId):null;}
  function phaseLabel(){return PHASE_LABELS[active.phase]||active.phase;}
  function status(id){var s=load(id);if(!s)return'Not started';if(s.mastered||s.phase==='complete')return'Mastered';return'In progress';}
  function phaseItemKey(){var item=Engine.currentItem(active);return active.lessonId+'|'+active.phase+'|'+(item?item.id:'none');}
  function clearTeachingTransient(){supportedIntervention=null;watchFeedback='';message='';}

  function renderCards(){cards.innerHTML=Data.LESSONS.map(function(l,i){var st=status(l.id);return '<article class="lesson-card '+(active&&active.lessonId===l.id?'selected':'')+'"><div class="lesson-number">Lesson '+(i+1)+'</div><div class="lesson-status '+st.toLowerCase().replace(/\s/g,'-')+'">'+esc(st)+'</div><h3>'+esc(l.title)+'</h3><p>'+esc(l.subtitle)+'</p><p class="source">'+esc(l.source)+'</p><button type="button" data-open-lesson="'+esc(l.id)+'">'+(st==='Not started'?'Start lesson':'Open lesson')+'</button></article>';}).join('');cards.querySelectorAll('[data-open-lesson]').forEach(function(b){b.addEventListener('click',function(){openLesson(b.dataset.openLesson);});});}
  function openLesson(id){active=load(id)||Engine.createSession(id,Date.now());clearTeachingTransient();save();render();history.replaceState(null,'','?lesson='+encodeURIComponent(id));}
  function fieldForm(item,buttonLabel,extra){return '<form class="answer-form" data-answer-form>'+item.fields.map(function(f){return '<label>'+esc(f.label)+'<input autocomplete="off" inputmode="text" name="'+esc(f.id)+'" aria-label="'+esc(f.label)+'"></label>';}).join('')+'<div class="actions"><button type="submit">'+esc(buttonLabel||'Check answer')+'</button>'+(extra||'')+'</div></form>';}
  function answers(form){var out={};new FormData(form).forEach(function(v,k){out[k]=v;});return out;}
  function isBlank(a){return Object.keys(a).every(function(k){return !String(a[k]||'').trim();});}
  function feedback(){return message?'<div class="feedback" role="status">'+esc(message)+'</div>':'';}
  function shell(inner){var l=lesson();return '<section class="lesson-shell"><div class="lesson-head"><div><div class="eyebrow">Chapter 1 · '+esc(l.source)+'</div><h2>'+esc(l.title)+'</h2></div><span class="phase-pill" id="phaseLabel">'+esc(phaseLabel())+'</span></div>'+feedback()+inner+'</section>';}
  function bindAnswer(handler,selector){var form=host.querySelector(selector||'[data-answer-form]');if(form)form.addEventListener('submit',function(e){e.preventDefault();handler(answers(form),form);});}
  function progressText(){var l=lesson();if(active.phase==='prerequisite')return 'Foundation '+(active.prerequisiteIndex+1)+' of '+l.prerequisite.length;if(active.phase==='concept')return 'Concept '+(active.conceptIndex+1)+' of '+l.concept.length;if(active.phase==='build')return 'Build step '+(active.buildIndex+1)+' of '+l.build.length;if(active.phase==='guided')return 'Guided step '+(active.guidedIndex+1)+' of '+l.guided.length;return'';}
  function supportedBanner(){
    if(active.phase==='prerequisite')return '<div class="diagnostic-banner"><b>First, find the foundation.</b><br>A miss here is not a failure. It tells Dr. Merissa what prerequisite needs repair before formal charge starts.</div>';
    if(active.phase==='concept')return '<div class="supported-banner"><b>Supported Concept Check</b><br>This is low-risk learning practice. A wrong answer becomes information about what to teach next.</div>';
    if(active.phase==='build')return '<div class="we-do-banner"><b>Build Together · '+esc(progressText())+'</b><br>We are doing one decision at a time. If a step breaks, we stop on that step instead of pushing forward.</div>';
    return '<div class="guided-banner"><b>Guided Practice · '+esc(progressText())+'</b><br>You do the work. Support stays available, but Dr. Merissa only steps in where the reasoning breaks.</div>';
  }
  function firstErrorCode(item){return item&&item.fields&&item.fields[0]?item.fields[0].errorCode:null;}
  function firstFieldLabel(item){return item&&item.fields&&item.fields[0]?item.fields[0].label:'this step';}
  function planFor(code){return Teach.plan(active.lessonId,code);}

  function reasonButtons(){return '<div class="reason-grid">'+Teach.REASONS.map(function(r){return '<button type="button" class="reason-button" data-supported-reason="'+esc(r.id)+'">'+esc(r.label)+'</button>';}).join('')+'</div>';}
  function interventionHtml(){
    var x=supportedIntervention;if(!x)return'';var plan=planFor(x.errorCode),label=plan?plan.label:(x.fieldLabel||'this step');
    if(x.mode==='wrong')return '<div class="diagnosis-card" data-supported-diagnosis><div class="eyebrow">Dr. Merissa noticed where it broke</div><h3>'+esc(label)+'</h3><p>Your answer gives me a clue about the first uncertain step. That is useful. I am not going to mark it wrong and stare at you.</p><p><b>First nudge:</b> '+esc(plan?plan.start:(lesson().reteach[x.errorCode]||'Work one step at a time.'))+'</p><div class="actions"><button type="button" id="supportedRetry">I know it — let me retry once</button><button type="button" class="ghost" id="supportedDiagnose">I need teaching on this</button></div></div>';
    if(x.mode==='diagnose')return '<div class="diagnosis-card" data-supported-diagnosis><div class="eyebrow">Find the reason before reteaching</div><h3>The first broken step looks like: '+esc(label)+'</h3><p>Which description is closest? Your choice changes what I do next.</p>'+reasonButtons()+'</div>';
    if(x.mode==='teach'){
      var check=lesson().repairChecks[x.errorCode];
      return '<div class="targeted-teach-card" data-supported-teach><div class="eyebrow">Targeted teaching · '+esc(Teach.reasonLabel(x.reason))+'</div><h3>'+esc(label)+'</h3><div class="teacher"><div class="avatar">DM</div><div><b>Dr. Merissa</b><p>'+esc(x.teaching)+'</p></div></div><div class="repair-mini"><b>Now check only that smaller idea.</b><p>This is supported repair. It does not count as cold evidence.</p><div class="prompt">'+esc(check.prompt)+'</div>'+fieldForm(check,'Check repaired step')+'<div data-repair-feedback></div></div></div>';
    }
    return'';
  }

  function bindSupportedIntervention(){
    if(!supportedIntervention)return;
    var retry=host.querySelector('#supportedRetry');if(retry)retry.addEventListener('click',function(){supportedIntervention=null;message='Try the same supported step once more. If it misses again, we stop and teach it.';render();});
    var diagnose=host.querySelector('#supportedDiagnose');if(diagnose)diagnose.addEventListener('click',function(){supportedIntervention.mode='diagnose';message='';render();});
    host.querySelectorAll('[data-supported-reason]').forEach(function(b){b.addEventListener('click',function(){supportedIntervention.reason=b.dataset.supportedReason;supportedIntervention.teaching=Teach.text(active.lessonId,supportedIntervention.errorCode,supportedIntervention.reason)||(lesson().reteach[supportedIntervention.errorCode]||'Repair this exact idea.');supportedIntervention.mode='teach';message='';render();});});
    if(supportedIntervention.mode==='teach')bindSupportedRepair();
  }

  function advanceAfterSupportedRepair(sourcePhase){var l=lesson();
    if(sourcePhase==='prerequisite'){active.prerequisiteIndex++;if(active.prerequisiteIndex>=l.prerequisite.length){active.prerequisiteIndex=0;Engine.setPhase(active,'watch');}}
    else if(sourcePhase==='concept'){active.conceptIndex++;if(active.conceptIndex>=l.concept.length){active.conceptIndex=0;Engine.setPhase(active,'build');}}
    else if(sourcePhase==='build'){active.buildIndex++;if(active.buildIndex>=l.build.length){active.buildIndex=0;Engine.setPhase(active,'guided');}}
    else if(sourcePhase==='guided'){active.guidedIndex++;if(active.guidedIndex>=l.guided.length){active.guidedIndex=0;active.independentIndex=0;Engine.setPhase(active,'independent');}}
  }
  function bindSupportedRepair(){var form=host.querySelector('.repair-mini [data-answer-form]');if(!form)return;form.addEventListener('submit',function(e){e.preventDefault();var a=answers(form),check=lesson().repairChecks[supportedIntervention.errorCode],g=Engine.grade(check,a),at=Date.now();Router.recordAttempt(active.skill,check.id,g.correct,g.errorCode,at,a);var fb=host.querySelector('[data-repair-feedback]');
      if(!g.correct){supportedIntervention.repairMisses=(supportedIntervention.repairMisses||0)+1;var alt=Teach.text(active.lessonId,supportedIntervention.errorCode,'explanation_not_making_sense');if(supportedIntervention.repairMisses===1){supportedIntervention.teaching=alt||supportedIntervention.teaching;message='That smaller check still missed, so I switched the representation instead of repeating myself.';save();render();return;}Engine.setPhase(active,'watch');active.watchIndex=0;active._watchChecks={};watchFeedback='';supportedIntervention=null;wrongCounts={};message='That foundation is still unstable. We are stepping back to Watch so you can see it built again before trying it.';save();render();return;}
      var source=supportedIntervention.sourcePhase,oldId=supportedIntervention.sourceItemId;delete wrongCounts[active.lessonId+'|'+source+'|'+oldId];advanceAfterSupportedRepair(source);supportedIntervention=null;message='That missing piece is repaired. I am not making you repeat the same question. Here is the next fresh step.';save();render();
    });}

  function renderWatch(){var l=lesson(),w=l.watch[active.watchIndex],check=(WATCH_CHECKS[active.lessonId]||[])[active.watchIndex],passed=active._watchChecks&&active._watchChecks[active.watchIndex];var options=check?'<div class="watch-check"><div class="eyebrow">Do something with the idea</div><h3>'+esc(check.q)+'</h3><div class="watch-options">'+check.choices.map(function(c){return '<button type="button" class="ghost" data-watch-choice="'+esc(c)+'">'+esc(c)+'</button>';}).join('')+'</div>'+(watchFeedback?'<div class="mini-feedback">'+esc(watchFeedback)+'</div>':'')+'</div>':'';host.innerHTML=shell('<div class="teacher"><div class="avatar">DM</div><div><b>Dr. Merissa</b><p>'+esc(w.text)+'</p></div></div><div class="visual-stage"><strong>'+esc(w.visual)+'</strong></div><div class="watch-note"><b>'+esc(w.title)+'</b><br>Follow the reasoning that makes it true instead of memorizing the picture.</div>'+options+'<div class="actions"><button type="button" id="nextWatch" '+(check&&!passed?'disabled aria-disabled="true"':'')+'>'+(active.watchIndex===l.watch.length-1?'Start supported check':'Next teaching step')+'</button></div>');host.querySelectorAll('[data-watch-choice]').forEach(function(b){b.addEventListener('click',function(){if(b.dataset.watchChoice===check.answer){if(!active._watchChecks)active._watchChecks={};active._watchChecks[active.watchIndex]=true;watchFeedback='Yes. '+check.why;save();render();}else{watchFeedback='Not yet. '+check.why+' Try the prediction again before moving on.';render();}});});var next=host.querySelector('#nextWatch');next.addEventListener('click',function(){if(check&&!active._watchChecks[active.watchIndex])return;message='';watchFeedback='';Engine.advanceWatch(active);save();render();});}

  function renderSupported(){var item=Engine.currentItem(active),title=phaseLabel(),answerArea=supportedIntervention?'':fieldForm(item,'Check','<button type="button" class="ghost" id="supportedIdk">I don’t know yet</button>')+'<div class="actions secondary-actions"><button type="button" class="ghost" id="supportedHint">Give me a first-step hint</button></div>';host.innerHTML=shell(supportedBanner()+'<div class="stage-progress">'+esc(progressText())+'</div><div class="prompt">'+esc(item.prompt)+'</div>'+answerArea+interventionHtml());if(!supportedIntervention)bindAnswer(function(a){
      if(isBlank(a)){supportedIntervention={sourcePhase:active.phase,sourceItemId:item.id,errorCode:firstErrorCode(item),fieldLabel:firstFieldLabel(item),mode:'diagnose',wrongCount:wrongCounts[phaseItemKey()]||0};message='A blank answer cannot tell me what misconception you have. Tell me where you are stuck and I will teach that part.';render();return;}
      var before=Engine.grade(item,a),r=Engine.submitSupported(active,a,Date.now());if(r.correct){delete wrongCounts[phaseItemKey()];supportedIntervention=null;message=active.phase==='build'?'Yes. That build step is accounted for. Keep the work and add the next decision.':active.phase==='guided'?'Correct with support available. Keep going; I will fade back unless you need me.':'Good. That idea is stable enough to move to the next supported step.';save();render();return;}
      var k=phaseItemKey(),count=(wrongCounts[k]||0)+1;wrongCounts[k]=count;supportedIntervention={sourcePhase:active.phase,sourceItemId:item.id,errorCode:before.errorCode||r.errorCode||firstErrorCode(item),fieldLabel:before.fieldLabel||firstFieldLabel(item),mode:(active.phase==='prerequisite'||active.phase==='build'||count>=2)?'diagnose':'wrong',wrongCount:count};message='Not yet. I am using that answer to locate the first broken step instead of just waiting for the right answer.';save();render();
    });var supportedIdk=host.querySelector('#supportedIdk');if(supportedIdk)supportedIdk.addEventListener('click',function(){supportedIntervention={sourcePhase:active.phase,sourceItemId:item.id,errorCode:firstErrorCode(item),fieldLabel:firstFieldLabel(item),mode:'diagnose',wrongCount:wrongCounts[phaseItemKey()]||0};message='You do not have to guess. Tell me what kind of stuck this is.';render();});var supportedHint=host.querySelector('#supportedHint');if(supportedHint)supportedHint.addEventListener('click',function(){var code=firstErrorCode(item),plan=planFor(code);supportedIntervention={sourcePhase:active.phase,sourceItemId:item.id,errorCode:code,fieldLabel:firstFieldLabel(item),mode:'wrong',wrongCount:wrongCounts[phaseItemKey()]||0};message=plan?'First-step hint: '+plan.start:(lesson().reteach[code]||'Work one step at a time.');render();});bindSupportedIntervention();}

  function renderIndependent(){if(active.repair&&active.repair.active)return renderRepair();var item=Engine.currentItem(active);host.innerHTML=shell('<div class="cold-banner"><b>Cold evidence</b><br>Try this without notes or hints. If you ask for help, this item becomes supported and a fresh item will be used for evidence.</div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check answer')+'<div class="actions secondary-actions"><button type="button" class="ghost" data-independent-help id="idkBtn">I do not know yet</button></div>');bindAnswer(function(a){var r=Engine.submitIndependent(active,a,Date.now());message=r.correct?(r.sufficientEvidence?'Cold answer recorded. Now explain why.':'Clean cold evidence recorded. You need another fresh cold construction before Explain Why.'):(r.teaching||'This item is now practice. Repair the idea, then use a fresh item.');save();render();});host.querySelector('#idkBtn').addEventListener('click',renderColdIdkChooser);}
  function renderColdIdkChooser(){var box=host.querySelector('[data-idk-box]');if(box){box.remove();return;}box=document.createElement('div');box.setAttribute('data-idk-box','');box.className='idk-box';box.innerHTML='<h3>What part is getting in your way?</h3><p>Choose the closest reason so the lesson can respond to the actual problem.</p><div class="reason-grid">'+Teach.REASONS.map(function(r){return'<button type="button" data-reason="'+r.id+'">'+esc(r.label)+'</button>';}).join('')+'</div>';var form=host.querySelector('.answer-form');if(form)form.insertAdjacentElement('afterend',box);box.querySelectorAll('[data-reason]').forEach(function(b){b.addEventListener('click',function(){var r=Engine.requestColdHelp(active,b.dataset.reason,Date.now());message=r.teaching||'Support opened. Repair this idea before the next cold item.';save();render();});});}
  function renderRepair(){var r=active.repair;host.innerHTML=shell('<div class="repair-card"><div class="eyebrow">Repair the exact broken step</div><h3>'+esc(r.teaching)+'</h3><p>Before another cold question, prove this smaller idea with support.</p><div class="prompt">'+esc(r.check.prompt)+'</div>'+fieldForm(r.check,'Check repaired idea')+'</div>');bindAnswer(function(a){var out=Engine.submitRepair(active,a,Date.now());message=out.correct?'Repair passed. The next question is fresh.':'That repair is not stable yet. We are returning to teaching instead of guessing.';save();render();});}
  function renderExplain(){var l=lesson();host.innerHTML=shell('<div class="cold-banner"><b>Your explanation is evidence too.</b><br>Explain the reasoning in your own words. Do not use outside help if you want this attempt to remain independent.</div><div class="prompt">'+esc(l.explanation.prompt)+'</div><form data-explain-form><label>Your explanation<textarea name="explanation" rows="6" required></textarea></label><div class="actions"><button type="submit">Check explanation</button></div></form>');host.querySelector('[data-explain-form]').addEventListener('submit',function(e){e.preventDefault();var text=new FormData(e.currentTarget).get('explanation');var r=Engine.submitExplanation(active,text,Date.now());message=r.correct?'Explanation attached to the cold success. Now transfer the idea.':r.teaching;save();render();});}
  function renderTransfer(){var item=Engine.currentItem(active);host.innerHTML=shell('<div class="supported-banner"><b>Transfer</b><br>This checks whether the same rule survives a new-looking problem. Transfer does not create the delayed mastery confirmation.</div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check transfer'));bindAnswer(function(a){var r=Engine.submitTransfer(active,a,Date.now());message=r.correct?'Transfer passed. Next comes a different chemistry activity before later retrieval.':r.teaching;save();render();});}
  function renderActivity(){var item=Engine.currentItem(active);host.innerHTML=shell('<div class="activity-card"><b>Switch skills on purpose</b><p>This different chemistry activity creates real spacing before retrieval. It does not add mastery evidence for this lesson.</p></div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check activity'));bindAnswer(function(a){var r=Engine.submitActivity(active,a,Date.now());message=r.correct?'Intervening activity complete. Later retrieval now waits on the minimum interval.':r.teaching;save();render();});}
  function formatWait(ms){var sec=Math.ceil(ms/1000);if(sec<60)return sec+' seconds';var min=Math.ceil(sec/60);return min+' minute'+(min===1?'':'s');}
  function renderRetrievalWait(){var r=Engine.retrievalReadiness(active,Date.now());host.innerHTML=shell('<div class="retrieval-card"><h3>Later retrieval is intentionally later.</h3><p>The engine requires both a meaningful intervening chemistry activity and at least '+(Router.MIN_RETRIEVAL_DELAY_MS/60000)+' minutes after the explained cold success. Nothing auto-advances.</p><p><b>Activity:</b> '+(active.activityComplete?'complete':'not complete')+'</p><p><b>Interval:</b> '+(r.ready?'ready':r.remainingMs!=null?formatWait(r.remainingMs)+' remaining':'not ready')+'</p><div class="actions"><button type="button" id="checkReady">'+(r.ready?'Start Later Retrieval':'Check retrieval readiness')+'</button></div></div>');host.querySelector('#checkReady').addEventListener('click',function(){var out=Engine.startRetrieval(active,Date.now());message=out.accepted?'Retrieval is ready. Answer from memory.':('Not ready yet: '+formatWait(out.remainingMs||0)+' remaining.');save();render();});}
  function renderRetrieval(){if(active.repair&&active.repair.active)return renderRepair();var item=Engine.currentItem(active);host.innerHTML=shell('<div class="cold-banner"><b>Later cold retrieval</b><br>This is the second distinct cold opportunity. Help remains available, but using it makes this item supported.</div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check retrieval')+'<div class="actions secondary-actions"><button type="button" class="ghost" data-retrieval-help id="retrievalHelp">I need help</button></div>');bindAnswer(function(a){var r=Engine.submitRetrieval(active,a,Date.now());if(r.mastery&&r.mastery.mastered)message='Mastery confirmed by the shared Student Model.';else if(r.correct)message='Correct retrieval recorded, but mastery is not yet valid: '+(r.mastery?r.mastery.reason:'fresh evidence still needed');else message=r.teaching||'That retrieval is diagnostic. Use the fresh item next.';save();render();});host.querySelector('#retrievalHelp').addEventListener('click',renderColdIdkChooser);}
  function renderComplete(){host.innerHTML=shell('<div class="complete-card"><div class="checkmark">✓</div><h2>Chapter 1 lesson mastered</h2><p>The shared Student Model found an explained cold success plus a different cold retrieval success after the required spacing and intervening activity.</p><div class="actions"><button type="button" id="backLessons">Back to Chapter 1 lessons</button></div></div>');host.querySelector('#backLessons').addEventListener('click',function(){active=null;clearTeachingTransient();render();});}
  function renderOverview(){host.innerHTML='<section class="overview"><div class="eyebrow">Chapter 1 teaching engine</div><h2>Learn the foundations in dependency order.</h2><p>Dr. Merissa does more than wait for a right answer. During teaching, a miss identifies the first uncertain step, asks what kind of stuck it is, repairs that deficit, checks the smaller idea, then returns to a fresh step.</p><div class="flow">Watch + prediction → Supported Check → Build Together → Guided → Cold Independent → Explain Why → Transfer → Different Chemistry Activity → Later Retrieval</div><p class="small">Support teaches. Only fresh cold evidence can move the shared Student Model toward mastery.</p></section>';}
  function render(){renderCards();if(!active){renderOverview();return;}if(active.phase==='watch')renderWatch();else if(['prerequisite','concept','build','guided'].indexOf(active.phase)!==-1)renderSupported();else if(active.phase==='independent')renderIndependent();else if(active.phase==='explain')renderExplain();else if(active.phase==='transfer')renderTransfer();else if(active.phase==='activity')renderActivity();else if(active.phase==='retrieval-wait')renderRetrievalWait();else if(active.phase==='retrieval')renderRetrieval();else if(active.phase==='complete')renderComplete();else renderOverview();}
  var q=new URLSearchParams(location.search).get('lesson');if(q&&Data.lesson(q))active=load(q)||Engine.createSession(q,Date.now());render();
})();