(function(){
  'use strict';
  var Data=globalThis.Chapter1TeachingData,Engine=globalThis.Chapter1TeachingEngine,Router=globalThis.StudentModelIdkRouter;
  if(!Data||!Engine||!Router)throw new Error('Chapter 1 teaching dependencies are missing');
  var host=document.querySelector('[data-ch1-host]'),cards=document.querySelector('[data-ch1-lessons]');
  var active=null,message='';
  var REASONS=[['dont_understand_concept','I do not understand the concept'],['dont_know_how_to_start','I do not know how to start'],['forgot_prerequisite','I forgot something I need first'],['started_but_stuck','I started but got stuck'],['show_me_example','Show me a similar example'],['explanation_not_making_sense','The explanation is not making sense']];
  var PHASE_LABELS={prerequisite:'Prerequisite check',watch:'Watch · I Do',concept:'Supported Concept Check',build:'Build Together',guided:'Guided Practice',independent:'Cold Independent',explain:'Explain Why',transfer:'Transfer',activity:'Intervening Chemistry Activity','retrieval-wait':'Later Retrieval',retrieval:'Later Retrieval · Cold',complete:'Mastered'};
  function key(id){return'chm221.chapter1.'+id+'.v1';}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function save(){if(active)localStorage.setItem(key(active.lessonId),JSON.stringify(active));renderCards();}
  function load(id){try{var raw=localStorage.getItem(key(id));return raw?JSON.parse(raw):null;}catch(_){return null;}}
  function lesson(){return active?Data.lesson(active.lessonId):null;}
  function phaseLabel(){return PHASE_LABELS[active.phase]||active.phase;}
  function status(id){var s=load(id);if(!s)return'Not started';if(s.mastered||s.phase==='complete')return'Mastered';return'In progress';}
  function renderCards(){cards.innerHTML=Data.LESSONS.map(function(l,i){var st=status(l.id);return '<article class="lesson-card '+(active&&active.lessonId===l.id?'selected':'')+'"><div class="lesson-number">Lesson '+(i+1)+'</div><div class="lesson-status '+st.toLowerCase().replace(/\s/g,'-')+'">'+esc(st)+'</div><h3>'+esc(l.title)+'</h3><p>'+esc(l.subtitle)+'</p><p class="source">'+esc(l.source)+'</p><button type="button" data-open-lesson="'+esc(l.id)+'">'+(st==='Not started'?'Start lesson':'Open lesson')+'</button></article>';}).join('');cards.querySelectorAll('[data-open-lesson]').forEach(function(b){b.addEventListener('click',function(){openLesson(b.dataset.openLesson);});});}
  function openLesson(id){active=load(id)||Engine.createSession(id,Date.now());message='';save();render();history.replaceState(null,'','?lesson='+encodeURIComponent(id));}
  function fieldForm(item,buttonLabel){return '<form class="answer-form" data-answer-form>'+item.fields.map(function(f){return '<label>'+esc(f.label)+'<input autocomplete="off" inputmode="text" name="'+esc(f.id)+'" aria-label="'+esc(f.label)+'"></label>';}).join('')+'<div class="actions"><button type="submit">'+esc(buttonLabel||'Check answer')+'</button></div></form>';}
  function answers(form){var out={};new FormData(form).forEach(function(v,k){out[k]=v;});return out;}
  function feedback(){return message?'<div class="feedback">'+esc(message)+'</div>':'';}
  function shell(inner){var l=lesson();return '<section class="lesson-shell"><div class="lesson-head"><div><div class="eyebrow">Chapter 1 · '+esc(l.source)+'</div><h2>'+esc(l.title)+'</h2></div><span class="phase-pill" id="phaseLabel">'+esc(phaseLabel())+'</span></div>'+feedback()+inner+'</section>';}
  function bindAnswer(handler){var form=host.querySelector('[data-answer-form]');if(form)form.addEventListener('submit',function(e){e.preventDefault();handler(answers(form));});}
  function renderWatch(){var l=lesson(),w=l.watch[active.watchIndex];host.innerHTML=shell('<div class="teacher"><div class="avatar">DM</div><div><b>Dr. Merissa</b><p>'+esc(w.text)+'</p></div></div><div class="visual-stage"><strong>'+esc(w.visual)+'</strong></div><div class="watch-note"><b>'+esc(w.title)+'</b><br>Follow the reasoning that makes it true instead of memorizing the picture.</div><div class="actions"><button type="button" id="nextWatch">'+(active.watchIndex===l.watch.length-1?'Start supported check':'Next teaching step')+'</button></div>');host.querySelector('#nextWatch').addEventListener('click',function(){message='';Engine.advanceWatch(active);save();render();});}
  function renderSupported(){var item=Engine.currentItem(active),title=phaseLabel();host.innerHTML=shell('<div class="supported-banner"><b>'+esc(title)+'</b><br>This is learning practice. Support here does not count as cold mastery evidence.</div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check')+'<div class="actions secondary-actions"><button type="button" class="ghost" id="supportedHint">Give me a hint</button></div>');bindAnswer(function(a){var r=Engine.submitSupported(active,a,Date.now());message=r.correct?'Good. Keep going.':r.teaching;save();render();});host.querySelector('#supportedHint').addEventListener('click',function(){var first=item.fields[0];message=lesson().reteach[first.errorCode]||'Work one field at a time.';render();});}
  function renderIndependent(){if(active.repair&&active.repair.active)return renderRepair();var item=Engine.currentItem(active);host.innerHTML=shell('<div class="cold-banner"><b>Cold evidence</b><br>Try this without notes or hints. If you ask for help, this item becomes supported and a fresh item will be used for evidence.</div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check answer')+'<div class="actions secondary-actions"><button type="button" class="ghost" data-independent-help id="idkBtn">I do not know yet</button></div>');bindAnswer(function(a){var r=Engine.submitIndependent(active,a,Date.now());message=r.correct?'Cold answer recorded. Now explain why.':(r.teaching||'This item is now practice. Repair the idea, then use a fresh item.');save();render();});host.querySelector('#idkBtn').addEventListener('click',renderIdkChooser);}
  function renderIdkChooser(){var box=host.querySelector('[data-idk-box]');if(box){box.remove();return;}box=document.createElement('div');box.setAttribute('data-idk-box','');box.className='idk-box';box.innerHTML='<h3>What part is getting in your way?</h3><p>Choose the closest reason so the lesson can respond to the actual problem.</p><div class="reason-grid">'+REASONS.map(function(r){return'<button type="button" data-reason="'+r[0]+'">'+esc(r[1])+'</button>';}).join('')+'</div>';var form=host.querySelector('.answer-form');if(form)form.insertAdjacentElement('afterend',box);box.querySelectorAll('[data-reason]').forEach(function(b){b.addEventListener('click',function(){var r=Engine.requestColdHelp(active,b.dataset.reason,Date.now());message=r.teaching||'Support opened. Repair this idea before the next cold item.';save();render();});});}
  function renderRepair(){var r=active.repair;host.innerHTML=shell('<div class="repair-card"><div class="eyebrow">Repair the exact broken step</div><h3>'+esc(r.teaching)+'</h3><p>Before another cold question, prove this smaller idea with support.</p><div class="prompt">'+esc(r.check.prompt)+'</div>'+fieldForm(r.check,'Check repaired idea')+'</div>');bindAnswer(function(a){var out=Engine.submitRepair(active,a,Date.now());message=out.correct?'Repair passed. The next question is fresh.':'That repair is not stable yet. We are returning to teaching instead of guessing.';save();render();});}
  function renderExplain(){var l=lesson();host.innerHTML=shell('<div class="cold-banner"><b>Your explanation is evidence too.</b><br>Explain the reasoning in your own words. Do not use outside help if you want this attempt to remain independent.</div><div class="prompt">'+esc(l.explanation.prompt)+'</div><form data-explain-form><label>Your explanation<textarea name="explanation" rows="6" required></textarea></label><div class="actions"><button type="submit">Check explanation</button></div></form>');host.querySelector('[data-explain-form]').addEventListener('submit',function(e){e.preventDefault();var text=new FormData(e.currentTarget).get('explanation');var r=Engine.submitExplanation(active,text,Date.now());message=r.correct?'Explanation attached to the cold success. Now transfer the idea.':r.teaching;save();render();});}
  function renderTransfer(){var item=Engine.currentItem(active);host.innerHTML=shell('<div class="supported-banner"><b>Transfer</b><br>This checks whether the same rule survives a new-looking problem. Transfer does not create the delayed mastery confirmation.</div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check transfer'));bindAnswer(function(a){var r=Engine.submitTransfer(active,a,Date.now());message=r.correct?'Transfer passed. Next comes a different chemistry activity before later retrieval.':r.teaching;save();render();});}
  function renderActivity(){var item=Engine.currentItem(active);host.innerHTML=shell('<div class="activity-card"><b>Switch skills on purpose</b><p>This different chemistry activity creates real spacing before retrieval. It does not add mastery evidence for this lesson.</p></div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check activity'));bindAnswer(function(a){var r=Engine.submitActivity(active,a,Date.now());message=r.correct?'Intervening activity complete. Later retrieval now waits on the minimum interval.':r.teaching;save();render();});}
  function formatWait(ms){var sec=Math.ceil(ms/1000);if(sec<60)return sec+' seconds';var min=Math.ceil(sec/60);return min+' minute'+(min===1?'':'s');}
  function renderRetrievalWait(){var r=Engine.retrievalReadiness(active,Date.now());host.innerHTML=shell('<div class="retrieval-card"><h3>Later retrieval is intentionally later.</h3><p>The engine requires both a meaningful intervening chemistry activity and at least '+(Router.MIN_RETRIEVAL_DELAY_MS/60000)+' minutes after the explained cold success. Nothing auto-advances.</p><p><b>Activity:</b> '+(active.activityComplete?'complete':'not complete')+'</p><p><b>Interval:</b> '+(r.ready?'ready':r.remainingMs!=null?formatWait(r.remainingMs)+' remaining':'not ready')+'</p><div class="actions"><button type="button" id="checkReady">'+(r.ready?'Start Later Retrieval':'Check retrieval readiness')+'</button></div></div>');host.querySelector('#checkReady').addEventListener('click',function(){var out=Engine.startRetrieval(active,Date.now());message=out.accepted?'Retrieval is ready. Answer from memory.':('Not ready yet: '+formatWait(out.remainingMs||0)+' remaining.');save();render();});}
  function renderRetrieval(){if(active.repair&&active.repair.active)return renderRepair();var item=Engine.currentItem(active);host.innerHTML=shell('<div class="cold-banner"><b>Later cold retrieval</b><br>This is the second distinct cold opportunity. Help remains available, but using it makes this item supported.</div><div class="prompt">'+esc(item.prompt)+'</div>'+fieldForm(item,'Check retrieval')+'<div class="actions secondary-actions"><button type="button" class="ghost" data-retrieval-help id="retrievalHelp">I need help</button></div>');bindAnswer(function(a){var r=Engine.submitRetrieval(active,a,Date.now());if(r.mastery&&r.mastery.mastered)message='Mastery confirmed by the shared Student Model.';else if(r.correct)message='Correct retrieval recorded, but mastery is not yet valid: '+(r.mastery?r.mastery.reason:'fresh evidence still needed');else message=r.teaching||'That retrieval is diagnostic. Use the fresh item next.';save();render();});host.querySelector('#retrievalHelp').addEventListener('click',renderIdkChooser);}
  function renderComplete(){host.innerHTML=shell('<div class="complete-card"><div class="checkmark">✓</div><h2>Chapter 1 lesson mastered</h2><p>The shared Student Model found an explained cold success plus a different cold retrieval success after the required spacing and intervening activity.</p><div class="actions"><button type="button" id="backLessons">Back to Chapter 1 lessons</button></div></div>');host.querySelector('#backLessons').addEventListener('click',function(){active=null;message='';render();});}
  function renderOverview(){host.innerHTML='<section class="overview"><div class="eyebrow">Chapter 1 teaching engine</div><h2>Learn the foundations in dependency order.</h2><p>Start with Lewis structures. Formal charge begins with a Lewis prerequisite check, so the engine does not teach formal charge on top of a missing electron-counting foundation.</p><div class="flow">Watch → Supported Check → Build Together → Guided → Cold Independent → Explain Why → Transfer → Different Chemistry Activity → Later Retrieval</div><p class="small">Support teaches. Only fresh cold evidence can move the shared Student Model toward mastery.</p></section>';}
  function render(){renderCards();if(!active){renderOverview();return;}if(active.phase==='watch')renderWatch();else if(['prerequisite','concept','build','guided'].indexOf(active.phase)!==-1)renderSupported();else if(active.phase==='independent')renderIndependent();else if(active.phase==='explain')renderExplain();else if(active.phase==='transfer')renderTransfer();else if(active.phase==='activity')renderActivity();else if(active.phase==='retrieval-wait')renderRetrievalWait();else if(active.phase==='retrieval')renderRetrieval();else if(active.phase==='complete')renderComplete();else renderOverview();}
  var q=new URLSearchParams(location.search).get('lesson');if(q&&Data.lesson(q))active=load(q)||Engine.createSession(q,Date.now());render();
})();