(function(root,factory){
  var data=typeof module==='object'&&module.exports?require('./chapter1-data.js'):root.Chapter1TeachingData;
  var router=typeof module==='object'&&module.exports?require('../../../student-model-idk-router.js'):root.StudentModelIdkRouter;
  var api=factory(data,router);
  if(typeof module==='object'&&module.exports)module.exports=api;
  else root.Chapter1TeachingEngine=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(Data,Router){
  'use strict';
  if(!Data)throw new Error('Chapter1TeachingData is required');
  if(!Router)throw new Error('StudentModelIdkRouter is required');

  function normalize(value){return String(value==null?'':value).trim().toLowerCase().replace(/[−–—]/g,'-').replace(/\s+/g,' ');}
  function accepted(field,value){var n=normalize(value);return field.accepted.some(function(a){return normalize(a)===n;});}
  function grade(item,answers){answers=answers||{};for(var i=0;i<item.fields.length;i++){var field=item.fields[i];if(!accepted(field,answers[field.id]))return{correct:false,errorCode:field.errorCode,fieldId:field.id,fieldLabel:field.label};}return{correct:true,errorCode:null,fieldId:null,fieldLabel:null};}
  function explanationGrade(config,text){var t=normalize(text);if(!t||t.length<24)return{correct:false,reason:'too_short'};var groups=config.requiredGroups||[];var ok=groups.every(function(group){return group.some(function(term){var x=normalize(term);if(x.length===1)return new RegExp('\\b'+x+'\\b','i').test(t);return t.indexOf(x)!==-1;});});return{correct:ok,reason:ok?null:'missing_reasoning_component'};}
  function findIndex(list,id){return(list||[]).findIndex(function(x){return x.id===id;});}
  function log(session,type,payload,at){session.events.push({type:type,payload:payload||null,timestamp:at||Date.now()});}
  function setPhase(session,phase){session.phase=phase;if(phase==='watch')Router.moveToWatch(session.skill);else if(phase==='build')Router.moveToBuildTogether(session.skill);else if(phase==='guided')Router.moveToGuided(session.skill);else if(phase==='independent'||phase==='retrieval'){session.skill.state=Router.STATES.INDEPENDENT_ATTEMPTED;session.skill.scaffoldLevel=Router.SCAFFOLD.COLD;}else if(phase==='explain')session.skill.state=Router.STATES.EXPLAIN_WHY;else if(phase==='retrieval-wait')session.skill.state=Router.STATES.REVIEW_DUE;return session;}
  function createSession(lessonId,timestamp){var lesson=Data.lesson(lessonId);if(!lesson)throw new Error('Unknown Chapter 1 lesson: '+lessonId);var skill=Router.createSkill(lesson.skillId);Router.startTeaching(skill);var phase=lesson.prerequisite&&lesson.prerequisite.length?'prerequisite':'watch';if(phase==='watch')Router.moveToWatch(skill);return{version:1,lessonId:lesson.id,skill:skill,phase:phase,prerequisiteIndex:0,watchIndex:0,conceptIndex:0,buildIndex:0,guidedIndex:0,independentIndex:0,transferIndex:0,retrievalIndex:0,currentColdItemId:null,currentColdContaminated:false,firstColdItemId:null,firstColdAt:null,explainedItemId:null,transferPassed:false,activityComplete:false,activityAt:null,repair:null,mastered:false,startedAt:timestamp||Date.now(),events:[]};}
  function currentItem(session){var lesson=Data.lesson(session.lessonId);if(session.phase==='prerequisite')return lesson.prerequisite[session.prerequisiteIndex]||null;if(session.phase==='concept')return lesson.concept[session.conceptIndex]||null;if(session.phase==='build')return lesson.build[session.buildIndex]||null;if(session.phase==='guided')return lesson.guided[session.guidedIndex]||null;if(session.phase==='independent')return lesson.independent[session.independentIndex]||null;if(session.phase==='transfer')return lesson.transfer[session.transferIndex]||null;if(session.phase==='activity')return lesson.intervening;if(session.phase==='retrieval')return lesson.retrieval[session.retrievalIndex]||null;return null;}
  function advanceSupported(session){var lesson=Data.lesson(session.lessonId);if(session.phase==='prerequisite'){session.prerequisiteIndex++;if(session.prerequisiteIndex>=lesson.prerequisite.length){session.prerequisiteIndex=0;setPhase(session,'watch');}}else if(session.phase==='concept'){session.conceptIndex++;if(session.conceptIndex>=lesson.concept.length){session.conceptIndex=0;setPhase(session,'build');}}else if(session.phase==='build'){session.buildIndex++;if(session.buildIndex>=lesson.build.length){session.buildIndex=0;setPhase(session,'guided');}}else if(session.phase==='guided'){session.guidedIndex++;if(session.guidedIndex>=lesson.guided.length){session.guidedIndex=0;setPhase(session,'independent');session.independentIndex=0;}}}
  function submitSupported(session,answers,timestamp){var item=currentItem(session);if(!item)return{accepted:false,reason:'no_current_item'};var result=grade(item,answers);Router.recordAttempt(session.skill,item.id,result.correct,result.errorCode,timestamp,answers);log(session,'supported_attempt',{itemId:item.id,phase:session.phase,correct:result.correct,errorCode:result.errorCode},timestamp);if(!result.correct)return{accepted:true,correct:false,errorCode:result.errorCode,teaching:(Data.lesson(session.lessonId).reteach[result.errorCode]||'Review the step and try again.')};advanceSupported(session);return{accepted:true,correct:true,nextPhase:session.phase};}
  function advanceWatch(session){var lesson=Data.lesson(session.lessonId);if(session.phase!=='watch')return{accepted:false,reason:'wrong_phase'};session.watchIndex++;if(session.watchIndex>=lesson.watch.length){session.watchIndex=0;setPhase(session,'concept');}return{accepted:true,nextPhase:session.phase};}
  function repairFor(session,errorCode,returnPhase){var lesson=Data.lesson(session.lessonId);return{active:true,errorCode:errorCode,teaching:lesson.reteach[errorCode]||'Rebuild the idea one step at a time.',check:lesson.repairChecks[errorCode]||lesson.concept[0],returnPhase:returnPhase||'independent'};}
  function nextFreshIndex(list,currentIndex,excludedIds){excludedIds=excludedIds||[];for(var step=1;step<=list.length;step++){var idx=(currentIndex+step)%list.length;if(excludedIds.indexOf(list[idx].id)===-1)return idx;}return-1;}
  function submitIndependent(session,answers,timestamp){if(session.phase!=='independent')return{accepted:false,reason:'wrong_phase'};var lesson=Data.lesson(session.lessonId),item=currentItem(session);if(!item)return{accepted:false,reason:'bank_end'};session.currentColdItemId=item.id;session.skill.scaffoldLevel=Router.SCAFFOLD.COLD;var result=grade(item,answers);if(!result.correct){session.currentColdContaminated=true;var route=Router.handleWrongAttempt(session.skill,item.id,result.errorCode,item.id,timestamp,answers);session.repair=repairFor(session,result.errorCode,'independent');log(session,'cold_wrong',{itemId:item.id,errorCode:result.errorCode,route:route.action},timestamp);return{accepted:true,correct:false,countedAsIndependent:false,freshItemRequired:true,errorCode:result.errorCode,teaching:session.repair.teaching,remediationActive:!!route.remediationActive};}if(session.currentColdContaminated||Router.isRemediationActive(session.skill)){Router.recordAttempt(session.skill,item.id,true,null,timestamp,answers);session.repair=repairFor(session,item.fields[0].errorCode,'independent');return{accepted:true,correct:true,countedAsIndependent:false,freshItemRequired:true,teaching:'This item already received support, so it cannot become cold evidence. Pass the repair check, then use a fresh item.'};}Router.recordIndependentAttempt(session.skill,item.id,true,false,timestamp,answers);session.firstColdItemId=item.id;session.firstColdAt=timestamp||Date.now();session.explainedItemId=null;setPhase(session,'explain');log(session,'cold_success',{itemId:item.id},timestamp);return{accepted:true,correct:true,countedAsIndependent:true,nextPhase:'explain'};}
  function requestColdHelp(session,reason,timestamp){if(session.phase!=='independent'&&session.phase!=='retrieval')return{accepted:false,reason:'wrong_phase'};var item=currentItem(session);if(!item)return{accepted:false,reason:'no_current_item'};session.currentColdItemId=item.id;session.currentColdContaminated=true;var route=Router.handleIdk(session.skill,reason,item.id,Data.lesson(session.lessonId).skillId,timestamp);session.repair=repairFor(session,item.fields[0].errorCode,'independent');log(session,'cold_help',{itemId:item.id,reason:reason,route:route.action},timestamp);return{accepted:true,countedAsIndependent:false,action:route.action,teaching:session.repair.teaching,remediationActive:true};}
  function submitRepair(session,answers,timestamp){if(!session.repair||!session.repair.active)return{accepted:false,reason:'no_repair'};var result=grade(session.repair.check,answers);if(Router.isRemediationActive(session.skill)){var routed=Router.recordRemediationCheck(session.skill,result.correct,session.repair.check.id,timestamp);if(!result.correct){setPhase(session,'watch');session.watchIndex=0;session.repair=null;return{accepted:true,correct:false,escalated:true,representation:routed.representation||null,nextPhase:'watch'};}}else if(!result.correct){setPhase(session,'watch');session.watchIndex=0;session.repair=null;return{accepted:true,correct:false,escalated:true,nextPhase:'watch'};}var lesson=Data.lesson(session.lessonId),returnPhase=session.repair.returnPhase;if(Router.isRemediationActive(session.skill)){var bank=returnPhase==='retrieval'?lesson.retrieval:lesson.independent;var exited=Router.exitRemediation(session.skill,bank);if(!exited.allowed)return{accepted:false,reason:exited.reason};var idx=findIndex(bank,exited.nextItem.id);if(returnPhase==='retrieval')session.retrievalIndex=idx;else session.independentIndex=idx;}else{var list=returnPhase==='retrieval'?lesson.retrieval:lesson.independent;var current=returnPhase==='retrieval'?session.retrievalIndex:session.independentIndex;var fresh=nextFreshIndex(list,current,[session.currentColdItemId]);if(fresh<0)return{accepted:false,reason:'bank_exhausted'};if(returnPhase==='retrieval')session.retrievalIndex=fresh;else session.independentIndex=fresh;}session.repair=null;session.currentColdContaminated=false;setPhase(session,returnPhase);return{accepted:true,correct:true,nextPhase:returnPhase,currentItem:currentItem(session)};}
  function submitExplanation(session,text,timestamp){if(session.phase!=='explain'||!session.firstColdItemId)return{accepted:false,reason:'wrong_phase'};var lesson=Data.lesson(session.lessonId),g=explanationGrade(lesson.explanation,text);var result=Router.recordIndependentExplanation(session.skill,session.firstColdItemId,g.correct,timestamp,text);log(session,'explanation',{itemId:session.firstColdItemId,correct:g.correct},timestamp);if(!g.correct){session.repair={active:true,errorCode:'EXPLANATION',teaching:'Your explanation must connect the electron-counting inputs to the conclusion, not only state the final answer.',check:lesson.concept[0],returnPhase:'independent'};return{accepted:true,correct:false,freshItemRequired:true,reason:g.reason,teaching:session.repair.teaching};}session.explainedItemId=session.firstColdItemId;setPhase(session,'transfer');session.transferIndex=0;return{accepted:true,correct:true,attached:result.attached,nextPhase:'transfer'};}
  function submitTransfer(session,answers,timestamp){if(session.phase!=='transfer')return{accepted:false,reason:'wrong_phase'};var lesson=Data.lesson(session.lessonId),item=currentItem(session),g=grade(item,answers);Router.recordAttempt(session.skill,item.id,g.correct,g.errorCode,timestamp,answers);if(!g.correct){session.transferIndex++;if(session.transferIndex>=lesson.transfer.length)session.transferIndex=0;return{accepted:true,correct:false,countedAsIndependent:false,errorCode:g.errorCode,teaching:lesson.reteach[g.errorCode]||'Repair the specific step, then use the fresh transfer.'};}session.transferPassed=true;setPhase(session,'activity');return{accepted:true,correct:true,countedAsIndependent:false,nextPhase:'activity'};}
  function submitActivity(session,answers,timestamp){if(session.phase!=='activity')return{accepted:false,reason:'wrong_phase'};var lesson=Data.lesson(session.lessonId),g=grade(lesson.intervening,answers);Router.recordAttempt(session.skill,lesson.intervening.id,g.correct,g.errorCode,timestamp,answers);if(!g.correct)return{accepted:true,correct:false,teaching:lesson.reteach[g.errorCode]||'Review this different chemistry skill and try again.'};session.activityComplete=true;session.activityAt=timestamp||Date.now();session.skill.reviewDue=(session.firstColdAt||Date.now())+Router.MIN_RETRIEVAL_DELAY_MS;setPhase(session,'retrieval-wait');return{accepted:true,correct:true,nextPhase:'retrieval-wait',reviewDue:session.skill.reviewDue};}
  function retrievalReadiness(session,timestamp){var now=timestamp||Date.now();if(!session.activityComplete)return{ready:false,reason:'intervening_activity_required',remainingMs:null};if(!session.firstColdAt)return{ready:false,reason:'no_anchor_success',remainingMs:null};var due=session.firstColdAt+Router.MIN_RETRIEVAL_DELAY_MS;if(now<due)return{ready:false,reason:'minimum_interval_not_elapsed',remainingMs:due-now,reviewDue:due};return{ready:true,reason:null,remainingMs:0,reviewDue:due};}
  function startRetrieval(session,timestamp){if(session.phase!=='retrieval-wait')return{accepted:false,reason:'wrong_phase'};var r=retrievalReadiness(session,timestamp);if(!r.ready)return{accepted:false,reason:r.reason,remainingMs:r.remainingMs};var lesson=Data.lesson(session.lessonId);var idx=lesson.retrieval.findIndex(function(x){return x.id!==session.firstColdItemId;});session.retrievalIndex=idx<0?0:idx;session.currentColdContaminated=false;setPhase(session,'retrieval');return{accepted:true,item:currentItem(session)};}
  function submitRetrieval(session,answers,timestamp){if(session.phase!=='retrieval')return{accepted:false,reason:'wrong_phase'};var lesson=Data.lesson(session.lessonId),item=currentItem(session),g=grade(item,answers);session.skill.scaffoldLevel=Router.SCAFFOLD.COLD;if(!g.correct){session.currentColdContaminated=true;var route=Router.handleWrongAttempt(session.skill,item.id,g.errorCode,item.id,timestamp,answers);var next=nextFreshIndex(lesson.retrieval,session.retrievalIndex,[item.id]);if(route.remediationActive){session.repair=repairFor(session,g.errorCode,'independent');return{accepted:true,correct:false,remediationActive:true,teaching:session.repair.teaching};}if(next>=0)session.retrievalIndex=next;return{accepted:true,correct:false,countedAsIndependent:false,freshItemRequired:true,errorCode:g.errorCode,teaching:lesson.reteach[g.errorCode]||'Repair the step and use the fresh retrieval item.'};}if(session.currentColdContaminated||Router.isRemediationActive(session.skill)){Router.recordAttempt(session.skill,item.id,true,null,timestamp,answers);return{accepted:true,correct:true,countedAsIndependent:false,freshItemRequired:true};}Router.recordIndependentAttempt(session.skill,item.id,true,false,timestamp,answers);var mastery=Router.evaluateMastery(session.skill);session.mastered=!!mastery.mastered;if(session.mastered)setPhase(session,'complete');return{accepted:true,correct:true,countedAsIndependent:true,mastery:mastery,nextPhase:session.phase};}
  return Object.freeze({grade:grade,explanationGrade:explanationGrade,createSession:createSession,currentItem:currentItem,advanceWatch:advanceWatch,submitSupported:submitSupported,submitIndependent:submitIndependent,requestColdHelp:requestColdHelp,submitRepair:submitRepair,submitExplanation:submitExplanation,submitTransfer:submitTransfer,submitActivity:submitActivity,retrievalReadiness:retrievalReadiness,startRetrieval:startRetrieval,submitRetrieval:submitRetrieval,setPhase:setPhase,Router:Router});
});