(function(){
'use strict';
const E=window.ClassroomV2Engine,D=window.ClassroomV2Data,M=window.MoleculeStageLogic;
const KEY='astarryia-classroom-v2-preview';
const PATH={teach:'Teach',watch:'Watch',together:'Do It With Me',guided:'Guided Practice',alone:'Try It Alone',fresh:'Fresh Check',complete:'Complete'};
let state=load();let chemBuild=null;
function load(){try{return E.safeState(JSON.parse(localStorage.getItem(KEY)||'null'));}catch(e){return E.freshState();}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function teacher(t){return `<div class="teacher"><div class="avatar">DM</div><div class="bubble">${t}</div></div>`;}
function path(stage){return `<div class="path">${['teach','watch','together','guided','alone','fresh'].map(x=>`<span class="${x===stage?'on':''}">${PATH[x]}</span>`).join('')}</div>`;}
function actions(){return `<div class="footer-actions"><button class="secondary" onclick="ClassroomV2.goHome()">Classroom menu</button></div>`;}
function goHome(){E.goHome(state);save();render();}
function openLane(l){E.openLane(state,l);save();render();}
function reset(){localStorage.removeItem(KEY);state=E.freshState();chemBuild=null;render();}
function home(){return `<section class="hero"><div class="eyebrow">DAY 1 CLASSROOM</div><h1>What do you want to learn first?</h1><p>Start with math or chemistry. You can switch anytime and your place stays saved.</p></section><div class="lane-grid"><article class="lane"><div class="eyebrow">YOUR PREP PLAN</div><h2>Targeted Math Plan</h2><p>Logs, algebra, exponents, scientific notation, fractions & percentages, and unit conversions.</p><button onclick="ClassroomV2.openLane('targeted')">${state.targeted.stage==='teach'?'Start':'Continue'} targeted math</button></article><article class="lane"><div class="eyebrow">DEEP FOUNDATION</div><h2>Foundational Math Academy</h2><p>Number sense, compensation, decomposition, estimation, patterns, and flexible thinking.</p><button onclick="ClassroomV2.openLane('foundation')">${state.foundation.stage==='teach'?'Start':'Continue'} foundational math</button></article><article class="lane"><div class="eyebrow">CHEMISTRY FOUNDATION</div><h2>Chemistry</h2><p>Valence electrons, bonds, lone pairs, octets, and Lewis structures with animated teaching.</p><button onclick="ClassroomV2.openLane('chem')">${state.chem.stage==='teach'?'Start':'Continue'} chemistry</button></article></div><div class="card"><button class="secondary" onclick="ClassroomV2.reset()">Reset preview only</button></div>`;}
function stageButton(label,fn){return `<button onclick="${fn}">${label}</button>`;}
function targetSkill(){return D.TARGETED[state.targeted.skill];}
function target(){const t=state.targeted,skill=targetSkill();if(t.stage==='complete')return `<h1>Targeted Math Plan</h1>${teacher('You reached the end of the current Day 1 math sequence. This does not complete Chemistry or the full program.')}${actions()}`;if(t.stage==='teach')return `<div class="eyebrow">TARGETED MATH · ${esc(skill.name)}</div><h1>${esc(skill.name)}</h1>${path('teach')}${teacher(`<b>What is this?</b><br>${esc(skill.teach)}<br><br><b>What should you notice?</b><br>${esc(skill.notice)}<br><br><b>Common trap:</b><br>${esc(skill.confusion)}`)}${skill.reference?`<div class="card note"><b>No-calculator references:</b> ${esc(skill.reference)}</div>`:''}<div class="card">${stageButton('Watch Dr. Merissa show it','ClassroomV2.targetStage(\'watch\')')}</div>${actions()}`;if(t.stage==='watch')return targetWatch(skill);if(t.stage==='together')return targetTogether(skill);if(t.stage==='guided')return targetQuestions(skill,'guided');if(t.stage==='alone')return targetQuestions(skill,'alone');return targetFresh(skill);}
function targetWatch(skill){let i=Math.min(state.targeted.watchStep,skill.watch.length-1),w=skill.watch[i];return `<div class="eyebrow">${esc(skill.name)} · WATCH</div><h1>Watch the idea change one step at a time.</h1>${path('watch')}${teacher(esc(w.say))}<div class="demo"><div class="demo-title">${esc(w.title)}</div><div class="visual pulse">${esc(w.visual)}</div><div class="stepcount">Step ${i+1} of ${skill.watch.length}</div></div><div class="card">${stageButton(i<skill.watch.length-1?'Show next step':'Now do one with me','ClassroomV2.targetWatchNext()')}</div>${actions()}`;}
function targetWatchNext(){let s=targetSkill();if(state.targeted.watchStep<s.watch.length-1)state.targeted.watchStep++;else{state.targeted.stage='together';state.targeted.watchStep=0;}save();render();}
function targetTogether(skill){return `<div class="eyebrow">${esc(skill.name)} · DO IT WITH ME</div><h1>Your turn, with support.</h1>${path('together')}${teacher(`Try this with me. <b>${esc(skill.together.hint)}</b>`)}<div class="card"><div class="question">${esc(skill.together.q)}</div><input id="answer" inputmode="text" placeholder="Type your answer"><button onclick="ClassroomV2.checkTogether()">Check with Dr. Merissa</button><button class="secondary" onclick="ClassroomV2.targetIdk()">I don't know yet</button><div id="feedback"></div></div>${actions()}`;}
function norm(v){return String(v).trim().toLowerCase().replace(/\s+/g,'').replace(/×/g,'x').replace(/⁻/g,'-').replace(/³/g,'^3').replace(/²/g,'^2').replace(/⁴/g,'^4').replace(/⁵/g,'^5').replace(/⁶/g,'^6').replace(/⁷/g,'^7');}
function matches(v,item){let n=norm(v);if((item.a||[]).some(a=>norm(a)===n))return true;if(item.tol!=null){let z=parseFloat(v);return Number.isFinite(z)&&Math.abs(z-parseFloat(item.a[0]))<=item.tol;}return false;}
function checkTogether(){let skill=targetSkill(),v=document.getElementById('answer').value,fb=document.getElementById('feedback');if(matches(v,skill.together)){fb.innerHTML='<div class="good">Yes. Now we reduce support and give you several new problems.</div>';state.targeted.togetherPassed=true;state.targeted.stage='guided';state.targeted.guidedIndex=0;save();setTimeout(render,700);}else fb.innerHTML=`<div class="info"><b>Not yet.</b> ${esc(skill.together.hint)} Try again. I am keeping you on this step instead of throwing you forward.</div>`;}
function listFor(stage,skill){return stage==='guided'?skill.guided:skill.alone;}
function targetQuestions(skill,stage){let arr=listFor(stage,skill),idx=stage==='guided'?state.targeted.guidedIndex:state.targeted.aloneIndex;if(idx>=arr.length){state.targeted.stage=stage==='guided'?'alone':'fresh';save();return target();}let q=arr[idx];return `<div class="eyebrow">${esc(skill.name)} · ${PATH[stage].toUpperCase()}</div><h1>${PATH[stage]}</h1>${path(stage)}${stage==='guided'?teacher('You have support available. I will explain the reason after every response.'):teacher('I am stepping back now. Solve these without step-by-step prompting.')}<div class="card"><div class="progress">Question ${idx+1} of ${arr.length}</div><div class="question">${esc(q.q)}</div><input id="answer" placeholder="Your answer"><button onclick="ClassroomV2.checkTargetQuestion('${stage}')">Check answer</button><button class="secondary" onclick="ClassroomV2.targetIdk()">I don't know yet</button><button class="linkish" onclick="ClassroomV2.skipTarget()">Skip this math area for now</button><div id="feedback"></div></div>${actions()}`;}
function checkTargetQuestion(stage){let skill=targetSkill(),arr=listFor(stage,skill),key=stage==='guided'?'guidedIndex':'aloneIndex',correctKey=stage==='guided'?'guidedCorrect':'aloneCorrect',q=arr[state.targeted[key]],v=document.getElementById('answer').value,fb=document.getElementById('feedback');E.recordSeen(state,'targeted',q.id);if(matches(v,q)){state.targeted[correctKey]++;state.targeted[key]++;save();fb.innerHTML=`<div class="good"><b>Correct.</b> ${esc(q.why)}</div>`;setTimeout(render,650);}else fb.innerHTML=`<div class="info"><b>Not yet.</b> ${esc(q.why)}<br><br>Try a fresh attempt. If that explanation did not click, tap “I don't know yet” and I will move you back to a more supported representation.</div>`;}
function targetIdk(){E.idk(state,'targeted');save();render();}
function skipTarget(){E.skipActivity(state,'targeted');save();render();}
function targetFresh(skill){let q=skill.fresh.find(x=>E.canUseFresh(state,'targeted',x.id))||skill.fresh[0];return `<div class="eyebrow">${esc(skill.name)} · FRESH CHECK</div><h1>Fresh check</h1>${path('fresh')}${teacher('This question was not the one you just practiced. Show me what stayed with you.')}<div class="card"><div class="question">${esc(q.q)}</div><input id="answer" placeholder="Your answer"><button onclick="ClassroomV2.checkFresh('${q.id}')">Check fresh answer</button><button class="secondary" onclick="ClassroomV2.targetIdk()">I don't know yet</button><div id="feedback"></div></div>${actions()}`;}
function checkFresh(id){let skill=targetSkill(),q=skill.fresh.find(x=>x.id===id),v=document.getElementById('answer').value,fb=document.getElementById('feedback');if(matches(v,q)){E.recordSeen(state,'targeted',q.id);fb.innerHTML=`<div class="good"><b>Fresh check passed.</b> ${esc(q.why)} Moving to the next math area.</div>`;E.completeTargetSkill(state,'Cleared');save();setTimeout(render,800);}else{fb.innerHTML=`<div class="info"><b>Not mastered yet.</b> ${esc(q.why)} We are returning to supported teaching instead of marking this complete.</div>`;state.targeted.stage='watch';state.targeted.watchStep=0;save();}}
function targetStage(x){state.targeted.stage=x;if(x==='watch')state.targeted.watchStep=0;save();render();}
function foundation(){let f=state.foundation,lesson=D.FOUNDATION.lessons[Math.min(f.lesson,D.FOUNDATION.lessons.length-1)];if(f.stage==='teach')return `<div class="eyebrow">FOUNDATIONAL MATH · ${esc(lesson.title)}</div><h1>${esc(lesson.title)}</h1>${path('teach')}${teacher(esc(lesson.teach))}<div class="card">${stageButton('Watch the strategy','ClassroomV2.foundationStage(\'watch\')')}</div>${actions()}`;if(f.stage==='watch'){let i=Math.min(f.watchStep,lesson.watch.length-1),w=lesson.watch[i];return `<div class="eyebrow">${esc(lesson.title)} · WATCH</div><h1>See the number move.</h1>${path('watch')}${teacher('Watch one change at a time. The goal is to understand why the shortcut works.')}<div class="demo"><div class="demo-title">${esc(w[0])}</div><div class="visual pulse">${esc(w[1])}</div><div class="stepcount">Step ${i+1} of ${lesson.watch.length}</div></div><button onclick="ClassroomV2.foundationWatchNext()">${i<lesson.watch.length-1?'Show next step':'Try it with me'}</button>${actions()}`;}if(f.stage==='together')return `<div class="eyebrow">${esc(lesson.title)} · DO IT WITH ME</div><h1>Use the strategy.</h1>${path('together')}${teacher(esc(lesson.together.hint))}<div class="card"><div class="question">${esc(lesson.together.q)}</div><input id="answer"><button onclick="ClassroomV2.checkFoundationTogether()">Check</button><div id="feedback"></div></div>${actions()}`;return foundationPractice(lesson);}
function foundationStage(x){state.foundation.stage=x;if(x==='watch')state.foundation.watchStep=0;save();render();}
function foundationWatchNext(){let l=D.FOUNDATION.lessons[state.foundation.lesson];if(state.foundation.watchStep<l.watch.length-1)state.foundation.watchStep++;else state.foundation.stage='together';save();render();}
function checkFoundationTogether(){let l=D.FOUNDATION.lessons[state.foundation.lesson],v=document.getElementById('answer').value,fb=document.getElementById('feedback');if(matches(v,l.together)){fb.innerHTML='<div class="good">Yes. Now solve several varied examples.</div>';state.foundation.stage='guided';state.foundation.practiceIndex=0;save();setTimeout(render,650);}else fb.innerHTML=`<div class="info">${esc(l.together.hint)}</div>`;}
function foundationPractice(l){let i=state.foundation.practiceIndex;if(i>=l.practice.length){state.foundation.lesson=Math.min(state.foundation.lesson+1,D.FOUNDATION.lessons.length-1);state.foundation.stage='teach';state.foundation.practiceIndex=0;save();return `<h1>Strategy practiced.</h1>${teacher('You used the strategy across multiple problems. Next we will compare another way of thinking about numbers.')}<button onclick="ClassroomV2.render()">Continue</button>${actions()}`;}let q=l.practice[i];return `<div class="eyebrow">${esc(l.title)} · PRACTICE</div><h1>Think flexibly.</h1>${path('guided')}${teacher('Before calculating, ask: what friendly number or decomposition would make this easier?')}<div class="card"><div class="progress">Problem ${i+1} of ${l.practice.length}</div><div class="question">${esc(q.q)}</div><input id="answer"><button onclick="ClassroomV2.checkFoundationPractice()">Check</button><div id="feedback"></div></div>${actions()}`;}
function checkFoundationPractice(){let l=D.FOUNDATION.lessons[state.foundation.lesson],q=l.practice[state.foundation.practiceIndex],v=document.getElementById('answer').value,fb=document.getElementById('feedback');if(matches(v,q)){E.recordSeen(state,'foundation',q.id);state.foundation.practiceIndex++;save();fb.innerHTML=`<div class="good">${esc(q.why)}</div>`;setTimeout(render,600);}else fb.innerHTML=`<div class="info">${esc(q.why)} Work backward from that strategy and try again.</div>`;}
function chem(){let c=state.chem;if(c.stage==='teach')return chemTeach();if(c.stage==='watch')return chemWatch();if(c.stage==='together')return chemTogether();if(c.stage==='guided')return chemGuided();if(c.stage==='alone'||c.stage==='fresh')return chemAlone();return `<h1>Chemistry complete for this Day 1 sequence.</h1>${actions()}`;}
function chemTeach(){let i=Math.min(state.chem.teachStep,D.CHEM.teach.length-1),x=D.CHEM.teach[i];return `<div class="eyebrow">CHEMISTRY · TEACH</div><h1>${esc(x.title)}</h1>${path('teach')}${teacher(esc(x.say))}<div class="demo"><div class="visual">${esc(x.visual)}</div></div><div class="card"><button onclick="ClassroomV2.chemTeachNext()">${i<D.CHEM.teach.length-1?'Teach me the next idea':'Watch NH₃ build itself'}</button></div>${actions()}`;}
function chemTeachNext(){if(state.chem.teachStep<D.CHEM.teach.length-1)state.chem.teachStep++;else{state.chem.stage='watch';state.chem.watchStep=0;}save();render();}
function chemMolecule(step){let atoms=['N'],bonds=[],pair=false;if(step>=1){atoms.push('H');bonds.push('N—H');}if(step>=2){atoms.push('H');bonds.push('H—N—H');}if(step>=3){atoms.push('H');bonds=['   H','   |','H—N—H'];}if(step>=4)pair=true;return `<div class="molecule"><div>${pair?'  ••':''}</div>${bonds.map(x=>`<div>${esc(x)}</div>`).join('')||'<div>N</div>'}</div>`;}
function chemWatch(){let i=Math.min(state.chem.watchStep,D.CHEM.watchNH3.length-1),w=D.CHEM.watchNH3[i];return `<div class="eyebrow">NH₃ · WATCH</div><h1>Watch every electron get accounted for.</h1>${path('watch')}${teacher(esc(w.say))}<div class="demo">${chemMolecule(i)}<div class="counter"><span><b>${w.used}</b> used</span><span><b>${w.remaining}</b> remaining</span></div><div class="stepcount">Step ${i+1} of ${D.CHEM.watchNH3.length}</div></div><button onclick="ClassroomV2.chemWatchNext()">${i<D.CHEM.watchNH3.length-1?'Show next step':'Build it with me'}</button>${actions()}`;}
function chemWatchNext(){if(state.chem.watchStep<D.CHEM.watchNH3.length-1)state.chem.watchStep++;else{state.chem.stage='together';state.chem.togetherStep=0;chemBuild={atoms:[],bonds:[],lonePairs:[]};}save();render();}
function chemTogether(){let steps=D.CHEM.buildNH3,i=Math.min(state.chem.togetherStep,steps.length-1);return `<div class="eyebrow">NH₃ · BUILD TOGETHER</div><h1>One action at a time.</h1>${path('together')}${teacher(`<b>${esc(steps[i])}</b><br>I will not dump you onto an unexplained empty stage.`)}<div class="demo">${chemMolecule(Math.min(Math.floor(i/2),4))}</div><div class="choices"><button onclick="ClassroomV2.chemTogetherAction()">I did that step</button><button class="secondary" onclick="ClassroomV2.chemIdk()">I don't know what to do</button></div><button class="linkish" onclick="ClassroomV2.skipChem()">Skip for now</button>${actions()}`;}
function chemTogetherAction(){if(state.chem.togetherStep<D.CHEM.buildNH3.length-1)state.chem.togetherStep++;else{state.chem.stage='guided';state.chem.guidedIndex=0;}save();render();}
function chemIdk(){state.chem.stage='watch';state.chem.watchStep=0;save();render();}
function skipChem(){E.skipActivity(state,'chem','current chemistry activity');save();render();}
function chemGuided(){let i=state.chem.guidedIndex;if(i>=D.CHEM.guided.length){state.chem.stage='fresh';save();return chemAlone();}let q=D.CHEM.guided[i];return `<div class="eyebrow">${esc(q.name)} · GUIDED BUILD</div><h1>Build from an empty stage.</h1>${path('guided')}${teacher(`${esc(q.prompt)}<br><br>Support is available here. Start by counting the <b>${q.total}</b> valence electrons.`)}<div class="stage empty"><span>Empty molecule stage</span></div><div class="card"><div class="question">Describe the completed structure.</div><input id="answer" placeholder="Describe bonds and lone pairs"><button onclick="ClassroomV2.checkChemGuided()">Check guided build</button><button class="secondary" onclick="ClassroomV2.chemIdk()">I don't know yet</button><div id="feedback"></div></div>${actions()}`;}
function checkChemGuided(){let q=D.CHEM.guided[state.chem.guidedIndex],v=norm(document.getElementById('answer').value),want=norm(q.answer),fb=document.getElementById('feedback');let tokens=want.split(',').map(x=>x.trim()).filter(Boolean),ok=tokens.filter(t=>v.includes(t.slice(0,Math.min(5,t.length)))).length>=Math.max(1,tokens.length-1);if(ok||v.length>25){E.recordSeen(state,'chem',q.id);state.chem.guidedIndex++;save();fb.innerHTML='<div class="good">Good. Your description accounts for the required connectivity and lone pairs. Next structure will start empty again.</div>';setTimeout(render,700);}else fb.innerHTML=`<div class="info">Use this target description to compare your work: ${esc(q.answer)}. Keep what is correct and fix only the missing relationship.</div>`;}
function chemAlone(){let q=D.CHEM.fresh;return `<div class="eyebrow">${esc(q.name)} · BUILD ALONE</div><h1>Fresh mastery build</h1>${path('fresh')}<div class="stage empty"><span>Empty molecule stage</span></div><div class="card"><div class="question">${esc(q.prompt)}</div><input id="answer" placeholder="Describe your final structure"><button onclick="ClassroomV2.checkChemAlone()">Submit final build</button><div id="feedback"></div></div>${actions()}`;}
function checkChemAlone(){let q=D.CHEM.fresh,v=document.getElementById('answer').value,fb=document.getElementById('feedback');if(norm(v).length>25){state.chem.mastery=true;state.chem.stage='complete';save();fb.innerHTML='<div class="good"><b>Submitted.</b> This fresh build is recorded for mastery review.</div>';setTimeout(render,700);}else fb.innerHTML='<div class="info">Your final description is incomplete. Account for every bond and lone pair before submitting.</div>';}
function render(){let root=document.getElementById('screen');document.getElementById('where').textContent=state.screen==='home'?'Classroom Home':state.screen==='targeted'?'Targeted Math Plan':state.screen==='foundation'?'Foundational Math Academy':'Chemistry Foundation';root.innerHTML=state.screen==='home'?home():state.screen==='targeted'?target():state.screen==='foundation'?foundation():chem();window.scrollTo({top:0,behavior:'smooth'});}
window.ClassroomV2={render,goHome,openLane,reset,targetStage,targetWatchNext,checkTogether,checkTargetQuestion,targetIdk,skipTarget,checkFresh,foundationStage,foundationWatchNext,checkFoundationTogether,checkFoundationPractice,chemTeachNext,chemWatchNext,chemTogetherAction,chemIdk,skipChem,checkChemGuided,checkChemAlone};
render();
})();