(function(root){
'use strict';
var VD=root.Chapter5VisualData;
if(!VD)throw new Error('Chapter 5 visual data missing');
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function box(title,body,cls){return '<figure class="stereo-visual '+(cls||'')+'"><figcaption>'+e(title)+'</figcaption>'+body+'</figure>';}
function arrowLabel(text,kind){return '<span class="bond-chip '+(kind||'')+'">'+e(text)+'</span>';}
function rs(v){var toward=v.expected.priority4Direction==='toward';return box(v.title,'<div class="rs-stage"><div class="rs-center">C*</div><div class="rs-groups"><span class="g g1">1</span><span class="g g2">2</span><span class="g g3">3</span><span class="g g4 '+(toward?'toward':'away')+'">4<br><small>'+(toward?'toward':'away')+'</small></span></div><div class="turn '+e(v.expected.path)+'">1 → 2 → 3<br><b>'+e(v.expected.path)+'</b></div></div><div class="visual-note">Priority 4 is '+e(v.expected.priority4Direction)+'. '+(v.expected.invert?'Reverse the apparent turn before naming the configuration.':'Read the turn directly.')+'</div>','rs-visual');}
function cip(v){return box(v.title,'<div class="priority-row">'+v.groups.slice().sort(function(a,b){return a.priority-b.priority;}).map(function(g){return '<div class="priority-card"><b>'+g.priority+'</b><span>'+e(g.label)+'</span><small>direct atom '+e(g.directAtom)+'</small></div>';}).join('')+'</div><div class="visual-note">Higher atomic number wins at the first point of difference.</div>','priority-visual');}
function wedge(v){return box(v.title,'<div class="wedge-stage"><div class="center-dot">C*</div><div class="wg top">'+e(v.groups[0].label)+'<small>solid wedge · toward</small></div><div class="wg bottom">'+e(v.groups[1].label)+'<small>dashed wedge · away</small></div><div class="wg left">'+e(v.groups[2].label)+'</div><div class="wg right">'+e(v.groups[3].label)+'</div><span class="wedge-line wl1"></span><span class="dash-line wl2"></span><span class="plain-line wl3"></span><span class="plain-line wl4"></span></div><div class="visual-note">Trace four complete substituent paths from the same tetrahedral carbon.</div>','wedge-visual');}
function connect(v){return box(v.title,'<div class="compare-grid"><div><b>'+e(v.left.name)+'</b><div class="connect-list">'+v.left.connectivity.map(arrowLabel).join('')+'</div></div><div class="versus">vs</div><div><b>'+e(v.right.name)+'</b><div class="connect-list">'+v.right.connectivity.map(arrowLabel).join('')+'</div></div></div><div class="visual-note">Number the atoms, then compare who is bonded to whom before judging the drawing shape.</div>','connect-visual');}
function relationship(v){return box(v.title,'<div class="config-pair"><div>'+v.left.config.map(function(x,i){return '<span>C'+(i+1)+' <b>'+e(x)+'</b></span>';}).join('')+'</div><div class="versus">vs</div><div>'+v.right.config.map(function(x,i){return '<span class="'+(v.expected.changedCenters.indexOf(i+1)>=0?'changed':'')+'">C'+(i+1)+' <b>'+e(x)+'</b></span>';}).join('')+'</div></div><div class="visual-note">Compare every corresponding stereocenter. Highlighted centers changed.</div>','relationship-visual');}
function meso(v){return box(v.title,'<div class="meso-stage"><div class="meso-half">stereocenter A</div><div class="symmetry-line"><span>internal symmetry</span></div><div class="meso-half">stereocenter B</div></div><div class="visual-note">Stereocenters are local. Chirality is decided by the whole molecule and whether the mirror image superimposes.</div>','meso-visual');}
function fischer(v){return box(v.title,'<div class="fischer-stage"><span class="ftop">'+e(v.top)+'</span><span class="fbottom">'+e(v.bottom)+'</span><span class="fleft">'+e(v.left)+'</span><span class="fright">'+e(v.right)+'</span><span class="fh"></span><span class="fv"></span><span class="fcenter"></span></div><div class="direction-key"><b>Horizontal:</b> toward you &nbsp; <b>Vertical:</b> away from you</div>','fischer-visual');}
function ez(v){return box(v.title,'<div class="alkene-stage"><div class="alkene-left"><span class="top '+(v.leftCarbon.top.priority==='high'?'high':'')+'">'+e(v.leftCarbon.top.label)+'</span><span class="bottom '+(v.leftCarbon.bottom.priority==='high'?'high':'')+'">'+e(v.leftCarbon.bottom.label)+'</span></div><div class="double-bond"><span></span><span></span></div><div class="alkene-right"><span class="top '+(v.rightCarbon.top.priority==='high'?'high':'')+'">'+e(v.rightCarbon.top.label)+'</span><span class="bottom '+(v.rightCarbon.bottom.priority==='high'?'high':'')+'">'+e(v.rightCarbon.bottom.label)+'</span></div></div><div class="visual-note">The outlined groups are the higher-priority group on each alkene carbon. Compare only those two after ranking.</div>','ez-visual');}
function generic(title,text){return box(title||'See the rule','<div class="concept-strip">'+e(text||'Use the chemical relationship, not the drawing appearance.')+'</div>','concept-visual');}
function renderVisual(v){if(!v)return'';if(v.kind==='rs-orientation')return rs(v);if(v.kind==='priority-sort')return cip(v);if(v.kind==='wedge-dash-center')return wedge(v);if(v.kind==='connectivity-compare')return connect(v);if(v.kind==='configuration-pair')return relationship(v);if(/symmetry/.test(v.kind))return meso(v);if(v.kind==='fischer-cross'||v.kind==='fischer-symmetry')return fischer(v);if(v.kind==='alkene-ez')return ez(v);return generic(v.title,v.framework||'Structured stereochemistry view');}
function item(item){if(!item||!item.visual)return'';return renderVisual(VD.get(item.visual));}
function watch(lessonId,index,lesson){var step=lesson&&lesson.watch&&lesson.watch[index];if(!step)return'';if(step.visual&&VD.get(step.visual))return renderVisual(VD.get(step.visual));
var maps={
'isomer-classification':['isomer-connectivity-compare-a',null],
'chirality-stereocenters':['stereocenter-wedge-a','stereocenter-wedge-a'],
'cip-rs':['cip-ranking-a','rs-visual-b-counterclockwise-4-toward'],
'stereoisomer-relationships':['relationship-pair-a','relationship-pair-a'],
'meso-symmetry':['meso-symmetry-plane-a','meso-symmetry-plane-a'],
'fischer-projections':['fischer-orientation-a','fischer-orientation-a'],
'ez-alkenes':['ez-guided-opposite','ez-guided-opposite'],
'optical-activity':[null,null]
};var id=maps[lessonId]&&maps[lessonId][index];return id&&VD.get(id)?renderVisual(VD.get(id)):generic(step.title,step.visual||step.text);}
function sketch(){return false;}
root.Chapter5Visuals=Object.freeze({item:item,watch:watch,renderVisual:renderVisual,sketch:sketch});
})(typeof globalThis!=='undefined'?globalThis:this);
