(function(){
'use strict';
var D=globalThis.Chapter5AdaptiveData,E=globalThis.Chapter5AdaptiveEngine,S=globalThis.Chapter5AdaptiveSupport,V=globalThis.Chapter5Visuals,R=globalThis.StudentModelIdkRouter;
if(!D||!E||!S||!V||!R)throw new Error('Chapter 5 learner dependencies missing');
var cards=document.querySelector('[data-c5-cards]'),host=document.querySelector('[data-c5-host]'),active=null,message='',showColdReasons=false;
var PH={probe:'Quick Diagnostic',watch:'Watch · I Do',concept:'Supported Concept Check',build:'Build Together · We Do',guided:'Guided Practice',independent:'Cold Independent',explain:'Explain Why',transfer:'Transfer',activity:'Different Chemistry Activity','retrieval-wait':'Later Retrieval',retrieval:'Later Retrieval · Cold',complete:'Mastered'};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function key(id){return'chm221.unit2.chapter5.'+id+'.v1';}
function save(){if(active)localStorage.setItem(key(active.lessonId),JSON.stringify(active));renderCards();}
function load(id){try{var raw=localStorage.getItem(key(id));return raw?JSON.parse(raw):null;}catch(_){return null;}}
function lesson(){return active?D.lesson(active.lessonId):null;}
function status(id){var s=load(id);if(!s)return'Not started';if(s.mastered||s.phase==='complete')return'Mastered';return'In progress';}
function renderCards(){var html=D.lessons().map(function(l){var st=status(l.id);return'<article class="skill-card '+(active&&active.lessonId===l.id?'selected':'')+'"><div class="eyebrow">Priority '+l.priority+' · '+esc(l.chapter)+'</div><span class="status '+st.toLowerCase().replace(/\s/g,'-')+'">'+esc(st)+'</span><h3>'+esc(l.title)+'</h3><p>'+esc(l.objective)+'</p><button type="button" data-open="'+esc(l.id)+'">'+(st==='Not started'?'Check this skill':'Continue')+'</button></article>';}).join('');cards.innerHTML=html;cards.querySelectorAll('[data-open]').forEach(function(b){b.addEventListener('click',function(){active=load(b.dataset.open)||E.createSession(b.dataset.open,Date.now());message='';showColdReasons=false;save();render();history.replaceState(null,'','?skill='+encodeURIComponent(active.lessonId));});});}
function answers(form){var out={};new FormData(form).forEach(function(v,k){out[k]=v;});return out;}
function fields(item,label,help){return'<form data-answer class="answer-form">'+item.fields.map(function(f){return'<label>'+esc(f.label)+'<input name="'+esc(f.id)+'" autocomplete="off" autocapitalize="off" spellcheck="false" inputmode="text"></label>';}).join('')+'<div class="actions"><button type="submit">'+esc(label||'Check')+'</button>'+(help?'<button type="button" class="ghost" data-help>I don’t know yet</button>':'')+'</div></form>';}
function feedback(){return message?'<div class="feedback" role="status">'+esc(message)+'</div>':'';}
function shell(inner){var l=lesson();return'<section class="lesson-shell"><div class="lesson-head"><div><div class="eyebrow">Unit 2 · Chapter 5 adaptive lesson</div><h2>'+esc(l.title)+'</h2><button type="button" class="tiny ghost" data-back-skills>← Chapter 5 skills</button></div><span class="phase-pill" id="phaseLabel">'+esc(PH[active.phase]||active.phase)+'</span></div>'+feedback()+inner+'</section>';}
function bindBack(){var b=host.querySelector('[data-back-skills]');if(b)b.addEventListener('click',function(){active=null;message='';showColdReasons=false;render();history.replaceState(null,'',location.pathname);});}
function bindForm(fn){var f=host.querySelector('[data-answer]');if(f)f.addEventListener('submit',function(ev){ev.preventDefault();fn(answers(f));});}
function reasonGrid(kind){return'<div class="reason-grid">'+S.REASONS.map(function(r){return'<button type="button" class="reason" data-reason="'+esc(r.id)+'" data-kind="'+kind+'">'+esc(r.label)+'</button>';}).join('')+'</div>';}
function issuePanel(){if(!active.supportedIssue)return'';return'<div class="diagnosis-card"><div class="eyebrow">First broken step found</div><h3>'+esc(S.label(active.supportedIssue.errorCode))+'</h3><p>I’m not going to repeat the same question. Tell me what kind of stuck this is so the repair matches the problem.</p>'+reasonGrid('supported')+'</div>';}
function coldPanel(){if(!showColdReasons)return'';return'<div class="diagnosis-card cold-choice"><div class="eyebrow">Before support opens</div><h3>Which one is closest?</h3><p>Once you choose help, this item becomes supported and cannot count as cold mastery evidence.</p>'+reasonGrid('cold')+'<button type="button" class="ghost tiny" data-cancel-help>Never mind, keep this item cold</button></div>';}
function bindReasons(){host.querySelectorAll('[data-reason]').forEach(function(b){b.addEventListener('click',function(){var reason=b.dataset.reason;if(b.dataset.kind==='cold'){showColdReasons=false;var r=E.requestColdHelp(active,reason,Date.now());message='This item is now supported. We are repairing '+(r.label||'the broken step')+' before a fresh cold item.';}else{E.requestSupportedHelp(active,reason,Date.now());message='';}save();render();});});var c=host.querySelector('[data-cancel-help]');if(c)c.addEventListener('click',function(){showColdReasons=false;message='No help opened. This item is still cold.';render();});}
function phaseBanner(){if(active.phase==='probe')return'<div class="probe-banner"><b>Quick diagnostic, not mastery.</b><br>Two clean answers can fast-track a strong skill. A miss tells the lesson what to teach.</div>';if(active.phase==='concept')return'<div class="supported-banner"><b>Supported Concept Check</b><br>This is teaching practice, not cold evidence.</div>';if(active.phase==='build')return'<div class="build-banner"><b>Build Together · We Do</b><br>One stereochemistry decision at a time.</div>';if(active.phase==='guided')return'<div class="guided-banner"><b>Guided Practice</b><br>You do the reasoning. Support appears only where it breaks.</div>';if(active.phase==='transfer')return'<div class="transfer-banner"><b>Transfer</b><br>Same rule in a different-looking structure.</div>';return'';}
function supportedHelp(){var h=host.querySelector('[data-help]');if(h)h.addEventListener('click',function(){E.askSupportedHelp(active);message='Tell me what kind of stuck this is so the lesson can switch the right part.';save();render();});}
function visualFor(item){return V.item(item);}
function renderProbe(){var item=E.currentItem(active);host.innerHTML=shell(phaseBanner()+visualFor(item)+'<div class="progress">Diagnostic '+(active.probeIndex+1)+' of '+lesson().probe.length+'</div><div class="prompt">'+esc(item.prompt)+'</div>'+fields(item,'Check diagnostic',true)+issuePanel());bindBack();bindForm(function(a){var r=E.submitProbe(active,a,Date.now());message=r.correct?(r.testedOutOfTeaching?'You proved both entry checks. Moving to fresh cold confirmation.':'Good. One more diagnostic check.'):'That answer exposed the '+S.label(r.errorCode)+' step. We can teach that instead of making you guess again.';save();render();});supportedHelp();bindReasons();}
function renderWatch(){var step=lesson().watch[active.watchIndex];host.innerHTML=shell('<div class="teacher"><div class="avatar">DM</div><div><b>Dr. Merissa</b><p>'+esc(step.text)+'</p></div></div>'+V.watch(active.lessonId,active.watchIndex,lesson())+'<div class="watch-check"><div class="eyebrow">Use the explanation</div><div class="prompt">'+esc(step.check.prompt)+'</div>'+fields(step.check,'Check prediction',true)+'</div>'+issuePanel());bindBack();bindForm(function(a){var r=E.submitWatchCheck(active,a,Date.now());message=r.correct?'Yes. That follows from the stereochemistry rule.':'The reasoning broke at '+S.label(r.errorCode)+'. We will repair that part, not repeat the question.';save();render();});supportedHelp();bindReasons();}
function renderSupported(){var item=E.currentItem(active);host.innerHTML=shell(phaseBanner()+visualFor(item)+'<div class="prompt">'+esc(item.prompt)+'</div>'+fields(item,active.phase==='build'?'Check this build step':'Check',true)+issuePanel());bindBack();bindForm(function(a){var before=active.phase,r=E.submitSupported(active,a,Date.now());message=r.correct?(before==='build'?'That build decision is solid. Next step.':'That step is solid. Moving forward.'):'I found the first broken step: '+S.label(r.errorCode)+'. Choose what is getting in your way and we will repair only that.';save();render();});supportedHelp();bindReasons();}
function renderRepair(){var rp=active.repair,check=rp.check;host.innerHTML=shell('<div class="repair-card"><div class="eyebrow">Targeted repair · '+esc(rp.label||S.label(rp.errorCode))+'</div><h3>Different representation first. Then a smaller check.</h3><div class="teacher"><div class="avatar">DM</div><div><b>Dr. Merissa</b><p>'+esc(rp.teaching)+'</p></div></div>'+visualFor(check)+(rp.foundationHref?'<a class="foundation-link" href="'+esc(rp.foundationHref)+'">Open the full prerequisite lesson</a>':'')+'<div class="repair-check"><b>Prove the smaller idea before we return.</b><div class="prompt">'+esc(check.prompt)+'</div>'+fields(check,'Check repair',false)+'</div></div>');bindBack();bindForm(function(a){var r=rp.cold?E.submitColdRepair(active,a,Date.now()):E.submitSupportedRepair(active,a,Date.now());if(r.correct)message='Repair passed. You return on a fresh or changed problem.';else if(r.representationSwitched)message='Still shaky, so the explanation changed representation instead of repeating itself.';else if(r.escalated)message='This needs a fuller re-teach. We stepped back to Watch.';else message='That smaller idea is not stable yet.';save();render();});}
function renderIndependent(){if(active.repair&&active.repair.active)return renderRepair();var item=E.currentItem(active),st=E.policy(active);host.innerHTML=shell('<div class="cold-banner"><b>Cold evidence</b><br>No notes or hints if you want this item to count. Asking for help contaminates this item and requires a fresh one.</div><div class="evidence">Clean cold items: '+st.cleanCount+'/'+st.minClean+(st.requiredTags.length?' · Coverage: '+esc(st.requiredTags.join(', ')):'')+'</div>'+visualFor(item)+'<div class="prompt">'+esc(item.prompt)+'</div>'+fields(item,'Check cold answer',true)+coldPanel());bindBack();bindForm(function(a){var r=E.submitIndependent(active,a,Date.now());if(r.correct)message=r.sufficientEvidence?'Cold evidence is sufficient. Now explain why.':'Correct cold item. More independent coverage is still needed.';else message='That miss is diagnostic. This item is contaminated, so we repair the exact step and then use a fresh item.';showColdReasons=false;save();render();});var help=host.querySelector('[data-help]');if(help)help.addEventListener('click',function(){showColdReasons=true;message='Choose the closest reason. Support will not open until you choose.';render();});bindReasons();}
function renderExplain(){host.innerHTML=shell('<div class="cold-banner"><b>Your reasoning is evidence.</b><br>Explain the chemical relationship, not just the final R/S, E/Z, or isomer label.</div><div class="prompt">'+esc(lesson().explanation.prompt)+'</div><form data-explain><textarea name="x" rows="6" required></textarea><div class="actions"><button type="submit">Check explanation</button></div></form>');bindBack();host.querySelector('[data-explain]').addEventListener('submit',function(ev){ev.preventDefault();var r=E.submitExplanation(active,new FormData(ev.currentTarget).get('x'),Date.now());message=r.correct?'Explanation attached. Now prove the skill transfers.':'The explanation does not yet prove the relationship. We will repair the missing reasoning and return to fresh cold evidence.';save();render();});}
function renderActivity(){var item=E.currentItem(active);host.innerHTML=shell('<div class="activity-banner"><b>Switch chemistry on purpose.</b><br>This creates meaningful spacing. It does not add mastery evidence for '+esc(lesson().title)+'.</div>'+visualFor(item)+'<div class="prompt">'+esc(item.prompt)+'</div>'+fields(item,'Check activity',false));bindBack();bindForm(function(a){var r=E.submitActivity(active,a,Date.now());message=r.correct?'Different chemistry activity complete. Retrieval still waits for the shared minimum interval.':r.teaching;save();render();});}
function waitText(ms){var sec=Math.ceil(ms/1000);return sec<60?sec+' seconds':Math.ceil(sec/60)+' minutes';}
function renderWait(){var r=E.retrievalReadiness(active,Date.now());host.innerHTML=shell('<div class="retrieval-card"><h3>Later means later.</h3><p>Both conditions are required: a different chemistry activity and the shared minimum retrieval interval.</p><p><b>Different chemistry:</b> '+(active.activityComplete?'complete':'not complete')+'</p><p><b>Interval:</b> '+(r.ready?'ready':r.remainingMs!=null?waitText(r.remainingMs)+' remaining':'not ready')+'</p><button type="button" id="ready">'+(r.ready?'Start later retrieval':'Check readiness')+'</button></div>');bindBack();host.querySelector('#ready').addEventListener('click',function(){var x=E.startRetrieval(active,Date.now());message=x.accepted?'Retrieval unlocked. Answer from memory.':'Not ready yet: '+waitText(x.remainingMs||0)+' remaining.';save();render();});}
function renderRetrieval(){if(active.repair&&active.repair.active)return renderRepair();var item=E.currentItem(active);host.innerHTML=shell('<div class="cold-banner"><b>Later cold retrieval</b><br>This is delayed evidence. Help contaminates this retrieval item.</div>'+visualFor(item)+'<div class="prompt">'+esc(item.prompt)+'</div>'+fields(item,'Check retrieval',true)+coldPanel());bindBack();bindForm(function(a){var r=E.submitRetrieval(active,a,Date.now());if(r.mastery&&r.mastery.mastered)message='Mastery confirmed by the shared Student Model.';else if(r.correct)message='Correct retrieval recorded, but mastery is not yet valid.';else message='Retrieval found a gap. We repair it, then rebuild fresh independent evidence.';showColdReasons=false;save();render();});var help=host.querySelector('[data-help]');if(help)help.addEventListener('click',function(){showColdReasons=true;message='Choose what broke. Help will make this retrieval item supported.';render();});bindReasons();}
function renderComplete(){host.innerHTML=shell('<div class="complete"><div class="checkmark">✓</div><h2>Skill mastered</h2><p>The shared Student Model found valid explained cold evidence and a different delayed cold success after meaningful intervening chemistry.</p><button type="button" id="back">Back to Chapter 5 skills</button></div>');bindBack();host.querySelector('#back').addEventListener('click',function(){active=null;message='';render();});}
function overview(){host.innerHTML='<section class="overview"><div class="eyebrow">Chapter 5 · Stereoisomerism</div><h2>Learn the 3D rules by skill, not by memorizing pictures.</h2><p>Every skill begins with a two-item check. Strong material can move quickly. A miss opens teaching at the exact broken step, then returns you to fresh independent proof.</p><div class="flow">Diagnostic → Watch → Build Together → Guided → Cold → Explain Why → Transfer → Different Chemistry → Later Retrieval</div><p class="small"><b>Important:</b> spatial drawings on this page support reasoning. The site does not pretend to grade arbitrary handwritten structures.</p></section>';}
function render(){renderCards();if(!active){overview();return;}if(active.repair&&active.repair.active)return renderRepair();if(active.phase==='probe')renderProbe();else if(active.phase==='watch')renderWatch();else if(['concept','build','guided','transfer'].indexOf(active.phase)!==-1)renderSupported();else if(active.phase==='independent')renderIndependent();else if(active.phase==='explain')renderExplain();else if(active.phase==='activity')renderActivity();else if(active.phase==='retrieval-wait')renderWait();else if(active.phase==='retrieval')renderRetrieval();else if(active.phase==='complete')renderComplete();else overview();}
var requested=new URLSearchParams(location.search).get('skill');if(requested&&D.lesson(requested))active=load(requested)||E.createSession(requested,Date.now());render();
})();
