(function(){
'use strict';
var teachSteps=[
 {say:'Before I give this a name, watch what the exponent is doing.',eq:'10¹ = 10',sub:'The exponent tells how many factors of ten are used.',anim:'pulse'},
 {say:'Now ten squared gives one hundred.',eq:'10² = 100',sub:'2 is the exponent.',anim:'pulse'},
 {say:'And ten cubed gives one thousand.',eq:'10³ = 1000',sub:'3 is the exponent.',anim:'pulse'},
 {say:'Now I am going to ask the same relationship backward.',eq:'log₁₀(1000) = 3',sub:'A logarithm asks: 10 to what power gives this number?',anim:'reverse'},
 {say:'Your turn. Ten to what power gives one thousand?',ask:{id:'teach_inverse',type:'numeric',prompt:'10 to what power gives 1000?',value:3},eq:'10 ? = 1000',sub:'Do not calculate. Read the exponent relationship.'},
 {say:'Good. Now watch what happens when the number is a product.',eq:'1000 = 10 × 100',sub:'We are going to connect multiplication to powers of ten.',anim:'line'},
 {say:'One thousand can also be written as ten times one hundred. Watch the log split that product.',eq:'log(10 × 100) → log(10) + log(100)',sub:'10 contributes one power. 100 contributes two powers.',anim:'split'},
 {say:'One plus two equals three. That is why the powers add.',eq:'1 + 2 = 3',sub:'The rule has a reason before it has a name.',anim:'pulse'},
 {say:'That pattern is called the product rule. Log of a product becomes the sum of the logs.',eq:'log(ab) = log(a) + log(b)',sub:'Product rule',anim:'line'},
 {say:'Check the rule before we use it.',ask:{id:'teach_product',type:'choice',prompt:'Which matches log(2 × 5)?',choices:['log(2) × log(5)','log(2) + log(5)','log(7)'],value:'log(2) + log(5)'},eq:'log(2 × 5) = ?',sub:'Use the rule you just watched.'},
 {say:'Now we can build log six. You are not supposed to magically know point seven eight.',eq:'6 = 2 × 3',sub:'Break 6 into useful factors.',anim:'split'},
 {say:'Use the product rule.',eq:'log(6) = log(2) + log(3)',sub:'This is built, not memorized.',anim:'line',toolbox:true},
 {say:'Use the tiny landmark set: log two is about point three zero and log three is about point four eight.',eq:'0.30 + 0.48',sub:'Landmarks are tools. You do not memorize log 1 through 29.',anim:'pulse',toolbox:true},
 {say:'Add them and you get about point seven eight.',eq:'log(6) ≈ 0.78',sub:'Now 0.78 has a reason.',anim:'pulse',toolbox:true},
 {say:'Now show me you can build another one with me.',ask:{id:'teach_log15',type:'numericTolerance',prompt:'Using log(3)≈0.48 and log(5)≈0.70, estimate log(15).',value:1.18,tolerance:.03},eq:'log(15) = log(3 × 5) = ?',sub:'This is still teaching practice, not mastery.',toolbox:true},
 {say:'Good. The lesson is not finished yet. Now let us make sure you can use the idea in more than one way.',eq:'Learning ✓  →  Practicing Together',sub:'One correct answer never completes this skill.',anim:'line'}
];
var practice=[
 {id:'g1',phase:'guided',form:'inverse',prompt:'What is log₁₀(100)?',type:'numeric',value:2,eq:'log₁₀(100) = ?',sub:'Think backward: 10 to what power gives 100?',support:'guided',toolbox:false},
 {id:'g2',phase:'guided',form:'product-rule',prompt:'Which expression equals log(3 × 5)?',type:'choice',choices:['log(3)+log(5)','log(3)×log(5)','log(8)'],value:'log(3)+log(5)',eq:'log(3 × 5) = ?',sub:'Name the relationship before calculating.',support:'guided',toolbox:true},
 {id:'i1',phase:'independent',form:'landmark-build',prompt:'Estimate log(10) from what you know.',type:'numericTolerance',value:1,tolerance:.001,eq:'log(10) = ?',sub:'Your turn. No answer is shown first.',support:'none',toolbox:false},
 {id:'i2',phase:'independent',form:'landmark-build',prompt:'Using the landmarks, estimate log(15).',type:'numericTolerance',value:1.18,tolerance:.03,eq:'log(15) = ?',sub:'Build 15 from useful factors.',support:'none',toolbox:false},
 {id:'i3',phase:'independent',form:'scientific-notation',prompt:'Estimate -log(3 × 10⁻⁵).',type:'numericTolerance',value:4.52,tolerance:.05,eq:'-log(3 × 10⁻⁵) = ?',sub:'Separate the coefficient and power of ten.',support:'none',toolbox:false},
 {id:'m1',phase:'mastery',form:'error-analysis',prompt:'A student says log(6)=log(2)×log(3). Which rule did they misuse?',type:'choice',choices:['Product rule','Power rule','No rule was misused'],value:'Product rule',eq:'log(6) = log(2) × log(3)  ? ',sub:'Fresh Check: explain the reasoning, not just the decimal.',support:'none',toolbox:false,isTransfer:true},
 {id:'m2',phase:'mastery',form:'scientific-notation',prompt:'Estimate -log(2 × 10⁻⁴).',type:'numericTolerance',value:3.70,tolerance:.05,eq:'-log(2 × 10⁻⁴) = ?',sub:'Fresh Check: no automatic toolbox.',support:'none',toolbox:false,isTransfer:true}
];
var i=-1,practiceIndex=-1,mode='teaching',paused=false,rate=1,currentUtterance=null;
var evidence=[],wrongCounts={},lastItem=null;
var $=function(id){return document.getElementById(id)};
var eq=$('equation'),sub=$('subtext'),teacher=$('teacherText'),status=$('stepStatus'),ask=$('ask'),q=$('question'),choices=$('choiceAnswers'),input=$('answerInput'),submit=$('submitAnswer'),feedback=$('answerFeedback'),toolbox=$('toolbox');
function speak(text){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();currentUtterance=new SpeechSynthesisUtterance(text);currentUtterance.rate=rate;currentUtterance.pitch=1;currentUtterance.volume=1;window.speechSynthesis.speak(currentUtterance)}
function animate(kind){eq.className='equation';$('visualLine').classList.remove('on');void eq.offsetWidth;if(kind==='pulse')eq.classList.add('pulse');if(kind==='reverse')eq.classList.add('slideIn');if(kind==='split')eq.classList.add('split');if(kind==='line')$('visualLine').classList.add('on')}
function phaseName(p){return p==='guided'?'Practicing Together':p==='independent'?'Your Turn':p==='mastery'?'Fresh Check':'Learning'}
function showTeach(){var s=teachSteps[i];status.textContent='Learning • Step '+(i+1)+' of '+teachSteps.length;eq.innerHTML=s.eq;sub.textContent=s.sub||'';teacher.textContent=s.say||'';toolbox.style.display=s.toolbox?'block':'none';ask.style.display='none';feedback.textContent='';animate(s.anim);if(s.say)speak(s.say);if(s.ask)setTimeout(function(){openAsk(s.ask,true)},350);$('next').disabled=!!s.ask;$('replay').disabled=false;$('pause').disabled=false;$('slower').disabled=false;}
function startPractice(){mode='practice';practiceIndex=0;showPractice();}
function showPractice(){var a=practice[practiceIndex];lastItem=a;status.textContent=phaseName(a.phase)+' • '+(practiceIndex+1)+' of '+practice.length;eq.innerHTML=a.eq;sub.textContent=a.sub||'';teacher.textContent=a.phase==='guided'?'I will stay close for these first practice problems.':a.phase==='independent'?'Now I am stepping back. Show me what you can do.':'Fresh check. I need new independent evidence before I call this learned.';toolbox.style.display=a.toolbox?'block':'none';ask.style.display='block';feedback.textContent='';animate('line');openAsk(a,false);$('next').disabled=true;speak(teacher.textContent+' '+a.prompt)}
function openAsk(a,isTeaching){ask.style.display='block';q.textContent=a.prompt;choices.innerHTML='';input.classList.add('hidden');submit.classList.add('hidden');if(a.type==='choice'){a.choices.forEach(function(c){var b=document.createElement('button');b.className='choice';b.textContent=c;b.onclick=function(){check(c,a,isTeaching)};choices.appendChild(b)})}else{input.value='';input.classList.remove('hidden');submit.classList.remove('hidden');submit.onclick=function(){check(input.value,a,isTeaching)};input.focus()}if(!isTeaching){var idk=document.createElement('button');idk.className='secondary';idk.textContent="I don't know yet";idk.onclick=function(){diagnoseIdk(a)};choices.appendChild(idk)}}
function isCorrect(v,a){if(a.type==='numeric')return Math.abs(Number(v)-a.value)<1e-9;if(a.type==='numericTolerance')return Math.abs(Number(v)-a.value)<=a.tolerance;if(a.type==='choice')return v===a.value;return false}
function inferError(v,a){if(a.form==='product-rule')return 'rule-selection';if(a.form==='scientific-notation'&&Number(v)<0)return 'sign-error';if(a.form==='scientific-notation')return 'log-combination';if(a.form==='inverse')return 'log-meaning';if(a.form==='landmark-build')return 'landmark-or-decomposition';if(a.form==='error-analysis')return 'rule-concept';return 'unresolved'}
function check(v,a,isTeaching){var ok=isCorrect(v,a);if(isTeaching){if(ok){feedback.className='good';feedback.textContent='Yes. That idea is working.';speak('Yes. That idea is working.');$('next').disabled=false;ask.style.display='none'}else{feedback.className='wrong';feedback.textContent='Not yet. We stay on this exact idea and try another representation before moving on.';speak(feedback.textContent)}return}
 var err=ok?null:inferError(v,a);if(err)wrongCounts[err]=(wrongCounts[err]||0)+1;
 evidence.push({itemId:a.id,form:a.form,phase:a.phase,response:v,correct:ok,independent:a.support==='none',supportLevel:a.support,errorType:err,isTransfer:!!a.isTransfer,toolboxUsed:toolbox.style.display==='block'});
 if(ok){feedback.className='good';feedback.textContent='Yes. I am recording that as '+(a.support==='none'?'independent':'supported')+' evidence.';speak(feedback.textContent);setTimeout(advancePractice,600)}else{repair(a,err)} }
function repair(a,err){feedback.className='wrong';var msg='I am not sending you back to the beginning. ';if(err==='sign-error')msg+='Your sign tells me the outside negative may be the broken link. We will isolate that next.';else if(err==='rule-selection'||err==='rule-concept')msg+='This looks like a rule-choice problem. Watch multiplication turn into addition again.';else if(err==='log-meaning')msg+='This looks like the backward-power meaning of log. Go back to 10²=100, then reverse it.';else if(err==='landmark-or-decomposition')msg+='This may be the factor choice or landmark addition. Break the number into factors first.';else msg+='I need one smaller check to locate the broken step.';if((wrongCounts[err]||0)>=2)msg+=' You have missed this same reasoning step twice, so I am changing the representation instead of repeating the same explanation.';feedback.textContent=msg;speak(msg);toolbox.style.display='block';setTimeout(function(){openAsk(a,false)},500)}
function diagnoseIdk(a){evidence.push({itemId:a.id,form:a.form,phase:a.phase,response:'IDK',correct:false,independent:false,supportLevel:'diagnostic',errorType:'idk',isTransfer:!!a.isTransfer});feedback.className='wrong';feedback.textContent='That is useful information. I will not count this as mastery and I will not restart the lesson. Use the toolbox or replay, then we will try a fresh problem of the same idea.';toolbox.style.display='block';speak(feedback.textContent);setTimeout(advancePractice,900)}
function independentStats(){var good=evidence.filter(function(e){return e.correct&&e.independent});var forms={};good.forEach(function(e){forms[e.form]=1});var transfer=good.some(function(e){return e.isTransfer});return {correct:good.length,forms:Object.keys(forms).length,transfer:transfer}}
function masteryMet(){var s=independentStats();return s.correct>=3&&s.forms>=2&&s.transfer}
function advancePractice(){ask.style.display='none';if(practiceIndex<practice.length-1){practiceIndex++;showPractice();return}if(masteryMet()){completeLesson()}else{extendPractice()}}
function extendPractice(){var s=independentStats();status.textContent='Your Turn • more evidence needed';eq.innerHTML='Not finished yet';sub.textContent='You have '+s.correct+' independent correct across '+s.forms+' forms. We need at least 3 across 2 forms plus a fresh transfer.';teacher.textContent='Needing more teaching is not a failure. I am giving you another fresh problem, not recycling the same one.';speak(teacher.textContent);var extra={id:'extra_'+evidence.length,phase:'independent',form:'inverse',prompt:'What is log₁₀(10000)?',type:'numeric',value:4,eq:'log₁₀(10000) = ?',sub:'Fresh extra practice.',support:'none',toolbox:false};practice.push(extra);practiceIndex++;setTimeout(showPractice,800)}
function completeLesson(){status.textContent='Skill evidence complete';eq.innerHTML='Learned today ✓';sub.textContent='Multiple independent forms + fresh transfer passed. A later retrieval check is still needed.';teacher.textContent='Now I can say you demonstrated this today. I will still bring it back later to make sure it stuck.';toolbox.style.display='none';ask.style.display='none';speak(teacher.textContent);try{localStorage.setItem('astarryia-log-mastery-evidence-v1',JSON.stringify({evidence:evidence,retrievalDueDays:3,completedAt:new Date().toISOString()}))}catch(e){}}
$('start').onclick=function(){i=0;showTeach();this.disabled=true};$('next').onclick=function(){if(mode==='teaching'){if(i<teachSteps.length-1){i++;showTeach()}else{startPractice()}}};$('replay').onclick=function(){if(mode==='teaching'&&i>=0)showTeach();else if(mode==='practice')showPractice()};$('pause').onclick=function(){if(!('speechSynthesis'in window))return;if(!paused){window.speechSynthesis.pause();paused=true;this.textContent='Resume voice'}else{window.speechSynthesis.resume();paused=false;this.textContent='Pause voice'}};$('slower').onclick=function(){rate=rate===1?.75:1;this.textContent=rate<1?'Normal speed':'Slow down';if(mode==='teaching'&&i>=0){window.speechSynthesis.cancel();speak(teachSteps[i].say)}};$('toolboxBtn').onclick=function(){toolbox.style.display=toolbox.style.display==='block'?'none':'block'};
})();