(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Chapter3AdaptiveData=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
function f(id,label,accepted,errorCode){return Object.freeze({id:id,label:label,accepted:Object.freeze(accepted),errorCode:errorCode});}
function q(id,prompt,fields,tags,visual){return Object.freeze({id:id,prompt:prompt,fields:Object.freeze(fields),tags:Object.freeze(tags||[]),visual:visual||null});}
function w(title,text,visual,check){return Object.freeze({title:title,text:text,visual:visual||null,check:check||null});}
function freezeLesson(x){['probe','watch','concept','build','guided','independent','transfer','retrieval','requiredTags','prerequisites'].forEach(function(k){x[k]=Object.freeze(x[k]||[]);});x.repairChecks=Object.freeze(x.repairChecks||{});x.reteach=Object.freeze(x.reteach||{});return Object.freeze(x);}
var L={};

L['proton-transfer']=freezeLesson({id:'proton-transfer',skillId:'u2.c3.proton_transfer',title:'Proton Transfer and Conjugate Pairs',chapter:'Chapter 3',priority:1,prerequisites:['day4-acid-base'],requiredTags:['mechanism','conjugates'],objective:'Identify acid/base roles, draw a valid proton-transfer electron flow, and identify both conjugate partners.',
probe:[q('PT-P1','In a Bronsted acid-base reaction, which species donates H+?',[f('a','Role',['acid','bronsted acid'],'AB_ROLE')]),q('PT-P2','For B: + H-A -> B-H+ + A-, where must the first curved-arrow tail begin?',[f('a','Arrow source',['lone pair on b','base lone pair','b lone pair','lone pair'],'PT_ARROW_SOURCE')],['mechanism'])],
watch:[w('Follow electrons, not the proton by itself','The base supplies an electron pair to H. At the same time, the H-A bond electron pair returns to A. The acid loses H+ and becomes its conjugate base; the base gains H+ and becomes its conjugate acid.','base lone pair -> H; H-A bond -> A',q('PT-W1','Does the arrow from the base start at the base lone pair or at H?',[f('a','Start',['base lone pair','lone pair'],'PT_ARROW_SOURCE')])),w('Conjugates differ by one proton','An acid and its conjugate base differ by H+. A base and its conjugate acid also differ by H+. Keep charge bookkeeping with that proton change.','acid <-> conjugate base; base <-> conjugate acid',q('PT-W2','If NH3 gains H+, what conjugate acid forms?',[f('a','Conjugate acid',['nh4+','nh4','ammonium'],'CONJUGATE_PAIR')]))],
concept:[q('PT-C1','If HCl donates H+, is Cl- its conjugate acid or conjugate base?',[f('a','Partner',['conjugate base','base'],'CONJUGATE_PAIR')]),q('PT-C2','When the H-A bond breaks heterolytically in proton transfer, where does that electron pair go?',[f('a','Destination',['onto a','to a','acid atom','a atom'],'PT_BOND_BREAK')])],
build:[q('PT-B1','Build: NH3 reacts with H2O as a base. Which atom on NH3 supplies the electron pair?',[f('a','Atom',['nitrogen','n'],'PT_ARROW_SOURCE')]),q('PT-B2','What conjugate acid forms when NH3 gains H+?',[f('a','Product',['nh4+','nh4','ammonium'],'CONJUGATE_PAIR')])],
guided:[q('PT-G1','Guided: HO- + H-CN -> H2O + CN-. Which reactant is the base?',[f('a','Base',['ho-','oh-','hydroxide'],'AB_ROLE')],['mechanism']),q('PT-G2','Guided: in that reaction, what is the conjugate base of HCN?',[f('a','Conjugate base',['cn-','cyanide'],'CONJUGATE_PAIR')])],
independent:[q('PT-I1','Cold: acid donates or accepts H+?',[f('a','Action',['donates','donate'],'AB_ROLE')]),q('PT-I2','Cold: base curved-arrow tail starts at what?',[f('a','Source',['electron pair','lone pair','base lone pair'],'PT_ARROW_SOURCE')],['mechanism']),q('PT-I3','Cold: conjugate base of CH3CO2H?',[f('a','Conjugate base',['ch3co2-','acetate','ch3coo-'],'CONJUGATE_PAIR')]),q('PT-I4','Cold: conjugate acid of H2O?',[f('a','Conjugate acid',['h3o+','hydronium'],'CONJUGATE_PAIR')])],
explanation:{prompt:'Explain a proton-transfer mechanism using electron movement and identify how each conjugate pair differs.',requiredGroups:[['base','lone pair','electron'],['proton','h+'],['bond','electron'],['conjugate','one proton']]},transfer:[q('PT-T1','Transfer: RO- + H2O -> ROH + HO-. Which product is the conjugate acid of RO-?',[f('a','Product',['roh','alcohol'],'CONJUGATE_PAIR')])],intervening:q('PT-A1','Different skill: lower pKa means stronger or weaker acid?',[f('a','Strength',['stronger','stronger acid'],'PKA_ACID')]),retrieval:[q('PT-R1','Later: what starts the base-to-H curved arrow?',[f('a','Source',['lone pair','electron pair'],'PT_ARROW_SOURCE')]),q('PT-R2','Later: acid and conjugate base differ by what?',[f('a','Difference',['one proton','h+','a proton'],'CONJUGATE_PAIR')])],repairChecks:{AB_ROLE:q('PT-RP1','Repair check: does a Bronsted acid donate H+?',[f('a','Answer',['yes','y'],'AB_ROLE')]),PT_ARROW_SOURCE:q('PT-RP2','Repair check: does the curved-arrow tail start at electrons or at the proton?',[f('a','Start',['electrons','electron pair','lone pair'],'PT_ARROW_SOURCE')]),PT_BOND_BREAK:q('PT-RP3','Repair check: when H-A breaks, do the bond electrons stay with A?',[f('a','Answer',['yes','y'],'PT_BOND_BREAK')]),CONJUGATE_PAIR:q('PT-RP4','Repair check: do conjugate acid-base partners differ by exactly one proton?',[f('a','Answer',['yes','y'],'CONJUGATE_PAIR')])},reteach:{AB_ROLE:'Bronsted acid donates H+; Bronsted base accepts H+.',PT_ARROW_SOURCE:'The base supplies electrons. Start the curved arrow at a base lone pair and point it to H.',PT_BOND_BREAK:'As the base forms a bond to H, the old H-A bond electron pair returns to A.',CONJUGATE_PAIR:'Remove one H+ from an acid to get its conjugate base. Add one H+ to a base to get its conjugate acid.'}});

L['pka-acidity']=freezeLesson({id:'pka-acidity',skillId:'u2.c3.pka_acidity',title:'pKa and Acid Strength',chapter:'Chapter 3',priority:1,prerequisites:['proton-transfer'],requiredTags:['pka','acid-strength'],objective:'Use pKa correctly: lower pKa means stronger acid, and the difference reflects the favorability of deprotonation.',
probe:[q('PA-P1','Which is stronger acid: pKa 2 or pKa 8?',[f('a','Stronger acid',['pka 2','2','the acid with pka 2'],'PKA_ACID')],['pka']),q('PA-P2','If acid HA has a lower pKa than HB, which is more willing to donate H+?',[f('a','More willing',['ha','acid ha'],'PKA_ACID')])],
watch:[w('pKa runs opposite acid strength','Ka measures ionization; pKa = -log Ka. A larger Ka becomes a smaller pKa. Therefore lower pKa means stronger acid.','lower pKa -> stronger acid',q('PA-W1','pKa -2 vs pKa 5: which acid is stronger?',[f('a','Stronger',['pka -2','-2','the -2 acid'],'PKA_ACID')])),w('Compare the same type of quantity','Do not use pKa to rank bases directly unless you are comparing the pKa values of their conjugate acids. For acids themselves, lower pKa wins.','acid pKa comparison',q('PA-W2','For two acids, does the lower pKa correspond to the stronger acid?',[f('a','Answer',['yes','y'],'PKA_ACID')]))],
concept:[q('PA-C1','As acid strength increases, pKa generally goes up or down?',[f('a','Direction',['down','decreases','lower'],'PKA_ACID')]),q('PA-C2','pKa 16 acid vs pKa 25 acid: which is stronger?',[f('a','Stronger',['pka 16','16'],'PKA_ACID')])],
build:[q('PA-B1','Build: HA pKa 4, HB pKa 10. Which has the larger Ka?',[f('a','Larger Ka',['ha','pka 4 acid','acid ha'],'PKA_KA')]),q('PA-B2','Therefore which is stronger acid?',[f('a','Stronger acid',['ha','pka 4 acid'],'PKA_ACID')])],
guided:[q('PA-G1','Guided: phenol pKa about 10 and ethanol about 16. Which is stronger acid?',[f('a','Stronger',['phenol'],'PKA_ACID')],['pka']),q('PA-G2','Guided: acid A pKa -1, acid B pKa 3. Which gives H+ more readily?',[f('a','Acid',['a','acid a','pka -1 acid'],'PKA_ACID')])],
independent:[q('PA-I1','Cold: pKa 5 vs 12, stronger acid?',[f('a','Stronger',['pka 5','5'],'PKA_ACID')]),q('PA-I2','Cold: stronger acid has larger or smaller pKa?',[f('a','pKa',['smaller','lower'],'PKA_ACID')]),q('PA-I3','Cold: pKa 30 vs 18, which is more acidic?',[f('a','More acidic',['pka 18','18'],'PKA_ACID')]),q('PA-I4','Cold: if Ka increases, pKa increases or decreases?',[f('a','Direction',['decreases','down','lower'],'PKA_KA')])],
explanation:{prompt:'Explain why lower pKa means stronger acid, connecting Ka and the negative logarithm.',requiredGroups:[['ka'],['pka','log'],['lower','smaller'],['stronger','acid']]},transfer:[q('PA-T1','Transfer: compound X pKa 9 and Y pKa 11. Which should be deprotonated more readily by the same base?',[f('a','Compound',['x','compound x'],'PKA_ACID')])],intervening:q('PA-A1','Different skill: conjugate base of H2O?',[f('a','Base',['ho-','oh-','hydroxide'],'CONJUGATE_PAIR')]),retrieval:[q('PA-R1','Later: lower pKa means what acid strength?',[f('a','Strength',['stronger','stronger acid'],'PKA_ACID')]),q('PA-R2','Later: Ka and pKa move in same or opposite directions?',[f('a','Relationship',['opposite','opposite directions'],'PKA_KA')])],repairChecks:{PKA_ACID:q('PA-RP1','Repair check: between pKa 3 and pKa 9, is pKa 3 the stronger acid?',[f('a','Answer',['yes','y'],'PKA_ACID')]),PKA_KA:q('PA-RP2','Repair check: because pKa = -log Ka, does larger Ka give smaller pKa?',[f('a','Answer',['yes','y'],'PKA_KA')])},reteach:{PKA_ACID:'For acids, lower pKa means stronger acid. Put the pKa values on a number line if needed: farther left/lower is stronger.',PKA_KA:'pKa is the negative logarithm of Ka, so Ka and pKa run opposite directions.'}});

L['basicity-conjugate-acid']=freezeLesson({id:'basicity-conjugate-acid',skillId:'u2.c3.pka_basicity',title:'Basicity from Conjugate-Acid pKa',chapter:'Chapter 3',priority:1,prerequisites:['pka-acidity'],requiredTags:['base-strength','conjugate-acid'],objective:'Rank bases by comparing the pKa values of their conjugate acids without reversing the relationship.',
probe:[q('PB-P1','Base B1 has conjugate acid pKa 12. Base B2 has conjugate acid pKa 5. Which base is stronger?',[f('a','Stronger base',['b1','base b1'],'BASE_CONJUGATE_PKA')],['base-strength']),q('PB-P2','A stronger acid has a weaker or stronger conjugate base?',[f('a','Conjugate base',['weaker','weaker base'],'ACID_BASE_INVERSE')])],
watch:[w('Acid and conjugate-base strengths run opposite','If HA is very willing to lose H+, A- is relatively unwilling to take H+ back. Strong acid -> weak conjugate base. Weak acid -> stronger conjugate base.','strong acid <-> weak conjugate base',q('PB-W1','Does a very strong acid have a strong conjugate base?',[f('a','Answer',['no','n'],'ACID_BASE_INVERSE')])),w('Use conjugate-acid pKa to rank bases','For bases, compare the pKa of each conjugate acid. The base whose conjugate acid has the higher pKa is the stronger base.','higher conjugate-acid pKa -> stronger base',q('PB-W2','Conjugate-acid pKa 15 vs 7: which base is stronger?',[f('a','Base',['the pka 15 base','pka 15','15'],'BASE_CONJUGATE_PKA')]))],
concept:[q('PB-C1','Stronger base corresponds to stronger or weaker conjugate acid?',[f('a','Acid',['weaker','weaker acid'],'ACID_BASE_INVERSE')]),q('PB-C2','If B-H+ pKa is higher, B is generally stronger or weaker base?',[f('a','Base strength',['stronger','stronger base'],'BASE_CONJUGATE_PKA')])],
build:[q('PB-B1','Build: NH4+ pKa about 9.2, H3O+ pKa about -1.7. Which conjugate acid is weaker?',[f('a','Weaker acid',['nh4+','ammonium'],'BASE_CONJUGATE_PKA')]),q('PB-B2','Therefore which conjugate base is stronger, NH3 or H2O?',[f('a','Stronger base',['nh3','ammonia'],'BASE_CONJUGATE_PKA')])],
guided:[q('PB-G1','Guided: conjugate acid of base X pKa 20; conjugate acid of Y pKa 10. Stronger base?',[f('a','Base',['x','base x'],'BASE_CONJUGATE_PKA')]),q('PB-G2','Guided: if an acid becomes stronger, what happens to its conjugate base strength?',[f('a','Change',['weaker','decreases'],'ACID_BASE_INVERSE')])],
independent:[q('PB-I1','Cold: conjugate-acid pKa 30 vs 16. Stronger base?',[f('a','Base',['pka 30 base','30'],'BASE_CONJUGATE_PKA')]),q('PB-I2','Cold: strong acid -> weak conjugate base. Yes or no?',[f('a','Answer',['yes','y'],'ACID_BASE_INVERSE')]),q('PB-I3','Cold: base A conjugate acid pKa 4; base B conjugate acid pKa 11. Stronger base?',[f('a','Base',['b','base b'],'BASE_CONJUGATE_PKA')]),q('PB-I4','Cold: weaker acid usually has stronger or weaker conjugate base?',[f('a','Base',['stronger','stronger base'],'ACID_BASE_INVERSE')])],
explanation:{prompt:'Explain how to rank bases using conjugate-acid pKa and why acid strength and conjugate-base strength are inverse.',requiredGroups:[['conjugate acid'],['higher','pka'],['stronger','base'],['inverse','weaker acid']]},transfer:[q('PB-T1','Transfer: two negatively charged bases have conjugate acids pKa 4.8 and 15.7. Which anion is the stronger base?',[f('a','Base',['the pka 15.7 base','15.7','higher pka conjugate acid'],'BASE_CONJUGATE_PKA')])],intervening:q('PB-A1','Different skill: lower pKa means stronger acid. Yes or no?',[f('a','Answer',['yes','y'],'PKA_ACID')]),retrieval:[q('PB-R1','Later: higher conjugate-acid pKa means stronger or weaker base?',[f('a','Base',['stronger','stronger base'],'BASE_CONJUGATE_PKA')]),q('PB-R2','Later: strong acid has what kind of conjugate base?',[f('a','Base',['weak','weaker','weak base'],'ACID_BASE_INVERSE')])],repairChecks:{BASE_CONJUGATE_PKA:q('PB-RP1','Repair check: conjugate-acid pKa 12 vs 5. Is the pKa 12 partner the stronger base?',[f('a','Answer',['yes','y'],'BASE_CONJUGATE_PKA')]),ACID_BASE_INVERSE:q('PB-RP2','Repair check: if HA is stronger acid, is A- generally weaker base?',[f('a','Answer',['yes','y'],'ACID_BASE_INVERSE')])},reteach:{BASE_CONJUGATE_PKA:'For bases, compare conjugate-acid pKa. Higher conjugate-acid pKa means that conjugate acid is weaker, so its conjugate base is stronger.',ACID_BASE_INVERSE:'Acid strength and conjugate-base strength move opposite each other.'}});

L['equilibrium-pka']=freezeLesson({id:'equilibrium-pka',skillId:'u2.c3.equilibrium_pka',title:'Predict Acid-Base Equilibrium with pKa',chapter:'Chapter 3',priority:1,prerequisites:['pka-acidity','basicity-conjugate-acid'],requiredTags:['equilibrium','pka'],objective:'Predict acid-base equilibrium direction by identifying the acid on each side and favoring the side with the weaker acid/higher pKa.',
probe:[q('EQ-P1','An acid-base reaction has acid pKa 5 on the left and acid pKa 12 on the right. Which side is favored?',[f('a','Favored side',['right','products','product side'],'EQ_WEAKER_ACID')],['equilibrium']),q('EQ-P2','Acid-base equilibria generally favor the side containing the stronger or weaker acid?',[f('a','Acid',['weaker','weaker acid'],'EQ_WEAKER_ACID')])],
watch:[w('Compare acid to acid across the arrow','Identify the acid on each side, then compare their pKa values. Equilibrium favors the side with the weaker acid, which is the acid with the higher pKa.','acid left pKa vs acid right pKa',q('EQ-W1','Left acid pKa 3, right acid pKa 8. Favored side?',[f('a','Side',['right','products'],'EQ_WEAKER_ACID')])),w('The base result follows automatically','The favored side also contains the weaker base. Do not compare random pKa numbers from unrelated species. Compare each acid with the conjugate acid across the reaction.','weaker acid + weaker base favored',q('EQ-W2','Does equilibrium generally favor formation of the weaker acid/base pair?',[f('a','Answer',['yes','y'],'EQ_PAIR')]))],
concept:[q('EQ-C1','Which acid is weaker: pKa 4 or pKa 10?',[f('a','Weaker acid',['pka 10','10'],'EQ_WEAKER_ACID')]),q('EQ-C2','If the product acid has higher pKa than reactant acid, products are generally favored. Yes or no?',[f('a','Answer',['yes','y'],'EQ_DIRECTION')])],
build:[q('EQ-B1','Build: HA pKa 6 reacts with B- to form A- and HB pKa 16. Which acid is weaker?',[f('a','Weaker acid',['hb','product acid','pka 16 acid'],'EQ_WEAKER_ACID')]),q('EQ-B2','Which side is favored?',[f('a','Side',['products','right','product side'],'EQ_DIRECTION')])],
guided:[q('EQ-G1','Guided: left acid pKa 25, right acid pKa 10. Which side is favored?',[f('a','Side',['left','reactants','reactant side'],'EQ_DIRECTION')]),q('EQ-G2','Guided: if equilibrium strongly favors products, which side usually contains the weaker acid?',[f('a','Side',['products','product side','right'],'EQ_PAIR')])],
independent:[q('EQ-I1','Cold: left acid pKa 4, right acid pKa 9. Favored side?',[f('a','Side',['right','products'],'EQ_DIRECTION')]),q('EQ-I2','Cold: left acid pKa 18, right acid pKa 12. Favored side?',[f('a','Side',['left','reactants'],'EQ_DIRECTION')]),q('EQ-I3','Cold: equilibrium favors stronger or weaker acid?',[f('a','Acid',['weaker','weaker acid'],'EQ_WEAKER_ACID')]),q('EQ-I4','Cold: product acid has lower pKa than reactant acid. Are products generally favored?',[f('a','Answer',['no','n'],'EQ_DIRECTION')])],
explanation:{prompt:'Explain how to predict acid-base equilibrium direction using the acid on each side and pKa.',requiredGroups:[['acid','each side'],['pka'],['higher'],['weaker'],['equilibrium','favor']]},transfer:[q('EQ-T1','Transfer: deprotonation would form an acid of pKa 35 from an acid of pKa 20. Does the equilibrium favor the deprotonated products?',[f('a','Answer',['yes','y'],'EQ_DIRECTION')])],intervening:q('EQ-A1','Different skill: stronger base has conjugate acid with higher or lower pKa?',[f('a','pKa',['higher','higher pka'],'BASE_CONJUGATE_PKA')]),retrieval:[q('EQ-R1','Later: acid-base equilibrium favors the side with what kind of acid?',[f('a','Acid',['weaker','weaker acid'],'EQ_WEAKER_ACID')]),q('EQ-R2','Later: weaker acid has higher or lower pKa?',[f('a','pKa',['higher','higher pka'],'EQ_WEAKER_ACID')])],repairChecks:{EQ_WEAKER_ACID:q('EQ-RP1','Repair check: between pKa 5 and 11, is pKa 11 the weaker acid?',[f('a','Answer',['yes','y'],'EQ_WEAKER_ACID')]),EQ_DIRECTION:q('EQ-RP2','Repair check: if the weaker acid is on the product side, are products favored?',[f('a','Answer',['yes','y'],'EQ_DIRECTION')]),EQ_PAIR:q('EQ-RP3','Repair check: favored equilibrium side contains the weaker acid/base pair. Yes or no?',[f('a','Answer',['yes','y'],'EQ_PAIR')])},reteach:{EQ_WEAKER_ACID:'Identify one acid on each side. Higher pKa means weaker acid.',EQ_DIRECTION:'Equilibrium favors the side whose acid has the higher pKa.',EQ_PAIR:'The favored side contains the weaker acid and weaker base pair.'}});

L['stability-atom']=freezeLesson({id:'stability-atom',skillId:'u2.c3.stability_atom',title:'Conjugate-Base Stability: Atom',chapter:'Chapter 3',priority:1,prerequisites:['equilibrium-pka'],requiredTags:['atom','periodic-trend'],objective:'Use the identity of the charged atom to compare conjugate-base stability and therefore acid strength.',
probe:[q('AT-P1','Across a row, which better stabilizes negative charge: oxygen or carbon?',[f('a','Atom',['oxygen','o'],'ATOM_ELECTRONEGATIVITY')]),q('AT-P2','Down a group, which often stabilizes negative charge better: a larger more polarizable atom or a smaller atom?',[f('a','Atom',['larger','larger atom','more polarizable atom'],'ATOM_SIZE')])],
watch:[w('Across a row, electronegativity matters','For comparable atoms in the same period, a more electronegative atom better stabilizes negative charge. O- is more stable than C- all else equal.','across row -> electronegativity',q('AT-W1','Across C, N, O, which best stabilizes - charge?',[f('a','Atom',['oxygen','o'],'ATOM_ELECTRONEGATIVITY')])),w('Down a group, size and polarizability can dominate','A larger atom can spread negative charge over a larger volume. This helps explain why thiols can be more acidic than analogous alcohols despite sulfur being less electronegative than oxygen.','down group -> size/polarizability',q('AT-W2','Within the same group, can a larger atom stabilize negative charge better?',[f('a','Answer',['yes','y'],'ATOM_SIZE')]))],
concept:[q('AT-C1','Same period: N- vs O-. Which is more stable?',[f('a','Ion',['o-','oxygen','o'],'ATOM_ELECTRONEGATIVITY')]),q('AT-C2','Same group: larger anion can spread charge over greater volume. Yes or no?',[f('a','Answer',['yes','y'],'ATOM_SIZE')])],
build:[q('AT-B1','Build: compare CH3- and NH2-. Both are second-row atoms. Which charged atom is more electronegative?',[f('a','Atom',['nitrogen','n'],'ATOM_ELECTRONEGATIVITY')]),q('AT-B2','Therefore which anion is generally more stable?',[f('a','Anion',['nh2-','amide','nitrogen anion'],'ATOM_ELECTRONEGATIVITY')])],
guided:[q('AT-G1','Guided: compare HO- and HS-. Down the group, which atom is larger?',[f('a','Atom',['sulfur','s'],'ATOM_SIZE')]),q('AT-G2','Guided: that larger size can help HS- stabilize charge relative to HO-. Yes or no?',[f('a','Answer',['yes','y'],'ATOM_SIZE')])],
independent:[q('AT-I1','Cold: C- vs O- same row, more stable negative charge?',[f('a','Atom',['oxygen','o'],'ATOM_ELECTRONEGATIVITY')]),q('AT-I2','Cold: N- vs O- same row, more stable?',[f('a','Atom',['oxygen','o'],'ATOM_ELECTRONEGATIVITY')]),q('AT-I3','Cold: down a group, larger atoms generally spread negative charge more effectively. Yes or no?',[f('a','Answer',['yes','y'],'ATOM_SIZE')]),q('AT-I4','Cold: if conjugate base is more stable, parent acid is generally stronger or weaker?',[f('a','Acid',['stronger','stronger acid'],'STABILITY_ACID')])],
explanation:{prompt:'Explain how atom identity can stabilize a conjugate base across a row versus down a group, and connect that stability to acid strength.',requiredGroups:[['electronegative','row'],['size','polariz'],['stable','conjugate base'],['stronger','acid']]},transfer:[q('AT-T1','Transfer: all else equal, an acid whose conjugate base puts charge on O rather than C is usually stronger or weaker?',[f('a','Acid',['stronger','stronger acid'],'STABILITY_ACID')])],intervening:q('AT-A1','Different skill: resonance delocalization stabilizes or destabilizes a conjugate base?',[f('a','Effect',['stabilizes','stabilize'],'STABILITY_RESONANCE')]),retrieval:[q('AT-R1','Later: across a period, negative charge prefers more or less electronegative atom?',[f('a','Preference',['more electronegative','more'],'ATOM_ELECTRONEGATIVITY')]),q('AT-R2','Later: more stable conjugate base means stronger or weaker acid?',[f('a','Acid',['stronger','stronger acid'],'STABILITY_ACID')])],repairChecks:{ATOM_ELECTRONEGATIVITY:q('AT-RP1','Repair check: across C and O, does O better stabilize negative charge?',[f('a','Answer',['yes','y'],'ATOM_ELECTRONEGATIVITY')]),ATOM_SIZE:q('AT-RP2','Repair check: down a group, can larger size spread negative charge over more volume?',[f('a','Answer',['yes','y'],'ATOM_SIZE')]),STABILITY_ACID:q('AT-RP3','Repair check: more stable conjugate base corresponds to stronger acid?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])},reteach:{ATOM_ELECTRONEGATIVITY:'Across the same row, more electronegative atoms better stabilize negative charge.',ATOM_SIZE:'Down a group, larger atoms can spread charge over a larger, more polarizable electron cloud.',STABILITY_ACID:'Anything that stabilizes the conjugate base generally increases acidity of the parent acid.'}});

L['stability-resonance']=freezeLesson({id:'stability-resonance',skillId:'u2.c3.stability_resonance',title:'Conjugate-Base Stability: Resonance',chapter:'Chapter 3',priority:1,prerequisites:['stability-atom','chapter2-resonance'],requiredTags:['resonance','acidity'],objective:'Use resonance delocalization of the conjugate base to compare acid strength without confusing acid resonance with conjugate-base resonance.',
probe:[q('SR-P1','If conjugate base A- delocalizes negative charge over several atoms while B- localizes it on one atom, which is generally more stable?',[f('a','More stable',['a-','a','delocalized base'],'STABILITY_RESONANCE')]),q('SR-P2','More stable conjugate base generally means stronger acid. Yes or no?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])],
watch:[w('Compare conjugate bases, not just the acids','Deprotonate each candidate acid at the site being compared. Then ask whether the resulting negative charge can be delocalized through valid resonance contributors.','acid -> conjugate base -> resonance',q('SR-W1','Should resonance acidity comparison focus on the conjugate bases after deprotonation?',[f('a','Answer',['yes','y'],'RESONANCE_COMPARE_BASES')])),w('Delocalization spreads charge','When negative charge is shared over multiple valid contributor positions, the conjugate base is stabilized relative to a comparable localized anion.','delocalization -> stability -> acidity',q('SR-W2','Does charge delocalization generally stabilize an anion?',[f('a','Answer',['yes','y'],'STABILITY_RESONANCE')]))],
concept:[q('SR-C1','Phenoxide has resonance-delocalized negative charge; ethoxide largely does not. Which conjugate base is more resonance-stabilized?',[f('a','Base',['phenoxide'],'STABILITY_RESONANCE')]),q('SR-C2','If phenoxide is more stable, phenol should be stronger or weaker acid than ethanol?',[f('a','Acid',['stronger','stronger acid'],'STABILITY_ACID')])],
build:[q('SR-B1','Build: deprotonate a carboxylic acid. Can the carboxylate negative charge be shared between two oxygens?',[f('a','Answer',['yes','y'],'STABILITY_RESONANCE')]),q('SR-B2','Does that stabilization help make carboxylic acids more acidic than comparable alcohols?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])],
guided:[q('SR-G1','Guided: conjugate base X has three valid contributors; Y has one localized structure. Which is generally more stabilized by resonance?',[f('a','Base',['x','base x'],'STABILITY_RESONANCE')]),q('SR-G2','Guided: which parent acid is generally stronger?',[f('a','Acid',['acid x','x'],'STABILITY_ACID')])],
independent:[q('SR-I1','Cold: resonance delocalization stabilizes negative charge. Yes or no?',[f('a','Answer',['yes','y'],'STABILITY_RESONANCE')]),q('SR-I2','Cold: more stable conjugate base -> stronger acid. Yes or no?',[f('a','Answer',['yes','y'],'STABILITY_ACID')]),q('SR-I3','Cold: compare phenoxide and ethoxide. Which is more resonance stabilized?',[f('a','Base',['phenoxide'],'STABILITY_RESONANCE')]),q('SR-I4','Cold: should you compare resonance of the conjugate bases after removing the acidic proton?',[f('a','Answer',['yes','y'],'RESONANCE_COMPARE_BASES')])],
explanation:{prompt:'Explain how resonance in a conjugate base affects acidity. Describe the correct comparison workflow.',requiredGroups:[['deprotonate','conjugate base'],['resonance','delocal'],['stable'],['stronger','acid']]},transfer:[q('SR-T1','Transfer: acid A gives an anion delocalized over O and C; acid B gives a localized carbanion. All else equal, which acid is generally stronger?',[f('a','Acid',['a','acid a'],'STABILITY_ACID')])],intervening:q('SR-A1','Different skill: electron-withdrawing groups stabilize nearby negative charge by what effect?',[f('a','Effect',['induction','inductive effect'],'STABILITY_INDUCTION')]),retrieval:[q('SR-R1','Later: more resonance-delocalized conjugate base means stronger or weaker parent acid?',[f('a','Acid',['stronger','stronger acid'],'STABILITY_ACID')]),q('SR-R2','Later: compare resonance before or after deprotonating candidate acids?',[f('a','When',['after','after deprotonation'],'RESONANCE_COMPARE_BASES')])],repairChecks:{STABILITY_RESONANCE:q('SR-RP1','Repair check: does spreading negative charge over valid resonance positions stabilize an anion?',[f('a','Answer',['yes','y'],'STABILITY_RESONANCE')]),RESONANCE_COMPARE_BASES:q('SR-RP2','Repair check: should acidity resonance analysis compare the conjugate bases?',[f('a','Answer',['yes','y'],'RESONANCE_COMPARE_BASES')]),STABILITY_ACID:q('SR-RP3','Repair check: more stable conjugate base usually gives stronger acid?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])},reteach:{STABILITY_RESONANCE:'Resonance stabilizes an anion by delocalizing electron density instead of concentrating it on one atom.',RESONANCE_COMPARE_BASES:'For acidity, remove the candidate proton first, then compare the resulting conjugate bases.',STABILITY_ACID:'Stabilizing the product of deprotonation makes proton loss more favorable, so acidity increases.'}});

L['stability-induction']=freezeLesson({id:'stability-induction',skillId:'u2.c3.stability_induction',title:'Conjugate-Base Stability: Induction',chapter:'Chapter 3',priority:1,prerequisites:['stability-resonance'],requiredTags:['induction','distance'],objective:'Use electron-withdrawing inductive effects and distance to compare conjugate-base stability and acid strength.',
probe:[q('SI-P1','An electron-withdrawing F substituent near a negatively charged conjugate base generally stabilizes or destabilizes that negative charge?',[f('a','Effect',['stabilizes','stabilize'],'STABILITY_INDUCTION')]),q('SI-P2','Is an inductive effect generally stronger when the electron-withdrawing group is closer or farther from the charge?',[f('a','Distance',['closer','nearer'],'INDUCTION_DISTANCE')])],
watch:[w('Sigma bonds transmit inductive effects','Electronegative substituents withdraw electron density through sigma bonds. This can stabilize a nearby negative charge in the conjugate base.','EWG through sigma bonds',q('SI-W1','Does an electron-withdrawing group generally help stabilize nearby negative charge?',[f('a','Answer',['yes','y'],'STABILITY_INDUCTION')])),w('Induction fades with distance','The inductive effect decreases as more sigma bonds separate the electron-withdrawing group from the charged site.','closer effect > farther effect',q('SI-W2','Which usually has stronger induction: one bond away or four bonds away?',[f('a','Distance',['one bond away','closer','1 bond'],'INDUCTION_DISTANCE')]))],
concept:[q('SI-C1','CF3 is strongly electron-withdrawing. Would CF3 near a carboxylate generally stabilize or destabilize it?',[f('a','Effect',['stabilize','stabilizes'],'STABILITY_INDUCTION')]),q('SI-C2','Does inductive stabilization weaken with distance?',[f('a','Answer',['yes','y'],'INDUCTION_DISTANCE')])],
build:[q('SI-B1','Build: compare acid A with Cl next to the acidic group and acid B with Cl several carbons away. Which has stronger inductive stabilization after deprotonation?',[f('a','Acid',['a','acid a','closer chlorine acid'],'INDUCTION_DISTANCE')]),q('SI-B2','Therefore which is generally more acidic?',[f('a','Acid',['a','acid a'],'STABILITY_ACID')])],
guided:[q('SI-G1','Guided: multiple electron-withdrawing halogens near a conjugate-base charge usually increase or decrease stabilization?',[f('a','Change',['increase','increases','more'],'STABILITY_INDUCTION')]),q('SI-G2','Guided: moving the same EWG farther away usually strengthens or weakens its effect?',[f('a','Change',['weakens','weaker','decreases'],'INDUCTION_DISTANCE')])],
independent:[q('SI-I1','Cold: EWG near an anion stabilizes or destabilizes?',[f('a','Effect',['stabilizes','stabilize'],'STABILITY_INDUCTION')]),q('SI-I2','Cold: induction is stronger closer or farther away?',[f('a','Distance',['closer','nearer'],'INDUCTION_DISTANCE')]),q('SI-I3','Cold: stronger conjugate-base stabilization means stronger or weaker acid?',[f('a','Acid',['stronger','stronger acid'],'STABILITY_ACID')]),q('SI-I4','Cold: an electron-donating alkyl group generally stabilizes negative charge as strongly as a nearby F substituent?',[f('a','Answer',['no','n'],'STABILITY_INDUCTION')])],
explanation:{prompt:'Explain how induction affects acidity, including electron withdrawal through sigma bonds and the effect of distance.',requiredGroups:[['electron-withdraw'],['sigma'],['negative','stabil'],['distance','closer'],['acid']]},transfer:[q('SI-T1','Transfer: two similar acids differ only by CF3 being closer in A than B. Which is generally more acidic?',[f('a','Acid',['a','acid a'],'STABILITY_ACID')])],intervening:q('SI-A1','Different skill: which hybridized carbanion is most stabilized by s character: sp, sp2, or sp3?',[f('a','Hybridization',['sp'],'STABILITY_ORBITAL')]),retrieval:[q('SI-R1','Later: inductive withdrawal through sigma bonds stabilizes nearby negative charge. Yes or no?',[f('a','Answer',['yes','y'],'STABILITY_INDUCTION')]),q('SI-R2','Later: inductive effect gets stronger or weaker with distance?',[f('a','Effect',['weaker','decreases','weaker with distance'],'INDUCTION_DISTANCE')])],repairChecks:{STABILITY_INDUCTION:q('SI-RP1','Repair check: does an electron-withdrawing group pull electron density away and help stabilize nearby negative charge?',[f('a','Answer',['yes','y'],'STABILITY_INDUCTION')]),INDUCTION_DISTANCE:q('SI-RP2','Repair check: is induction generally strongest close to the charged site?',[f('a','Answer',['yes','y'],'INDUCTION_DISTANCE')]),STABILITY_ACID:q('SI-RP3','Repair check: stabilizing the conjugate base generally strengthens the acid?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])},reteach:{STABILITY_INDUCTION:'Electron-withdrawing groups pull electron density through sigma bonds and can stabilize a nearby anion.',INDUCTION_DISTANCE:'Inductive effects fade with distance through the sigma-bond framework.',STABILITY_ACID:'A more stabilized conjugate base corresponds to a stronger parent acid.'}});

L['stability-orbitals']=freezeLesson({id:'stability-orbitals',skillId:'u2.c3.stability_orbitals',title:'Conjugate-Base Stability: Orbitals',chapter:'Chapter 3',priority:1,prerequisites:['stability-induction'],requiredTags:['hybridization','s-character'],objective:'Use orbital hybridization and s character to compare carbanion stability and C-H acidity.',
probe:[q('SO-P1','Which orbital has more s character: sp or sp3?',[f('a','Orbital',['sp'],'STABILITY_ORBITAL')]),q('SO-P2','For comparable carbanions, which is generally more stable: sp or sp3?',[f('a','Carbanion',['sp','sp carbanion'],'STABILITY_ORBITAL')])],
watch:[w('More s character holds electrons closer to the nucleus','An sp orbital has 50% s character, sp2 about 33%, and sp3 25%. More s character keeps electron density closer to the positively charged nucleus and stabilizes negative charge.','sp > sp2 > sp3 for carbanion stability',q('SO-W1','Which has most s character: sp, sp2, or sp3?',[f('a','Hybridization',['sp'],'STABILITY_ORBITAL')])),w('That changes C-H acidity','If deprotonation places negative charge in an orbital with more s character, the conjugate base is more stable. Therefore terminal alkynes are more acidic than comparable alkenes and alkanes.','more s -> stable base -> stronger C-H acid',q('SO-W2','Which is more acidic: terminal alkyne C-H or alkane C-H?',[f('a','More acidic',['terminal alkyne','alkyne'],'ORBITAL_ACIDITY')]))],
concept:[q('SO-C1','Order s character highest to lowest: sp, sp2, sp3.',[f('a','Order',['sp > sp2 > sp3','sp sp2 sp3','sp, sp2, sp3'],'STABILITY_ORBITAL')]),q('SO-C2','More s character generally stabilizes a carbanion. Yes or no?',[f('a','Answer',['yes','y'],'STABILITY_ORBITAL')])],
build:[q('SO-B1','Build: deprotonating a terminal alkyne gives an sp carbanion. Deprotonating an alkane gives sp3 carbanion. Which is more stable?',[f('a','Carbanion',['sp','alkynyl','terminal alkyne conjugate base'],'STABILITY_ORBITAL')]),q('SO-B2','Therefore which parent C-H bond is more acidic?',[f('a','Acid',['terminal alkyne','alkyne'],'ORBITAL_ACIDITY')])],
guided:[q('SO-G1','Guided: sp2 carbanion vs sp3 carbanion, which is generally more stable?',[f('a','Carbanion',['sp2','sp2 carbanion'],'STABILITY_ORBITAL')]),q('SO-G2','Guided: alkene C-H vs alkane C-H, which is generally more acidic on this factor alone?',[f('a','Acid',['alkene','sp2 c-h','alkene c-h'],'ORBITAL_ACIDITY')])],
independent:[q('SO-I1','Cold: highest s character?',[f('a','Hybridization',['sp'],'STABILITY_ORBITAL')]),q('SO-I2','Cold: carbanion stability from s character: sp or sp3?',[f('a','Answer',['sp'],'STABILITY_ORBITAL')]),q('SO-I3','Cold: terminal alkyne vs alkane, more acidic?',[f('a','Acid',['terminal alkyne','alkyne'],'ORBITAL_ACIDITY')]),q('SO-I4','Cold: more stable conjugate base gives stronger acid. Yes or no?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])],
explanation:{prompt:'Explain why increasing s character stabilizes a carbanion and how that changes C-H acidity across sp, sp2, and sp3 centers.',requiredGroups:[['s character'],['closer','nucleus'],['sp','sp2','sp3'],['stable','carbanion'],['acid']]},transfer:[q('SO-T1','Transfer: all else equal, which C-H is more acidic, sp2 or sp3?',[f('a','C-H',['sp2','sp2 c-h'],'ORBITAL_ACIDITY')])],intervening:q('SO-A1','Different skill: electron-withdrawing induction is strongest close or far from the charge?',[f('a','Distance',['close','closer'],'INDUCTION_DISTANCE')]),retrieval:[q('SO-R1','Later: orbital stability order for carbanions by s character?',[f('a','Order',['sp > sp2 > sp3','sp sp2 sp3'],'STABILITY_ORBITAL')]),q('SO-R2','Later: terminal alkyne C-H is more acidic than comparable alkane C-H. Yes or no?',[f('a','Answer',['yes','y'],'ORBITAL_ACIDITY')])],repairChecks:{STABILITY_ORBITAL:q('SO-RP1','Repair check: does sp have more s character than sp3?',[f('a','Answer',['yes','y'],'STABILITY_ORBITAL')]),ORBITAL_ACIDITY:q('SO-RP2','Repair check: if the sp conjugate base is more stable, is terminal alkyne C-H more acidic?',[f('a','Answer',['yes','y'],'ORBITAL_ACIDITY')]),STABILITY_ACID:q('SO-RP3','Repair check: more stable conjugate base means stronger acid?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])},reteach:{STABILITY_ORBITAL:'sp has the greatest s character, then sp2, then sp3. More s character holds negative charge closer to the nucleus and stabilizes it.',ORBITAL_ACIDITY:'A terminal alkyne forms an sp carbanion after deprotonation, so its C-H bond is more acidic than comparable sp2 or sp3 C-H bonds.',STABILITY_ACID:'Conjugate-base stabilization increases parent-acid strength.'}});

L['combined-stability']=freezeLesson({id:'combined-stability',skillId:'u2.c3.stability_all',title:'Combine Atom, Resonance, Induction, and Orbital Effects',chapter:'Chapter 3',priority:1,prerequisites:['stability-atom','stability-resonance','stability-induction','stability-orbitals'],requiredTags:['multi-factor','ranking'],objective:'Compare acids by generating conjugate bases and applying atom, resonance, induction, and orbital stabilization without blindly counting factors.',
probe:[q('CS-P1','When comparing acid strength structurally, should you compare the acids only, or first generate the conjugate bases?',[f('a','First step',['generate conjugate bases','conjugate bases','deprotonate both'],'COMBINED_FIRST')]),q('CS-P2','If one conjugate base has strong resonance stabilization and the other does not, is resonance a meaningful deciding factor?',[f('a','Answer',['yes','y'],'COMBINED_WEIGHT')],['multi-factor'])],
watch:[w('Compare the actual conjugate bases','Remove the proton being compared from each acid. Then inspect where the negative charge lives and what stabilizes it: atom identity, resonance, induction, and orbital hybridization.','deprotonate -> compare bases',q('CS-W1','Do you need to deprotonate the same kind of candidate site before comparing stability?',[f('a','Answer',['yes','y'],'COMBINED_FIRST')])),w('Do not turn ARIO into a point-counting game','Structural factors are not equal one-point votes. A major difference such as placing charge on O instead of C can outweigh a weak remote inductive effect. Use chemical magnitude, not factor count.','weigh factors, do not count them',q('CS-W2','Should two weak factors automatically beat one much stronger stabilization factor?',[f('a','Answer',['no','n'],'COMBINED_WEIGHT')]))],
concept:[q('CS-C1','Name the four common structural categories used here: atom, resonance, induction, and what?',[f('a','Fourth',['orbital','orbitals','hybridization'],'COMBINED_FACTORS')]),q('CS-C2','More stable conjugate base corresponds to stronger acid. Yes or no?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])],
build:[q('CS-B1','Build: acid A gives an O- conjugate base; acid B gives a C- conjugate base, with no major other differences. Which base is more stable?',[f('a','Base',['a','base a','oxygen anion'],'COMBINED_WEIGHT')]),q('CS-B2','Therefore which acid is stronger?',[f('a','Acid',['a','acid a'],'STABILITY_ACID')])],
guided:[q('CS-G1','Guided: two conjugate bases place charge on O, but A is resonance-delocalized and B is localized. Which is more stable?',[f('a','Base',['a','base a'],'COMBINED_WEIGHT')]),q('CS-G2','Guided: two similar anions differ mainly by a nearby CF3 in A vs remote CF3 in B. Which is more stabilized inductively?',[f('a','Base',['a','base a'],'COMBINED_WEIGHT')])],
independent:[q('CS-I1','Cold: first step in structural acidity comparison?',[f('a','First step',['generate conjugate bases','deprotonate','compare conjugate bases'],'COMBINED_FIRST')]),q('CS-I2','Cold: the four factors include atom, resonance, induction, and what?',[f('a','Factor',['orbital','orbitals','hybridization'],'COMBINED_FACTORS')]),q('CS-I3','Cold: should you simply count how many factors favor each acid?',[f('a','Answer',['no','n'],'COMBINED_WEIGHT')]),q('CS-I4','Cold: the acid with more stable conjugate base is stronger or weaker?',[f('a','Acid',['stronger','stronger acid'],'STABILITY_ACID')])],
explanation:{prompt:'Describe a reliable workflow for comparing acid strength using atom, resonance, induction, and orbital effects. Explain why the factors should be weighed, not merely counted.',requiredGroups:[['conjugate base','deproton'],['atom'],['resonance'],['induction'],['orbital'],['weigh','magnitude','not count']]},transfer:[q('CS-T1','Transfer: base A is resonance-delocalized on oxygen; base B is localized on carbon but has one remote fluorine. Which stabilization is likely more decisive?',[f('a','Choice',['a','base a','resonance on oxygen'],'COMBINED_WEIGHT')],['ranking'])],intervening:q('CS-A1','Different skill: acid-base equilibrium favors side with weaker acid or stronger acid?',[f('a','Acid',['weaker','weaker acid'],'EQ_WEAKER_ACID')]),retrieval:[q('CS-R1','Later: compare acids by comparing what products of deprotonation?',[f('a','Products',['conjugate bases','conjugate base'],'COMBINED_FIRST')]),q('CS-R2','Later: does more stable conjugate base mean stronger acid?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])],repairChecks:{COMBINED_FIRST:q('CS-RP1','Repair check: should you remove the candidate proton and compare conjugate bases first?',[f('a','Answer',['yes','y'],'COMBINED_FIRST')]),COMBINED_FACTORS:q('CS-RP2','Repair check: are atom, resonance, induction, and orbital the four categories used here?',[f('a','Answer',['yes','y'],'COMBINED_FACTORS')]),COMBINED_WEIGHT:q('CS-RP3','Repair check: should stabilization factors be weighed by chemical importance rather than just counted?',[f('a','Answer',['yes','y'],'COMBINED_WEIGHT')]),STABILITY_ACID:q('CS-RP4','Repair check: more stable conjugate base -> stronger acid?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])},reteach:{COMBINED_FIRST:'Generate the conjugate base from each candidate acid before comparing structural effects.',COMBINED_FACTORS:'Check atom, resonance, induction, and orbital stabilization.',COMBINED_WEIGHT:'Do not award one point per factor. Ask which structural difference most strongly changes charge stability.',STABILITY_ACID:'The acid that forms the more stable conjugate base is generally the stronger acid.'}});

L['acidity-without-table']=freezeLesson({id:'acidity-without-table',skillId:'u2.c3.equilibrium_no_pka',title:'Predict Acidity Without a pKa Table',chapter:'Chapter 3',priority:2,prerequisites:['combined-stability'],requiredTags:['no-table','cationic-acid'],objective:'Predict relative acidity when exact pKa values are unavailable, including cationic acids, by comparing conjugate-base stability and charge relief.',
probe:[q('NT-P1','Without a pKa table, what should you compare after removing the candidate proton?',[f('a','Compare',['conjugate base stability','stability of conjugate bases','conjugate bases'],'NO_TABLE_WORKFLOW')]),q('NT-P2','If deprotonation of a cationic acid gives a neutral conjugate base, can relief of positive charge favor deprotonation?',[f('a','Answer',['yes','y'],'CATIONIC_ACID')],['cationic-acid'])],
watch:[w('Use structure when the table is missing','Generate the conjugate bases and compare the same stabilization factors: atom, resonance, induction, orbital effects, and charge. Exact numbers are not required to make many relative predictions.','structure -> conjugate-base stability',q('NT-W1','Without pKa values, is conjugate-base stability still useful?',[f('a','Answer',['yes','y'],'NO_TABLE_WORKFLOW')])),w('Charge state matters','A positively charged acid can become neutral after losing H+. That charge relief can make it substantially more acidic than a neutral analogue, though structure still matters.','cation -> neutral after deprotonation',q('NT-W2','Can converting a cation to a neutral conjugate base increase acidity?',[f('a','Answer',['yes','y'],'CATIONIC_ACID')]))],
concept:[q('NT-C1','No pKa table: first compare acid drawings or conjugate-base stability?',[f('a','Choice',['conjugate-base stability','conjugate bases'],'NO_TABLE_WORKFLOW')]),q('NT-C2','A protonated amine loses H+ to become neutral amine. Is that a cationic-acid deprotonation?',[f('a','Answer',['yes','y'],'CATIONIC_ACID')])],
build:[q('NT-B1','Build: acid A deprotonates to a resonance-stabilized anion; B to a localized anion. Which acid is predicted stronger?',[f('a','Acid',['a','acid a'],'NO_TABLE_WORKFLOW')]),q('NT-B2','Build: protonated alcohol ROH2+ loses H+ to neutral ROH. Does charge relief support acidity?',[f('a','Answer',['yes','y'],'CATIONIC_ACID')])],
guided:[q('NT-G1','Guided: no pKa values. One conjugate base places charge on O; another on C. Which parent acid is generally stronger?',[f('a','Acid',['the oxygen conjugate-base acid','oxygen acid','acid giving o-'],'NO_TABLE_WORKFLOW')]),q('NT-G2','Guided: cationic acid gives neutral base; neutral acid gives anion. Is the cationic species often substantially more acidic?',[f('a','Answer',['yes','y'],'CATIONIC_ACID')])],
independent:[q('NT-I1','Cold: without pKa, compare what?',[f('a','Compare',['conjugate base stability','conjugate bases'],'NO_TABLE_WORKFLOW')]),q('NT-I2','Cold: more stable conjugate base predicts stronger acid. Yes or no?',[f('a','Answer',['yes','y'],'STABILITY_ACID')]),q('NT-I3','Cold: loss of H+ that neutralizes a cation can favor acidity. Yes or no?',[f('a','Answer',['yes','y'],'CATIONIC_ACID')]),q('NT-I4','Cold: should you guess acidity from formal charge alone without checking the conjugate base?',[f('a','Answer',['no','n'],'NO_TABLE_WORKFLOW')])],
explanation:{prompt:'Explain how to predict relative acidity without pKa values and how cationic acids fit into the same conjugate-base stability logic.',requiredGroups:[['conjugate base'],['stability'],['atom','resonance','induction','orbital'],['cation','neutral','charge']]},transfer:[q('NT-T1','Transfer: two acids lack pKa data. A gives a neutral resonance-stabilized base; B gives a localized anion. Which is likely more acidic?',[f('a','Acid',['a','acid a'],'NO_TABLE_WORKFLOW')])],intervening:q('NT-A1','Different skill: stronger base has conjugate acid with higher pKa. Yes or no?',[f('a','Answer',['yes','y'],'BASE_CONJUGATE_PKA')]),retrieval:[q('NT-R1','Later: no-table acidity prediction rests on stability of what species?',[f('a','Species',['conjugate base','conjugate bases'],'NO_TABLE_WORKFLOW')]),q('NT-R2','Later: can cation-to-neutral deprotonation enhance acidity?',[f('a','Answer',['yes','y'],'CATIONIC_ACID')])],repairChecks:{NO_TABLE_WORKFLOW:q('NT-RP1','Repair check: when pKa is unavailable, should you compare the conjugate bases structurally?',[f('a','Answer',['yes','y'],'NO_TABLE_WORKFLOW')]),CATIONIC_ACID:q('NT-RP2','Repair check: can losing H+ remove a positive charge and form a neutral conjugate base?',[f('a','Answer',['yes','y'],'CATIONIC_ACID')]),STABILITY_ACID:q('NT-RP3','Repair check: more stable conjugate base usually means stronger acid?',[f('a','Answer',['yes','y'],'STABILITY_ACID')])},reteach:{NO_TABLE_WORKFLOW:'No pKa table does not mean guess. Generate conjugate bases and compare their stabilization structurally.',CATIONIC_ACID:'When a cationic acid loses H+ and becomes neutral, charge relief can strongly favor deprotonation.',STABILITY_ACID:'Conjugate-base stability remains the core link to acid strength.'}});

L['reagent-choice']=freezeLesson({id:'reagent-choice',skillId:'u2.c3.reagent_choice',title:'Choose a Proton-Transfer Reagent',chapter:'Chapter 3',priority:2,prerequisites:['equilibrium-pka','acidity-without-table'],requiredTags:['reagent','equilibrium'],objective:'Choose a base or acid reagent that drives the desired proton transfer by comparing conjugate-acid pKa and avoiding incompatible choices.',
probe:[q('RC-P1','To deprotonate an acid HA effectively, should the reagent base have a conjugate acid with pKa higher or lower than HA?',[f('a','pKa',['higher','higher pka'],'REAGENT_PKA')]),q('RC-P2','If the desired product acid is stronger than the starting acid, will equilibrium generally favor that product side?',[f('a','Answer',['no','n'],'REAGENT_DIRECTION')])],
watch:[w('Choose a base by its conjugate acid','For B- + HA -> HB + A-, compare pKa(HA) with pKa(HB). To favor products, HB should be the weaker acid, so pKa(HB) should be higher than pKa(HA).','base choice -> conjugate acid pKa higher',q('RC-W1','If HA pKa 18, is a base whose conjugate acid pKa 35 thermodynamically capable of favorable deprotonation?',[f('a','Answer',['yes','y'],'REAGENT_PKA')])),w('Do not confuse ability with side reactions','A thermodynamically strong enough base can still be a poor synthetic choice if it reacts elsewhere. At this stage, first prove the acid-base driving force, then consider chemical compatibility.','thermodynamics first, compatibility second',q('RC-W2','Should pKa driving force be checked before calling a base suitable?',[f('a','Answer',['yes','y'],'REAGENT_DIRECTION')]))],
concept:[q('RC-C1','Desired deprotonation: starting acid pKa 10. Reagent conjugate acid pKa 5 or 20, which is favorable?',[f('a','Choice',['20','pka 20'],'REAGENT_PKA')]),q('RC-C2','Product side is favored when product acid is weaker. Yes or no?',[f('a','Answer',['yes','y'],'REAGENT_DIRECTION')])],
build:[q('RC-B1','Build: HA pKa 25. Candidate base X has conjugate acid pKa 16, Y has pKa 35. Which is thermodynamically better for deprotonation?',[f('a','Base',['y','base y'],'REAGENT_PKA')]),q('RC-B2','Why?',[f('a','Reason',['product acid has higher pka','higher conjugate-acid pka','weaker product acid'],'REAGENT_DIRECTION')])],
guided:[q('RC-G1','Guided: target is to protonate B-. Would you choose an acid substantially stronger or weaker than BH?',[f('a','Acid',['stronger','stronger acid'],'REAGENT_DIRECTION')]),q('RC-G2','Guided: for deprotonation, base conjugate acid pKa 40 vs substrate acid pKa 20. Products favored?',[f('a','Answer',['yes','y'],'REAGENT_PKA')])],
independent:[q('RC-I1','Cold: deprotonating base should have conjugate acid pKa higher or lower than substrate acid?',[f('a','pKa',['higher'],'REAGENT_PKA')]),q('RC-I2','Cold: substrate acid pKa 15; conjugate acid of base pKa 5. Favorable deprotonation?',[f('a','Answer',['no','n'],'REAGENT_DIRECTION')]),q('RC-I3','Cold: substrate acid pKa 15; conjugate acid of base pKa 30. Favorable?',[f('a','Answer',['yes','y'],'REAGENT_PKA')]),q('RC-I4','Cold: after pKa check, should chemical compatibility still matter in a real reaction?',[f('a','Answer',['yes','y'],'REAGENT_COMPATIBILITY')])],
explanation:{prompt:'Explain how to choose a base for deprotonation using conjugate-acid pKa, then explain why pKa is necessary but not always sufficient for a synthetic reagent choice.',requiredGroups:[['conjugate acid'],['higher','pka'],['weaker acid','equilibrium'],['compatib','side reaction']]},transfer:[q('RC-T1','Transfer: acid pKa 8. Candidate bases have conjugate acids pKa 4 and 18. Which candidate is thermodynamically suited to deprotonate it?',[f('a','Candidate',['pka 18 base','18','the second base'],'REAGENT_PKA')])],intervening:q('RC-A1','Different skill: Lewis base donates or accepts an electron pair?',[f('a','Action',['donates','donate'],'LEWIS_ROLE')]),retrieval:[q('RC-R1','Later: for favorable deprotonation, base conjugate acid should be weaker or stronger than starting acid?',[f('a','Acid',['weaker','weaker acid'],'REAGENT_DIRECTION')]),q('RC-R2','Later: weaker product acid has higher or lower pKa?',[f('a','pKa',['higher'],'REAGENT_PKA')])],repairChecks:{REAGENT_PKA:q('RC-RP1','Repair check: HA pKa 10, HB pKa 20. Does B- favorably deprotonate HA to form HB?',[f('a','Answer',['yes','y'],'REAGENT_PKA')]),REAGENT_DIRECTION:q('RC-RP2','Repair check: equilibrium favors formation of the weaker acid?',[f('a','Answer',['yes','y'],'REAGENT_DIRECTION')]),REAGENT_COMPATIBILITY:q('RC-RP3','Repair check: after thermodynamics, can side reactions still make a reagent poor?',[f('a','Answer',['yes','y'],'REAGENT_COMPATIBILITY')])},reteach:{REAGENT_PKA:'To deprotonate HA, choose a base whose conjugate acid HB has a higher pKa than HA.',REAGENT_DIRECTION:'The desired proton transfer is favored when it forms the weaker acid/base pair.',REAGENT_COMPATIBILITY:'A pKa-favorable reagent can still react at the wrong site or by another mechanism, so compatibility matters after the acid-base check.'}});

L['lewis-acid-base']=freezeLesson({id:'lewis-acid-base',skillId:'u2.c3.lewis_acid_base',title:'Lewis Acids and Lewis Bases',chapter:'Chapter 3',priority:2,prerequisites:['proton-transfer'],requiredTags:['lewis','electron-pair'],objective:'Identify Lewis acids and bases by electron-pair acceptance and donation, including reactions with no proton transfer.',
probe:[q('LA-P1','A Lewis base donates or accepts an electron pair?',[f('a','Action',['donates','donate'],'LEWIS_ROLE')]),q('LA-P2','BF3 accepts an electron pair at boron. Lewis acid or base?',[f('a','Role',['lewis acid','acid'],'LEWIS_ROLE')],['lewis'])],
watch:[w('Lewis language tracks electron pairs','Lewis base = electron-pair donor. Lewis acid = electron-pair acceptor. Bronsted proton transfer is one important subset, but Lewis acid-base reactions can occur without any H+ transfer.','base donates pair -> acid accepts pair',q('LA-W1','If NH3 donates its lone pair to BF3, which is the Lewis base?',[f('a','Base',['nh3','ammonia'],'LEWIS_ROLE')])),w('Look for electron-rich and electron-poor centers','Lone pairs, negative charge, and pi bonds can provide electron pairs. Electron-deficient atoms, carbocations, and species with incomplete octets can accept them.','electron rich -> donor; electron poor -> acceptor',q('LA-W2','A carbocation is usually Lewis acid or Lewis base?',[f('a','Role',['lewis acid','acid'],'LEWIS_ACCEPTOR')]))],
concept:[q('LA-C1','OH- donates a lone pair to H+. Which is the Lewis base?',[f('a','Base',['oh-','ho-','hydroxide'],'LEWIS_ROLE')]),q('LA-C2','Does every Lewis acid-base reaction require proton transfer?',[f('a','Answer',['no','n'],'LEWIS_NO_PROTON')])],
build:[q('LA-B1','Build: NH3 + BF3. Which atom supplies the electron pair?',[f('a','Donor atom',['nitrogen','n'],'LEWIS_ROLE')]),q('LA-B2','Which atom accepts that pair?',[f('a','Acceptor atom',['boron','b'],'LEWIS_ACCEPTOR')])],
guided:[q('LA-G1','Guided: Cl- donates a lone pair to an electron-poor metal center. Cl- is Lewis acid or base?',[f('a','Role',['lewis base','base'],'LEWIS_ROLE')]),q('LA-G2','Guided: AlCl3 accepts an electron pair. Lewis acid or base?',[f('a','Role',['lewis acid','acid'],'LEWIS_ACCEPTOR')])],
independent:[q('LA-I1','Cold: Lewis base does what with an electron pair?',[f('a','Action',['donates','donate'],'LEWIS_ROLE')]),q('LA-I2','Cold: Lewis acid does what with an electron pair?',[f('a','Action',['accepts','accept'],'LEWIS_ACCEPTOR')]),q('LA-I3','Cold: BF3 role?',[f('a','Role',['lewis acid','acid'],'LEWIS_ACCEPTOR')]),q('LA-I4','Cold: can a Lewis reaction happen without H+ transfer?',[f('a','Answer',['yes','y'],'LEWIS_NO_PROTON')])],
explanation:{prompt:'Explain Lewis acid-base behavior in terms of electron-pair donation and acceptance, and distinguish it from the narrower Bronsted definition.',requiredGroups:[['electron pair'],['donor','base'],['acceptor','acid'],['proton','not required','bronsted']]},transfer:[q('LA-T1','Transfer: a carbonyl oxygen lone pair coordinates to a metal cation. Which partner is the Lewis base?',[f('a','Base',['carbonyl oxygen','oxygen','carbonyl'],'LEWIS_ROLE')])],intervening:q('LA-A1','Different skill: acid-base equilibrium favors the side with weaker or stronger acid?',[f('a','Acid',['weaker','weaker acid'],'EQ_WEAKER_ACID')]),retrieval:[q('LA-R1','Later: electron-pair donor is Lewis acid or base?',[f('a','Role',['lewis base','base'],'LEWIS_ROLE')]),q('LA-R2','Later: electron-pair acceptor is Lewis acid or base?',[f('a','Role',['lewis acid','acid'],'LEWIS_ACCEPTOR')])],repairChecks:{LEWIS_ROLE:q('LA-RP1','Repair check: does a Lewis base donate an electron pair?',[f('a','Answer',['yes','y'],'LEWIS_ROLE')]),LEWIS_ACCEPTOR:q('LA-RP2','Repair check: does a Lewis acid accept an electron pair?',[f('a','Answer',['yes','y'],'LEWIS_ACCEPTOR')]),LEWIS_NO_PROTON:q('LA-RP3','Repair check: is proton transfer required for every Lewis acid-base reaction?',[f('a','Answer',['no','n'],'LEWIS_NO_PROTON')])},reteach:{LEWIS_ROLE:'Lewis base donates an electron pair. Find a lone pair, negative charge, or other electron-rich source.',LEWIS_ACCEPTOR:'Lewis acid accepts an electron pair. Look for electron deficiency, positive charge, or an incomplete octet.',LEWIS_NO_PROTON:'Bronsted chemistry requires H+ transfer; Lewis chemistry is broader and only requires electron-pair donation/acceptance.'}});

var ORDER=Object.freeze(['proton-transfer','pka-acidity','basicity-conjugate-acid','equilibrium-pka','stability-atom','stability-resonance','stability-induction','stability-orbitals','combined-stability','acidity-without-table','reagent-choice','lewis-acid-base']);
var LESSONS=Object.freeze(L);
var CHECKPOINTS=Object.freeze([
 Object.freeze({id:'C3-D1',skill:'proton-transfer',task:'Select the complete two-arrow proton-transfer mechanism and identify both conjugate pairs.',grading:'structured arrow/source/product selection'}),
 Object.freeze({id:'C3-D2',skill:'equilibrium-pka',task:'Compare acid pKa on both sides and predict the favored equilibrium direction.',grading:'structured pKa comparison'}),
 Object.freeze({id:'C3-D3',skill:'stability-resonance',task:'Generate two conjugate bases and identify which receives resonance stabilization.',grading:'structured conjugate-base comparison'}),
 Object.freeze({id:'C3-D4',skill:'stability-induction',task:'Compare inductive stabilization at two substituent distances.',grading:'structured distance comparison'}),
 Object.freeze({id:'C3-D5',skill:'stability-orbitals',task:'Rank sp, sp2, and sp3 carbanion stability and connect it to C-H acidity.',grading:'structured orbital ranking'}),
 Object.freeze({id:'C3-D6',skill:'combined-stability',task:'Rank fresh acids after evaluating atom, resonance, induction, and orbital effects without point counting.',grading:'structured multifactored ranking plus explanation'}),
 Object.freeze({id:'C3-D7',skill:'reagent-choice',task:'Choose a proton-transfer reagent from conjugate-acid pKa and reject a thermodynamically wrong option.',grading:'structured reagent selection'}),
 Object.freeze({id:'C3-D8',skill:'lewis-acid-base',task:'Identify electron-pair donor and acceptor in a proton-free Lewis acid-base reaction.',grading:'structured donor/acceptor selection'})
]);
var META=Object.freeze({unit:'Unit 2',chapter:'Chapter 3',title:'Acids and Bases',status:'authored-not-live',foundationRoutes:Object.freeze({language:'../../../day4/',stability:'../../../day5/',equilibrium:'../../../day6/'})});
function lessonById(id){return LESSONS[id]||null;}function lessons(){return ORDER.map(function(id){return LESSONS[id];});}function lessonIds(){return ORDER.slice();}
return Object.freeze({META:META,LESSONS:LESSONS,ORDER:ORDER,PRODUCTION_CHECKPOINTS:CHECKPOINTS,lesson:lessonById,lessons:lessons,lessonIds:lessonIds});
});