(function(root){'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function box(title,body,note){return'<figure class="chem-visual"><figcaption>'+e(title)+'</figcaption>'+body+(note?'<div class="visual-note">'+e(note)+'</div>':'')+'</figure>';}
function proton(){return box('Proton transfer follows the electron pair','<div class="donor-acceptor"><div class="panel donor"><b>Base:</b><br>electron pair donor</div><div class="arrow-mid">→ H →</div><div class="panel acceptor"><b>Acid H-A</b><br>H-A bond pair returns to A</div></div>','Base gains H+ to become its conjugate acid. Acid loses H+ to become its conjugate base.');}
function pka(){return box('pKa number line','<div class="pka-key"><span>stronger acid</span><span>weaker acid</span></div><div class="pka-line"><span>-5</span><span>0</span><span>10</span><span>20</span><span>40</span><div class="pka-track"></div></div>','For acids: lower pKa means stronger acid. For bases: higher conjugate-acid pKa means stronger base.');}
function equilibrium(){return box('Equilibrium favors the weaker acid/base pair','<div class="equilibrium-row"><div class="pair-card"><b>Left acid</b>compare pKa</div><div class="arrow-mid">⇌</div><div class="pair-card favored"><b>Higher-pKa acid</b>weaker acid side</div></div>','Circle one acid on each side. The side with the higher-pKa acid is generally favored.');}
function atom(){return box('Atom effect on negative charge','<div class="two-panel"><div class="panel"><b>Across a row</b><br>more electronegative atom stabilizes - charge</div><div class="versus">and</div><div class="panel"><b>Down a group</b><br>larger, more polarizable atom can spread - charge</div></div>','Always compare the charged atom in the conjugate base.');}
function resonance(){return box('Resonance stabilizes a conjugate base','<div class="resonance-row"><div class="structure-card"><strong>localized -</strong><span class="charge-chip">one site</span></div><div class="res-arrow">→</div><div class="structure-card"><strong>delocalized -</strong><span class="charge-chip">shared sites</span></div></div>','Generate the conjugate bases first. More delocalization generally means greater stability and stronger parent acid.');}
function induction(){return box('Induction fades with distance','<div class="three-panel"><div class="panel favored"><b>EWG close</b><br>stronger stabilization</div><div class="panel"><b>EWG farther</b><br>weaker effect</div><div class="panel"><b>sigma bonds</b><br>transmit the effect</div></div>','Count sigma bonds from the electron-withdrawing group to the charged site.');}
function orbitals(){return box('s character stabilizes carbanions','<div class="three-panel"><div class="panel favored"><b>sp</b><br>50% s</div><div class="panel"><b>sp2</b><br>about 33% s</div><div class="panel"><b>sp3</b><br>25% s</div></div>','For comparable carbanions: sp is more stable than sp2, which is more stable than sp3.');}
function combined(){return box('Compare conjugate bases, then weigh the factors','<div class="factor-grid"><div class="factor"><b>A</b>Atom</div><div class="factor"><b>R</b>Resonance</div><div class="factor"><b>I</b>Induction</div><div class="factor"><b>O</b>Orbital</div></div>','Do not count factors as equal votes. Weigh how strongly each structural difference changes charge stability.');}
function noTable(){return box('No pKa table does not mean guess','<div class="charge-before-after"><div class="charge-box">Acid<br><span class="charge-chip">before H+ loss</span></div><div class="arrow-mid">→</div><div class="charge-box favored">Conjugate base<br><span class="charge-chip">compare stability</span></div></div>','For a cationic acid, notice when deprotonation also relieves positive charge.');}
function reagent(){return box('Choose a proton-transfer reagent by conjugate-acid pKa','<div class="two-panel"><div class="panel"><b>Substrate acid</b><br>pKa = X</div><div class="versus">compare</div><div class="panel favored"><b>Base conjugate acid</b><br>pKa should be higher for favorable deprotonation</div></div>','After the pKa test, check chemical compatibility and possible side reactions.');}
function lewis(){return box('Lewis acid-base roles','<div class="donor-acceptor"><div class="panel donor"><b>Lewis base</b><br>donates electron pair</div><div class="arrow-mid">→</div><div class="panel acceptor"><b>Lewis acid</b><br>accepts electron pair</div></div>','No proton is required for a Lewis acid-base reaction.');}
function byLesson(id){if(id==='proton-transfer')return proton();if(id==='pka-acidity'||id==='basicity-conjugate-acid')return pka();if(id==='equilibrium-pka')return equilibrium();if(id==='stability-atom')return atom();if(id==='stability-resonance')return resonance();if(id==='stability-induction')return induction();if(id==='stability-orbitals')return orbitals();if(id==='combined-stability')return combined();if(id==='acidity-without-table')return noTable();if(id==='reagent-choice')return reagent();if(id==='lewis-acid-base')return lewis();return'';}
function item(item,lessonId){return byLesson(lessonId);}
function watch(lessonId,index,lesson){return byLesson(lessonId);}
function repair(code,lessonId,teaching){if(/PT_|AB_ROLE|CONJUGATE/.test(code))return proton();if(/PKA_|BASE_CONJUGATE|ACID_BASE/.test(code))return pka();if(/^EQ_/.test(code))return equilibrium();if(/ATOM_/.test(code))return atom();if(/RESONANCE/.test(code))return resonance();if(/INDUCTION/.test(code))return induction();if(/ORBITAL/.test(code))return orbitals();if(/COMBINED/.test(code))return combined();if(/NO_TABLE|CATIONIC/.test(code))return noTable();if(/REAGENT/.test(code))return reagent();if(/LEWIS/.test(code))return lewis();return byLesson(lessonId);}
root.Chapter3Visuals=Object.freeze({item:item,watch:watch,repair:repair});
})(typeof globalThis!=='undefined'?globalThis:this);