(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Chapter3AdaptiveSupport=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
var REASONS=Object.freeze([
 Object.freeze({id:'dont_understand_concept',label:'I do not understand the concept'}),
 Object.freeze({id:'dont_know_how_to_start',label:'I do not know how to start'}),
 Object.freeze({id:'forgot_prerequisite',label:'I forgot a prerequisite'}),
 Object.freeze({id:'started_but_stuck',label:'I started but got stuck'}),
 Object.freeze({id:'show_me_example',label:'Show me another example'}),
 Object.freeze({id:'explanation_not_making_sense',label:'The explanation is not making sense'})
]);
var LABELS=Object.freeze({
 AB_ROLE:'Bronsted acid/base role',PT_ARROW_SOURCE:'proton-transfer electron source',PT_BOND_BREAK:'H-A bond electron destination',CONJUGATE_PAIR:'conjugate pair',
 PKA_ACID:'pKa and acid strength',PKA_KA:'Ka versus pKa direction',BASE_CONJUGATE_PKA:'base strength from conjugate-acid pKa',ACID_BASE_INVERSE:'acid/conjugate-base inverse relationship',
 EQ_WEAKER_ACID:'weaker-acid comparison',EQ_DIRECTION:'equilibrium direction',EQ_PAIR:'favored weak acid/base pair',
 ATOM_ELECTRONEGATIVITY:'charged-atom electronegativity',ATOM_SIZE:'charged-atom size/polarizability',STABILITY_ACID:'conjugate-base stability to acid strength',
 STABILITY_RESONANCE:'resonance stabilization',RESONANCE_COMPARE_BASES:'resonance comparison after deprotonation',STABILITY_INDUCTION:'inductive stabilization',INDUCTION_DISTANCE:'inductive distance',
 STABILITY_ORBITAL:'orbital s-character stabilization',ORBITAL_ACIDITY:'orbital effect on C-H acidity',COMBINED_FIRST:'combined-stability first step',COMBINED_FACTORS:'atom/resonance/induction/orbital factors',COMBINED_WEIGHT:'weighing structural factors',
 NO_TABLE_WORKFLOW:'acidity prediction without pKa table',CATIONIC_ACID:'cationic-acid charge relief',REAGENT_PKA:'reagent conjugate-acid pKa',REAGENT_DIRECTION:'reagent equilibrium direction',REAGENT_COMPATIBILITY:'reagent chemical compatibility',
 LEWIS_ROLE:'Lewis-base electron-pair donation',LEWIS_ACCEPTOR:'Lewis-acid electron-pair acceptance',LEWIS_NO_PROTON:'Lewis reaction without proton transfer'
});
var FIRST=Object.freeze({
 AB_ROLE:'Label the species losing H+ as the acid and the species gaining H+ as the base.',PT_ARROW_SOURCE:'Find the base electron pair first. The curved-arrow tail starts at a lone pair or other electron pair on the base.',PT_BOND_BREAK:'When the new bond to H forms, send the old H-A bond pair back onto A.',CONJUGATE_PAIR:'Remove one H+ from an acid to get its conjugate base; add one H+ to a base to get its conjugate acid.',
 PKA_ACID:'For acids, lower pKa means stronger acid.',PKA_KA:'pKa = -log Ka, so larger Ka corresponds to smaller pKa.',BASE_CONJUGATE_PKA:'For bases, compare conjugate-acid pKa. Higher conjugate-acid pKa means stronger base.',ACID_BASE_INVERSE:'Strong acid has weak conjugate base; weak acid has stronger conjugate base.',
 EQ_WEAKER_ACID:'Identify the acid on each side and compare pKa. The higher-pKa acid is weaker.',EQ_DIRECTION:'Equilibrium favors the side containing the weaker acid, usually the higher-pKa acid.',EQ_PAIR:'The favored side contains the weaker acid and weaker base pair.',
 ATOM_ELECTRONEGATIVITY:'Across the same period, a more electronegative atom better stabilizes negative charge.',ATOM_SIZE:'Down a group, a larger atom can spread negative charge over a larger, more polarizable cloud.',STABILITY_ACID:'A more stable conjugate base generally means a stronger parent acid.',
 STABILITY_RESONANCE:'Spread negative charge over valid resonance positions to stabilize the conjugate base.',RESONANCE_COMPARE_BASES:'Deprotonate both acids first, then compare resonance in the resulting conjugate bases.',STABILITY_INDUCTION:'Nearby electron-withdrawing groups stabilize negative charge through sigma bonds.',INDUCTION_DISTANCE:'Induction weakens as the electron-withdrawing group moves farther from the charge.',
 STABILITY_ORBITAL:'More s character stabilizes a carbanion: sp more than sp2 more than sp3.',ORBITAL_ACIDITY:'More stable carbanion after deprotonation means the corresponding C-H bond is more acidic.',COMBINED_FIRST:'Generate the conjugate bases first before judging atom, resonance, induction, or orbital effects.',COMBINED_FACTORS:'Check atom, resonance, induction, and orbital effects in the conjugate bases.',COMBINED_WEIGHT:'Do not count factors as equal votes. Ask which structural difference most strongly changes charge stability.',
 NO_TABLE_WORKFLOW:'Without exact pKa values, generate the conjugate bases and compare their structural stability.',CATIONIC_ACID:'Check whether deprotonation relieves a positive charge and produces a neutral conjugate base.',REAGENT_PKA:'For favorable deprotonation, choose a base whose conjugate acid has a higher pKa than the substrate acid.',REAGENT_DIRECTION:'The desired reaction is favored when it forms the weaker acid/base pair.',REAGENT_COMPATIBILITY:'After the pKa check, ask whether the reagent can react elsewhere or create an unwanted pathway.',
 LEWIS_ROLE:'A Lewis base donates an electron pair. Find the electron-rich donor.',LEWIS_ACCEPTOR:'A Lewis acid accepts an electron pair. Find the electron-poor acceptor.',LEWIS_NO_PROTON:'Lewis acid-base chemistry does not require H+ transfer; it only requires electron-pair donation and acceptance.'
});
var ALT=Object.freeze({
 AB_ROLE:'Switch representation: draw two columns labeled LOSES H+ and GAINS H+. Put the acid in the first and base in the second.',PT_ARROW_SOURCE:'Switch representation: mark electron pairs as dots before drawing any arrows. Start at a marked electron pair, not at H.',PT_BOND_BREAK:'Switch representation: treat H as changing partners. When the new partner bonds to H, the old H-A bond pair stays with A.',CONJUGATE_PAIR:'Switch representation: use +H and -H cards. Acid minus H gives conjugate base; base plus H gives conjugate acid.',
 PKA_ACID:'Switch representation: place pKa values on a number line. Lower numbers sit on the stronger-acid side.',PKA_KA:'Switch representation: write pKa = -log Ka with arrows showing Ka up -> pKa down.',BASE_CONJUGATE_PKA:'Switch representation: rank the conjugate acids first. The weaker acid, with higher pKa, has the stronger conjugate base.',ACID_BASE_INVERSE:'Switch representation: use a seesaw. Acid strength up means conjugate-base strength down.',
 EQ_WEAKER_ACID:'Switch representation: circle exactly one acid on each side, write its pKa underneath, then point toward the higher pKa.',EQ_DIRECTION:'Switch representation: put a WEAKER ACID sign over the side with higher acid pKa. That is the favored side.',EQ_PAIR:'Switch representation: label both acid and base on each side, then choose the weaker pair.',
 ATOM_ELECTRONEGATIVITY:'Switch representation: across one row, place charged atoms on an electronegativity ladder.',ATOM_SIZE:'Switch representation: draw small vs large electron clouds. The larger cloud spreads the same negative charge over more space.',STABILITY_ACID:'Switch representation: draw acid -> conjugate base. Stabilize the product and the deprotonation becomes easier.',
 STABILITY_RESONANCE:'Switch representation: color the negative charge in every valid contributor position. More delocalized positions means more stabilization.',RESONANCE_COMPARE_BASES:'Switch representation: cross out the acidic H first on both structures, then compare the two resulting anions.',STABILITY_INDUCTION:'Switch representation: draw an electron-withdrawing arrow through sigma bonds away from the negative charge.',INDUCTION_DISTANCE:'Switch representation: count sigma bonds from EWG to the charged site. Fewer bonds means stronger induction.',
 STABILITY_ORBITAL:'Switch representation: use an s-character bar: sp 50%, sp2 about 33%, sp3 25%.',ORBITAL_ACIDITY:'Switch representation: compare the orbital holding the negative charge after H is removed.',COMBINED_FIRST:'Switch representation: make a two-column CONJUGATE BASE comparison before looking at the original acids.',COMBINED_FACTORS:'Switch representation: use four boxes labeled Atom, Resonance, Induction, Orbital and fill only the differences that actually apply.',COMBINED_WEIGHT:'Switch representation: use a balance scale instead of tally marks. Strong structural effects get more weight than weak remote effects.',
 NO_TABLE_WORKFLOW:'Switch representation: replace missing pKa numbers with a structural conjugate-base comparison chart.',CATIONIC_ACID:'Switch representation: write charge BEFORE and charge AFTER deprotonation. Notice when +1 becomes 0.',REAGENT_PKA:'Switch representation: put substrate-acid pKa on the left and reagent-conjugate-acid pKa on the right. Products are favored when the right value is higher.',REAGENT_DIRECTION:'Switch representation: point the equilibrium arrow toward the weaker acid, not toward the stronger base by guesswork.',REAGENT_COMPATIBILITY:'Switch representation: run two checks in order: pKa works? then chemistry compatible?',
 LEWIS_ROLE:'Switch representation: label DONOR over the species with a lone pair/electron pair and ACCEPTOR over the electron-poor partner.',LEWIS_ACCEPTOR:'Switch representation: draw an empty receiving box on the electron-poor center and an electron-pair token on the donor.',LEWIS_NO_PROTON:'Switch representation: hide every H atom and ask whether an electron pair can still be donated and accepted.'
});
var EXAMPLE=Object.freeze({
 PKA_ACID:'Example: pKa 3 acid is stronger than pKa 9 acid.',BASE_CONJUGATE_PKA:'Example: a base whose conjugate acid has pKa 20 is stronger than one whose conjugate acid has pKa 8.',EQ_DIRECTION:'Example: left acid pKa 5, right acid pKa 12. Products are favored because pKa 12 is the weaker acid.',STABILITY_RESONANCE:'Example: phenoxide is resonance-stabilized while ethoxide is not, helping make phenol more acidic than ethanol.',STABILITY_INDUCTION:'Example: a nearby CF3 group stabilizes a conjugate-base negative charge more than the same CF3 several bonds away.',STABILITY_ORBITAL:'Example: terminal alkyne deprotonation gives an sp carbanion, more stable than an sp3 carbanion from an alkane.',REAGENT_PKA:'Example: to deprotonate an acid of pKa 18, a base whose conjugate acid has pKa 35 is thermodynamically favorable.',LEWIS_ROLE:'Example: NH3 donates its lone pair to BF3. NH3 is the Lewis base; BF3 is the Lewis acid.'
});
function label(code){return LABELS[code]||String(code||'reasoning step').toLowerCase().replace(/_/g,' ');}
function foundationHref(code){if(/^STABILITY_RESONANCE|RESONANCE_COMPARE_BASES/.test(code))return'../../../day3/';if(/^(AB_ROLE|PT_|CONJUGATE_PAIR|PKA_|BASE_|ACID_BASE_|LEWIS_)/.test(code))return'../../../day4/';if(/^(ATOM_|STABILITY_|INDUCTION_|ORBITAL_|COMBINED_|NO_TABLE_|CATIONIC_)/.test(code))return'../../../day5/';if(/^(EQ_|REAGENT_)/.test(code))return'../../../day6/';return'../../../day4/';}
function prereqText(code){var href=foundationHref(code);if(/day3/.test(href))return'Review Day 3 resonance: valid electron moves, fixed connectivity, and contributor reasoning.';if(/day5/.test(href))return'Review Day 5 conjugate-base stability before continuing.';if(/day6/.test(href))return'Review Day 6 equilibrium direction and weaker-acid reasoning before continuing.';return'Review Day 4 acid/base roles, conjugate pairs, Ka, and pKa before continuing.';}
function text(lesson,code,reason,fieldLabel){var fallback=lesson&&lesson.reteach&&lesson.reteach[code]||FIRST[code]||'Return to the first chemical decision and rebuild it one step at a time.';if(reason==='dont_understand_concept')return fallback;if(reason==='dont_know_how_to_start')return'Start with only '+label(code)+'. '+(FIRST[code]||fallback);if(reason==='forgot_prerequisite')return'Prerequisite repair: '+prereqText(code);if(reason==='started_but_stuck')return'Keep the part you already completed. Repair only '+label(code)+'. '+(FIRST[code]||fallback);if(reason==='show_me_example')return EXAMPLE[code]||('Example focus: '+fallback);if(reason==='explanation_not_making_sense')return ALT[code]||('Switch representation: '+fallback);return fallback;}
function route(lesson,code,reason,fieldLabel){return{errorCode:code,label:label(code),reason:reason,text:text(lesson,code,reason,fieldLabel),foundationHref:reason==='forgot_prerequisite'?foundationHref(code):null};}
return Object.freeze({REASONS:REASONS,LABELS:LABELS,label:label,text:text,route:route,foundationHref:foundationHref});
});