(function(root){'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function box(title,body,note){return'<figure class="chem-visual"><figcaption>'+e(title)+'</figcaption>'+body+(note?'<div class="visual-note">'+e(note)+'</div>':'')+'</figure>';}
function resonanceRank(){return box('Rank only after validity','<div class="resonance-row"><div class="structure-card"><strong>Contributor A</strong><span class="tag-chip">full octet</span><span class="tag-chip">less charge separation</span></div><div class="res-arrow">↔</div><div class="structure-card"><strong>Contributor B</strong><span class="tag-chip">check octet</span><span class="tag-chip">check charge placement</span></div></div>','Order: same connectivity first, then octet, charge separation, electronegativity, and equivalence.');}
function hybrid(){return box('Contributors describe one resonance hybrid','<div class="resonance-row"><div class="structure-card"><strong>Contributor A</strong><span class="bond-chip">pi bond here</span></div><div class="res-arrow">↔</div><div class="structure-card"><strong>Contributor B</strong><span class="bond-chip">pi bond there</span></div></div><div class="hybrid-bar"></div><div style="text-align:center;font-weight:900">one real electron distribution</div>','The molecule does not switch between drawings. Equivalent contributors make equivalent hybrid features.');}
function lonePair(){return box('Can the lone pair join a conjugated path?','<div class="orbital-row"><div class="orbital active">LP</div><div class="orbital active">p</div><div class="orbital active">p</div></div><div class="pka-key"><span>adjacent lone pair</span><span>continuous overlap</span></div>','An intervening sp3 center breaks the direct p-orbital pathway.');}
function arrows(){return box('Curved arrows track electron pairs','<div class="electron-row"><div class="electron-source">lone pair or pi bond<br><small>electron source</small></div><div class="curved-arrow">↷</div><div class="electron-dest">receiving atom or bond<br><small>electron destination</small></div></div>','Tail starts at electrons. The sigma skeleton stays fixed. If a new pi bond overfills carbon, move an old pi pair away.');}
function transfer(){return box('Unfamiliar structure, same resonance workflow','<div class="factor-grid"><div class="factor"><b>1</b>Freeze connectivity</div><div class="factor"><b>2</b>Find movable electrons</div><div class="factor"><b>3</b>Validate charges and octets</div><div class="factor"><b>4</b>Rank and build the hybrid</div></div>','The surface changes. The invariants do not.');}
function byLesson(id){if(id==='rank-resonance')return resonanceRank();if(id==='resonance-hybrid')return hybrid();if(id==='localized-delocalized')return lonePair();if(id==='arrow-reasoning')return arrows();if(id==='resonance-transfer')return transfer();return'';}
function item(item,lessonId){return byLesson(lessonId);}
function watch(lessonId,index,lesson){return byLesson(lessonId);}
function repair(code,lessonId,teaching){if(/ARROW/.test(code))return arrows();if(/HYBRID/.test(code))return hybrid();if(/LONE_PAIR|CONJUGATION/.test(code))return lonePair();if(/RANK/.test(code))return resonanceRank();if(/TRANSFER/.test(code))return transfer();return byLesson(lessonId);}
root.Chapter2Visuals=Object.freeze({item:item,watch:watch,repair:repair});
})(typeof globalThis!=='undefined'?globalThis:this);