(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Chapter2AdaptiveData=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
function f(id,label,accepted,errorCode){return Object.freeze({id:id,label:label,accepted:Object.freeze(accepted),errorCode:errorCode});}
function q(id,prompt,fields,tags,visual){return Object.freeze({id:id,prompt:prompt,fields:Object.freeze(fields),tags:Object.freeze(tags||[]),visual:visual||null});}
function w(title,text,visual,check){return Object.freeze({title:title,text:text,visual:visual||null,check:check||null});}
function lesson(x){['probe','watch','concept','build','guided','independent','transfer','retrieval','requiredTags','prerequisites'].forEach(function(k){x[k]=Object.freeze(x[k]||[]);});x.repairChecks=Object.freeze(x.repairChecks||{});x.reteach=Object.freeze(x.reteach||{});return Object.freeze(x);}
var L={};
L['rank-resonance']=lesson({id:'rank-resonance',skillId:'u2.c2.rank_resonance',title:'Rank Resonance Contributors',chapter:'Chapter 2.7-2.13',priority:1,prerequisites:['day3-resonance'],requiredTags:['ranking','octet','charge-placement'],objective:'Rank valid resonance contributors using octets, charge separation, electronegativity, and equivalence rather than picture preference.',
probe:[q('RR-P1','Two valid contributors have the same connectivity. Contributor A gives every second-row atom a full octet. Contributor B leaves carbon with only six electrons. Which is usually the larger contributor?',[f('a','Larger contributor',['a','contributor a','A'],'RANK_OCTET')],['ranking']),q('RR-P2','Two contributors both satisfy octets. One places negative charge on oxygen and the other places the same negative charge on carbon. Which is usually favored?',[f('a','Favored atom',['oxygen','o'],'RANK_ELECTRONEGATIVITY')],['charge-placement'])],
watch:[w('First ask whether the drawings are valid','Ranking starts only after validity. Resonance contributors keep the same atom connectivity and differ only in electron placement. Then compare octets, unnecessary charge separation, and whether charge sits on a chemically sensible atom.','valid first -> rank second',q('RR-W1','If one drawing moves a hydrogen to a different atom, should you rank it as a resonance contributor?',[f('a','Answer',['no','n'],'RANK_VALIDITY')])) ,w('Equivalent contributors tie','When two contributors are related by symmetry and exchange identical atom roles, they contribute equally. Do not invent a major form just because one double bond is drawn on the left.','equivalent forms = equal weight',q('RR-W2','The two carboxylate contributors exchange identical oxygens. Does one dominate the other?',[f('a','Answer',['no','equal','equivalent','same'],'RANK_EQUIVALENT')],['ranking']))],
concept:[q('RR-C1','When valid contributors differ in octet completion on carbon, which usually matters more: a full octet or minimizing a small formal charge?',[f('a','Priority',['full octet','octet','complete octet'],'RANK_OCTET')]),q('RR-C2','If two contributors are symmetry-equivalent, how should their weights compare?',[f('a','Weights',['equal','same','equivalent'],'RANK_EQUIVALENT')])],
build:[q('RR-B1','Build the ranking: neutral carbonyl contributor vs charge-separated C+ - O-. Which gives carbon a full octet?',[f('a','Contributor',['neutral','neutral carbonyl'],'RANK_OCTET')]),q('RR-B2','Therefore which contributor is larger?',[f('a','Larger contributor',['neutral','neutral carbonyl'],'RANK_OCTET')])],
guided:[q('RR-G1','Guided: two valid contributors both satisfy octets. Form A has no formal charges. Form B has +1 and -1 separated. Which is usually larger?',[f('a','Larger contributor',['a','form a','uncharged','neutral'],'RANK_CHARGE_SEPARATION')],['ranking']),q('RR-G2','Guided: if negative charge must appear in one contributor, is oxygen or carbon usually the better location?',[f('a','Better location',['oxygen','o'],'RANK_ELECTRONEGATIVITY')],['charge-placement'])],
independent:[q('RR-I1','Cold: one valid contributor gives carbon a full octet; another leaves carbon electron-deficient. Which is usually larger?',[f('a','Larger',['full octet contributor','full octet','the one with a full octet'],'RANK_OCTET')],['ranking']),q('RR-I2','Cold: two full-octet contributors differ mainly because one avoids charge separation. Which is usually larger?',[f('a','Larger',['the one without charge separation','uncharged','neutral','less charge separation'],'RANK_CHARGE_SEPARATION')],['ranking']),q('RR-I3','Cold: two valid full-octet forms place -1 on O vs C. Which is generally favored?',[f('a','Favored',['oxygen','o'],'RANK_ELECTRONEGATIVITY')],['charge-placement']),q('RR-I4','Cold: two carboxylate contributors exchange identical oxygens. Relationship of their weights?',[f('a','Weights',['equal','same','equivalent'],'RANK_EQUIVALENT')],['ranking'])],
explanation:{prompt:'Explain a defensible order for ranking valid resonance contributors. Include octet completion, charge separation, electronegativity, and equivalence.',requiredGroups:[['octet'],['charge','separation'],['electronegative','oxygen'],['equivalent','equal']]},
transfer:[q('RR-T1','Transfer: two amide-related contributors are valid. One is neutral; the other is charge-separated but gives all second-row atoms octets. Can the charge-separated form still contribute meaningfully even if it is smaller?',[f('a','Answer',['yes','y'],'RANK_VALIDITY')],['ranking'])],
intervening:q('RR-A1','Different skill: in resonance, do atom identities and sigma-bond connectivity stay fixed?',[f('a','Answer',['yes','y'],'CONNECTIVITY_FIXED')]),
retrieval:[q('RR-R1','Later: what usually outranks reduced charge separation when carbon otherwise lacks an octet?',[f('a','Priority',['full octet','octet completion','octet'],'RANK_OCTET')]),q('RR-R2','Later: symmetry-equivalent contributors have what relative weight?',[f('a','Weight',['equal','same'],'RANK_EQUIVALENT')])],
repairChecks:{RANK_VALIDITY:q('RR-RP1','Repair check: if a hydrogen changes which atom it is attached to, is that resonance?',[f('a','Answer',['no','n'],'RANK_VALIDITY')]),RANK_OCTET:q('RR-RP2','Repair check: for second-row carbon, is a full octet generally more stable than six electrons?',[f('a','Answer',['yes','y'],'RANK_OCTET')]),RANK_CHARGE_SEPARATION:q('RR-RP3','Repair check: all else equal, do we usually prefer less unnecessary charge separation?',[f('a','Answer',['yes','y'],'RANK_CHARGE_SEPARATION')]),RANK_ELECTRONEGATIVITY:q('RR-RP4','Repair check: is negative formal charge generally better on O or C?',[f('a','Atom',['oxygen','o'],'RANK_ELECTRONEGATIVITY')]),RANK_EQUIVALENT:q('RR-RP5','Repair check: symmetry-equivalent contributors have equal or unequal weight?',[f('a','Weight',['equal','same'],'RANK_EQUIVALENT')])},
reteach:{RANK_VALIDITY:'Do not rank until connectivity is confirmed identical. Resonance moves electrons, not atoms.',RANK_OCTET:'For ordinary second-row atoms, complete octets are a major stabilizing factor. A contributor leaving carbon with six electrons is usually smaller than a comparable full-octet form.',RANK_CHARGE_SEPARATION:'When octets are comparable, avoid creating unnecessary opposite formal charges.',RANK_ELECTRONEGATIVITY:'When comparing comparable contributors, negative charge is better supported on a more electronegative atom such as oxygen.',RANK_EQUIVALENT:'If symmetry exchanges identical atoms and produces the other contributor, neither is larger. They contribute equally.'}});

L['resonance-hybrid']=lesson({id:'resonance-hybrid',skillId:'u2.c2.resonance_hybrid',title:'Resonance Hybrid and Partial Bonding',chapter:'Chapter 2.7-2.13',priority:1,prerequisites:['rank-resonance'],requiredTags:['hybrid','partial-bond','partial-charge'],objective:'Interpret the resonance hybrid as the real electron distribution and connect contributor weights to partial bonds and partial charges.',
probe:[q('RH-P1','Is a molecule rapidly switching back and forth between resonance contributors as separate structures?',[f('a','Answer',['no','n'],'HYBRID_NOT_SWITCHING')],['hybrid']),q('RH-P2','In a carboxylate ion with two equivalent contributors, are the two C-O bonds equal in the real resonance hybrid?',[f('a','Answer',['yes','y'],'HYBRID_EQUIVALENT_BONDS')],['partial-bond'])],
watch:[w('The hybrid is the real structure','Contributors are bookkeeping drawings. The real molecule has one electron distribution described by all valid contributors together. It does not physically jump between drawings.','contributors -> one hybrid',q('RH-W1','Are resonance arrows equilibrium arrows between isolable species?',[f('a','Answer',['no','n'],'HYBRID_NOT_SWITCHING')])),w('Contributor weights show up as partial bond and charge character','Equivalent contributors can make bonds equal. Unequal contributors still influence the hybrid, but the larger contributor contributes more to the real electron distribution.','larger contributor -> more character in hybrid',q('RH-W2','If two carboxylate contributors are equivalent, should one C-O bond be permanently single and the other permanently double?',[f('a','Answer',['no','n'],'HYBRID_EQUIVALENT_BONDS')],['partial-bond']))],
concept:[q('RH-C1','What is physically real: a set of contributors switching, or one resonance hybrid?',[f('a','Real structure',['one resonance hybrid','resonance hybrid','hybrid'],'HYBRID_NOT_SWITCHING')]),q('RH-C2','Equivalent contributors generally produce equivalent bond lengths in the hybrid. Yes or no?',[f('a','Answer',['yes','y'],'HYBRID_EQUIVALENT_BONDS')])],
build:[q('RH-B1','Build the carboxylate hybrid: the pi bond is drawn to either oxygen in equivalent contributors. In the hybrid, is pi bonding delocalized over both C-O bonds?',[f('a','Answer',['yes','y'],'HYBRID_PARTIAL_BOND')]),q('RH-B2','Therefore are the two C-O bonds intermediate between a pure single and pure double bond?',[f('a','Answer',['yes','y'],'HYBRID_PARTIAL_BOND')])],
guided:[q('RH-G1','Guided: if negative charge is equivalent on either oxygen in two equal contributors, is negative charge delocalized over both oxygens in the hybrid?',[f('a','Answer',['yes','y'],'HYBRID_PARTIAL_CHARGE')],['partial-charge']),q('RH-G2','Guided: one contributor is much larger than another. Should the hybrid resemble the larger contributor more strongly?',[f('a','Answer',['yes','y'],'HYBRID_WEIGHT')],['hybrid'])],
independent:[q('RH-I1','Cold: does a resonance hybrid contain partial bonding that may not appear as an integer bond order in a single contributor?',[f('a','Answer',['yes','y'],'HYBRID_PARTIAL_BOND')],['partial-bond']),q('RH-I2','Cold: in equivalent carboxylate contributors, are both C-O bonds the same length in the hybrid?',[f('a','Answer',['yes','y'],'HYBRID_EQUIVALENT_BONDS')],['partial-bond']),q('RH-I3','Cold: if one contributor is much more important than another, does the hybrid weight them equally?',[f('a','Answer',['no','n'],'HYBRID_WEIGHT')],['hybrid']),q('RH-I4','Cold: is resonance delocalization a statement about electron distribution rather than atoms moving?',[f('a','Answer',['yes','y'],'HYBRID_NOT_SWITCHING')],['hybrid'])],
explanation:{prompt:'Explain why resonance contributors are not separate molecules in equilibrium. Then explain how equivalent contributors affect bond lengths and charge distribution in the hybrid.',requiredGroups:[['hybrid','real'],['not','switch'],['equal','equivalent'],['bond','charge','delocalized']]},
transfer:[q('RH-T1','Transfer: benzene can be drawn with alternating double bonds. In the real molecule, are the six C-C bonds equivalent?',[f('a','Answer',['yes','y'],'HYBRID_EQUIVALENT_BONDS')],['hybrid'])],intervening:q('RH-A1','Different skill: can a curved-arrow tail start at a plus sign?',[f('a','Answer',['no','n'],'ARROW_SOURCE')]),retrieval:[q('RH-R1','Later: the real resonance structure is called the what?',[f('a','Term',['resonance hybrid','hybrid'],'HYBRID_NOT_SWITCHING')]),q('RH-R2','Later: equivalent contributors make related bond/charge features equal or unequal in the hybrid?',[f('a','Relationship',['equal','equivalent'],'HYBRID_EQUIVALENT_BONDS')])],repairChecks:{HYBRID_NOT_SWITCHING:q('RH-RP1','Repair check: do atoms physically move when we redraw resonance contributors?',[f('a','Answer',['no','n'],'HYBRID_NOT_SWITCHING')]),HYBRID_EQUIVALENT_BONDS:q('RH-RP2','Repair check: if two contributors are equivalent by symmetry, should the corresponding hybrid bonds be equivalent?',[f('a','Answer',['yes','y'],'HYBRID_EQUIVALENT_BONDS')]),HYBRID_PARTIAL_BOND:q('RH-RP3','Repair check: delocalized pi bonding can give a bond partial double-bond character. Yes or no?',[f('a','Answer',['yes','y'],'HYBRID_PARTIAL_BOND')]),HYBRID_PARTIAL_CHARGE:q('RH-RP4','Repair check: if charge is equivalent on two atoms across equal contributors, can the hybrid share that charge over both atoms?',[f('a','Answer',['yes','y'],'HYBRID_PARTIAL_CHARGE')]),HYBRID_WEIGHT:q('RH-RP5','Repair check: should a larger contributor influence the hybrid more than a much smaller one?',[f('a','Answer',['yes','y'],'HYBRID_WEIGHT')])},reteach:{HYBRID_NOT_SWITCHING:'The resonance hybrid is the actual electronic structure. Contributors are alternate Lewis-style drawings used to describe it.',HYBRID_EQUIVALENT_BONDS:'Equal contributors place the pi bond or charge in symmetry-equivalent positions, so the related bonds/charges are equivalent in the hybrid.',HYBRID_PARTIAL_BOND:'When pi electron density is spread across more than one bond, each affected bond can have partial multiple-bond character.',HYBRID_PARTIAL_CHARGE:'Equivalent charge placement in contributors means charge is delocalized in the hybrid rather than permanently sitting on one atom.',HYBRID_WEIGHT:'The hybrid is a weighted blend. More stable contributors have more influence.'}});

L['localized-delocalized']=lesson({id:'localized-delocalized',skillId:'u2.c2.localized_delocalized',title:'Localized vs Delocalized Lone Pairs',chapter:'Chapter 2.7-2.13',priority:1,prerequisites:['resonance-hybrid'],requiredTags:['lone-pair','adjacency','conjugation'],objective:'Decide whether a lone pair can participate in resonance by checking adjacency, orbital overlap, and whether a valid contributor can be drawn without moving atoms.',
probe:[q('LD-P1','A lone pair on nitrogen is directly adjacent to a carbonyl carbon. Can that lone pair potentially delocalize into the carbonyl if a valid contributor can be drawn?',[f('a','Answer',['yes','y'],'LONE_PAIR_ADJACENCY')],['lone-pair']),q('LD-P2','A lone pair is separated from the nearest pi bond by an sp3 carbon. Is direct resonance delocalization across that interrupted path usually available?',[f('a','Answer',['no','n'],'CONJUGATION_INTERRUPTED')],['adjacency'])],
watch:[w('Adjacency is the first screen','A lone pair can only participate in ordinary resonance when it is next to a compatible p orbital or pi system. An intervening saturated sp3 center usually breaks the conjugated pathway.','lone pair next to pi system',q('LD-W1','If a lone pair is directly next to a carbonyl, is resonance participation possible in principle?',[f('a','Answer',['yes','y'],'LONE_PAIR_ADJACENCY')])),w('Then test with a valid curved-arrow move','Do not label a lone pair delocalized just because it looks close. Draw the electron move. The sigma skeleton must stay fixed and octet/charge bookkeeping must remain chemically valid.','adjacency + valid electron move',q('LD-W2','If the only way to move the lone pair requires moving an atom, is that resonance?',[f('a','Answer',['no','n'],'LONE_PAIR_VALIDITY')]))],
concept:[q('LD-C1','Which normally breaks conjugation: an intervening sp3 carbon or an adjacent p orbital?',[f('a','Breaker',['sp3 carbon','sp3','saturated carbon'],'CONJUGATION_INTERRUPTED')]),q('LD-C2','A lone pair that participates in more than one valid contributor is localized or delocalized?',[f('a','Type',['delocalized'],'LONE_PAIR_DELOCALIZED')])],
build:[q('LD-B1','Build the amide check: nitrogen lone pair is directly adjacent to C=O. Does adjacency pass the first screen?',[f('a','Answer',['yes','y'],'LONE_PAIR_ADJACENCY')]),q('LD-B2','Can that lone pair form a C=N pi bond while the C=O pi pair moves to oxygen, preserving connectivity?',[f('a','Answer',['yes','y'],'LONE_PAIR_VALIDITY')])],
guided:[q('LD-G1','Guided: an ether oxygen lone pair is next to a simple alkane carbon with no adjacent pi system or empty p orbital. Is that lone pair delocalized by ordinary resonance through that carbon?',[f('a','Answer',['no','n'],'CONJUGATION_INTERRUPTED')],['adjacency']),q('LD-G2','Guided: a phenoxide lone pair can be drawn into the aromatic pi system in valid contributors. Localized or delocalized?',[f('a','Type',['delocalized'],'LONE_PAIR_DELOCALIZED')],['lone-pair'])],
independent:[q('LD-I1','Cold: amide nitrogen lone pair adjacent to C=O. Localized only, or resonance-delocalized?',[f('a','Type',['delocalized','resonance delocalized'],'LONE_PAIR_DELOCALIZED')],['lone-pair']),q('LD-I2','Cold: lone pair separated from C=C by CH2. Directly conjugated through that CH2?',[f('a','Answer',['no','n'],'CONJUGATION_INTERRUPTED')],['adjacency']),q('LD-I3','Cold: phenoxide negative charge can appear at multiple ring positions in valid contributors. Localized or delocalized?',[f('a','Type',['delocalized'],'LONE_PAIR_DELOCALIZED')],['lone-pair']),q('LD-I4','Cold: if a proposed lone-pair resonance move changes sigma-bond connectivity, is it valid resonance?',[f('a','Answer',['no','n'],'LONE_PAIR_VALIDITY')],['conjugation'])],
explanation:{prompt:'Explain how you decide whether a lone pair is localized or delocalized. Include adjacency, conjugation, a valid electron move, and fixed atom connectivity.',requiredGroups:[['adjacent','next'],['pi','p orbital','conjug'],['electron','arrow'],['connectivity','sigma']]},transfer:[q('LD-T1','Transfer: an aniline nitrogen lone pair is attached directly to an aromatic ring. Can it be resonance-delocalized into the ring?',[f('a','Answer',['yes','y'],'LONE_PAIR_DELOCALIZED')],['conjugation'])],intervening:q('LD-A1','Different skill: are equivalent resonance contributors equal in weight?',[f('a','Answer',['yes','y'],'RANK_EQUIVALENT')]),retrieval:[q('LD-R1','Later: what structural feature most often interrupts direct conjugation between a lone pair and a pi bond?',[f('a','Feature',['sp3 carbon','saturated sp3 carbon','sp3'],'CONJUGATION_INTERRUPTED')]),q('LD-R2','Later: if a lone pair appears in valid contributors over several atoms, it is localized or delocalized?',[f('a','Type',['delocalized'],'LONE_PAIR_DELOCALIZED')])],repairChecks:{LONE_PAIR_ADJACENCY:q('LD-RP1','Repair check: is direct adjacency to a compatible pi/p system a first requirement for common lone-pair resonance?',[f('a','Answer',['yes','y'],'LONE_PAIR_ADJACENCY')]),CONJUGATION_INTERRUPTED:q('LD-RP2','Repair check: does an sp3 carbon between a lone pair and pi bond usually interrupt direct conjugation?',[f('a','Answer',['yes','y'],'CONJUGATION_INTERRUPTED')]),LONE_PAIR_VALIDITY:q('LD-RP3','Repair check: may a resonance move change which atoms are sigma-bonded to each other?',[f('a','Answer',['no','n'],'LONE_PAIR_VALIDITY')]),LONE_PAIR_DELOCALIZED:q('LD-RP4','Repair check: if the same electron pair is represented in multiple valid contributor positions, is it delocalized?',[f('a','Answer',['yes','y'],'LONE_PAIR_DELOCALIZED')])},reteach:{LONE_PAIR_ADJACENCY:'Start by asking whether the lone-pair atom is directly adjacent to a compatible p orbital or pi bond.',CONJUGATION_INTERRUPTED:'A saturated sp3 center usually breaks continuous p-orbital overlap, so resonance cannot pass directly through it.',LONE_PAIR_VALIDITY:'Prove delocalization by drawing a valid electron move with the atom/sigma skeleton fixed.',LONE_PAIR_DELOCALIZED:'If valid contributors place the same electron density over multiple adjacent positions, the lone pair is delocalized rather than confined to one atom.'}});

L['arrow-reasoning']=lesson({id:'arrow-reasoning',skillId:'u2.c2.arrow_reasoning',title:'Curved-Arrow Resonance Reasoning',chapter:'Chapter 2.7-2.13',priority:1,prerequisites:['localized-delocalized'],requiredTags:['arrow-source','arrow-destination','octet'],objective:'Choose valid resonance arrow sources and destinations, preserve connectivity, and repair octet or charge-bookkeeping failures.',
probe:[q('AR-P1','Where must a curved-arrow tail begin in resonance: at an electron pair or at a positive charge symbol?',[f('a','Tail begins at',['electron pair','lone pair or pi bond','lone pair','pi bond'],'ARROW_SOURCE')],['arrow-source']),q('AR-P2','A lone pair forms a new pi bond to an adjacent atom that already has an octet. What may need to move at the same time?',[f('a','Move',['existing pi bond','old pi pair','pi electrons'],'ARROW_OCTET')],['octet'])],
watch:[w('Arrow tails start at electrons','A curved arrow shows an electron pair moving. The tail begins on a lone pair or pi bond. A plus sign is electron deficiency, not an electron source.','tail = electrons',q('AR-W1','Can the tail of a two-electron curved arrow begin on a plus sign?',[f('a','Answer',['no','n'],'ARROW_SOURCE')])),w('One new bond may require one old bond to move','If a lone pair forms a new pi bond to an atom that already has an octet, move an adjacent pi pair away in the same resonance step so the atom does not exceed an octet.','new pi in -> old pi out',q('AR-W2','If carbon already has an octet and receives a new pi bond, should an old pi pair often move away simultaneously?',[f('a','Answer',['yes','y'],'ARROW_OCTET')]))],
concept:[q('AR-C1','Arrow head shows where the electron pair ends up. Yes or no?',[f('a','Answer',['yes','y'],'ARROW_DESTINATION')]),q('AR-C2','May resonance arrows break a sigma bond and reconnect the atom somewhere else?',[f('a','Answer',['no','n'],'ARROW_CONNECTIVITY')])],
build:[q('AR-B1','Build the formate move: the electron source is a lone pair on the singly bonded O-. Where should that pair go first?',[f('a','Destination',['into the c-o bond','c-o bond','form c=o','carbon oxygen bond'],'ARROW_DESTINATION')]),q('AR-B2','What old electron pair must move off the existing C=O to preserve carbon octet?',[f('a','Pair',['c=o pi pair','old pi pair','carbonyl pi pair'],'ARROW_OCTET')])],
guided:[q('AR-G1','Guided: allyl anion lone pair sits next to C=C. Does the lone pair move into the adjacent bond to make a new pi bond?',[f('a','Answer',['yes','y'],'ARROW_DESTINATION')],['arrow-destination']),q('AR-G2','Guided: after that new pi bond forms, where must the old alkene pi pair move?',[f('a','Destination',['onto the terminal carbon','terminal carbon','onto carbon'],'ARROW_OCTET')],['octet'])],
independent:[q('AR-I1','Cold: curved-arrow tail starts at what kind of thing?',[f('a','Source',['electron pair','lone pair','pi bond','lone pair or pi bond'],'ARROW_SOURCE')],['arrow-source']),q('AR-I2','Cold: curved-arrow head points to where the electrons will be. Yes or no?',[f('a','Answer',['yes','y'],'ARROW_DESTINATION')],['arrow-destination']),q('AR-I3','Cold: may a resonance arrow sequence change sigma connectivity?',[f('a','Answer',['no','n'],'ARROW_CONNECTIVITY')]),q('AR-I4','Cold: if a new pi bond would give carbon ten electrons, what must be repaired?',[f('a','Repair',['move an old pi pair','move pi electrons','remove an existing pi pair','old pi bond must move'],'ARROW_OCTET')],['octet'])],
explanation:{prompt:'Explain how you validate a resonance curved-arrow step. Include arrow source, arrow destination, fixed connectivity, and octet bookkeeping.',requiredGroups:[['tail','source','electron'],['head','destination'],['connectivity','sigma'],['octet']]},transfer:[q('AR-T1','Transfer: a nitrogen lone pair next to C=O forms C=N. What must happen to the C=O pi pair in the same resonance move?',[f('a','Move',['move to oxygen','onto oxygen','move the pi pair to o','oxygen'],'ARROW_OCTET')],['octet'])],intervening:q('AR-A1','Different skill: the real structure represented by resonance contributors is called the what?',[f('a','Term',['resonance hybrid','hybrid'],'HYBRID_NOT_SWITCHING')]),retrieval:[q('AR-R1','Later: may the arrow tail start at an electron-poor plus sign?',[f('a','Answer',['no','n'],'ARROW_SOURCE')]),q('AR-R2','Later: what skeleton must remain fixed across resonance contributors?',[f('a','Skeleton',['sigma skeleton','atom connectivity','sigma-bond connectivity','connectivity'],'ARROW_CONNECTIVITY')])],repairChecks:{ARROW_SOURCE:q('AR-RP1','Repair check: which contains the moving electrons, a lone pair or a plus sign?',[f('a','Source',['lone pair'],'ARROW_SOURCE')]),ARROW_DESTINATION:q('AR-RP2','Repair check: does the arrow head mark where electrons start or where they end?',[f('a','Meaning',['where they end','destination','end'],'ARROW_DESTINATION')]),ARROW_CONNECTIVITY:q('AR-RP3','Repair check: must atom/sigma connectivity remain unchanged during resonance?',[f('a','Answer',['yes','y'],'ARROW_CONNECTIVITY')]),ARROW_OCTET:q('AR-RP4','Repair check: if a new pi bond would overfill carbon, should another electron pair move away?',[f('a','Answer',['yes','y'],'ARROW_OCTET')])},reteach:{ARROW_SOURCE:'Find actual electrons first. A curved-arrow tail belongs on a lone pair or pi bond, never on a positive-charge symbol.',ARROW_DESTINATION:'The head points to the atom or bond that receives the moving electron pair.',ARROW_CONNECTIVITY:'Resonance changes electron placement only. Atom identities and the sigma skeleton stay fixed.',ARROW_OCTET:'When forming a new pi bond to an already-octet atom, move an existing adjacent pi pair away in the same step.'}});

L['resonance-transfer']=lesson({id:'resonance-transfer',skillId:'u2.c2.resonance_transfer',title:'Resonance Transfer in Unfamiliar Structures',chapter:'Chapter 2.7-2.13',priority:2,prerequisites:['rank-resonance','resonance-hybrid','localized-delocalized','arrow-reasoning'],requiredTags:['transfer','ranking','hybrid'],objective:'Integrate validity, arrow pushing, ranking, and hybrid interpretation in unfamiliar allylic, aromatic, carbonyl, and heteroatom systems.',
probe:[q('RT-P1','An unfamiliar structure has a lone pair directly adjacent to a pi bond. What should you test first to see whether resonance is possible?',[f('a','First test',['draw a valid electron move','valid curved arrow move','check adjacency and draw resonance','try a valid resonance contributor'],'TRANSFER_FIRST_STEP')],['transfer']),q('RT-P2','After generating valid contributors, what must you do before predicting the hybrid?',[f('a','Next step',['rank the contributors','rank contributors','compare contributor stability'],'TRANSFER_RANK')],['ranking'])],
watch:[w('Use one repeatable sequence','For a new structure: freeze the atom/sigma skeleton, locate movable lone pairs or pi bonds, draw a valid electron move, recalculate formal charges, rank contributors, then translate the weights into the resonance hybrid.','freeze -> move -> check -> rank -> hybrid',q('RT-W1','In this sequence, does contributor ranking come before or after validating the electron move?',[f('a','Order',['after','after validation','after validating'],'TRANSFER_FIRST_STEP')])),w('Transfer means the drawing can look different while the logic stays the same','Do not memorize acetate, allyl, amide, and benzene as separate tricks. They all use the same invariants: electrons move, atoms do not; octets and charge are checked; contributor weights determine the hybrid.','same rules, new surface',q('RT-W2','If the molecule looks unfamiliar, should the sigma-connectivity rule change?',[f('a','Answer',['no','n'],'TRANSFER_INVARIANT')]))],
concept:[q('RT-C1','What stays fixed in every valid resonance contributor?',[f('a','Fixed feature',['atom connectivity','sigma skeleton','sigma-bond connectivity','atoms'],'TRANSFER_INVARIANT')]),q('RT-C2','What determines how strongly a valid contributor shapes the hybrid?',[f('a','Factor',['its stability','contributor stability','relative stability','weight'],'TRANSFER_RANK')])],
build:[q('RT-B1','Build the sequence: after identifying an adjacent lone pair, do you move an atom or move electrons?',[f('a','Move',['electrons','electron pair'],'TRANSFER_INVARIANT')]),q('RT-B2','After drawing the new contributor, should you check formal charges and octets before accepting it?',[f('a','Answer',['yes','y'],'TRANSFER_VALIDATION')])],
guided:[q('RT-G1','Guided: a lone pair is adjacent to an aromatic pi system. You can draw a valid contributor without moving atoms. Is delocalization possible?',[f('a','Answer',['yes','y'],'TRANSFER_FIRST_STEP')],['transfer']),q('RT-G2','Guided: two valid contributors are not equivalent; one has a full carbon octet and less charge separation. Which should influence the hybrid more?',[f('a','Answer',['the more stable contributor','larger contributor','the full octet contributor'],'TRANSFER_RANK')],['ranking'])],
independent:[q('RT-I1','Cold transfer: an unfamiliar ion has several drawings. One changes where H is attached. Is that drawing resonance?',[f('a','Answer',['no','n'],'TRANSFER_INVARIANT')],['transfer']),q('RT-I2','Cold transfer: a lone pair is adjacent to C=C and a valid arrow sequence can move it into conjugation. Is the pair potentially delocalized?',[f('a','Answer',['yes','y'],'TRANSFER_FIRST_STEP')],['transfer']),q('RT-I3','Cold transfer: after drawing contributors, what must you compare to estimate their weights?',[f('a','Compare',['stability','octets charges electronegativity','contributor stability'],'TRANSFER_RANK')],['ranking']),q('RT-I4','Cold transfer: if two contributors are equivalent, should the hybrid favor one side?',[f('a','Answer',['no','n'],'TRANSFER_RANK')],['hybrid'])],
explanation:{prompt:'Give the full resonance workflow you would use on an unfamiliar structure, from first inspection through the hybrid.',requiredGroups:[['connectivity','sigma'],['lone pair','pi','electrons'],['formal charge','octet'],['rank','stability'],['hybrid']]},transfer:[q('RT-T1','Transfer: an unfamiliar conjugated anion has three valid contributors. Two are equivalent and one is less stable. Will the hybrid be described equally by all three?',[f('a','Answer',['no','n'],'TRANSFER_RANK')],['transfer'])],intervening:q('RT-A1','Different skill: a lower pKa means a stronger or weaker acid?',[f('a','Acid strength',['stronger','stronger acid'],'PKA_DIRECTION')]),retrieval:[q('RT-R1','Later: what is the first invariant before any resonance move?',[f('a','Invariant',['same atom connectivity','sigma skeleton fixed','connectivity fixed','atoms stay fixed'],'TRANSFER_INVARIANT')]),q('RT-R2','Later: after contributor validation and ranking, what final model describes the real molecule?',[f('a','Model',['resonance hybrid','hybrid'],'TRANSFER_RANK')])],repairChecks:{TRANSFER_FIRST_STEP:q('RT-RP1','Repair check: before drawing resonance, should you identify an actual adjacent electron source such as a lone pair or pi bond?',[f('a','Answer',['yes','y'],'TRANSFER_FIRST_STEP')]),TRANSFER_INVARIANT:q('RT-RP2','Repair check: can atom connectivity change between resonance contributors?',[f('a','Answer',['no','n'],'TRANSFER_INVARIANT')]),TRANSFER_VALIDATION:q('RT-RP3','Repair check: after moving electrons, should formal charges and octets be checked?',[f('a','Answer',['yes','y'],'TRANSFER_VALIDATION')]),TRANSFER_RANK:q('RT-RP4','Repair check: do more stable contributors have more or less influence on the hybrid?',[f('a','Influence',['more','greater','more influence'],'TRANSFER_RANK')])},reteach:{TRANSFER_FIRST_STEP:'On a new molecule, first locate a genuine electron source next to a compatible pi/p system and test whether a valid resonance move can be drawn.',TRANSFER_INVARIANT:'Freeze the atom identities and sigma skeleton. If those change, stop: it is not resonance.',TRANSFER_VALIDATION:'After every electron move, recalculate formal charges and check octets and total charge before accepting the contributor.',TRANSFER_RANK:'Valid contributors do not all count equally. Rank them, then let the larger contributors shape the hybrid more strongly.'}});

var ORDER=Object.freeze(['rank-resonance','resonance-hybrid','localized-delocalized','arrow-reasoning','resonance-transfer']);
var LESSONS=Object.freeze(L);
var CHECKPOINTS=Object.freeze([
 Object.freeze({id:'C2-D1',skill:'rank-resonance',task:'Rank three fresh resonance contributors and justify the order using octet, charge separation, and electronegativity.',grading:'structured ranking plus explanation'}),
 Object.freeze({id:'C2-D2',skill:'resonance-hybrid',task:'Select the hybrid bond/charge pattern implied by equivalent contributors.',grading:'structured hybrid selection'}),
 Object.freeze({id:'C2-D3',skill:'localized-delocalized',task:'Mark a lone pair as localized or delocalized after checking adjacency and a valid electron move.',grading:'structured classification'}),
 Object.freeze({id:'C2-D4',skill:'arrow-reasoning',task:'Select arrow source, destination, and any required companion pi-electron move.',grading:'structured arrow-path selection; no arbitrary handwriting grading'}),
 Object.freeze({id:'C2-D5',skill:'resonance-transfer',task:'Solve an unfamiliar resonance case from validity through hybrid interpretation.',grading:'structured multistep reasoning'})
]);
var META=Object.freeze({unit:'Unit 2',chapter:'Chapter 2.7-2.13',title:'Resonance Continuation',status:'authored-not-live',foundationRoute:'../../../day3/'});
function lessonById(id){return LESSONS[id]||null;}function lessons(){return ORDER.map(function(id){return LESSONS[id];});}function lessonIds(){return ORDER.slice();}
return Object.freeze({META:META,LESSONS:LESSONS,ORDER:ORDER,PRODUCTION_CHECKPOINTS:CHECKPOINTS,lesson:lessonById,lessons:lessons,lessonIds:lessonIds});
});