(function(root){'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function box(title,body,note){return'<figure class="chem-visual"><figcaption>'+e(title)+'</figcaption>'+body+(note?'<div class="visual-note">'+e(note)+'</div>':'')+'</figure>';}
function stereo(){return box('Relationship decision tree','<div class="three-panel"><div class="panel favored"><b>1. Connectivity</b><br>different = constitutional</div><div class="panel"><b>2. Same connectivity</b><br>compare every stereocenter</div><div class="panel"><b>3. Result</b><br>all invert = enantiomers<br>some invert = diastereomers</div></div>','Do not compare R/S labels until atom connectivity is confirmed.');}
function configuration(){return box('Configuration checklist','<div class="three-panel"><div class="panel"><b>R/S</b><br>rank 1-4<br>place 4 in space</div><div class="panel"><b>Fischer</b><br>horizontal = toward<br>vertical = away</div><div class="panel"><b>E/Z</b><br>rank each alkene carbon<br>compare high priorities</div></div>','R/S and E/Z are rules about priority and geometry, not how the drawing happens to sit on the page.');}
function optical(){return box('Optical mixture equations','<div class="two-panel"><div class="panel favored"><b>Specific rotation</b><br>[α] = αobs / (l × c)</div><div class="panel"><b>Enantiomeric excess</b><br>ee = major% - minor%<br>major = (100 + ee)/2</div></div>','R/S configuration does not predict the sign of optical rotation.');}
function resonance(){return box('Resonance workflow','<div class="factor-grid"><div class="factor"><b>1</b>Freeze atom connectivity</div><div class="factor"><b>2</b>Move real electron pairs</div><div class="factor"><b>3</b>Check octets and charge</div><div class="factor"><b>4</b>Rank, then build hybrid</div></div>','Equivalent contributors contribute equally; more stable contributors influence the hybrid more.');}
function proton(){return box('Proton transfer plus pKa','<div class="donor-acceptor"><div class="panel donor"><b>Base electron pair</b><br>arrow starts here</div><div class="arrow-mid">→ H →</div><div class="panel acceptor"><b>Acid H-A</b><br>old H-A pair returns to A</div></div><div class="pka-key"><span>lower pKa = stronger acid</span><span>higher pKa = weaker acid</span></div>','Conjugate partners differ by one proton.');}
function equilibrium(){return box('Base strength and equilibrium use pKa differently','<div class="two-panel"><div class="panel"><b>Rank bases</b><br>higher conjugate-acid pKa = stronger base</div><div class="panel favored"><b>Predict equilibrium</b><br>favor side with higher-pKa acid = weaker acid</div></div>','Circle one acid on each side before deciding equilibrium direction.');}
function stability(){return box('Conjugate-base stability comparison','<div class="factor-grid"><div class="factor"><b>A</b>Atom</div><div class="factor"><b>R</b>Resonance</div><div class="factor"><b>I</b>Induction</div><div class="factor"><b>O</b>Orbital</div></div><div class="three-panel"><div class="panel"><b>Generate bases</b><br>remove the candidate H</div><div class="panel"><b>Locate charge</b><br>compare stabilization</div><div class="panel favored"><b>Weigh effects</b><br>do not count votes</div></div>','More stable conjugate base generally means stronger parent acid.');}
function reagent(){return box('Reagent choice and Lewis roles','<div class="two-panel"><div class="panel"><b>Proton-transfer screen</b><br>product conjugate acid should have higher pKa</div><div class="panel"><b>Lewis screen</b><br>base donates electron pair<br>acid accepts electron pair</div></div>','After pKa thermodynamics, still check chemical compatibility and side reactions.');}
function byLesson(id){if(id==='stereo-relationships')return stereo();if(id==='configuration-mixed')return configuration();if(id==='optical-mixtures')return optical();if(id==='resonance-mixed')return resonance();if(id==='proton-pka')return proton();if(id==='equilibrium-base')return equilibrium();if(id==='stability-mixed')return stability();if(id==='reagent-lewis')return reagent();return'';}
function item(item,lessonId){return byLesson(lessonId);}
function watch(lessonId,index,lesson){return byLesson(lessonId);}
function repair(code,lessonId,teaching){if(/STEREO_|RS_|EZ_|FISCHER/.test(code))return /STEREO_/.test(code)?stereo():configuration();if(/SPECIFIC_ROTATION|EE_|RS_NOT_SIGN/.test(code))return optical();if(/RANK_|HYBRID_|ARROW_/.test(code))return resonance();if(/PT_|PKA_|CONJUGATE/.test(code))return proton();if(/BASE_CONJUGATE|EQ_|ACID_BASE/.test(code))return equilibrium();if(/ATOM_|STABILITY_|INDUCTION|COMBINED/.test(code))return stability();if(/REAGENT|LEWIS/.test(code))return reagent();return byLesson(lessonId);}
root.Test2Visuals=Object.freeze({item:item,watch:watch,repair:repair});
})(typeof globalThis!=='undefined'?globalThis:this);