(function(root){'use strict';
var VALENCE={H:1,C:4,N:5,O:6,F:7,Cl:7};
function formalCharge(element,nonbondingElectrons,bondOrderSum){var v=VALENCE[element];if(v==null)throw new Error('Unsupported element: '+element);return v-Number(nonbondingElectrons)-Number(bondOrderSum);}
function parseNumber(v){var s=String(v==null?'':v).trim().replace(/−/g,'-');if(!s)return NaN;var n=Number(s);return Number.isFinite(n)?n:NaN;}
function parseCharge(v){var s=String(v==null?'':v).trim().toLowerCase().replace(/−/g,'-').replace(/\s+/g,' ');if(!s)return NaN;if(/^\+?0(?:\.0+)?$/.test(s))return 0;var m=s.match(/^(?:positive|plus)\s*([0-9]+(?:\.[0-9]+)?)$/);if(m)return Number(m[1]);m=s.match(/^(?:negative|minus)\s*([0-9]+(?:\.[0-9]+)?)$/);if(m)return-Number(m[1]);var n=Number(s);return Number.isFinite(n)?n:NaN;}
function chargeText(n){n=Number(n);return n>0?'+'+n:String(n);}
function sumCharges(values){return(values||[]).reduce(function(a,b){return a+Number(b||0);},0);}
function diagnose(item,answer){answer=answer||{};var checks=[['V',parseNumber(answer.V),item.V],['N',parseNumber(answer.N),item.N],['B',parseNumber(answer.B),item.B],['FC',parseCharge(answer.FC),item.FC]];for(var i=0;i<checks.length;i++)if(checks[i][1]!==checks[i][2])return checks[i][0];return null;}
function masteryCreditAllowed(helpTier,priorWrong){return Number(helpTier||0)===0&&!priorWrong;}
function sufficientEvidence(records){records=records||[];var clean=records.filter(function(r){return r.correct&&r.clean;});return{met:clean.length>=3&&clean.some(function(r){return r.tags&&r.tags.indexOf('charged')>=0;})&&clean.some(function(r){return r.tags&&r.tags.indexOf('multiple')>=0;}),cleanCount:clean.length,charged:clean.some(function(r){return r.tags&&r.tags.indexOf('charged')>=0;}),multiple:clean.some(function(r){return r.tags&&r.tags.indexOf('multiple')>=0;})};}
var GATE_A=[{id:'GA1',prompt:'An oxygen is drawn with two lone pairs. How many nonbonding electrons are shown on oxygen?',answer:4},{id:'GA2',prompt:'A nitrogen has three single bonds. What is its total bond order?',answer:3}];
var GATE_B=[{id:'GB1',prompt:'Three lone pairs contain how many nonbonding electrons?',answer:6},{id:'GB2',prompt:'One double bond plus one single bond gives what total bond order?',answer:3}];
var LESSONS=[
 {title:'Formal charge is bookkeeping',body:'Pretend each covalent bond is split evenly. An atom gets all of its own lone-pair electrons and one electron from each bond line. Formal charge compares that bookkeeping total with the neutral atom’s usual valence-electron count.',note:'Formal charge is not the same as partial charge and does not mean the atom literally carries that full ionic charge in every molecule.'},
 {title:'Build the rule from electron ownership',body:'Full form: formal charge = valence electrons − nonbonding electrons − one-half of bonding electrons. Since half of the bonding electrons equals the total bond order attached to the atom, the working shortcut is FC = V − N − B.',note:'V = neutral-atom valence electrons. N = nonbonding electrons, not lone pairs. B = total bond order: single 1, double 2, triple 3.'},
 {title:'Worked example: carbon in methane',body:'Carbon starts with 4 valence electrons. It has 0 nonbonding electrons and 4 single bonds. FC = 4 − 0 − 4 = 0.',note:'Why: for bookkeeping, carbon owns one electron from each of its four C–H bonds, so it still owns four electrons.'},
 {title:'Worked example: oxygen in hydronium',body:'In H₃O⁺, oxygen has 6 valence electrons, one lone pair = 2 nonbonding electrons, and 3 single bonds. FC = 6 − 2 − 3 = +1.',note:'The three hydrogens each have formal charge 0, so the formal charges add to +1, matching H₃O⁺.'},
 {title:'Always do the sum check',body:'After assigning formal charge to every atom, add the signed charges. A neutral molecule must sum to 0. An ion must sum to the written ion charge.',note:'The sum check is an error detector. If the total is wrong, at least one atom needs to be rechecked.'}
];
var GUIDED={id:'G1',element:'O',context:'Guided: oxygen in OH⁻ has three lone pairs and one O–H single bond.',V:6,N:6,B:1,FC:-1,tags:['charged']};
var ITEMS=[
 {id:'FC-I1',element:'N',context:'Nitrogen in NH₄⁺: four single bonds, no lone pairs.',V:5,N:0,B:4,FC:1,tags:['charged']},
 {id:'FC-I2',element:'O',context:'Oxygen in a carbonyl: one double bond, two lone pairs.',V:6,N:4,B:2,FC:0,tags:['multiple']},
 {id:'FC-I3',element:'C',context:'Carbon with three single bonds and one lone pair.',V:4,N:2,B:3,FC:-1,tags:['charged']},
 {id:'FC-I4',element:'N',context:'Nitrogen with three single bonds and one lone pair.',V:5,N:2,B:3,FC:0,tags:['neutral']},
 {id:'FC-I5',element:'O',context:'Oxygen with one double bond, one single bond, and one lone pair.',V:6,N:2,B:3,FC:1,tags:['multiple','charged']},
 {id:'FC-I6',element:'C',context:'Carbon with one triple bond, one single bond, and no lone pairs.',V:4,N:0,B:4,FC:0,tags:['multiple']}
];
var TRANSFERS=[
 {id:'T1',title:'Fresh transfer: methylammonium, CH₃NH₃⁺',body:'Carbon is bonded to three H and to N. Nitrogen is bonded to carbon and three H and has no lone pair.',fields:{carbon:0,nitrogen:1,total:1},explain:{numbers:['5','4'],charge:1,needsZeroNonbonding:true},help:'Focus on nitrogen: V = 5, N = 0, B = 4. Carbon has four bonds and no lone pairs.'},
 {id:'T2',title:'Fresh transfer: NH₂⁻',body:'Nitrogen is bonded to two H and has two lone pairs.',fields:{nitrogen:-1,total:-1},explain:{numbers:['5','4','2'],charge:-1},help:'Two lone pairs are 4 nonbonding electrons. Nitrogen has two single bonds.'}
];
function explanationLooksRight(text,transfer){var s=String(text||'').toLowerCase().replace(/−/g,'-');if(s.length<12)return false;var nums=transfer.explain.numbers.every(function(n){return s.indexOf(n)>=0;});var hasValence=/valence|starts? with|\bv\s*=/.test(s);var hasNonbond=/nonbond|lone pair|\bn\s*=/.test(s);var hasBond=/bond|\bb\s*=/.test(s);var zeroNonbond=!transfer.explain.needsZeroNonbonding||/\bn\s*=\s*0\b|\b0\s+nonbond|no\s+(?:lone\s*pairs?|nonbonding)/.test(s);var charge=transfer.explain.charge>0?/(\+1|positive\s*1|equals?\s*1|=\s*1)/.test(s):/(-1|negative\s*1|minus\s*1)/.test(s);return nums&&hasValence&&hasNonbond&&hasBond&&zeroNonbond&&charge;}
var API={VALENCE:VALENCE,formalCharge:formalCharge,parseCharge:parseCharge,chargeText:chargeText,sumCharges:sumCharges,diagnose:diagnose,masteryCreditAllowed:masteryCreditAllowed,sufficientEvidence:sufficientEvidence,GATE_A:GATE_A,GATE_B:GATE_B,LESSONS:LESSONS,GUIDED:GUIDED,ITEMS:ITEMS,TRANSFERS:TRANSFERS,explanationLooksRight:explanationLooksRight};
if(typeof module!=='undefined'&&module.exports)module.exports=API;
if(typeof document==='undefined')return;

var KEY='dr-merissa-day2-formal-charge-v1',view=document.getElementById('view');
var state={screen:'home',gateRound:'A',lesson:0,records:[],itemIndex:0,itemAttempts:0,itemHelp:0,transferIndex:0,status:'Not started',errors:[]};
try{state=Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'));state.records=state.records||[];state.errors=state.errors||[];}catch(e){}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])});}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}var n=document.getElementById('saveState');if(n)n.textContent='Saved';}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(String(text).replace(/FC/g,'formal charge').replace(/−/g,' minus ').replace(/\+/g,' plus '));u.rate=.84;window.speechSynthesis.speak(u);}
function shell(inner){return '<div class="topline"><div><div class="phase">DAY 2</div><h1>Formal Charge</h1></div><div class="save" id="saveState">Saved</div></div>'+inner;}
function home(){return shell('<div class="hero"><h2>Today you will stop guessing charge from patterns.</h2><p>You will calculate it from the Lewis structure, prove where each number came from, and finish on a fresh whole-structure transfer.</p></div><div class="card"><h3>The one rule for today</h3><div class="formula">FC = V − N − B</div><p class="muted">Meaning comes before memorizing the shortcut.</p><button class="btn" id="startDay2">Start the 2-question foundation check</button></div><div class="card subtle"><b>Day 1 stays intact.</b> This page only checks the Lewis-structure pieces formal charge needs.</div>');}
function gate(){var bank=state.gateRound==='A'?GATE_A:GATE_B;return shell('<div class="card"><div class="phase">Lewis prerequisite check</div><h2>'+(state.gateRound==='A'?'Two quick checks before formal charge':'Fresh check after the reminder')+'</h2><p>No notes for these two. They only test counting lone-pair electrons and bond order.</p>'+bank.map(function(q,i){return '<label class="q"><b>'+esc(q.prompt)+'</b><input class="input gateInput" data-i="'+i+'" inputmode="numeric" autocomplete="off"></label>';}).join('')+'<button class="btn" id="checkGate">Check both</button><div id="gateFeedback"></div></div>');}
function gateRefresh(){return shell('<div class="card teacher"><div class="avatar">DM</div><div><h2>Only the missing counting rule</h2><p><b>One lone pair = 2 nonbonding electrons.</b> Count electrons, not the number of pairs.</p><p><b>Bond order counts lines:</b> single = 1, double = 2, triple = 3.</p><p>I am not restarting Lewis structures. Now prove those two counts on different examples.</p><button class="btn" id="freshGate">Try the fresh 2-question check</button></div></div>');}
function prerequisiteStop(){return shell('<div class="card"><div class="phase badText">Prerequisite needs a short repair</div><h2>Formal charge is waiting on one Lewis-structure counting skill.</h2><p>Go back to the Day 1 Lewis review, repair lone-pair or bond-order counting, then return here. We are not teaching around a missing prerequisite.</p><a class="btn linkBtn" href="../day1/">Open Day 1 Lewis review</a><button class="btn secondary" id="retryGate">Retry this gate later</button></div>');}
function teach(){var x=LESSONS[state.lesson];return shell('<div class="card teacher"><div class="avatar">DM</div><div class="bubble"><b>Dr. Merissa</b><p>'+esc(x.body)+'</p></div></div><div class="card"><div class="phase">Learn • '+(state.lesson+1)+' of '+LESSONS.length+'</div><h2>'+esc(x.title)+'</h2><div class="board">'+esc(x.body)+'</div><div class="warning"><b>Keep this straight</b><p>'+esc(x.note)+'</p></div><div class="actions"><button class="btn secondary" id="lessonBack" '+(state.lesson===0?'disabled':'')+'>← Back</button><button class="btn" id="lessonNext">'+(state.lesson===LESSONS.length-1?'Work one together →':'Next →')+'</button><button class="btn ghost" id="readLesson">Read aloud</button></div></div>');}
function fourFields(item,prefix){prefix=prefix||'';return '<div class="calcGrid"><label>V <span>valence electrons</span><input id="'+prefix+'V" class="input" inputmode="numeric"></label><label>N <span>nonbonding electrons</span><input id="'+prefix+'N" class="input" inputmode="numeric"></label><label>B <span>total bond order</span><input id="'+prefix+'B" class="input" inputmode="numeric"></label><label>FC <span>formal charge</span><input id="'+prefix+'FC" class="input" inputmode="text" placeholder="0, +1, −1..."></label></div>';}
function readFields(prefix){prefix=prefix||'';return{V:document.getElementById(prefix+'V').value,N:document.getElementById(prefix+'N').value,B:document.getElementById(prefix+'B').value,FC:document.getElementById(prefix+'FC').value};}
function guided(){return shell('<div class="card"><div class="phase">Guided practice</div><h2>OH⁻: you fill the bookkeeping</h2><p>'+esc(GUIDED.context)+'</p>'+fourFields(GUIDED,'g')+'<button class="btn" id="checkGuided">Check my four entries</button><div id="guidedFeedback"></div></div><div class="card subtle"><b>This is supported practice.</b> It does not count as independent mastery evidence.</div>');}
function evidenceLine(){var e=sufficientEvidence(state.records);return '<div class="evidence"><b>Independent evidence:</b> '+e.cleanCount+'/3 clean correct &nbsp; • &nbsp; charged '+(e.charged?'✓':'○')+' &nbsp; • &nbsp; multiple bond '+(e.multiple?'✓':'○')+'</div>';}
function practice(){if(state.itemIndex>=ITEMS.length)return developing('The six fresh atom items are complete, but the evidence rule was not met.');var item=ITEMS[state.itemIndex];return shell(evidenceLine()+'<div class="card"><div class="phase">Independent formal charge</div><h2>'+esc(item.context)+'</h2><p>Enter each component. The first wrong component tells us what actually needs repair.</p>'+fourFields(item)+'<div class="actions"><button class="btn" id="checkPractice">Check</button><button class="btn secondary" id="hint">Give me a hint</button><button class="btn secondary" id="firstStep">Give me the first step</button><button class="btn ghost" id="walk">Walk me through it</button></div><div id="practiceFeedback"></div><div id="helpPanel"></div></div>');}
function transfer(){var t=TRANSFERS[state.transferIndex];var fields=t.id==='T1'?'<div class="calcGrid"><label>Carbon FC<input id="tCarbon" class="input" inputmode="text"></label><label>Nitrogen FC<input id="tNitrogen" class="input" inputmode="text"></label><label>Total formal charge<input id="tTotal" class="input" inputmode="text"></label></div>':'<div class="calcGrid"><label>Nitrogen FC<input id="tNitrogen" class="input" inputmode="text"></label><label>Total formal charge<input id="tTotal" class="input" inputmode="text"></label></div>';return shell(evidenceLine()+'<div class="card"><div class="phase">Cold whole-structure transfer</div><h2>'+esc(t.title)+'</h2><p>'+esc(t.body)+'</p>'+fields+'<label class="q"><b>Explain one atom using V, N, and B.</b><textarea id="tExplain" class="input textarea" placeholder="Explain why the charge follows from the structure."></textarea></label><div class="actions"><button class="btn" id="checkTransfer">Check transfer</button><button class="btn secondary" id="transferHelp">I need help — make this practice</button></div><div id="transferFeedback"></div></div>');}
function mastered(){return shell('<div class="card success"><div class="phase">Day 2 cleared</div><h2>Formal charge is independently available.</h2><p>You produced clean atom-level calculations, handled a multiple bond, handled a charged atom, and passed a fresh whole-structure sum check.</p><div class="formula">FC = V − N − B</div><p><b>Next dependency:</b> resonance can now build on this without guessing where charges came from.</p></div>'+summaryCard());}
function developing(reason){return shell('<div class="card"><div class="phase badText">Formal charge: Developing</div><h2>Stop the loop here.</h2><p>'+esc(reason)+'</p><p>The next session should target the specific component errors below, then use fresh problems. Repeating the same six questions is not the plan.</p></div>'+summaryCard());}
function summaryCard(){var e=sufficientEvidence(state.records),counts={V:0,N:0,B:0,FC:0,sum:0};state.errors.forEach(function(x){if(counts[x]!=null)counts[x]++;});return '<div class="card"><h3>Evidence record</h3><p>Clean independent correct: <b>'+e.cleanCount+'</b><br>Supported/repaired correct: <b>'+state.records.filter(function(r){return r.correct&&!r.clean;}).length+'</b></p><div class="chips"><span>V errors '+counts.V+'</span><span>N errors '+counts.N+'</span><span>B errors '+counts.B+'</span><span>FC errors '+counts.FC+'</span><span>Sum errors '+counts.sum+'</span></div></div>';}
function render(){if(!view)return;view.innerHTML=state.screen==='home'?home():state.screen==='gate'?gate():state.screen==='gateRefresh'?gateRefresh():state.screen==='prerequisiteStop'?prerequisiteStop():state.screen==='teach'?teach():state.screen==='guided'?guided():state.screen==='practice'?practice():state.screen==='transfer'?transfer():state.screen==='mastered'?mastered():developing(state.developReason||'More fresh evidence is needed.');bind();save();}
function targetedMessage(code){if(code==='V')return 'Valence count is the first mismatch. Use the neutral atom’s group valence before doing any subtraction.';if(code==='N')return 'Nonbonding-electron count is the first mismatch. Count electrons, not lone pairs: one lone pair contains 2 electrons.';if(code==='B')return 'Bond order is the first mismatch. Single = 1, double = 2, triple = 3.';return 'Your V, N, and B are right. Recompute the signed arithmetic: V − N − B.';}
function bind(){var el;
 if((el=document.getElementById('startDay2')))el.onclick=function(){state.screen='gate';state.gateRound='A';state.status='Checking prerequisite';save();render();};
 if((el=document.getElementById('checkGate')))el.onclick=function(){var bank=state.gateRound==='A'?GATE_A:GATE_B,inputs=document.querySelectorAll('.gateInput'),ok=true;inputs.forEach(function(inp){var i=Number(inp.dataset.i);if(parseNumber(inp.value)!==bank[i].answer)ok=false;});if(ok){state.screen='teach';state.lesson=0;state.status='Learning formal charge';save();render();}else if(state.gateRound==='A'){state.screen='gateRefresh';save();render();}else{state.screen='prerequisiteStop';state.status='Needs Lewis refresh';save();render();}};
 if((el=document.getElementById('freshGate')))el.onclick=function(){state.gateRound='B';state.screen='gate';save();render();};
 if((el=document.getElementById('retryGate')))el.onclick=function(){state.gateRound='A';state.screen='gate';save();render();};
 if((el=document.getElementById('lessonBack')))el.onclick=function(){if(state.lesson>0)state.lesson--;save();render();};
 if((el=document.getElementById('lessonNext')))el.onclick=function(){if(state.lesson<LESSONS.length-1){state.lesson++;save();render();}else{state.screen='guided';state.status='Guided';save();render();}};
 if((el=document.getElementById('readLesson')))el.onclick=function(){var x=LESSONS[state.lesson];speak(x.title+'. '+x.body+'. '+x.note);};
 if((el=document.getElementById('checkGuided')))el.onclick=function(){var a=readFields('g'),code=diagnose(GUIDED,a),host=document.getElementById('guidedFeedback');if(code){host.innerHTML='<div class="feedback bad"><b>Not yet.</b> '+esc(targetedMessage(code))+'</div>';return;}host.innerHTML='<div class="feedback good"><b>Correct.</b> 6 − 6 − 1 = −1, and the ion total is −1.<div class="actions"><button class="btn" id="startIndependent">Start fresh independent work →</button></div></div>';document.getElementById('startIndependent').onclick=function(){state.screen='practice';state.itemIndex=0;state.itemAttempts=0;state.itemHelp=0;state.records=[];state.errors=[];state.status='Independent practice';save();render();};};
 if((el=document.getElementById('hint')))el.onclick=function(){state.itemHelp=Math.max(state.itemHelp,1);save();var item=ITEMS[state.itemIndex];document.getElementById('helpPanel').innerHTML='<div class="warning"><b>Hint</b><p>Read only what is attached to the '+esc(item.element)+': neutral valence count, nonbonding electrons, then total bond order. Do not use the overall ion charge as the atom’s answer.</p></div>';};
 if((el=document.getElementById('firstStep')))el.onclick=function(){state.itemHelp=Math.max(state.itemHelp,2);save();var item=ITEMS[state.itemIndex];document.getElementById('helpPanel').innerHTML='<div class="warning"><b>First step</b><p>'+esc(item.element)+' starts with <b>'+item.V+'</b> valence electrons. You still have to count N and B from the structure.</p></div>';};
 if((el=document.getElementById('walk')))el.onclick=function(){state.itemHelp=Math.max(state.itemHelp,3);save();document.getElementById('helpPanel').innerHTML='<div class="warning"><b>Walkthrough route</b><ol><li>Write V from the neutral atom.</li><li>Count every lone-pair electron for N.</li><li>Count bond order for B: single 1, double 2, triple 3.</li><li>Compute V − N − B.</li></ol><p>Fill the four boxes yourself. This item is now supported practice.</p></div>';};
 if((el=document.getElementById('checkPractice')))el.onclick=function(){var item=ITEMS[state.itemIndex],a=readFields(''),priorWrong=state.itemAttempts>0,code=diagnose(item,a);state.itemAttempts++;if(code){state.errors.push(code);save();document.getElementById('practiceFeedback').innerHTML='<div class="feedback bad"><b>Not yet.</b> '+esc(targetedMessage(code))+' Stay on this same problem and repair that component.</div>';return;}var clean=masteryCreditAllowed(state.itemHelp,priorWrong);state.records.push({id:item.id,correct:true,clean:clean,tags:item.tags.slice(),helpTier:state.itemHelp,attempts:state.itemAttempts});var e=sufficientEvidence(state.records);if(e.met){state.screen='transfer';state.transferIndex=0;state.status='Transfer';save();render();return;}state.itemIndex++;state.itemAttempts=0;state.itemHelp=0;if(state.itemIndex>=ITEMS.length){state.screen='developing';state.developReason='The six fresh atom items are complete, but 3 clean correct with charged and multiple-bond coverage was not established.';}save();render();};
 if((el=document.getElementById('transferHelp')))el.onclick=function(){var t=TRANSFERS[state.transferIndex];state.status='Transfer supported';save();document.getElementById('transferFeedback').innerHTML='<div class="warning"><b>This transfer is now practice, not mastery evidence.</b><p>'+esc(t.help)+'</p><button class="btn" id="freshTransfer">Use a fresh transfer</button></div>';document.getElementById('freshTransfer').onclick=function(){if(state.transferIndex+1<TRANSFERS.length){state.transferIndex++;state.screen='transfer';state.status='Fresh transfer';save();render();}else{state.screen='developing';state.developReason='Both transfer items required support.';save();render();}};};
 if((el=document.getElementById('checkTransfer')))el.onclick=function(){var t=TRANSFERS[state.transferIndex],wrong=false;if(t.fields.carbon!=null&&parseCharge(document.getElementById('tCarbon').value)!==t.fields.carbon)wrong=true;if(parseCharge(document.getElementById('tNitrogen').value)!==t.fields.nitrogen)wrong=true;if(parseCharge(document.getElementById('tTotal').value)!==t.fields.total){wrong=true;state.errors.push('sum');}if(!explanationLooksRight(document.getElementById('tExplain').value,t))wrong=true;if(!wrong){state.screen='mastered';state.status='Independent';save();render();return;}var host=document.getElementById('transferFeedback');if(state.transferIndex+1<TRANSFERS.length){host.innerHTML='<div class="feedback bad"><b>Not yet.</b> This transfer no longer counts as cold evidence. Check each atom with V − N − B, then use the fresh transfer.<div class="actions"><button class="btn" id="nextTransfer">Try fresh transfer →</button></div></div>';document.getElementById('nextTransfer').onclick=function(){state.transferIndex++;state.status='Fresh transfer';save();render();};}else{state.screen='developing';state.developReason='The fresh transfer still needs repair before resonance opens.';save();render();}};
}
render();
})(typeof globalThis!=='undefined'?globalThis:this);