(function(){'use strict';var $=id=>document.getElementById(id);var i=-1,rate=1,paused=false,buildStep=0;var steps=[
{say:'We are going to build ammonia from an empty workspace. First, count the valence electrons.',phase:'Learning',show:'empty'},
{say:'Nitrogen brings five valence electrons.',counter:'N = 5 valence electrons',show:'n-electrons'},
{say:'Each hydrogen brings one. Three hydrogens add three more, so ammonia has eight valence electrons total.',counter:'5 + 3 = 8 valence electrons',show:'all-electrons'},
{say:'Quick check. How many total valence electrons does NH3 have?',ask:{type:'numeric',value:8,prompt:'How many total valence electrons does NH₃ have?'}},
{say:'Hydrogen can only make one bond, so it cannot be the center. Watch nitrogen move to the center.',show:'center'},
{say:'Now watch the three hydrogens move around nitrogen.',show:'arrange-h'},
{say:'Each nitrogen hydrogen bond uses two electrons. Watch the three bonds form.',counter:'8 available → 6 in bonds → 2 remaining',show:'bonds'},
{say:'The final two electrons stay together as one lone pair on nitrogen.',counter:'8 available → 8 placed → 0 remaining',show:'lone'},
{say:'Now verify instead of memorizing. Nitrogen sees eight electrons. Each hydrogen sees two.',show:'verify'},
{say:'That was Watch. Now you will build it with me from an uncompleted stage.',phase:'Practicing Together',show:'reset-build',build:true},
{say:'Place nitrogen in the center.',manip:'center'},
{say:'Place the three hydrogens around nitrogen.',manip:'hydrogens'},
{say:'Create the three single bonds.',manip:'bonds'},
{say:'Place the remaining lone pair on nitrogen.',manip:'lone'},
{say:'Good. That was guided construction. Next comes fresh chemistry practice. One molecule will not count as mastery.',phase:'Your Turn',show:'complete'}];
function speak(t){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.rate=rate;u.onend=function(){};window.speechSynthesis.speak(u)}
function resetStage(){['n','h1','h2','h3'].forEach(id=>$(id).classList.remove('pulse'));$('n').style.left='8%';$('n').style.top='150px';$('h1').style.left='8%';$('h1').style.top='80px';$('h2').style.right='8%';$('h2').style.left='';$('h2').style.top='80px';$('h3').style.left='calc(50% - 24px)';$('h3').style.bottom='30px';$('h3').style.top='';['b1','b2','b3'].forEach(id=>$(id).classList.remove('on'));$('lp').classList.remove('on');$('counter').textContent='';}
function arrange(){ $('n').style.left='calc(50% - 30px)';$('n').style.top='150px';$('h1').style.left='calc(50% - 120px)';$('h1').style.top='160px';$('h2').style.left='calc(50% + 72px)';$('h2').style.right='';$('h2').style.top='160px';$('h3').style.left='calc(50% - 24px)';$('h3').style.top='250px';$('h3').style.bottom='';setBond($('b1'), 'calc(50% - 76px)','186px',46,0);setBond($('b2'),'calc(50% + 30px)','186px',46,0);setBond($('b3'),'50%','205px',45,90);$('lp').style.left='calc(50% - 12px)';$('lp').style.top='120px';}
function setBond(el,left,top,w,rot){el.style.left=left;el.style.top=top;el.style.width=w+'px';el.style.transform='rotate('+rot+'deg)'}
function visual(kind){if(!kind)return;if(kind==='empty')resetStage();if(kind==='n-electrons'){$('n').classList.add('pulse')}if(kind==='all-electrons'){['n','h1','h2','h3'].forEach(id=>$(id).classList.add('pulse'))}if(kind==='center'){$('n').style.left='calc(50% - 30px)';$('n').classList.add('pulse')}if(kind==='arrange-h')arrange();if(kind==='bonds'){arrange();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'))}if(kind==='lone'){arrange();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'));$('lp').classList.add('on')}if(kind==='verify'){$('n').classList.add('pulse')}if(kind==='reset-build'){resetStage();$('palette').classList.remove('hidden');buildStep=0}if(kind==='complete'){arrange();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'));$('lp').classList.add('on')}}
function show(){var s=steps[i];$('teacherText').textContent=s.say;$('phaseLabel').textContent=s.phase||$('phaseLabel').textContent;if(s.counter)$('counter').textContent=s.counter;visual(s.show);$('prompt').classList.add('hidden');$('palette').classList.toggle('hidden',!s.manip&&!s.build);$('next').disabled=!!s.ask||!!s.manip||i===steps.length-1;$('replay').disabled=false;$('pause').disabled=false;$('slow').disabled=false;$('idk').disabled=false;speak(s.say);if(s.ask)openAsk(s.ask);if(s.manip){$('question').textContent=s.say;$('prompt').classList.remove('hidden')}}
function openAsk(a){$('prompt').classList.remove('hidden');$('question').textContent=a.prompt;$('choices').innerHTML='';$('answer').classList.remove('hidden');$('check').classList.remove('hidden');$('check').onclick=function(){var ok=Math.abs(Number($('answer').value)-a.value)<1e-9;if(ok){$('feedback').className='good';$('feedback').textContent='Yes. That idea is working.';$('next').disabled=false;speak('Yes. That idea is working.')}else{$('feedback').className='bad';$('feedback').textContent='Not yet. Let us recount nitrogen and the three hydrogens instead of jumping ahead.';speak('Not yet. Let us recount nitrogen and the three hydrogens instead of jumping ahead.')}}}
function act(name){var need=steps[i]&&steps[i].manip;if(!need)return;if(name!==need){$('feedback').className='bad';$('feedback').textContent='That action does not match this step. Focus only on '+need+'.';speak('That action does not match this step. Focus only on the current step.');return}if(name==='center'){$('n').style.left='calc(50% - 30px)';$('n').classList.add('pulse')}if(name==='hydrogens')arrange();if(name==='bonds'){arrange();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'))}if(name==='lone'){$('lp').classList.add('on')}buildStep++;$('feedback').className='good';$('feedback').textContent='Yes. You performed that step.';$('next').disabled=false;speak('Yes. You performed that step.')}
$('start').onclick=function(){i=0;resetStage();show();this.disabled=true};$('next').onclick=function(){if(i<steps.length-1){i++;show()}};$('replay').onclick=function(){if(i>=0)show()};$('pause').onclick=function(){if(!('speechSynthesis'in window))return;if(!paused){window.speechSynthesis.pause();paused=true;this.textContent='Resume voice'}else{window.speechSynthesis.resume();paused=false;this.textContent='Pause voice'}};$('slow').onclick=function(){rate=rate===1?.75:1;this.textContent=rate<1?'Normal speed':'Slow down';if(i>=0){speak(steps[i].say)}};$('idk').onclick=function(){var s=steps[i];$('feedback').className='bad';$('feedback').textContent='We will stay on this exact chemistry step and explain it a different way. Replay first, then try the action again.';speak('We will stay on this exact chemistry step and explain it a different way. Replay first, then try the action again.');};document.querySelectorAll('.chip').forEach(b=>b.onclick=function(){act(this.dataset.action)});resetStage();})();