(function(){'use strict';var $=id=>document.getElementById(id);var i=-1,rate=.84,paused=false;var steps=[
{say:'We are going to build ammonia from an empty workspace. Before drawing bonds, we need to know what pieces we have. Valence electrons are the outer electrons atoms use when they bond.',phase:'Learning',show:'empty'},
{say:'This N means nitrogen. Nitrogen is in group fifteen of the periodic table, so a neutral nitrogen atom brings five valence electrons. Watch five dots appear around nitrogen.',counter:'Nitrogen: 5 valence electrons',show:'n-electrons'},
{say:'Each hydrogen brings one valence electron. There are three hydrogens, so three more dots appear. Five plus three gives eight total valence electrons for NH3.',counter:'5 from N + 3 from H = 8 total',show:'all-electrons'},
{say:'Quick check. How many total valence electrons does NH3 have?',ask:{value:8,prompt:'How many total valence electrons does NH₃ have?'}},
{say:'Now we choose the center atom. Hydrogen can form only one bond, so hydrogen cannot connect several atoms together. Nitrogen can, so watch nitrogen move to the center.',show:'center'},
{say:'Now the three hydrogen atoms move around nitrogen. Nothing is bonded yet. We are only arranging the atoms.',show:'arrange-h'},
{say:'Now watch what a bond actually is. One electron from nitrogen and one electron from a hydrogen meet between the two atoms. Those two electrons are shared. The same thing happens with each hydrogen.',counter:'3 shared pairs = 6 electrons in bonds',show:'shared-electrons'},
{say:'Chemists usually replace each shared pair of two dots with one line. The electrons did not disappear. Each line is shorthand for two shared electrons.',counter:'•• = one shared pair = one single bond',show:'bonds'},
{say:'Two electrons are still left. They stay together on nitrogen and are not shared with hydrogen. Two nonbonding electrons together are called one lone pair.',counter:'6 in bonds + 2 in lone pair = 8 placed',show:'lone'},
{say:'Now verify it. Nitrogen is surrounded by eight electrons: six represented by the three bond lines and two shown in its lone pair. Each hydrogen has two shared electrons represented by its one bond.',show:'verify'},
{say:'Now we build it together from an empty workspace. I will ask for one chemistry action at a time.',phase:'Practicing Together',show:'reset-build'},
{say:'Place nitrogen in the center. Remember, hydrogen cannot be the center because it makes only one bond.',manip:'center'},
{say:'Place the three hydrogens around nitrogen.',manip:'hydrogens'},
{say:'Create the three shared electron pairs. Remember, each pair contains two electrons between nitrogen and one hydrogen.',manip:'bonds'},
{say:'Place the two remaining electrons together as the lone pair on nitrogen.',manip:'lone'},
{say:'Good. You completed guided construction. This preview stops here. The real lesson will now give a different molecule with less help, then a fresh transfer problem. One NH3 build will never count as mastery.',phase:'Your Turn',show:'complete'}];
var reteach={'0':'Let me make the first idea smaller. Atoms have electrons. The electrons farthest from the nucleus are called valence electrons. Those are the electrons we keep track of when we draw a Lewis structure.','1':'Forget the phrase group fifteen for a moment. For this lesson, look at nitrogen as an atom arriving with five usable outer electrons. Each dot I am showing is one of those five electrons. Later we can connect that fact back to the periodic table.','2':'We are only counting right now. Nitrogen contributes 5 dots. Each of the 3 hydrogen atoms contributes 1 dot. So the pile is 5 + 1 + 1 + 1 = 8. We have not made any bonds yet.','3':'Do not solve the whole molecule. Just count what each atom brings: nitrogen gives 5, and three hydrogens give 3 more. Count the visible dots with me. That makes 8.','4':'The center atom needs to connect to more than one other atom. Hydrogen can make only one connection, so it cannot serve as the hub. Nitrogen can make several connections, so nitrogen goes in the middle.','5':'This step is only positioning. Think of nitrogen as the hub and the three hydrogens as three spokes around it. We are not spending electrons yet.','6':'Focus on just one nitrogen hydrogen pair. Nitrogen contributes one electron and hydrogen contributes one electron. Put those two electrons between the atoms. They are now a shared pair. That shared pair is the bond.','7':'The line is only a shortcut. When you see N-H, mentally read the line as two electrons shared between N and H. Three lines mean three shared pairs, which means six shared electrons.','8':'A lone pair is simply two electrons sitting together on one atom instead of being shared in a bond. We had 8 electrons. Six are represented by the three bonds. The last two dots stay on nitrogen.','9':'To verify nitrogen, translate the lines back into electrons: three bond lines times two electrons gives six, plus the two lone-pair electrons. Six plus two equals eight.','11':'You are not being asked for a number here. You are choosing which atom belongs in the middle. Tap Place N in center. Nitrogen is the hub because it can make several bonds.','12':'Keep nitrogen where it is. Now put all three hydrogen atoms around it. This step still does not create bonds.','13':'Do not think line yet. Think electron pair. For each N and H connection, two electrons sit between the atoms and are shared. Tap Create bonds to build those shared pairs first.','14':'After three shared pairs, six of the eight electrons are in bonds. Two remain. Put those last two together on nitrogen. That pair is called the lone pair.'};
function speak(t){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.rate=rate;window.speechSynthesis.speak(u)}
function clearElectrons(){var e=$('electrons');e.innerHTML='';$('legend').classList.add('hidden')}
function hideShared(){['sp1','sp2','sp3'].forEach(id=>$(id).classList.remove('on'))}
function dot(x,y,delay){var d=document.createElement('span');d.className='electron';d.style.left=x;d.style.top=y;$('electrons').appendChild(d);setTimeout(function(){d.classList.add('on')},delay||20);return d}
function nitrogenDots(){clearElectrons();$('legend').classList.remove('hidden');var xs=['calc(50% - 45px)','calc(50% - 15px)','calc(50% + 18px)','calc(50% - 15px)','calc(50% + 18px)'];var ys=['135px','120px','120px','210px','210px'];for(var k=0;k<5;k++)dot(xs[k],ys[k],120*k)}
function allDots(){nitrogenDots();dot('10%','70px',650);dot('86%','70px',780);dot('calc(50% - 5px)','315px',910)}
function resetStage(){['n','h1','h2','h3'].forEach(id=>$(id).classList.remove('pulse'));$('n').style.left='8%';$('n').style.top='150px';$('h1').style.left='8%';$('h1').style.top='80px';$('h2').style.right='8%';$('h2').style.left='';$('h2').style.top='80px';$('h3').style.left='calc(50% - 24px)';$('h3').style.bottom='30px';$('h3').style.top='';['b1','b2','b3'].forEach(id=>$(id).classList.remove('on'));hideShared();$('lp').classList.remove('on');$('counter').textContent='';clearElectrons()}
function arrange(){$('n').style.left='calc(50% - 30px)';$('n').style.top='150px';$('h1').style.left='calc(50% - 120px)';$('h1').style.top='160px';$('h2').style.left='calc(50% + 72px)';$('h2').style.right='';$('h2').style.top='160px';$('h3').style.left='calc(50% - 24px)';$('h3').style.top='250px';$('h3').style.bottom='';setBond($('b1'),'calc(50% - 76px)','186px',46,0);setBond($('b2'),'calc(50% + 30px)','186px',46,0);setBond($('b3'),'50%','205px',45,90);$('sp1').style.left='calc(50% - 71px)';$('sp1').style.top='174px';$('sp2').style.left='calc(50% + 38px)';$('sp2').style.top='174px';$('sp3').style.left='calc(50% - 9px)';$('sp3').style.top='218px';$('lp').style.left='calc(50% - 12px)';$('lp').style.top='120px'}
function setBond(el,left,top,w,rot){el.style.left=left;el.style.top=top;el.style.width=w+'px';el.style.transform='rotate('+rot+'deg)'}
function sharedPairs(animate){arrange();['b1','b2','b3'].forEach(id=>$(id).classList.remove('on'));hideShared();['sp1','sp2','sp3'].forEach(function(id,k){setTimeout(function(){$(id).classList.add('on')},animate?350*k:0)})}
function visual(kind){if(!kind)return;if(kind==='empty')resetStage();if(kind==='n-electrons'){resetStage();$('n').style.left='calc(50% - 30px)';nitrogenDots();$('n').classList.add('pulse')}if(kind==='all-electrons'){resetStage();allDots();['n','h1','h2','h3'].forEach(id=>$(id).classList.add('pulse'))}if(kind==='center'){resetStage();$('n').style.left='calc(50% - 30px)';$('n').classList.add('pulse')}if(kind==='arrange-h'){resetStage();arrange()}if(kind==='shared-electrons'){clearElectrons();sharedPairs(true)}if(kind==='bonds'){clearElectrons();arrange();hideShared();['b1','b2','b3'].forEach(function(id,k){setTimeout(function(){$(id).classList.add('on')},250*k)})}if(kind==='lone'){clearElectrons();arrange();hideShared();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'));$('lp').classList.add('on')}if(kind==='verify'){clearElectrons();arrange();hideShared();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'));$('lp').classList.add('on');$('n').classList.add('pulse')}if(kind==='reset-build'){resetStage()}if(kind==='complete'){clearElectrons();arrange();hideShared();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'));$('lp').classList.add('on')}}
function cleanPrompt(){$('prompt').classList.add('hidden');$('answer').value='';$('answer').classList.add('hidden');$('check').classList.add('hidden');$('feedback').textContent='';$('reteach').classList.add('hidden');$('reteach').innerHTML=''}
function show(){var s=steps[i];cleanPrompt();$('teacherText').textContent=s.say;$('phaseLabel').textContent=s.phase||$('phaseLabel').textContent;if(s.counter)$('counter').textContent=s.counter;visual(s.show);$('palette').classList.toggle('hidden',!s.manip);$('back').disabled=i<=0;$('next').disabled=!!s.ask||!!s.manip||i===steps.length-1;$('replay').disabled=false;$('pause').disabled=false;$('slow').disabled=false;$('idk').disabled=false;speak(s.say);if(s.ask)openAsk(s.ask);if(s.manip){$('question').textContent=s.say;$('prompt').classList.remove('hidden')}}
function openAsk(a){$('prompt').classList.remove('hidden');$('question').textContent=a.prompt;$('answer').classList.remove('hidden');$('check').classList.remove('hidden');$('check').onclick=function(){var ok=Math.abs(Number($('answer').value)-a.value)<1e-9;if(ok){$('feedback').className='good';$('feedback').textContent='Yes. Nitrogen gives 5 and the three hydrogens give 3, for 8 total.';$('next').disabled=false;speak($('feedback').textContent)}else{$('feedback').className='bad';$('feedback').textContent='Not yet. I am staying on this exact idea. Tap I don’t understand this and I will break the counting down visually.';speak($('feedback').textContent)}}}
function act(name){var need=steps[i]&&steps[i].manip;if(!need)return;if(name!==need){$('feedback').className='bad';$('feedback').textContent='That is a different chemistry action. We are staying on this one step.';speak($('feedback').textContent);return}if(name==='center'){$('n').style.left='calc(50% - 30px)';$('n').classList.add('pulse')}if(name==='hydrogens')arrange();if(name==='bonds'){sharedPairs(true);setTimeout(function(){hideShared();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'))},1500)}if(name==='lone'){$('lp').classList.add('on')}$('feedback').className='good';$('feedback').textContent=name==='bonds'?'Yes. You built three shared electron pairs. Watch those pairs become the three bond lines.':'Yes. You performed that chemistry step.';$('next').disabled=false;speak($('feedback').textContent)}
$('start').onclick=function(){i=0;resetStage();show();this.disabled=true};$('back').onclick=function(){if(i>0){i--;show()}};$('next').onclick=function(){if(i<steps.length-1){i++;show()}};$('replay').onclick=function(){if(i>=0)show()};$('pause').onclick=function(){if(!('speechSynthesis'in window))return;if(!paused){window.speechSynthesis.pause();paused=true;this.textContent='Resume voice'}else{window.speechSynthesis.resume();paused=false;this.textContent='Pause voice'}};$('slow').onclick=function(){rate=rate<.8?.84:.7;this.textContent=rate<.8?'Normal speed':'Slow down';if(i>=0)speak(steps[i].say)};$('idk').onclick=function(){if(i<0)return;var text=reteach[String(i)]||'I am going to keep this exact step and make it smaller instead of sending you backward.';$('reteach').classList.remove('hidden');$('reteach').innerHTML='<b>Let me teach this another way.</b>'+text;speak(text);if(i===1)nitrogenDots();if(i===2||i===3)allDots();if(i===6)sharedPairs(true);if(i===7){arrange();hideShared();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'))}if(i===8){arrange();['b1','b2','b3'].forEach(id=>$(id).classList.add('on'));$('lp').classList.add('on')}};document.querySelectorAll('.chip').forEach(b=>b.onclick=function(){act(this.dataset.action)});resetStage();})();