(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Test1AdaptiveData=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
function f(id,label,accepted,errorCode){return Object.freeze({id:id,label:label,accepted:Object.freeze(accepted),errorCode:errorCode});}
function q(id,prompt,fields,tags,visual){return Object.freeze({id:id,prompt:prompt,fields:Object.freeze(fields),tags:Object.freeze(tags||[]),visual:visual||null});}
function w(title,text,visual,check){return Object.freeze({title:title,text:text,visual:visual||null,check:check||null});}
function lesson(x){x.probe=Object.freeze(x.probe||[]);x.watch=Object.freeze(x.watch||[]);x.concept=Object.freeze(x.concept||[]);x.build=Object.freeze(x.build||[]);x.guided=Object.freeze(x.guided||[]);x.independent=Object.freeze(x.independent||[]);x.transfer=Object.freeze(x.transfer||[]);x.retrieval=Object.freeze(x.retrieval||[]);x.requiredTags=Object.freeze(x.requiredTags||[]);x.prerequisites=Object.freeze(x.prerequisites||[]);x.repairChecks=Object.freeze(x.repairChecks||{});x.reteach=Object.freeze(x.reteach||{});return Object.freeze(x);}
var LESSONS=Object.freeze({
'hybridization':lesson({id:'hybridization',skillId:'t1.hybridization',title:'Carbon Hybridization',chapter:'Chapter 2 foundation used on Test 1',priority:2,prerequisites:['bond-line'],objective:'Determine carbon hybridization from electron-domain geometry, then connect sp3/sp2/sp to tetrahedral/trigonal-planar/linear geometry.',requiredTags:['sp2_or_sp'],
probe:[q('HY-P1','A carbon with four single bonds has what hybridization?',[f('a','Hybridization',['sp3','sp³'],'HYBRID_LABEL')]),q('HY-P2','A carbonyl carbon in C=O has what hybridization?',[f('a','Hybridization',['sp2','sp²'],'HYBRID_LABEL')],['sp2_or_sp'])],
watch:[w('Count electron domains, not bond strokes','Hybridization follows the number of electron domains around the carbon. A single, double, or triple bond to one neighboring atom is one domain for geometry.','domains: 4 → sp3 · 3 → sp2 · 2 → sp',q('HY-W1','A C=C carbon has three electron domains. Predict its hybridization.',[f('a','Prediction',['sp2','sp²'],'DOMAIN_COUNT')])),w('Connect geometry to the label','Four domains are approximately tetrahedral (sp3), three trigonal planar (sp2), and two linear (sp).','sp3 ≈109.5° · sp2 ≈120° · sp =180°',q('HY-W2','A nitrile carbon in C≡N has two electron domains. Predict its hybridization.',[f('a','Prediction',['sp','sp1'],'DOMAIN_COUNT')]))],
concept:[q('HY-C1','Does a double bond count as one electron domain or two around a carbon for hybridization geometry?',[f('a','Answer',['one','1','one domain','1 domain'],'DOMAIN_COUNT')]),q('HY-C2','Three electron domains around carbon correspond to what hybridization?',[f('a','Hybridization',['sp2','sp²'],'HYBRID_LABEL')])],
build:[q('HY-B1','Build the decision for CH3-CH3: each carbon has how many electron domains?',[f('a','Domains',['4','four'],'DOMAIN_COUNT')]),q('HY-B2','With four domains, what hybridization is each carbon?',[f('a','Hybridization',['sp3','sp³'],'HYBRID_LABEL')])],
guided:[q('HY-G1','Guided: the carbonyl carbon in CH3CHO is bonded to H, C, and O (double bond). How many electron domains?', [f('a','Domains',['3','three'],'DOMAIN_COUNT')]),q('HY-G2','Therefore the carbonyl carbon is what hybridization?',[f('a','Hybridization',['sp2','sp²'],'HYBRID_LABEL')],['sp2_or_sp'])],
independent:[q('HY-I1','A carbon in an alkane has four sigma-bonding directions. Hybridization?',[f('a','Hybridization',['sp3','sp³'],'HYBRID_LABEL')]),q('HY-I2','A carbon in C=C has three electron domains. Hybridization?',[f('a','Hybridization',['sp2','sp²'],'HYBRID_LABEL')],['sp2_or_sp']),q('HY-I3','A carbon in C≡N has two electron domains. Hybridization?',[f('a','Hybridization',['sp'],'HYBRID_LABEL')],['sp2_or_sp']),q('HY-I4','A carbonyl carbon has what approximate geometry?', [f('a','Geometry',['trigonal planar','trigonal-planar'],'HYBRID_LABEL')],['sp2_or_sp'])],
explanation:{prompt:'Explain why a carbonyl carbon is sp2 without saying only “because it has a double bond.” Connect electron domains to geometry and hybridization.',requiredGroups:[['three','3'],['domain'],['sp2','trigonal planar']]},
transfer:[q('HY-T1','Transfer: the central carbon of CO2 has two electron domains. What hybridization and geometry?', [f('h','Hybridization',['sp'],'HYBRID_LABEL'),f('g','Geometry',['linear'],'HYBRID_LABEL')])],intervening:q('HY-A1','Different skill: an acyclic saturated alkane with 5 carbons has what formula?',[f('a','Formula',['c5h12','C5H12'],'ALKANE_FORMULA')]),retrieval:[q('HY-R1','Later: a nitrile carbon has two domains. Hybridization?', [f('a','Hybridization',['sp'],'HYBRID_LABEL')]),q('HY-R2','Later: a C=C carbon has three domains. Hybridization?', [f('a','Hybridization',['sp2','sp²'],'HYBRID_LABEL')])],
repairChecks:{DOMAIN_COUNT:q('HY-RP1','Repair check: a double bond to one atom counts as how many electron domains?',[f('a','Domains',['1','one'],'DOMAIN_COUNT')]),HYBRID_LABEL:q('HY-RP2','Repair check: four electron domains correspond to what hybridization?',[f('a','Hybridization',['sp3','sp³'],'HYBRID_LABEL')])},reteach:{DOMAIN_COUNT:'For geometry, count neighboring directions/electron domains. A multiple bond is one domain because it points toward one neighboring atom.',HYBRID_LABEL:'Map domains to hybridization: 4 → sp3, 3 → sp2, 2 → sp.'}}),

'functional-ir':lesson({id:'functional-ir',skillId:'t1.functional_ir',title:'Functional Groups + IR Recognition',chapter:'Chapter 2.4 + Lab 1 evidence',priority:2,prerequisites:['bond-line'],objective:'Recognize functional groups from connectivity, then use diagnostic IR features to distinguish alcohols, ketones, carboxylic acids, ethers, amines, and amides.',requiredTags:['ir'],
probe:[q('IR-P1','CH3CH2OH contains what functional group?',[f('a','Group',['alcohol','hydroxyl'],'FG_PATTERN')]),q('IR-P2','A spectrum has a strong C=O near 1715 cm-1 and no broad O-H. Which is the best match: ketone or alcohol?',[f('a','Match',['ketone'],'IR_MATCH')],['ir'])],
watch:[w('Connectivity comes before the spectrum','First identify what bonds define the candidate groups. IR confirms bond types; it does not replace structural reasoning.','O-H alcohol · C=O carbonyl · C-O-C ether',q('IR-W1','Which bond is the defining clue for an alcohol: O-H or C=O?',[f('a','Prediction',['o-h','oh','O-H'],'FG_PATTERN')])),w('Use diagnostic peaks, not every wiggle','Alcohol O-H is broad around 3200–3600 cm-1. A simple ketone has a strong C=O near ~1715 cm-1. A carboxylic acid typically has both a strong C=O and a very broad O-H spanning roughly 2500–3300 cm-1.','broad O-H vs strong C=O',q('IR-W2','Broad O-H plus strong C=O is most characteristic of which class?',[f('a','Class',['carboxylic acid','carboxylic-acid','acid'],'IR_MATCH')]))],
concept:[q('IR-C1','A ketone carbonyl carbon is bonded to how many carbon groups?',[f('a','Carbon groups',['2','two'],'FG_PATTERN')]),q('IR-C2','Does an ether normally show a broad O-H stretch?',[f('a','Answer',['no','n'],'IR_OH')])],
build:[q('IR-B1','Build a match: spectrum X has a broad 3200–3600 feature and no strong carbonyl. Which major group is indicated?',[f('a','Group',['alcohol','o-h','oh'],'IR_MATCH')]),q('IR-B2','Spectrum Y has a strong ~1715 peak and no broad O-H. Among alcohol, ketone, ether, choose the best match.',[f('a','Match',['ketone'],'IR_MATCH')])],
guided:[q('IR-G1','Guided: very broad 2500–3300 plus strong ~1710. Best class?',[f('a','Class',['carboxylic acid','acid'],'IR_MATCH')],['ir']),q('IR-G2','Guided: no O-H, no C=O, but a molecule is known to contain C-O-C. Functional group?',[f('a','Group',['ether'],'FG_PATTERN')])],
independent:[q('IR-I1','A spectrum has a broad O-H near 3300 and no strong C=O. Best class?', [f('a','Class',['alcohol'],'IR_MATCH')],['ir']),q('IR-I2','Strong C=O near 1715 with no broad O-H. Best of ketone/alcohol/ether?', [f('a','Class',['ketone'],'IR_MATCH')],['ir']),q('IR-I3','Strong C=O plus very broad acid O-H. Best class?', [f('a','Class',['carboxylic acid','acid'],'IR_MATCH')],['ir']),q('IR-I4','CH3OCH3 is what functional group?', [f('a','Group',['ether'],'FG_PATTERN')])],
explanation:{prompt:'Explain how you would distinguish an alcohol, ketone, and carboxylic acid using the presence or absence of broad O-H and strong C=O features.',requiredGroups:[['o-h','oh'],['c=o','carbonyl'],['alcohol'],['ketone','acid']]},transfer:[q('IR-T1','Transfer: an unknown has a strong carbonyl and a very broad low-frequency O-H envelope. Which candidate is more plausible: ketone or carboxylic acid?',[f('a','Answer',['carboxylic acid','acid'],'IR_MATCH')])],intervening:q('IR-A1','Different skill: a carbonyl carbon has how many electron domains?',[f('a','Domains',['3','three'],'DOMAIN_COUNT')]),retrieval:[q('IR-R1','Later: broad 3200–3600 with no carbonyl suggests what class?',[f('a','Class',['alcohol'],'IR_MATCH')]),q('IR-R2','Later: strong carbonyl plus very broad 2500–3300 suggests what class?',[f('a','Class',['carboxylic acid','acid'],'IR_MATCH')])],repairChecks:{FG_PATTERN:q('IR-RP1','Repair: C-O-C with no O-H is what group?',[f('a','Group',['ether'],'FG_PATTERN')]),IR_OH:q('IR-RP2','Repair: does a simple ether have an O-H bond?',[f('a','Answer',['no'],'IR_OH')]),IR_MATCH:q('IR-RP3','Repair: strong C=O with no broad O-H, choose ketone or alcohol.',[f('a','Match',['ketone'],'IR_MATCH')])},reteach:{FG_PATTERN:'Identify the actual connectivity first. Alcohol contains O-H; ether contains C-O-C; ketone contains a carbonyl carbon bonded to two carbons.',IR_OH:'A broad O-H stretch requires an O-H bond. Ethers do not have that bond unless another group supplies it.',IR_MATCH:'Use the largest diagnostic features first: broad O-H, strong C=O, then combination patterns.'}}),

'imf-boiling':lesson({id:'imf-boiling',skillId:'t1.imf_boiling',title:'Intermolecular Forces + Boiling Point',chapter:'Cumulative foundation / historical Test 1 pattern',priority:2,prerequisites:['functional-ir'],objective:'Identify the intermolecular forces a molecule can use with itself and rank boiling points using force class, polarizability/size, and shape without turning trends into absolutes.',requiredTags:['ranking'],
probe:[q('IM-P1','Ethanol molecules interacting with each other can hydrogen-bond. Yes or no?',[f('a','Answer',['yes','y'],'H_BOND_DONOR')]),q('IM-P2','Between n-pentane and neopentane (same formula), which generally has the higher boiling point?',[f('a','Higher boiling',['n-pentane','pentane','n pentane'],'BOILING_ORDER')],['ranking'])],
watch:[w('All molecules have London dispersion','Dispersion is always present. Polar molecules can add dipole-dipole interactions. Molecules with suitable O-H, N-H, or F-H donors can add hydrogen bonding to compatible acceptors.','dispersion ⊂ every molecule',q('IM-W1','Does propane have London dispersion forces?',[f('a','Prediction',['yes','y'],'IMF_SET')])),w('Ranking is a hierarchy, not one magic rule','First compare unusually strong force classes such as hydrogen bonding. When force classes are similar, compare molecular size/polarizability and surface contact; branching often lowers boiling point among comparable isomers by reducing contact area.','force class → size/polarizability → shape',q('IM-W2','Same formula: which usually boils higher, a less-branched or more-branched alkane?',[f('a','Prediction',['less branched','less-branched','straight chain','straight-chain'],'BOILING_ORDER')]))],
concept:[q('IM-C1','Acetone has a carbonyl but no O-H/N-H donor. Can two acetone molecules donate hydrogen bonds to each other?', [f('a','Answer',['no','n'],'H_BOND_DONOR')]),q('IM-C2','What intermolecular force is present in every molecular substance?', [f('a','Force',['london dispersion','dispersion','london forces'],'IMF_SET')])],
build:[q('IM-B1','Build the force list for ethanol with itself. Name the strongest special interaction beyond dispersion/dipole.',[f('a','Interaction',['hydrogen bonding','hydrogen bond','h bonding','h-bonding'],'H_BOND_DONOR')]),q('IM-B2','Build a boiling comparison: butane vs 1-butanol. Which should boil higher?', [f('a','Higher boiling',['1-butanol','butanol','1 butanol'],'BOILING_ORDER')])],
guided:[q('IM-G1','Guided: acetone vs propane of similar size. Which has dipole-dipole interactions?',[f('a','Molecule',['acetone'],'IMF_SET')]),q('IM-G2','Guided: n-pentane vs neopentane. Which usually has greater surface contact and higher boiling point?',[f('a','Molecule',['n-pentane','pentane','n pentane'],'BOILING_ORDER')],['ranking'])],
independent:[q('IM-I1','List the strongest special intermolecular interaction ethanol can use with itself.',[f('a','Interaction',['hydrogen bonding','hydrogen bond','h bonding'],'H_BOND_DONOR')]),q('IM-I2','Which generally boils higher: propane or acetone?',[f('a','Higher',['acetone'],'BOILING_ORDER')],['ranking']),q('IM-I3','Which generally boils higher: n-pentane or neopentane?',[f('a','Higher',['n-pentane','pentane'],'BOILING_ORDER')],['ranking']),q('IM-I4','Which has only London dispersion among these: propane or ethanol?',[f('a','Molecule',['propane'],'IMF_SET')])],
explanation:{prompt:'Explain why n-pentane generally boils higher than neopentane even though they have the same molecular formula and molar mass.',requiredGroups:[['surface','contact'],['dispersion','london'],['branch','compact']]},transfer:[q('IM-T1','Transfer: between hexane and 2,2-dimethylbutane, which usually has the higher boiling point?',[f('a','Higher',['hexane','n-hexane','n hexane'],'BOILING_ORDER')])],intervening:q('IM-A1','Different skill: CH3OCH3 is what functional group?',[f('a','Group',['ether'],'FG_PATTERN')]),retrieval:[q('IM-R1','Later: among pentane isomers, does increased branching generally raise or lower boiling point?',[f('a','Trend',['lower','lowers','decrease','decreases'],'BOILING_ORDER')]),q('IM-R2','Later: ethanol’s strongest special self-interaction?',[f('a','Interaction',['hydrogen bonding','hydrogen bond'],'H_BOND_DONOR')])],repairChecks:{H_BOND_DONOR:q('IM-RP1','Repair: does an O-H bond provide a hydrogen-bond donor?',[f('a','Answer',['yes'],'H_BOND_DONOR')]),IMF_SET:q('IM-RP2','Repair: what force is present in all molecules?',[f('a','Force',['dispersion','london dispersion','london forces'],'IMF_SET')]),BOILING_ORDER:q('IM-RP3','Repair: same-formula alkane pair, which usually boils higher: less branched or more branched?',[f('a','Answer',['less branched','straight chain','less-branched'],'BOILING_ORDER')])},reteach:{H_BOND_DONOR:'For self hydrogen bonding, look for a donor H directly attached to O, N, or F and a compatible lone-pair acceptor.',IMF_SET:'London dispersion is universal. Add dipole-dipole for polar molecules and hydrogen bonding when donor/acceptor requirements are met.',BOILING_ORDER:'Compare force class first. For similar force classes and size, greater surface contact usually strengthens dispersion; branching often lowers boiling point among comparable alkane isomers.'}}),

'alkane-isomers':lesson({id:'alkane-isomers',skillId:'t1.alkane_formula_isomers',title:'Alkane Formulas + Constitutional Isomers',chapter:'Chapter 4',priority:1,prerequisites:['bond-line'],objective:'Use CnH2n+2 for saturated acyclic alkanes and distinguish genuine connectivity changes from redrawing the same molecule.',requiredTags:['connectivity'],
probe:[q('AI-P1','What is the formula of an acyclic saturated alkane with 6 carbons?',[f('a','Formula',['c6h14','C6H14'],'ALKANE_FORMULA')]),q('AI-P2','How many constitutional isomers does C4H10 have?',[f('a','Count',['2','two'],'ISOMER_COUNT')],['connectivity'])],
watch:[w('Formula first','An open-chain saturated alkane follows CnH2n+2. A ring or multiple bond changes this hydrogen count.','acyclic saturated: CnH2n+2',q('AI-W1','For n=5, predict H count.',[f('a','Hydrogens',['12','twelve'],'ALKANE_FORMULA')])),w('Isomers require different connectivity','Constitutional isomers have the same molecular formula but different atom-to-atom connections. Rotation or a prettier redraw is not a new constitutional isomer.','same formula + different connectivity',q('AI-W2','If connectivity stays identical after rotation, is it a new constitutional isomer?', [f('a','Answer',['no','n'],'CONNECTIVITY')]))],
concept:[q('AI-C1','C5 acyclic saturated alkane formula?',[f('a','Formula',['c5h12','C5H12'],'ALKANE_FORMULA')]),q('AI-C2','Same formula but different connectivity means what relationship?',[f('a','Relationship',['constitutional isomers','constitutional isomer','structural isomers'],'CONNECTIVITY')])],
build:[q('AI-B1','Build C4H10: calculate H = 2(4)+2.',[f('a','H count',['10','ten'],'ALKANE_FORMULA')]),q('AI-B2','C4H10 has a straight-chain connectivity and a branched connectivity. How many distinct constitutional isomers?',[f('a','Count',['2','two'],'ISOMER_COUNT')])],
guided:[q('AI-G1','Guided: formula for saturated acyclic C7?', [f('a','Formula',['c7h16','C7H16'],'ALKANE_FORMULA')]),q('AI-G2','Guided: C5H12 has how many constitutional isomers?',[f('a','Count',['3','three'],'ISOMER_COUNT')],['connectivity'])],
independent:[q('AI-I1','Acyclic saturated alkane with 8 carbons: formula?',[f('a','Formula',['c8h18','C8H18'],'ALKANE_FORMULA')]),q('AI-I2','How many constitutional isomers does C4H10 have?',[f('a','Count',['2','two'],'ISOMER_COUNT')],['connectivity']),q('AI-I3','How many constitutional isomers does C5H12 have?',[f('a','Count',['3','three'],'ISOMER_COUNT')],['connectivity']),q('AI-I4','Two drawings have the same formula and exactly the same atom connectivity. Are they constitutional isomers?',[f('a','Answer',['no','same molecule','same'],'CONNECTIVITY')],['connectivity'])],
explanation:{prompt:'Explain why rotating or redrawing a molecule does not make a constitutional isomer, and state what must actually change.',requiredGroups:[['connectivity','connections'],['same formula','formula'],['change','different']]},transfer:[q('AI-T1','Transfer: C6H14 is an acyclic saturated alkane. What hydrogen count does the formula rule predict?',[f('a','Hydrogens',['14','fourteen'],'ALKANE_FORMULA')])],intervening:q('AI-A1','Different skill: a carbon with four electron domains is what hybridization?',[f('a','Hybridization',['sp3','sp³'],'HYBRID_LABEL')]),retrieval:[q('AI-R1','Later: C5 saturated acyclic formula?',[f('a','Formula',['c5h12','C5H12'],'ALKANE_FORMULA')]),q('AI-R2','Later: C4H10 constitutional-isomer count?',[f('a','Count',['2','two'],'ISOMER_COUNT')])],repairChecks:{ALKANE_FORMULA:q('AI-RP1','Repair: for n=4, 2n+2 equals?',[f('a','Hydrogens',['10'],'ALKANE_FORMULA')]),CONNECTIVITY:q('AI-RP2','Repair: constitutional isomers differ in what: connectivity or drawing orientation?',[f('a','Answer',['connectivity','connections'],'CONNECTIVITY')]),ISOMER_COUNT:q('AI-RP3','Repair: C4H10 has how many distinct connectivities?',[f('a','Count',['2','two'],'ISOMER_COUNT')])},reteach:{ALKANE_FORMULA:'Use CnH2n+2 only after confirming the molecule is saturated and acyclic.',CONNECTIVITY:'Constitutional isomerism is an atom-connection change, not rotation, flipping paper, or conformational change.',ISOMER_COUNT:'Generate distinct carbon skeletons systematically and reject duplicates with the same connectivity.'}}),

'nomenclature':lesson({id:'nomenclature',skillId:'t1.iupac_alkanes',title:'IUPAC Alkane Naming',chapter:'Chapter 4',priority:1,prerequisites:['bond-line','alkane-isomers'],objective:'Find the correct parent chain, assign the lowest set of substituent locants, identify substituents, alphabetize names when needed, and assemble the full alkane name.',requiredTags:['full_name'],
probe:[q('NM-P1','For CH3-CH(CH3)-CH2-CH2-CH3, how many carbons are in the longest parent chain?',[f('a','Parent carbons',['5','five'],'PARENT_CHAIN')]),q('NM-P2','Name CH3-CH(CH3)-CH2-CH2-CH3.',[f('a','Name',['2-methylpentane','2 methylpentane'],'FULL_NAME')],['full_name'])],
watch:[w('Parent chain before branches','Trace the longest continuous carbon chain first. Branches do not get named until the parent is locked.','trace parent → name parent',q('NM-W1','A longest chain of 6 carbons gives what parent name?',[f('a','Parent',['hexane'],'PARENT_CHAIN')])),w('Number for the lowest set of locants','Compare numbering from both ends and choose the set that is lower at the first point of difference.','2,3 beats 3,4',q('NM-W2','For a single methyl that could be at carbon 2 or 4, which locant is chosen?',[f('a','Locant',['2','two'],'NUMBER_DIRECTION')])),w('Assemble carefully','Write locant-substituent + parent. Multiple identical substituents use di-, tri-, etc. Different substituent names are alphabetized, ignoring multiplicative prefixes for alphabetization.','3-ethyl-2-methylhexane',q('NM-W3','Which comes first alphabetically: ethyl or methyl?',[f('a','First',['ethyl'],'SUBSTITUENT')]))],
concept:[q('NM-C1','A five-carbon parent is called?', [f('a','Parent',['pentane'],'PARENT_CHAIN')]),q('NM-C2','Do you choose the parent chain by the most visually horizontal line or by the longest continuous chain?',[f('a','Rule',['longest continuous chain','longest chain','continuous chain'],'PARENT_CHAIN')])],
build:[q('NM-B1','Build CH3-CH(CH3)-CH2-CH2-CH3: parent length?',[f('a','Carbons',['5','five'],'PARENT_CHAIN')]),q('NM-B2','Numbering from the nearer end puts methyl at which carbon?',[f('a','Locant',['2','two'],'NUMBER_DIRECTION')]),q('NM-B3','Assemble the name.',[f('a','Name',['2-methylpentane','2 methylpentane'],'FULL_NAME')])],
guided:[q('NM-G1','Guided: CH3-CH2-CH(CH3)-CH2-CH3. Parent length and methyl locant?',[f('p','Parent carbons',['5'],'PARENT_CHAIN'),f('l','Methyl locant',['3'],'NUMBER_DIRECTION')]),q('NM-G2','Full name?',[f('a','Name',['3-methylpentane','3 methylpentane'],'FULL_NAME')],['full_name'])],
independent:[q('NM-I1','Name CH3-CH(CH3)-CH(CH3)-CH3.',[f('a','Name',['2,3-dimethylbutane','2 3 dimethylbutane'],'FULL_NAME')],['full_name']),q('NM-I2','Name CH3-C(CH3)2-CH2-CH3.',[f('a','Name',['2,2-dimethylbutane','2 2 dimethylbutane'],'FULL_NAME')],['full_name']),q('NM-I3','Name CH3-CH(CH3)-CH2-CH2-CH3.',[f('a','Name',['2-methylpentane','2 methylpentane'],'FULL_NAME')],['full_name']),q('NM-I4','In CH3-CH(CH3)-CH(CH2CH3)-CH2-CH2-CH3, give the full name.',[f('a','Name',['3-ethyl-2-methylhexane','3 ethyl 2 methylhexane'],'FULL_NAME')],['full_name'])],
explanation:{prompt:'Explain the naming order: how you choose the parent, choose the numbering direction, and then assemble substituent names and locants.',requiredGroups:[['longest','parent'],['number','locant'],['substituent'],['name']]},transfer:[q('NM-T1','Transfer: CH3-CH2-CH(CH3)-CH2-CH3.',[f('a','Name',['3-methylpentane','3 methylpentane'],'FULL_NAME')])],intervening:q('NM-A1','Different skill: C5H12 has how many constitutional isomers?',[f('a','Count',['3','three'],'ISOMER_COUNT')]),retrieval:[q('NM-R1','Later: CH3-CH(CH3)-CH2-CH2-CH3 name?',[f('a','Name',['2-methylpentane','2 methylpentane'],'FULL_NAME')]),q('NM-R2','Later: CH3-CH(CH3)-CH(CH3)-CH3 name?',[f('a','Name',['2,3-dimethylbutane','2 3 dimethylbutane'],'FULL_NAME')])],repairChecks:{PARENT_CHAIN:q('NM-RP1','Repair: a longest chain with 5 carbons uses what parent?',[f('a','Parent',['pentane'],'PARENT_CHAIN')]),NUMBER_DIRECTION:q('NM-RP2','Repair: choose locant 2 or 4 for the same single substituent.',[f('a','Locant',['2'],'NUMBER_DIRECTION')]),SUBSTITUENT:q('NM-RP3','Repair: CH3- as a branch is called?',[f('a','Branch',['methyl'],'SUBSTITUENT')]),FULL_NAME:q('NM-RP4','Repair: methyl on carbon 2 of pentane gives what name?',[f('a','Name',['2-methylpentane','2 methylpentane'],'FULL_NAME')])},reteach:{PARENT_CHAIN:'Do not name what looks straightest. Trace every continuous option and choose the longest carbon chain.',NUMBER_DIRECTION:'Compare complete locant sets from both ends and choose the lower set at the first difference.',SUBSTITUENT:'A one-carbon branch is methyl, two-carbon branch ethyl; alphabetize different substituent names in the final name.',FULL_NAME:'Build the name only after parent, numbering, and substituents are individually correct.'}}),

'relationships':lesson({id:'relationships',skillId:'t1.molecular_relationships',title:'Same Molecule vs Isomers vs Stereoisomers',chapter:'Chapter 4 integrated comparison',priority:1,prerequisites:['bond-line','alkane-isomers'],objective:'Classify two structures by checking formula, then connectivity, then three-dimensional configuration in that order.',requiredTags:['stereo'],
probe:[q('RL-P1','Same formula, different connectivity: constitutional isomers or stereoisomers?',[f('a','Relationship',['constitutional isomers','constitutional isomer'],'RELATIONSHIP')]),q('RL-P2','Same connectivity but cis versus trans configuration: constitutional isomers or stereoisomers?',[f('a','Relationship',['stereoisomers','stereoisomer'],'RELATIONSHIP')],['stereo'])],
watch:[w('Use a three-gate comparison','Gate 1: same molecular formula? If no, none. Gate 2: same connectivity? If no, constitutional isomers. Gate 3: same connectivity but different fixed 3D configuration? Then stereoisomers. If all relevant configuration is the same and only conformation/view changed, same molecule.','formula → connectivity → configuration',q('RL-W1','If formulas differ, can the pair be constitutional isomers?', [f('a','Prediction',['no','n'],'RELATIONSHIP')])),w('Conformation is not configuration','Rotation about single bonds and chair flips can redraw the same molecule. A chair flip preserves up/down configuration even though axial/equatorial swap.','chair flip ≠ new stereoisomer',q('RL-W2','Does a chair flip by itself change cis into trans?',[f('a','Prediction',['no','n'],'STEREO_COMPARE')]))],
concept:[q('RL-C1','Same formula + different connectivity = ?', [f('a','Relationship',['constitutional isomers','constitutional isomer'],'CONNECTIVITY_COMPARE')]),q('RL-C2','Same connectivity + different cis/trans configuration = ?', [f('a','Relationship',['stereoisomers','stereoisomer'],'STEREO_COMPARE')])],
build:[q('RL-B1','Pair A has C4H10 on both sides. One is straight-chain, one branched. Same connectivity?', [f('a','Answer',['no','different'],'CONNECTIVITY_COMPARE')]),q('RL-B2','Therefore their relationship?',[f('a','Relationship',['constitutional isomers','constitutional isomer'],'RELATIONSHIP')])],
guided:[q('RL-G1','Guided: two drawings of trans-1,2-dimethylcyclohexane differ only by chair flip. Relationship?',[f('a','Relationship',['same molecule','same'],'RELATIONSHIP')]),q('RL-G2','Guided: cis-1,2-dimethylcyclohexane vs trans-1,2-dimethylcyclohexane. Relationship?',[f('a','Relationship',['stereoisomers','stereoisomer'],'RELATIONSHIP')],['stereo'])],
independent:[q('RL-I1','n-butane vs isobutane: relationship?',[f('a','Relationship',['constitutional isomers','constitutional isomer'],'RELATIONSHIP')]),q('RL-I2','cis-1,2-dimethylcyclohexane vs trans-1,2-dimethylcyclohexane: relationship?',[f('a','Relationship',['stereoisomers','stereoisomer'],'RELATIONSHIP')],['stereo']),q('RL-I3','Two chair drawings related by a ring flip with identical up/down substituent configuration: relationship?',[f('a','Relationship',['same molecule','same'],'RELATIONSHIP')],['stereo']),q('RL-I4','Butane vs pentane: relationship among same/constitutional/stereo/none?',[f('a','Relationship',['none','none of the above'],'RELATIONSHIP')])],
explanation:{prompt:'Explain the decision order you use to distinguish none, constitutional isomers, stereoisomers, and the same molecule.',requiredGroups:[['formula'],['connectivity','connections'],['configuration','cis','trans'],['same']]},transfer:[q('RL-T1','Transfer: same molecular formula and connectivity, but one pair is cis and the other trans. Relationship?',[f('a','Relationship',['stereoisomers','stereoisomer'],'RELATIONSHIP')])],intervening:q('RL-A1','Different skill: C4H10 has how many constitutional isomers?',[f('a','Count',['2','two'],'ISOMER_COUNT')]),retrieval:[q('RL-R1','Later: same formula, different connectivity?',[f('a','Relationship',['constitutional isomers','constitutional isomer'],'RELATIONSHIP')]),q('RL-R2','Later: chair flip only, up/down preserved?',[f('a','Relationship',['same molecule','same'],'RELATIONSHIP')])],repairChecks:{CONNECTIVITY_COMPARE:q('RL-RP1','Repair: if atom-to-atom connections differ, is connectivity same?',[f('a','Answer',['no'],'CONNECTIVITY_COMPARE')]),STEREO_COMPARE:q('RL-RP2','Repair: does a chair flip change up/down configuration?',[f('a','Answer',['no'],'STEREO_COMPARE')]),RELATIONSHIP:q('RL-RP3','Repair: same formula but different connectivity gives what relationship?',[f('a','Relationship',['constitutional isomers','constitutional isomer'],'RELATIONSHIP')])},reteach:{CONNECTIVITY_COMPARE:'Ignore orientation first. Trace which atom is bonded to which atom. If that map changes, connectivity changed.',STEREO_COMPARE:'Configuration asks whether fixed 3D relationships such as cis/trans changed. A conformational redraw alone does not.',RELATIONSHIP:'Use the gates in order: formula, connectivity, configuration. Do not jump straight to how the pictures look.'}}),

'newman-energy':lesson({id:'newman-energy',skillId:'t1.newman_conformations',title:'Newman Projections + Conformational Energy',chapter:'Chapter 4',priority:1,prerequisites:['bond-line','hybridization'],objective:'Read the viewing axis, classify eclipsed/staggered conformations, identify anti/gauche, rank stability, and map rotations to a conformational energy profile.',requiredTags:['energy','ranking'],
probe:[q('NW-P1','In a staggered Newman, the largest groups are 180° apart. Name the conformation.',[f('a','Name',['anti'],'DIHEDRAL')]),q('NW-P2','For butane, which is higher in energy: anti or fully eclipsed CH3/CH3?',[f('a','Higher',['fully eclipsed','eclipsed','fully-eclipsed'],'ENERGY')],['energy','ranking'])],
watch:[w('Know what you are looking down','A Newman projection views straight down a C-C single bond. The front carbon is the center point; the back carbon is represented by the circle.','front •  back ○',q('NW-W1','Are you looking along or perpendicular to the C-C bond?',[f('a','Prediction',['along','down the bond','along the bond'],'VIEW_AXIS')])),w('Aligned versus offset','Eclipsed means front/back bonds align: higher torsional strain. Staggered means they are offset by 60°: lower torsional strain.','eclipsed = aligned · staggered = offset',q('NW-W2','Aligned front/back bonds are called?',[f('a','Prediction',['eclipsed','eclipse'],'ECLIPSED_STAGGERED')])),w('Anti and gauche are staggered relationships','For butane, anti places the methyl groups 180° apart and is the lowest-energy staggered conformation. Gauche places them 60° apart and is a higher local minimum because of steric interaction. Fully eclipsed methyl/methyl is the highest point.','anti < gauche < eclipsed CH3-H < fully eclipsed CH3-CH3',q('NW-W3','Which is lower in energy for butane: anti or gauche?',[f('a','Prediction',['anti'],'STABILITY')]))],
concept:[q('NW-C1','Staggered largest groups 60° apart = ?', [f('a','Name',['gauche'],'DIHEDRAL')]),q('NW-C2','Eclipsed arrangements are higher mainly because of what strain?',[f('a','Strain',['torsional strain','torsional'],'ECLIPSED_STAGGERED')])],
build:[q('NW-B1','Build a 0→60° rotation: start fully eclipsed at 0°. After rotating 60°, is the conformation eclipsed or staggered?',[f('a','Class',['staggered'],'ECLIPSED_STAGGERED')]),q('NW-B2','If the two methyl groups are 60° apart in that staggered state, name it.',[f('a','Name',['gauche'],'DIHEDRAL')]),q('NW-B3','At 180° methyl-methyl separation, name the staggered state.',[f('a','Name',['anti'],'DIHEDRAL')])],
guided:[q('NW-G1','Guided: rank anti and gauche from lower to higher energy.',[f('a','Order',['anti < gauche','anti,gauche','anti then gauche'],'STABILITY')]),q('NW-G2','Guided: rank butane anti, gauche, CH3-H eclipsed, CH3-CH3 fully eclipsed from low to high.',[f('a','Order',['anti < gauche < eclipsed < fully eclipsed','anti,gauche,eclipsed,fully eclipsed','anti then gauche then eclipsed then fully eclipsed'],'ENERGY')],['energy','ranking'])],
independent:[q('NW-I1','Largest groups 180° apart and staggered: name?',[f('a','Name',['anti'],'DIHEDRAL')]),q('NW-I2','Largest groups 60° apart and staggered: name?',[f('a','Name',['gauche'],'DIHEDRAL')]),q('NW-I3','For butane, which conformation is highest in energy?',[f('a','Answer',['fully eclipsed','methyl-methyl eclipsed','ch3-ch3 eclipsed'],'ENERGY')],['energy','ranking']),q('NW-I4','In a standard butane energy profile with fully eclipsed methyl/methyl at 0°, what conformation is at 180°?',[f('a','Answer',['anti'],'ENERGY')],['energy'])],
explanation:{prompt:'Explain why anti butane is lower in energy than gauche and why fully eclipsed methyl/methyl is higher than both. Use torsional and steric ideas.',requiredGroups:[['anti'],['gauche'],['torsional'],['steric','methyl']]},transfer:[q('NW-T1','Transfer: if front/back bonds align after rotation, is that point a local maximum or minimum on the torsional energy curve?',[f('a','Answer',['maximum','max','local maximum'],'ENERGY')])],intervening:q('NW-A1','Different skill: a saturated C-C single-bond carbon with four domains is what hybridization?',[f('a','Hybridization',['sp3','sp³'],'HYBRID_LABEL')]),retrieval:[q('NW-R1','Later: butane lowest-energy staggered state?',[f('a','Name',['anti'],'STABILITY')]),q('NW-R2','Later: fully aligned bonds are what class?',[f('a','Class',['eclipsed','eclipse'],'ECLIPSED_STAGGERED')])],repairChecks:{VIEW_AXIS:q('NW-RP1','Repair: a Newman projection looks directly ___ a C-C bond.',[f('a','Word',['down','along','down the bond'],'VIEW_AXIS')]),ECLIPSED_STAGGERED:q('NW-RP2','Repair: aligned front/back bonds are?',[f('a','Class',['eclipsed'],'ECLIPSED_STAGGERED')]),DIHEDRAL:q('NW-RP3','Repair: staggered methyl groups 180° apart are?',[f('a','Name',['anti'],'DIHEDRAL')]),STABILITY:q('NW-RP4','Repair: anti or gauche is lower for butane?',[f('a','Answer',['anti'],'STABILITY')]),ENERGY:q('NW-RP5','Repair: fully eclipsed CH3/CH3 is a high or low point?',[f('a','Answer',['high','highest','maximum'],'ENERGY')])},reteach:{VIEW_AXIS:'Set the viewing direction before reading positions. You are looking along the chosen C-C bond.',ECLIPSED_STAGGERED:'Eclipsed = aligned bonds and torsional strain. Staggered = 60° offset and lower torsional strain.',DIHEDRAL:'For the two largest groups: 180° staggered is anti; 60° staggered is gauche.',STABILITY:'For butane, anti minimizes methyl-methyl steric interaction; gauche retains a 60° methyl-methyl interaction.',ENERGY:'Energy maxima are eclipsed. The methyl-methyl fully eclipsed state is highest; anti is the lowest minimum.'}}),

'ring-strain':lesson({id:'ring-strain',skillId:'t1.ring_strain',title:'Cycloalkane Ring Strain',chapter:'Chapter 4',priority:1,prerequisites:['hybridization'],objective:'Explain ring strain using angle strain, torsional strain, and nonplanar conformations rather than memorizing a stability list.',requiredTags:['explain_strain'],
probe:[q('RS-P1','Cyclopropane C-C-C bond angles are about 60°. Is that close to or far from the ~109.5° preferred tetrahedral angle?',[f('a','Answer',['far','far from','very far'],'ANGLE_STRAIN')]),q('RS-P2','Name one major source of cyclopropane strain.',[f('a','Strain',['angle strain','torsional strain','angle','torsional'],'STRAIN_EXPLAIN')],['explain_strain'])],
watch:[w('sp3 carbon prefers tetrahedral geometry','An unconstrained sp3 carbon prefers bond angles near 109.5°. Rings can force C-C-C angles away from that value, creating angle strain.','109.5° preferred vs ring constraint',q('RS-W1','Cyclopropane forces ~60°. Does that create angle strain?',[f('a','Prediction',['yes','y'],'ANGLE_STRAIN')])),w('Planarity can create torsional strain too','Cyclopropane is essentially planar, so many C-H bonds on adjacent carbons are eclipsed. That adds torsional strain on top of severe angle strain.','cyclopropane: angle + torsional strain',q('RS-W2','Eclipsed adjacent bonds contribute what type of strain?',[f('a','Prediction',['torsional strain','torsional'],'TORSIONAL_STRAIN')])),w('Cyclohexane escapes by folding','The chair conformation brings carbon angles close to tetrahedral and keeps neighboring bonds staggered, greatly reducing angle and torsional strain.','chair ≈ low angle + low torsional strain',q('RS-W3','Does chair cyclohexane stay flat?',[f('a','Prediction',['no','n'],'STRAIN_EXPLAIN')]))],
concept:[q('RS-C1','Distorting an sp3 bond angle away from ~109.5° creates what strain?',[f('a','Strain',['angle strain','angle'],'ANGLE_STRAIN')]),q('RS-C2','Eclipsing adjacent bonds creates what strain?',[f('a','Strain',['torsional strain','torsional'],'TORSIONAL_STRAIN')])],
build:[q('RS-B1','Build the cyclopropane explanation: preferred sp3 angle?',[f('a','Degrees',['109.5','109.5 degrees','109'],'ANGLE_STRAIN')]),q('RS-B2','Cyclopropane ring angle?',[f('a','Degrees',['60','60 degrees'],'ANGLE_STRAIN')]),q('RS-B3','Besides angle strain, its eclipsed bonds add what strain?',[f('a','Strain',['torsional strain','torsional'],'TORSIONAL_STRAIN')])],
guided:[q('RS-G1','Guided: cyclobutane puckers rather than staying perfectly planar mainly to reduce which kind of strain?',[f('a','Strain',['torsional strain','torsional'],'TORSIONAL_STRAIN')]),q('RS-G2','Guided: why is the cyclohexane chair especially stable? Name the two strain types it minimizes.',[f('a','Strains',['angle and torsional','angle strain and torsional strain','torsional and angle'],'STRAIN_EXPLAIN')],['explain_strain'])],
independent:[q('RS-I1','Give one reason cyclopropane is high energy relative to propane.',[f('a','Reason',['angle strain','torsional strain','60 degree bond angles','eclipsed bonds'],'STRAIN_EXPLAIN')],['explain_strain']),q('RS-I2','What strain comes from 60° C-C-C angles at sp3 carbons?',[f('a','Strain',['angle strain','angle'],'ANGLE_STRAIN')]),q('RS-I3','What strain comes from eclipsed adjacent bonds?',[f('a','Strain',['torsional strain','torsional'],'TORSIONAL_STRAIN')]),q('RS-I4','Which cyclohexane conformation strongly minimizes both angle and torsional strain?',[f('a','Conformation',['chair','chair conformation'],'STRAIN_EXPLAIN')],['explain_strain'])],
explanation:{prompt:'Explain why cyclopropane is much higher in energy than an open-chain propane framework. Include both bond-angle distortion and eclipsing.',requiredGroups:[['60','angle'],['109.5','tetrahedral'],['torsional','eclips'],['strain']]},transfer:[q('RS-T1','Transfer: why does cyclobutane pucker out of plane instead of remaining perfectly flat?',[f('a','Reason',['reduce torsional strain','reduce eclipsing','torsional strain'],'TORSIONAL_STRAIN')])],intervening:q('RS-A1','Different skill: an sp3 carbon has how many electron domains?',[f('a','Domains',['4','four'],'DOMAIN_COUNT')]),retrieval:[q('RS-R1','Later: severe 60° ring-angle distortion creates what strain?',[f('a','Strain',['angle strain','angle'],'ANGLE_STRAIN')]),q('RS-R2','Later: eclipsed adjacent bonds create what strain?',[f('a','Strain',['torsional strain','torsional'],'TORSIONAL_STRAIN')])],repairChecks:{ANGLE_STRAIN:q('RS-RP1','Repair: sp3 preferred angle is closest to 109.5° or 60°?',[f('a','Angle',['109.5','109.5°','109.5 degrees'],'ANGLE_STRAIN')]),TORSIONAL_STRAIN:q('RS-RP2','Repair: eclipsed bonds create what strain?',[f('a','Strain',['torsional strain','torsional'],'TORSIONAL_STRAIN')]),STRAIN_EXPLAIN:q('RS-RP3','Repair: cyclopropane has angle strain plus what other major strain?',[f('a','Strain',['torsional strain','torsional'],'STRAIN_EXPLAIN')])},reteach:{ANGLE_STRAIN:'Angle strain comes from forcing bond angles away from the preferred geometry. sp3 carbon prefers about 109.5°, while cyclopropane forces about 60°.',TORSIONAL_STRAIN:'Torsional strain rises when adjacent bonds eclipse. Nonplanar conformations often reduce eclipsing.',STRAIN_EXPLAIN:'Do not memorize “small ring = bad.” Name the geometric cause: angle distortion and/or eclipsing.'}}),

'cyclohexane-chairs':lesson({id:'cyclohexane-chairs',skillId:'t1.cyclohexane_chairs',title:'Cyclohexane Chairs + Substituent Stability',chapter:'Chapter 4',priority:1,prerequisites:['ring-strain','bond-line'],objective:'Track axial/equatorial and up/down positions through ring flips, preserve cis/trans configuration, and choose the lower-energy chair by minimizing unfavorable axial interactions.',requiredTags:['flip','stability'],
probe:[q('CH-P1','In a chair flip, does a substituent switch axial↔equatorial?',[f('a','Answer',['yes','y'],'RING_FLIP')],['flip']),q('CH-P2','For monosubstituted tert-butylcyclohexane, axial or equatorial is more stable?',[f('a','Position',['equatorial'],'STABILITY')],['stability'])],
watch:[w('Axial/equatorial is not the same as up/down','Every ring carbon has one axial and one equatorial direction. A substituent can be up or down while being axial or equatorial depending on the chair.','orientation: axial/equatorial · configuration: up/down',q('CH-W1','During a ring flip, does up become down?',[f('a','Prediction',['no','n'],'UP_DOWN')])),w('Ring flip rule','A ring flip swaps axial ↔ equatorial for every substituent but preserves each substituent’s up/down orientation. Therefore cis/trans relationships are preserved.','ax↔eq · up stays up · down stays down',q('CH-W2','An axial-up substituent becomes what after a flip?',[f('a','Prediction',['equatorial up','equatorial-up','equatorial and up'],'RING_FLIP')])),w('Stability comes from avoiding axial crowding','Bulky axial substituents suffer unfavorable 1,3-diaxial interactions. When configuration allows, the lower-energy chair places the larger group(s) equatorial.','bulky equatorial usually favored',q('CH-W3','For a bulky monosubstituent, which position is usually favored?',[f('a','Prediction',['equatorial'],'STABILITY')]))],
concept:[q('CH-C1','Ring flip: axial becomes?',[f('a','Position',['equatorial'],'RING_FLIP')]),q('CH-C2','Ring flip: up becomes down, or stays up?',[f('a','Answer',['stays up','up','remains up'],'UP_DOWN')])],
build:[q('CH-B1','Build one flip: start axial up. New axial/equatorial position?',[f('a','Position',['equatorial'],'RING_FLIP')]),q('CH-B2','New up/down orientation?',[f('a','Orientation',['up','stays up'],'UP_DOWN')]),q('CH-B3','A bulky group is now equatorial. Is that generally more or less stable than axial?',[f('a','Answer',['more stable','more','lower energy'],'STABILITY')])],
guided:[q('CH-G1','Guided: cis-1,4-dimethylcyclohexane must have one methyl axial and one equatorial in a given chair. After a flip, how many are axial?',[f('a','Count',['1','one'],'CIS_TRANS')]),q('CH-G2','Guided: trans-1,4-dimethylcyclohexane can have a diequatorial chair. Is diequatorial or diaxial lower in energy?',[f('a','Answer',['diequatorial','di-equatorial'],'STABILITY')],['stability'])],
independent:[q('CH-I1','A substituent is axial down. After a ring flip, what is it?',[f('a','Position',['equatorial down','equatorial-down','equatorial and down'],'RING_FLIP')],['flip']),q('CH-I2','Does a ring flip convert cis to trans?',[f('a','Answer',['no','n'],'CIS_TRANS')]),q('CH-I3','For trans-1,4-dimethylcyclohexane, which conformer is more stable: diequatorial or diaxial?',[f('a','Answer',['diequatorial','di-equatorial'],'STABILITY')],['stability']),q('CH-I4','For cis-1,4-dimethylcyclohexane with identical methyl groups, how many methyl groups are axial in either chair?',[f('a','Count',['1','one'],'CIS_TRANS')],['stability'])],
explanation:{prompt:'Explain what changes and what stays the same during a cyclohexane ring flip, then explain why a bulky equatorial substituent is usually favored.',requiredGroups:[['axial','equatorial'],['up','down'],['preserve','same','stays'],['1,3','diaxial','crowd','interaction']]},transfer:[q('CH-T1','Transfer: a tert-butyl group is axial in one chair and equatorial in the flipped chair. Which chair is strongly favored?',[f('a','Answer',['equatorial','equatorial chair','chair with equatorial tert-butyl'],'STABILITY')])],intervening:q('CH-A1','Different skill: cyclopropane’s 60° angles create what strain?',[f('a','Strain',['angle strain','angle'],'ANGLE_STRAIN')]),retrieval:[q('CH-R1','Later: ring flip swaps axial/equatorial but preserves what orientation?',[f('a','Answer',['up/down','up and down','up-down','configuration'],'UP_DOWN')]),q('CH-R2','Later: bulky monosubstituent usually prefers?',[f('a','Position',['equatorial'],'STABILITY')])],repairChecks:{AXIAL_EQUATORIAL:q('CH-RP1','Repair: the two chair position types are axial and what?',[f('a','Position',['equatorial'],'AXIAL_EQUATORIAL')]),UP_DOWN:q('CH-RP2','Repair: does ring flip change up to down?',[f('a','Answer',['no'],'UP_DOWN')]),RING_FLIP:q('CH-RP3','Repair: axial becomes what after a flip?',[f('a','Position',['equatorial'],'RING_FLIP')]),CIS_TRANS:q('CH-RP4','Repair: does a chair flip change cis/trans configuration?',[f('a','Answer',['no'],'CIS_TRANS')]),STABILITY:q('CH-RP5','Repair: bulky substituent usually prefers axial or equatorial?',[f('a','Position',['equatorial'],'STABILITY')])},reteach:{AXIAL_EQUATORIAL:'Axial positions point roughly parallel to the ring axis; equatorial positions point outward around the ring.',UP_DOWN:'Up/down is configuration. A ring flip changes conformation, not configuration.',RING_FLIP:'Ring flip rule: every axial becomes equatorial and every equatorial becomes axial, while up/down stays fixed.',CIS_TRANS:'Cis means same face (both up or both down); trans means opposite faces. Ring flipping does not change faces.',STABILITY:'Compare unavoidable axial groups. Bulky axial groups suffer 1,3-diaxial interactions, so the chair with the larger groups equatorial is usually lower in energy.'}})
});
var ORDER=Object.freeze(['alkane-isomers','nomenclature','relationships','newman-energy','ring-strain','cyclohexane-chairs','hybridization','functional-ir','imf-boiling']);
var EXTERNAL=Object.freeze([{id:'chapter1',title:'Chapter 1 Foundations',href:'../chapter1/',note:'Valence electrons, Lewis structures, lone pairs, formal charge.'},{id:'bond-line',title:'Bond-Line Structures',href:'../bond-line/',note:'Chapter 2.1–2.3 representations and implied atoms/hydrogens.'}]);
function get(id){return LESSONS[id]||null;}function all(){return ORDER.map(function(id){return LESSONS[id];});}
return Object.freeze({LESSONS:LESSONS,ORDER:ORDER,EXTERNAL:EXTERNAL,lesson:get,all:all});
});